force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Location stores all the Master Data related to the reservations. It can hold building, suite, room and bed separated by record types.</description>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Template Provider</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Active Care Episode Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>This object stores both template and patient providers. Providers in elixir are facilties.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Represents patient-provider relationship.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Patient_Provider__c.field-meta.xml
<CustomField>
    <fullName>Patient_Provider__c</fullName>
    <description>Describes whether the record is patient provider or not.</description>
    <formula>IF( RecordType.Name = &apos;Patient Provider&apos;, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Patient Provider</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents self-relationship.</description>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.Account__r.Id</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Provider_Code__c.field-meta.xml
<CustomField>
    <fullName>Provider_Code__c</fullName>
    <description>This field denotes the provider NPI code information.</description>
    <label>Provider NPI</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProviderTriggerHelper.cls
public with sharing class ProviderTriggerHelper {
    public static void evaluateOpportunityLocation(Set<Id> accountIds) {
        List<Account> accounts = [SELECT Id,(SELECT Id, Name FROM Providers__r ORDER BY CreatedDate DESC LIMIT 1) 
                                    FROM Account WHERE Id IN :accountIds WITH SECURITY_ENFORCED];
        Map<Id,Account> providers = new Map<Id,Account>(accounts);
        List<Account> opportunities = [SELECT Id,(SELECT Id,AccountId,StageName,Location__c FROM Opportunities 
                                    WHERE StageName!='Closed Lost' ORDER BY CreatedDate DESC LIMIT 200)
                                    FROM Account WHERE Id IN :accountIds  WITH SECURITY_ENFORCED];
        List<Opportunity> oppToUpdate = new List<Opportunity>();
        try{
        for(Account oppo :opportunities){
            Id accountId = oppo.Id;
            if(providers.containsKey(accountId)){
                Account acc = providers.get(accountId);
                List<Provider__c> relatedProviders = acc.Providers__r;
                if(relatedProviders!=null && relatedProviders.size()>0){
                    String location = relatedProviders[0].Name;
                    for(Opportunity opportunityToUpdate :oppo.Opportunities){
                        opportunityToUpdate.Location__c = location;
                        oppToUpdate.add(opportunityToUpdate);
                        system.debug(opportunityToUpdate.Location__c);
                    }
                }else{
                    for(Opportunity opportunityToUpdate :oppo.Opportunities){
                        opportunityToUpdate.Location__c = '';
                        oppToUpdate.add(opportunityToUpdate);
                        system.debug(opportunityToUpdate.Location__c);
                    }
                }
            }
        }
        if(oppToUpdate!=null && oppToUpdate.size()>0 &&
        Schema.sObjectType.Opportunity.isUpdateable() &&
        Schema.sObjectType.Opportunity.fields.Location__c.isUpdateable()){
            StopRecursion.stopLocationUpdation = false;
            update oppToUpdate;
        }
        }
        catch(Exception e){
            ExceptionLog.logError(e);
        }
    }
    public static void populateProviders(List<Provider__c> providers){
        Map<String,Id> npiMap = new Map<String,Id>();
        Set<String> npi = new Set<String>();
        try{
        for(Provider__c provider :providers){
            if(provider.Patient_Provider__c && String.isNotBlank(provider.Provider_Code__c)){
                npi.add(provider.Provider_Code__c);
            }
        }
        if(npi!=null && npi.size()>0){
            List<Provider__c> templateProviders = [SELECT Id,Provider_Code__c FROM Provider__c 
                                                WHERE Provider_Code__c IN :npi AND Account__c=NULL WITH SECURITY_ENFORCED LIMIT 999];
            if(templateProviders!=null && templateProviders.size()>0){
                for(Provider__c templateProvider :templateProviders){
                    npiMap.put(templateProvider.Provider_Code__c, templateProvider.Id);
                }
            }
        }
        if(npiMap!=null && npiMap.size()>0){
            for(Provider__c provider :providers){
                    if(provider.Patient_Provider__c && String.isNotBlank(provider.Provider_Code__c)){
                    String billId = provider.Provider_Code__c;
                    if(npiMap.containsKey(billId)){
                        provider.Provider__c = npiMap.get(billId);
                    }
                }
            }
        }
    }
     catch(Exception e){
     ExceptionLog.logError(e);
        }
    }
}