force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>TO BE DEPRECATED:
Form was used to store all the forms related to the patient.</description>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/Form_Value__c.object-meta.xml
<CustomObject>
    <description>Form value stores all the miscellaneous features of the saved forms like Approvals, Care Episodes and Status. All the problems, diagnoses, medications and allergies selected on the forms are also linked with this object as the record in this object is also responsible for giving one identity to the forms saved in multiple objects.</description>
    <label>Form Value</label>
    <nameField>
        <label>Form Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Value__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Form Values</relationshipLabel>
    <relationshipName>Form_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Approval_Level__c.field-meta.xml
<CustomField>
    <fullName>Approval_Level__c</fullName>
    <label>Approval Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Approved_Signature__c.field-meta.xml
<CustomField>
    <fullName>Approved_Signature__c</fullName>
    <label>Approved Signature</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Date_Of_Approval__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Approval__c</fullName>
    <label>Date Of Approval</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Form_Id__c.field-meta.xml
<CustomField>
    <fullName>Form_Id__c</fullName>
    <label>Form Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Form_Name__c.field-meta.xml
<CustomField>
    <fullName>Form_Name__c</fullName>
    <label>Form Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Is_Approver__c.field-meta.xml
<CustomField>
    <fullName>Is_Approver__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Approver</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Is_External_Signature__c.field-meta.xml
<CustomField>
    <fullName>Is_External_Signature__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is External Signature</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Is_Old__c.field-meta.xml
<CustomField>
    <fullName>Is_Old__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Old</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Signed_Patient__c.field-meta.xml
<CustomField>
    <fullName>Signed_Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Signed Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Form Values (Signed Patient)</relationshipLabel>
    <relationshipName>Form_Values1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Form_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/Object_1_css__c.object-meta.xml
<CustomObject>
    <description>Form css stores all the attributes that defines how a form will look like when you view a form. All configuration records are saved in this object from Form Configuration screen.</description>
    <label>Form css</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Object 1 css Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form css</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_1_css__c/fields/Approv__c.field-meta.xml
<CustomField>
    <fullName>Approv__c</fullName>
    <label>Approver</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Approval_Level__c.field-meta.xml
<CustomField>
    <fullName>Approval_Level__c</fullName>
    <label>Approval Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Approval_Members__c.field-meta.xml
<CustomField>
    <fullName>Approval_Members__c</fullName>
    <label>Approval Members</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Object_1_css__c.field-meta.xml
<CustomField>
    <fullName>Object_1_css__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Object 1 css</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Section_Number__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Object_1_css__c</referenceTo>
    <relationshipName>Object_1_css</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PreviousSignature.cls
public with sharing class PreviousSignature {
    
     @AuraEnabled
     public static FormApprovalData.currentUserInfo fetchApprovalLevels(String recordTypeName, String formId){
        try {
            List<Object_1_css__c> defaultApprovalLevels = new List<Object_1_css__c>();
            SObjectAccessDecision decisionNonApproved = Security.stripInaccessible(AccessType.READABLE,
            [SELECT Id, Approval_Level__c, Approv__c, Approval_Members__c, ElixirSuite__Approver_Custom_Label__c FROM 
                            Object_1_css__c WHERE Form__c= :recordTypeName AND Approval_Level__c!=NULL
                             WITH SECURITY_ENFORCED
                            ORDER BY Approval_Level__c]);
            defaultApprovalLevels = decisionNonApproved.getRecords();
            List<Form_Value__c> approvedValues = new List<Form_Value__c>();
            SObjectAccessDecision decisionApproved = Security.stripInaccessible(AccessType.READABLE,
            [SELECT Id, Account__c, Is_Approver__c, Date_Of_Approval__c,Is_External_Signature__c,
            User__r.Name, User__r.UserRole.Name, Approval_Level__c, Comment__c, Is_old__c, Form_Name__c, ElixirSuite__Reopened_Date__c,Approved_Signature__c,
            Signed_Patient__r.Name FROM Form_Value__c
            WHERE Is_Approver__c=true AND Form_Id__c= :formId  AND Is_old__c = false
              WITH SECURITY_ENFORCED
            ORDER BY Approval_Level__c]);
            approvedValues = decisionApproved.getRecords();
            system.debug('approvedValues'+approvedValues);
            
            
            List<Form_Value__c> fetchSignature = new List<Form_Value__c>();
            SObjectAccessDecision approvedSignature = Security.stripInaccessible(AccessType.READABLE,
            [SELECT Id, Account__c, Is_Approver__c, Date_Of_Approval__c,Is_External_Signature__c,
            User__r.Name, User__r.UserRole.Name, Approval_Level__c, Comment__c, Is_old__c, Form_Name__c, Approved_Signature__c,ElixirSuite__Reopened_Date__c,
            Signed_Patient__r.Name FROM Form_Value__c
            WHERE Is_Approver__c=true AND Form_Id__c= :formId AND Is_old__c = true
              WITH SECURITY_ENFORCED
            ORDER BY ElixirSuite__Reopened_Date__c DESC,Approval_Level__c]);
             fetchSignature = approvedSignature.getRecords();
            List<List<Form_Value__c>> previousApprovedValues= new List<List<Form_Value__c>>();
            List<Form_Value__c> lst= new List<Form_Value__c>();
            DateTime oldvalue;
            
            for(Form_Value__c Sign : fetchSignature){
                DateTime NewValue = Sign.ElixirSuite__Reopened_Date__c;
                if(NewValue == oldvalue | oldvalue == null){
                    lst.add(Sign);
                }
                else{
                    previousApprovedValues.add(lst);
                    lst= new List<Form_Value__c>();
                    lst.add(Sign);
                }
                
                oldvalue = Sign.ElixirSuite__Reopened_Date__c;
            }
            previousApprovedValues.add(lst);
            system.debug('Previous signature'+previousApprovedValues);
            system.debug('Previous signature---'+lst);
            
            FormApprovalData.currentUserInfo userInfo = new FormApprovalData.currentUserInfo();
            userInfo.setUserId();
            userInfo.setProfileId();
            userInfo.setRoleId();
            userInfo.setDefaultLevels(defaultApprovalLevels);
            userInfo.setApprovedValues(approvedValues);
            userInfo.setpreviousApprovedValues(previousApprovedValues);
            system.debug('userInfo'+userInfo);
            return userInfo;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
        
}