force-app/main/default/objects/HL7__c/HL7__c.object-meta.xml
<CustomObject>
    <label>LabOrder HL7 Results</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>LabOrder HL7 Results ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LabOrder HL7 Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HL7__c/fields/Full_HL7_Dump_Message__c.field-meta.xml
<CustomField>
    <fullName>Full_HL7_Dump_Message__c</fullName>
    <label>Full_HL7_Dump_Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HL7__c/fields/Message_Header__c.field-meta.xml
<CustomField>
    <fullName>Message_Header__c</fullName>
    <label>Message Header</label>
    <length>99999</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HL7__c/fields/Observation_Request__c.field-meta.xml
<CustomField>
    <fullName>Observation_Request__c</fullName>
    <label>Observation Request</label>
    <length>99999</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HL7__c/fields/Order_ID__c.field-meta.xml
<CustomField>
    <fullName>Order_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order_ID</label>
    <referenceTo>Lab_Order__c</referenceTo>
    <relationshipName>LabOrder_HL7_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HL7__c/fields/Patient_Identification__c.field-meta.xml
<CustomField>
    <fullName>Patient_Identification__c</fullName>
    <label>Patient Identification</label>
    <length>99999</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/PushHl7MessageDataHelper.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-14-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class PushHl7MessageDataHelper {
public  void myHL7msg(List<HL7__c> sID){
       List<HL7__c> hl7MsgList=new List<HL7__c>();
     
        List<HL7__c> listOfHL7 = [Select Id, Order_ID__c, Full_HL7_Dump_Message__c,Patient_Identification__c,Message_Header__c,Observation_Request__c from HL7__c where Id in :sID WITH SECURITY_ENFORCED];
        for(HL7__c Hl7Msg : listOfHL7){
            if(Hl7Msg.Full_HL7_Dump_Message__c!=null){                 
                Hl7MessageParsing.Parse(Hl7Msg);   
                Hl7MsgList.add(Hl7Msg);
            }            
        }
        DMLManager.updateAsUser(Hl7MsgList);  
        
       /* List<HL7__c> Hl7MsgList=new List<HL7__c>();
        List<HL7__c> listOfHL7 = [Select Id,Full_HL7_Dump_Message__c,Patient_Identification__c,Message_Header__c,Observation_Request__c from HL7__c where Id =: sID WITH SECURITY_ENFORCED];
        for(HL7__c Hl7Msg : listOfHL7){
            if(Hl7Msg.Full_HL7_Dump_Message__c!=null){                 
                Hl7MessageParsing.Parse(Hl7Msg);   
                Hl7MsgList.add(Hl7Msg);
            }            
        }
        //update Hl7MsgList;   
DMLManager.updateAsUser(Hl7MsgList);*/}
}