force-app/main/default/objects/Form_Object__mdt/Form_Object__mdt.object-meta.xml
<CustomObject>
    <label>Form Object</label>
    <pluralLabel>Form Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/Form_Object__mdt/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/Form_Value__c.object-meta.xml
<CustomObject>
    <description>Form value stores all the miscellaneous features of the saved forms like Approvals, Care Episodes and Status. All the problems, diagnoses, medications and allergies selected on the forms are also linked with this object as the record in this object is also responsible for giving one identity to the forms saved in multiple objects.</description>
    <label>Form Value</label>
    <nameField>
        <label>Form Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Value__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Form Values</relationshipLabel>
    <relationshipName>Form_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Approval_Level__c.field-meta.xml
<CustomField>
    <fullName>Approval_Level__c</fullName>
    <label>Approval Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Approved_Signature__c.field-meta.xml
<CustomField>
    <fullName>Approved_Signature__c</fullName>
    <label>Approved Signature</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Date_Of_Approval__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Approval__c</fullName>
    <label>Date Of Approval</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Form_Detail__c.field-meta.xml
<CustomField>
    <fullName>Form_Detail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Form Detail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Form_Id__c.field-meta.xml
<CustomField>
    <fullName>Form_Id__c</fullName>
    <label>Form Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Form_Name__c.field-meta.xml
<CustomField>
    <fullName>Form_Name__c</fullName>
    <label>Form Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Is_Approver__c.field-meta.xml
<CustomField>
    <fullName>Is_Approver__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Approver</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Waiting For Patient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Form_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Signature_Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Signature_Attachment_Id__c</fullName>
    <label>Signature Attachment Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Verification_Code__c.field-meta.xml
<CustomField>
    <fullName>Verification_Code__c</fullName>
    <label>Verification Code</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Verification_Code_New__c.field-meta.xml
<CustomField>
    <fullName>Verification_Code_New__c</fullName>
    <label>Verification Code New</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SessionNotesSignature.cls
public with sharing class SessionNotesSignature {
    @AuraEnabled
    public static void checkValidation(string eventid){
        set<String> formSessionId = new set<String>();
        List<Event> evtlst = new List<Event>();
        Set<string> formValueId = new Set<string>();
        List<Form_Value__c> formLst = new List<Form_Value__c>();
        
        evtlst = [SELECT Id, WhoId, WhatId, Subject, ElixirSuite__Form_Unique_Id__c, 
                  ElixirSuite__Parent_Event_Id__c 
                  FROM Event
                  where ElixirSuite__Parent_Event_Id__c =: eventid
                  WITH SECURITY_ENFORCED];
        if(evtlst != null && evtlst.size() >0){
            for(Event recid :evtlst){
                if(recid.ElixirSuite__Form_Unique_Id__c != null){
                    formSessionId.add(recid.ElixirSuite__Form_Unique_Id__c);
                }
                
            }
        }
        System.debug('formSessionId**'+formSessionId);
        if(formSessionId != null && formSessionId.size() > 0){
            formLst = [SELECT Id, ElixirSuite__Account__c, ElixirSuite__Form_Id__c, 
                       ElixirSuite__Form_Name__c,Is_Approver__c 
                       FROM ElixirSuite__Form_Value__c
                       WHERE ElixirSuite__Form_Id__c IN:formSessionId
                       WITH SECURITY_ENFORCED];
            if(formLst != null && formLst.size() > 0){
                for(Form_Value__c rec : formLst){
                    if(rec.Is_Approver__c == true){
                        formValueId.add(rec.ElixirSuite__Form_Id__c);
                    }
                }
            }
        }
        
        
        if(formSessionId.size() == 0)
        {
            AuraHandledException e = new AuraHandledException('No notes exist for this session');
            e.setMessage('No notes exist for this session');
            throw e;
        }
        if(formSessionId.size() == formValueId.size())
        {
            AuraHandledException e = new AuraHandledException('All notes are already signed for this session');
            e.setMessage('All notes are already signed for this session');
            throw e;
        }
        
    }
    @AuraEnabled
    public static void approveForm(string eventid,String code, String comments){
        try {
            List<Event> evtlst = new List<Event>();
            set<String> formId = new set<String>();
            List<Form_Value__c> formDetails = new List<Form_Value__c>();
            Set<String> metadataObjects = new Set<String>();
            Set<id> userIds = new Set<id>();
            String signature;
            String userId;
            List<Event> eventAssignedID =[SELECT Id, WhoId, WhatId,OwnerId
                                          FROM Event
                                          where Id =: eventid
                                          WITH SECURITY_ENFORCED];
            if(eventAssignedID != null && eventAssignedID.size() >0){
                for(Event ids :eventAssignedID){
                    if(ids.id == eventid){
                        userIds.add(ids.OwnerId);
                    }
                    
                }
            }
             System.debug('userIds**'+userIds);
            if(userIds != null){
                
                User users = [SELECT Id, Signature_Attachment_Id__c, Verification_Code__c, Verification_Code_New__c
                              FROM User 
                              WHERE Id IN:userIds WITH SECURITY_ENFORCED LIMIT 1];
                if(users != null){
                    String verificationCode = users.Verification_Code_New__c;
                    userId = users.Id;
                    signature = users.Signature_Attachment_Id__c;
                    if(String.isBlank(signature)){
                        AuraHandledException e = new AuraHandledException('Please Register Signature First!');
                        e.setMessage('Please Register Signature First!');
                        throw e;
                    }
                    if(code != verificationCode){
                        AuraHandledException e = new AuraHandledException('Verification Failed!');
                        e.setMessage('Verification Failed!');
                        throw e;
                    }
                }
            }
            evtlst = [SELECT Id, WhoId, WhatId, Subject, ElixirSuite__Form_Unique_Id__c, 
                      ElixirSuite__Parent_Event_Id__c,OwnerId
                      FROM Event
                      where ElixirSuite__Parent_Event_Id__c =: eventid
                      WITH SECURITY_ENFORCED];
            if(evtlst != null && evtlst.size() >0){
                for(Event formuniqueid :evtlst){
                    formId.add(formuniqueid.ElixirSuite__Form_Unique_Id__c);
                }
            }
           
            if(formId != null && formId.size() >0){
                Set<string> formValueId = new Set<string>();
                List<Form_Value__c> formrecords = new List<Form_Value__c>();
                List<Form_Object__mdt> metadata = [SELECT Id, QualifiedApiName, Object_Name__c FROM Form_Object__mdt WHERE Object_Name__c!=NULL WITH SECURITY_ENFORCED LIMIT 1];//Getting metadata
                if(metadata!=null && metadata.size()>0){ 
                    metadataObjects = new Set<String>(metadata[0].Object_Name__c.split(';'));
                }
                formrecords = [SELECT Id, ElixirSuite__Account__c, ElixirSuite__Form_Id__c, 
                               ElixirSuite__Form_Name__c,Is_Approver__c 
                               FROM ElixirSuite__Form_Value__c
                               WHERE ElixirSuite__Form_Id__c IN:formId
                               WITH SECURITY_ENFORCED];
                if(formrecords != null && formrecords.size() > 0){
                    for(Form_Value__c rec : formrecords){
                        if(rec.Is_Approver__c == true){
                            formValueId.add(rec.ElixirSuite__Form_Id__c);
                        }
                    }
                }
                System.debug('formValueId**'+formValueId);
                for(String column : metadataObjects){
                    
                    String objectName = column;
                    
                    if(objectName == 'ONLYTEXT'){
                        continue;
                    }
                    
                    if(objectName.endsWithIgnoreCase('__c')){
                        system.debug(objectName);
                        String defineQuery = 'SELECT Id, AccountId__c, Form_Name__c, Form_unique_id__c, Event_Id__c FROM '+ String.escapeSingleQuotes(objectName) + ' WHERE Form_unique_id__c IN:formId AND Form_unique_id__c!=NULL' ;
                        // String defineQuery = 'SELECT Id FROM '+ +objName + ' WHERE Form_unique_id__c IN :String.escapeSingleQuotes(lstRecordId) AND Form_unique_id__c!=NULL' ;
                        
                        List<sObject> records = Database.query(defineQuery);
                        System.debug('records**'+records);
                        for(sObject obj : records){
                            String patientId = String.valueOf(obj.get('AccountId__c'));
                            String formUniqueId = String.valueOf(obj.get('Form_unique_id__c'));
                            String formName = String.valueOf(obj.get('Form_Name__c'));
                            if(!formValueId.contains(formUniqueId)){
                                System.debug('formValueId**'+formUniqueId);
                                Form_Value__c approvalValue = new Form_Value__c();
                                approvalValue.Account__c = patientId;
                                approvalValue.Form_Id__c = formUniqueId;
                                approvalValue.Form_Name__c = formName;
                                approvalValue.User__c = userId;
                                approvalValue.Approval_Level__c =  '1';
                                approvalValue.Comment__c = comments;
                                approvalValue.Approved_Signature__c = signature;
                                approvalValue.Date_Of_Approval__c = System.now();
                                approvalValue.Is_Approver__c = true;
                                approvalValue.Status__c = 'Completed';
                                approvalValue.Form_Detail__c = true;
                                formDetails.add(approvalValue);
                            }
                        }
                        DMLManager.insertAsUser(formDetails);
                        
                    }
                    
                }      
            }
        }
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
}