force-app/main/default/objects/Form_Value__c/Form_Value__c.object-meta.xml
<CustomObject>
    <description>Form value stores all the miscellaneous features of the saved forms like Approvals, Care Episodes and Status. All the problems, diagnoses, medications and allergies selected on the forms are also linked with this object as the record in this object is also responsible for giving one identity to the forms saved in multiple objects.</description>
    <label>Form Value</label>
    <nameField>
        <label>Form Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_1_css__c/Object_1_css__c.object-meta.xml
<CustomObject>
    <description>Form css stores all the attributes that defines how a form will look like when you view a form. All configuration records are saved in this object from Form Configuration screen.</description>
    <label>Form css</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Object 1 css Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form css</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_1_css__c/fields/Object_1_css__c.field-meta.xml
<CustomField>
    <fullName>Object_1_css__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Object 1 css</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Section_Number__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Object_1_css__c</referenceTo>
    <relationshipName>Object_1_css</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FormApprovalData.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-10-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class FormApprovalData {
    public class currentUserInfo{
        @AuraEnabled public Id userId {get;set;}
        @AuraEnabled public Id profileId {get;set;}
        @AuraEnabled public Id roleId {get;set;}
        @AuraEnabled public List<Object_1_css__c> defaultApprovalLevels {get;set;}
        @AuraEnabled public List<Form_Value__c> approvedValues {get;set;}
        @AuraEnabled public List<List<Form_Value__c>> previousApprovedValues {get;set;}
        public void setUserId(){
            this.userId = UserInfo.getUserId();
            //methods
        }
        public void setProfileId(){
            this.profileId = UserInfo.getProfileId();
        }
        public void setRoleId(){
            this.roleId = UserInfo.getUserRoleId();
        }
        public void setDefaultLevels(List<Object_1_css__c> defaultApprovalLevels){
            this.defaultApprovalLevels = defaultApprovalLevels;
        }
        public void setApprovedValues(List<Form_Value__c> approvedValues){
            this.approvedValues = approvedValues;
        }
        public void setpreviousApprovedValues(List<List<Form_Value__c>> previousApprovedValues){
            this.previousApprovedValues = previousApprovedValues;
        }
    }
}