force-app/main/default/objects/Procedure__c/Procedure__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the template procedures in the system. These might include lab order, medications, CPT codes, Appointment procedures.</description>
    <label>Procedure Codes</label>
    <nameField>
        <label>Code Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedure Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Procedure__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Procedures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Procedure__c/recordTypes/Template_Procedure.recordType-meta.xml
<RecordType>
    <fullName>Template_Procedure</fullName>
    <active>true</active>
    <label>Template Procedure</label>
</RecordType>

force-app/main/default/classes/CreatePaymentTransaction.cls
public with sharing class CreatePaymentTransaction {    
    public static void updateCharges(List<Procedure__c> procedureList,Map<Id,Procedure__c> oldmap,Boolean isInsert, Boolean isUpdate){
        Set<Id> patientAccIdSet = new Set<Id>();
        List<Procedure__c> filteredProcedures = new List<Procedure__c>();  
        List<Procedure__c> procCareRecIds = new List<Procedure__c>();
        try{
        for(Procedure__c procedureRec : procedureList){  
            
            if(procedureRec.Account__c != null && procedureRec.RecordType.DeveloperName != 'Template_Procedure'){            
                patientAccIdSet.add(procedureRec.Account__c); 
                filteredProcedures.add(procedureRec);
            }
            if(procedureRec.Account__c != null && procedureRec.RecordType.DeveloperName != 'Template_Procedure' && procedureRec.ElixirSuite__Visits__c != null){
                procCareRecIds.add(procedureRec);
            }
        }
        }
        catch(Exception e){
            ExceptionLog.logError(e);
        }
        if(isInsert){
       CreatePaymentTransactionHelper.updateCharges(patientAccIdSet, filteredProcedures,null, isInsert,  isUpdate);
       CreatePaymentTransactionHelper.afterInsertAttachProvider(procCareRecIds);
        }else if(isUpdate){
            CreatePaymentTransactionHelper.updateCharges(patientAccIdSet, filteredProcedures, oldmap, isInsert,  isUpdate);
        }
    }
   
    public static void afterProcedureInsertCharges(List<Procedure__c> procedureList){
        Set<Id> patientAccIdSet = new Set<Id>();
        Set<Id> procedureRecIds = new Set<Id>();
        List<Procedure__c> filteredProcedures = new List<Procedure__c>();  
        try{
        for(Procedure__c procedureRec : procedureList){  
            
            if(procedureRec.Account__c != null && procedureRec.RecordType.DeveloperName != 'Template_Procedure'){  
                procedureRecIds.add(procedureRec.Id);
                patientAccIdSet.add(procedureRec.Account__c); 
                filteredProcedures.add(procedureRec);
            }
        }
        }
        catch(Exception e){
            ExceptionLog.logError(e);
        }
        CreatePaymentTransactionHelper.afterInsert(patientAccIdSet, filteredProcedures);
    }
    public static void afterProcedureupdation(List<Procedure__c> procedureList){
        Set<Id> patientAccIdSet = new Set<Id>();
        Set<Id> procedureRecIds = new Set<Id>();
        List<Procedure__c> filteredProcedures = new List<Procedure__c>();  
        try{
        for(Procedure__c procedureRec : procedureList){  
            
            if(procedureRec.Account__c != null && procedureRec.RecordType.DeveloperName != 'Template_Procedure'){  
                procedureRecIds.add(procedureRec.Id);
                patientAccIdSet.add(procedureRec.Account__c); 
                filteredProcedures.add(procedureRec);
            }
        }
        }
        catch(Exception e){
            ExceptionLog.logError(e);
        }
        CreatePaymentTransactionHelper.afterUpdate(patientAccIdSet, filteredProcedures,procedureRecIds);
    }
   
}