force-app/main/default/objects/Estimates__c/Estimates__c.object-meta.xml
<CustomObject>
    <description>This object stores the patient and insurance responsibility calculated via cost of calculator.</description>
    <label>Estimates</label>
    <nameField>
        <displayFormat>Est-{0000}</displayFormat>
        <label>Estimates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimates__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOB__c/VOB__c.object-meta.xml
<CustomObject>
    <description>This object tracks the verification of benefits/Patient Insurance details.</description>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VOB__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associated the patient with Account.</description>
    <label>Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurance</relationshipLabel>
    <relationshipName>VOB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EstimateListViewApexForOppTest.cls
@isTest
public class EstimateListViewApexForOppTest {
@testSetup
    public static void createTestData() {
        
        Account patient = TestDataFactory.createPatientAcc();
		insert patient;
        
        VOB__c newVob = TestDataFactory.createVOB();
        insert newVob ;
    }
@isTest
    public static void BringDataTest(){
       List<Account> patAccList = [Select id from Account];
        List<VOB__c> vobDataList = [Select id from VOB__c];
        Account patAcc = patAccList[0];
        VOB__c vobData = vobDataList[0];
        Estimates__c estimateRec = new Estimates__c();
        estimateRec.Account__c = patAcc.Id;
        insert estimateRec;
        
        test.startTest();
        EstimateListViewApexForOpp.BringData(String.valueOf(patAcc.Id), vobData.Id);
        EstimateListViewApexForOpp.BringDataViewAll(String.valueOf(patAcc.Id), vobData.Id);
        EstimateListViewApexForOpp.BringFilterData(String.valueOf(Date.today()), String.valueOf(Date.today()), String.valueOf(patAcc.Id),vobData.Id);
        EstimateListViewApexForOpp.BringFilterDataViewAll(String.valueOf(Date.today()), String.valueOf(Date.today()), String.valueOf(patAcc.Id),vobData.Id);
        EstimateListViewApexForOpp.LicensBasdPermission();
        System.assertEquals(1, 1, '');
        test.stopTest();
    }
}