force-app/main/default/objects/Dataset1__c/Dataset1__c.object-meta.xml
<CustomObject>
    <label>Patient Problem</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patient Problems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dataset1__c/fields/Template_Problem__c.field-meta.xml
<CustomField>
    <fullName>Template_Problem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Problem Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Template_Problem__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Problem</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Template_Problem__c</referenceTo>
    <relationshipLabel>Patient Problems</relationshipLabel>
    <relationshipName>Problems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Template_Problem__c/Template_Problem__c.object-meta.xml
<CustomObject>
    <description>Template Problem stores the Master Data of problems.</description>
    <label>Template Problem</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Template Problems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Template_Problem__c/fields/SNOMED_CT_Code__c.field-meta.xml
<CustomField>
    <fullName>SNOMED_CT_Code__c</fullName>
    <label>SNOMED CT Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Template_Problem__c/recordTypes/Problem.recordType-meta.xml
<RecordType>
    <fullName>Problem</fullName>
    <active>true</active>
    <label>Problem</label>
</RecordType>

force-app/main/default/classes/PopulateInfoInPatientProblemTest.cls
@isTest
public class PopulateInfoInPatientProblemTest {
	@isTest
    public static void createPatientProblem(){
        Id problemRecType = Schema.SObjectType.ElixirSuite__Template_Problem__c.getRecordTypeInfosByDeveloperName().get('Problem').getRecordTypeId();
        Template_Problem__c temp = new Template_Problem__c();
        temp.Name = 'Test';
        temp.SNOMED_CT_Code__c = '123';
        temp.RecordTypeId = problemRecType;
        insert temp;
        
        Dataset1__c pProblem = new Dataset1__c();
        pProblem.Name = 'Patient Problem';
        pProblem.Template_Problem__c = temp.Id;
        insert pProblem;
        
        System.assertEquals(1, 1, '');
    }
}