force-app/main/default/objects/Dataset1__c/Dataset1__c.object-meta.xml
<CustomObject>
    <label>Patient Problem</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patient Problems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dataset1__c/fields/ICD_codes__c.field-meta.xml
<CustomField>
    <fullName>ICD_codes__c</fullName>
    <label>ICD codes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>TO BE DEPRECATED:
Form was used to store all the forms related to the patient.</description>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ICD_Codes__c/ICD_Codes__c.object-meta.xml
<CustomObject>
    <description>Diagnosis Code stores diagnosis code along with their ICDs.
Both template and patient related diagnosis are stored in this object differentiated by the record type.</description>
    <label>Diagnosis Code</label>
    <nameField>
        <label>Code Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diagnoses Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ICD_Codes__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>This field is used to add the notes while adding the diagnosis.</description>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Master_Object__c/Master_Object__c.object-meta.xml
<CustomObject>
    <label>Record</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Object__c/fields/Master_Object__c.field-meta.xml
<CustomField>
    <fullName>Master_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Object</label>
    <referenceTo>Master_Object__c</referenceTo>
    <relationshipLabel>Master Objects</relationshipLabel>
    <relationshipName>Master_Objects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Object__c/fields/Object_Category__c.field-meta.xml
<CustomField>
    <fullName>Object_Category__c</fullName>
    <label>Object Category</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Master_Object__c/fields/Object_Color__c.field-meta.xml
<CustomField>
    <fullName>Object_Color__c</fullName>
    <label>Object Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Object__c/fields/Patient_Account_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Patient_Account_Lookup__c</fullName>
    <label>Patient Account Lookup</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Object__c/recordTypes/Timeline_Configuration.recordType-meta.xml
<RecordType>
    <fullName>Timeline_Configuration</fullName>
    <active>true</active>
    <label>Timeline Configuration</label>
</RecordType>

force-app/main/default/objects/Medical_Examination__c/Medical_Examination__c.object-meta.xml
<CustomObject>
    <label>Medical Examination</label>
    <nameField>
        <displayFormat>ME-{000}</displayFormat>
        <label>Medical Examination</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Examinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notes__c/Notes__c.object-meta.xml
<CustomObject>
    <label>Notes</label>
    <nameField>
        <displayFormat>NT-{0000}</displayFormat>
        <label>Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notes__c/fields/Dataset1__c.field-meta.xml
<CustomField>
    <fullName>Dataset1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dataset1</label>
    <referenceTo>Dataset1__c</referenceTo>
    <relationshipLabel>Notes (Dataset1)</relationshipLabel>
    <relationshipName>Notes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notes__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notes__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/Prescription_Order__c.object-meta.xml
<CustomObject>
    <label>Prescription Order</label>
    <nameField>
        <displayFormat>Prescription Order-{0000}</displayFormat>
        <label>Prescription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescription Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prescription_Order__c/fields/Prescription_Order__c.field-meta.xml
<CustomField>
    <fullName>Prescription_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prescription Order</label>
    <referenceTo>Prescription_Order__c</referenceTo>
    <relationshipLabel>Prescription Order</relationshipLabel>
    <relationshipName>Prescription_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ElixirOEM_TimelineHelper.cls
/*
Developer Name : Tanveer Ahmed
Created Date : 07 / 12 / 2020  2:00PM
Purpose : To send data of Master objects(Timeline Configuration Object) and it's records to timeline component
*/
public with sharing class ElixirOEM_TimelineHelper { 
    //Added by Ashwini
    @AuraEnabled
    public static string fetchAccountName(string accountId){
        List<Account> acc=[SELECT Id, name FROM Account WHERE Id= :accountId WITH SECURITY_ENFORCED];
        string accName = acc[0].name;
        return accName;
    }
    @AuraEnabled 
    public static ParentWrapperForAllAccountInformation parentMethod_FetchAllData(String acctId) {
        System.debug('init ');
        Map<String,List<sObject>> dirtyMap = new Map<String,List<sObject>>();
        Map<String,List<sObject>> allDataOnGraph = new Map<String,List<sObject>>();
        Map<String,List<sObject>> objectNameAndDataMap = new Map<String,List<sObject>>();
        List<DisplayGraphdataWrappper> tolist = new List<DisplayGraphdataWrappper>();
        String recType =  Schema.SObjectType.ElixirSuite__Master_Object__c.getRecordTypeInfosByDeveloperName().get('Timeline_Configuration').getRecordTypeId();
        List<Master_Object__c> allObjectsToDisplayOnTimeline = [SELECT CreatedById,CreatedDate,Id,Object_Color__c,IsDeleted,LastModifiedById,LastModifiedDate,Name,
                                                                Object_API_Name__c,Object_Category__c,Object_Name__c,OwnerId,Patient_Account_Lookup__c,
                                                                Sort_Order__c FROM Master_Object__c WHERE RecordTypeId =:recType
                                                                WITH SECURITY_ENFORCED LIMIT 49999];
        
        if(allObjectsToDisplayOnTimeline!=null && allObjectsToDisplayOnTimeline.size()>0){
            List<TimelineSortWrapper> toSortTimeLineObjects = new List<TimelineSortWrapper>();
            for(Master_Object__c toAddRecords : allObjectsToDisplayOnTimeline){
                toSortTimeLineObjects.add(new TimelineSortWrapper(toAddRecords));          
            }
            toSortTimeLineObjects.sort();
            allObjectsToDisplayOnTimeline = new List<Master_Object__c>();
            List<Master_Object__c> getData = new List<Master_Object__c>();
            for(TimelineSortWrapper f : toSortTimeLineObjects){              
                allObjectsToDisplayOnTimeline.add(f.oppy);  
            }
            System.debug('allObjectsToDisplayOnTimeline '+allObjectsToDisplayOnTimeline);
            for(Integer i=0;i<allObjectsToDisplayOnTimeline.size();i++){
                
                String objectName = allObjectsToDisplayOnTimeline[i].ElixirSuite__Object_API_Name__c;     
                System.debug('objectName '+objectName);
                String fieldApiNames = String.escapeSingleQuotes(getAllFieldsNameOfObject(objectName));
                fieldApiNames+=' FROM '+ String.escapeSingleQuotes(objectName) 
                    + ' WHERE ' + String.escapeSingleQuotes(allObjectsToDisplayOnTimeline[i].ElixirSuite__Patient_Account_Lookup__c) + ' = '+ '\''+
                    String.escapeSingleQuotes(acctId)+'\'';
                mDebugUntruncated(fieldApiNames);
                List<sObject> objectWiseData = new List<sObject>();
                objectWiseData = Database.query(fieldApiNames);
                objectNameAndDataMap.put(objectName,objectWiseData);
                allDataOnGraph.put(allObjectsToDisplayOnTimeline[i].Object_Category__c,objectWiseData);
            }
            list<Master_Object__c> sameObjectCategoryRecords = new list<Master_Object__c>();
            for(Master_Object__c rec : allObjectsToDisplayOnTimeline){
                if(dirtyMap.containsKey(rec.Object_Category__c)){
                    sameObjectCategoryRecords.add(rec);
                    List<sObject> getCurrentIndexList = dirtyMap.get(rec.Object_Category__c);
                    getCurrentIndexList.add(rec);
                    dirtyMap.put(rec.Object_Category__c,getCurrentIndexList);
                }
                else {
                    list<Master_Object__c> currentInstanceList = new list<Master_Object__c>();
                    currentInstanceList.add(rec);
                    dirtyMap.put(rec.Object_Category__c,currentInstanceList);
                }
                
            }
            for(String iterationOverKey : dirtyMap.keySet()){
                DisplayGraphdataWrappper dirtyWrapperInstance  = new DisplayGraphdataWrappper();
                dirtyWrapperInstance.objectCategory = iterationOverKey;
                dirtyWrapperInstance.data = dirtyMap.get(iterationOverKey);
                tolist.add(dirtyWrapperInstance);
            }
            for(String dataKeys : allDataOnGraph.keySet()){
                for(DisplayGraphdataWrappper dirtyRecords : tolist){
                    if(dirtyRecords.objectCategory == dataKeys){
                        dirtyRecords.allObjectDataForGraph = (allDataOnGraph.get(dirtyRecords.objectCategory));
                    }
                }
            }
        }
        System.debug('dirty map' +dirtyMap);
        
        
        ParentWrapperForAllAccountInformation toReturnParentWrapper = new ParentWrapperForAllAccountInformation(); 
        toReturnParentWrapper.allObjectsToDisplayOnTimeline=allObjectsToDisplayOnTimeline;
        toReturnParentWrapper.allDataOnGraph = allDataOnGraph;
        toReturnParentWrapper.cleanMapOfGraphObjects = dirtyMap;
        toReturnParentWrapper.rootDataObject = tolist;
        toReturnParentWrapper.objectNameAndDataMap = objectNameAndDataMap;
        toReturnParentWrapper.nameSpace= Elixir_Utility.getNamespace();
        toReturnParentWrapper.baseURL = System.URL.getSalesforceBaseUrl().toExternalForm();
        System.debug('---> '+toReturnParentWrapper);
        return toReturnParentWrapper;
    }
    @AuraEnabled
    public static  List<sObject> fetchObjectdataIfChecked(String lookupField, String objectName,String acctId) {
        String startAppendingQueryItems = String.escapeSingleQuotes(getAllFieldsNameOfObject(objectName));
        startAppendingQueryItems+=' FROM '+ String.escapeSingleQuotes(objectName) + ' WHERE ' + String.escapeSingleQuotes(lookupField) + ' = '+ '\''+
            String.escapeSingleQuotes(acctId)+'\'';
        mDebugUntruncated(startAppendingQueryItems);
        List<sObject> parentData = Database.query(startAppendingQueryItems);
        return parentData;
    }
    public class ParentWrapperForAllAccountInformation {     
        @AuraEnabled public List<DisplayGraphdataWrappper> rootDataObject {get;set;}
        @AuraEnabled public Map<String,List<sObject>> cleanMapOfGraphObjects {get;set;}
        @AuraEnabled public  Map<String,List<sObject>> allDataOnGraph {get;set;}
        @AuraEnabled public List<Master_Object__c> allObjectsToDisplayOnTimeline {get;set;}
        @AuraEnabled public  List<Medical_Examination__c> listOfAllergy{ get; set; }
        @AuraEnabled public  List<Prescription_Order__c> listOfMedication{ get; set; }
        @AuraEnabled public User currentUser { get; set; }
        @AuraEnabled public List<Dataset1__c> parentProblems {get;set;}
        @AuraEnabled public List<Notes__c> listOfrelatedNotes {get;set;}
        @AuraEnabled public Integer dynamicOffset{get;set;}
        @AuraEnabled public List<ICD_Codes__c> listOfRelatedDaignoses {get;set;}
        @AuraEnabled public List<Form__c> formData{ get; set; }
        @AuraEnabled public String VerficationCode{ get; set; }
        @AuraEnabled public String userVerifyCode{ get; set; }
        @AuraEnabled public List<Account> acctDetails{ get; set; }
        @AuraEnabled public List<Medical_Examination__c> vitalData{ get; set; }
        @AuraEnabled public List<Medical_Examination__c> glucoseData{ get; set; }
        @AuraEnabled public Map<String,List<sObject>> objectNameAndDataMap {get;set;}
        @AuraEnabled public String nameSpace;
        @AuraEnabled public String baseURL;
    }
    public class DisplayGraphdataWrappper{
        @AuraEnabled public String objectCategory;
        @AuraEnabled public Boolean isObjectOnGraph;
        @AuraEnabled  public List<Master_Object__c> data;
        @AuraEnabled  public List<sObject> allObjectDataForGraph= new List<sObject>();
    }
    public static String getAllFieldsNameOfObject(String objectName){
        if(objectName.endsWith('__c')){
            objectName = 'ElixirSuite__' + objectName;
        }
        String fieldApiNames = 'SELECT '; 
        Map <String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Map <String, Schema.SObjectField> fieldMap = schemaMap.get(objectName).getDescribe().fields.getMap();
        for(Schema.SObjectField sfield : fieldMap.Values())
        {
            schema.describefieldresult dfield = sfield.getDescribe();
            fieldApiNames+=dfield.getname()+',';
        }
        System.debug(fieldApiNames);
        fieldApiNames = fieldApiNames.removeEnd(',');
        return  fieldApiNames;
    }
    public static void mDebugUntruncated(String sMsg) {
        for (Integer i = 0; i < sMsg.length(); i=i+300) {
            Integer iEffectiveEnd = (i+300 > (sMsg.length()-1) ? sMsg.length()-1 : i+300);
            System.debug(sMsg.substring(i,iEffectiveEnd));
        }
    }
    @AuraEnabled
    public static void tryCallback() { 
    }
}