force-app/main/default/objects/Dataset1__c/Dataset1__c.object-meta.xml
<CustomObject>
    <label>Patient Problem</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patient Problems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Field__c/Form_Field__c.object-meta.xml
<CustomObject>
    <label>Form Field</label>
    <nameField>
        <displayFormat>Data-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Field__c/fields/Form_Field__c.field-meta.xml
<CustomField>
    <fullName>Form_Field__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Field</label>
    <referenceTo>Form_Field__c</referenceTo>
    <relationshipLabel>Form Fields</relationshipLabel>
    <relationshipName>Form_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notes__c/Notes__c.object-meta.xml
<CustomObject>
    <label>Notes</label>
    <nameField>
        <displayFormat>NT-{0000}</displayFormat>
        <label>Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notes__c/fields/Dataset1__c.field-meta.xml
<CustomField>
    <fullName>Dataset1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dataset1</label>
    <referenceTo>Dataset1__c</referenceTo>
    <relationshipLabel>Notes (Dataset1)</relationshipLabel>
    <relationshipName>Notes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notes__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/Prescription_Order__c.object-meta.xml
<CustomObject>
    <label>Prescription Order</label>
    <nameField>
        <displayFormat>Prescription Order-{0000}</displayFormat>
        <label>Prescription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescription Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prescription_Order__c/fields/Prescription_Order__c.field-meta.xml
<CustomField>
    <fullName>Prescription_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prescription Order</label>
    <referenceTo>Prescription_Order__c</referenceTo>
    <relationshipLabel>Prescription Order</relationshipLabel>
    <relationshipName>Prescription_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FirstVisitNotesController_Test.cls
@isTest
public class FirstVisitNotesController_Test 
{
    
	@isTest
    public static void getAcctSpecificProblemTest()
    {
        Account accId = new Account();
                
        FirstVisitNotesController.parentWrapper objParent = new FirstVisitNotesController.parentWrapper();
         List<Dataset1__c> relatedProblemsTest =objParent.relatedProblems;
         List<Form_Field__c > formFieldsTest =objParent.formFields;
         List<Prescription_Order__c > currentMedTest =objParent.currentMed;
         List<case> relatedProblems1Test =objParent.relatedProblems1;
        
        List<Prescription_Order__c> presList = new List<Prescription_Order__c>();
         Prescription_Order__c objpresc = new Prescription_Order__c();
         presList.add(objpresc);
        
        Notes__c N1 = new Notes__c();
        N1.ElixirSuite__Type__c ='Doctor Notes';
        N1.Notes__c = 'abc';
            insert N1;
        
       deserializeWrapper dobj = new deserializeWrapper();
        List<deserializeWrapper> desList = new List<deserializeWrapper>();
            desList.add(dobj);
        
        medicines mtest = new medicines();
        mtest.medications = desList;
        
        labOrders labTest = new labOrders();
        labTest.labOrders = desList;
        
        problems probTest = new problems();
        probTest.problems = desList;
        
        diagnosis diagTest = new diagnosis();
        diagTest.diagnosis = desList;

        List<vitals> vitList = new List<vitals>(); 
        vitals vitalTest = new vitals();
        vitalTest.height ='as';
        vitalTest.Weight ='sa';
        vitalTest.bpsys ='ss';
        vitalTest.bpDias ='aa';
        vitalTest.temp ='ww';
        vitalTest.pulse ='ee';
        vitalTest.oxySat ='rr';
        vitList.add(vitalTest);
       
        test.startTest();
        FirstVisitNotesController.getAcctSpecificProblem(accId.Id);
        FirstVisitNotesController.saveNotes(string.valueOf(accId.Id),N1.Notes__c,'abc','bca','cdf',JSON.serialize(mtest),'str',JSON.serialize(labTest),JSON.serialize(probTest),JSON.serialize(diagTest),JSON.serialize(vitalTest),presList,N1.ElixirSuite__Type__c);
        FirstVisitNotesController.getNotesData(N1.id);
        test.stopTest();
          System.assertEquals(1, 1, ' ');
         }
     public class medicines{
        List<deserializeWrapper> medications;
    }
    public class labOrders{
        List<deserializeWrapper> labOrders;
    } 
    public class problems{
        List<deserializeWrapper> problems;
    }
     public class diagnosis{
        List<deserializeWrapper> diagnosis;
    }
     public class deserializeWrapper{
        public String Id;
        public String FieldName;
        public String Description;
    }
     public class vitals{
        public String height;
        public String Weight;
        public String bpsys;
        public String bpDias;
        public String temp;
        public String pulse;
        public String oxySat; 
    }
    }