force-app/main/default/objects/Dataset1__c/Dataset1__c.object-meta.xml
<CustomObject>
    <label>Patient Problem</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patient Problems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dataset1__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Datasets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dataset1__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Dataset1__c/fields/ICD_codes__c.field-meta.xml
<CustomField>
    <fullName>ICD_codes__c</fullName>
    <label>ICD codes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Field__c/Form_Field__c.object-meta.xml
<CustomObject>
    <label>Form Field</label>
    <nameField>
        <displayFormat>Data-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Field__c/fields/Form_Field__c.field-meta.xml
<CustomField>
    <fullName>Form_Field__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Field</label>
    <referenceTo>Form_Field__c</referenceTo>
    <relationshipLabel>Form Fields</relationshipLabel>
    <relationshipName>Form_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frequency__c/Frequency__c.object-meta.xml
<CustomObject>
    <label>Frequency</label>
    <nameField>
        <displayFormat>Frequency-{0000}</displayFormat>
        <label>Frequency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Frequency</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Frequency__c/fields/Prescription_Order__c.field-meta.xml
<CustomField>
    <fullName>Prescription_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prescription Order</label>
    <referenceTo>Prescription_Order__c</referenceTo>
    <relationshipLabel>Frequency</relationshipLabel>
    <relationshipName>Frequency</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ICD_Codes__c/ICD_Codes__c.object-meta.xml
<CustomObject>
    <description>Diagnosis Code stores diagnosis code along with their ICDs.
Both template and patient related diagnosis are stored in this object differentiated by the record type.</description>
    <label>Diagnosis Code</label>
    <nameField>
        <label>Code Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diagnoses Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ICD_Codes__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate the diagnosis with the Patient.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Diagnosis Code</relationshipLabel>
    <relationshipName>Diagnosis_Code</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ICD_Codes__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>This field is used to add the notes while adding the diagnosis.</description>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Medical_Examination__c/Medical_Examination__c.object-meta.xml
<CustomObject>
    <label>Medical Examination</label>
    <nameField>
        <displayFormat>ME-{000}</displayFormat>
        <label>Medical Examination</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Examinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Examination__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Medical Examinations</relationshipLabel>
    <relationshipName>Medical_Examinations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Examination__c/fields/Blood_Pressure_Diasystolic__c.field-meta.xml
<CustomField>
    <fullName>Blood_Pressure_Diasystolic__c</fullName>
    <label>Blood Pressure Diastolic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medical_Examination__c/fields/Blood_Pressure_Systolic__c.field-meta.xml
<CustomField>
    <fullName>Blood_Pressure_Systolic__c</fullName>
    <label>Blood Pressure Systolic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medical_Examination__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Medical_Examination__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Before Breakfast</fullName>
            </value>
            <value>
                <fullName>After Breakfast</fullName>
            </value>
            <value>
                <fullName>Before Lunch</fullName>
            </value>
            <value>
                <fullName>After Lunch</fullName>
            </value>
            <value>
                <fullName>Before Dinner</fullName>
            </value>
            <value>
                <fullName>After Dinner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medical_Examination__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Notes__c/Notes__c.object-meta.xml
<CustomObject>
    <label>Notes</label>
    <nameField>
        <displayFormat>NT-{0000}</displayFormat>
        <label>Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notes__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notes__c/fields/Dataset1__c.field-meta.xml
<CustomField>
    <fullName>Dataset1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dataset1</label>
    <referenceTo>Dataset1__c</referenceTo>
    <relationshipLabel>Notes (Dataset1)</relationshipLabel>
    <relationshipName>Notes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notes__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/Prescription_Order__c.object-meta.xml
<CustomObject>
    <label>Prescription Order</label>
    <nameField>
        <displayFormat>Prescription Order-{0000}</displayFormat>
        <label>Prescription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescription Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prescription_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Prescription Order</relationshipLabel>
    <relationshipName>Prescription_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/fields/Drug_Name__c.field-meta.xml
<CustomField>
    <fullName>Drug_Name__c</fullName>
    <label>Drug Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/fields/End_time__c.field-meta.xml
<CustomField>
    <fullName>End_time__c</fullName>
    <label>End time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/fields/Ferquency__c.field-meta.xml
<CustomField>
    <fullName>Ferquency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Repeat</fullName>
            </value>
            <value>
                <fullName>Number Of Times</fullName>
            </value>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Weeks</fullName>
            </value>
            <value>
                <fullName>After every &apos;n’ hours</fullName>
            </value>
            <value>
                <fullName>After lunch</fullName>
            </value>
            <value>
                <fullName>After supper/Dinner</fullName>
            </value>
            <value>
                <fullName>Before Breakfast</fullName>
            </value>
            <value>
                <fullName>Custom pheno</fullName>
            </value>
            <value>
                <fullName>Once a day (AM)</fullName>
            </value>
            <value>
                <fullName>Once a day (HS)</fullName>
            </value>
            <value>
                <fullName>Once a day midday</fullName>
            </value>
            <value>
                <fullName>Once a day (Qam)</fullName>
            </value>
            <value>
                <fullName>Once a day (QHS)</fullName>
            </value>
            <value>
                <fullName>At a specific time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to select the master data of type = Frequency</description>
    <label>Frequency Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Master_Object__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Frequency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Object__c</referenceTo>
    <relationshipLabel>Prescription Order (Frequency)</relationshipLabel>
    <relationshipName>Prescription_Order2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/fields/Prescription_Order__c.field-meta.xml
<CustomField>
    <fullName>Prescription_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prescription Order</label>
    <referenceTo>Prescription_Order__c</referenceTo>
    <relationshipLabel>Prescription Order</relationshipLabel>
    <relationshipName>Prescription_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/fields/Start_time__c.field-meta.xml
<CustomField>
    <fullName>Start_time__c</fullName>
    <label>Start time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/recordTypes/Medication.recordType-meta.xml
<RecordType>
    <fullName>Medication</fullName>
    <active>true</active>
    <label>Medication</label>
</RecordType>

force-app/main/default/objects/UA_Sample_Details__c/UA_Sample_Details__c.object-meta.xml
<CustomObject>
    <label>UA Sample Detail</label>
    <nameField>
        <displayFormat>Lab Order-{0000}</displayFormat>
        <label>Lab Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UA Sample Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/UA_Sample_Details__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>UA Sample Details</relationshipLabel>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Once</fullName>
                <default>true</default>
                <label>Once</label>
            </value>
            <value>
                <fullName>Every Day</fullName>
            </value>
            <value>
                <fullName>Every 2 Days</fullName>
            </value>
            <value>
                <fullName>Every 3 Days</fullName>
            </value>
            <value>
                <fullName>Every 5 Days</fullName>
            </value>
            <value>
                <fullName>Every 7 Days</fullName>
            </value>
            <value>
                <fullName>Every 2 weeks</fullName>
            </value>
            <value>
                <fullName>Once a month</fullName>
            </value>
            <value>
                <fullName>On return from pass or outing</fullName>
            </value>
            <value>
                <fullName>When attending IOP/OP group</fullName>
            </value>
            <value>
                <fullName>Confirm positive analyzer results</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Medical_Test__c.field-meta.xml
<CustomField>
    <fullName>Medical_Test__c</fullName>
    <label>Medical Test</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/UA_Sample_Details__c.field-meta.xml
<CustomField>
    <fullName>UA_Sample_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UA Sample Details</label>
    <referenceTo>UA_Sample_Details__c</referenceTo>
    <relationshipLabel>UA Sample Details</relationshipLabel>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProgressNotesHelperFinal1.cls
public with sharing class ProgressNotesHelperFinal1 {
    @AuraEnabled
    public static parentWrapper abc(String acctId){
        List<Dataset1__c> relatedProblems = new List<Dataset1__c>();
      //  relatedProblems = [SELECT Account__c,id,Dataset1__c,Description__c,IsActive__c,Problem_Name__c,Templatized_Problem__c
                        //   FROM Dataset1__c where Account__c =: acctId WITH SECURITY_ENFORCED];
        List<Form_Field__c > formField = new List<Form_Field__c >();
        List<Prescription_Order__c > currentMeds = new List<Prescription_Order__c >();
        currentMeds=[SELECT id , name ,Account__c, Drug_Name__c,Notes__c
                     FROM Prescription_Order__c where Account__c=:acctId WITH SECURITY_ENFORCED];       
        parentWrapper toReturn = new parentWrapper();
      //  toReturn.relatedProblems = relatedProblems; 
        toReturn.currentMed = currentMeds ;
        return toReturn ;
    }
    public class parentWrapper {        
        @AuraEnabled public List<Dataset1__c> relatedProblems {get;set;}
        @AuraEnabled public List<Form_Field__c > formFields {get;set;}
        @AuraEnabled public List<Prescription_Order__c > currentMed {get;set;}
        @AuraEnabled public List<case> relatedProblems1 {get;set;}
    }
    
    @AuraEnabled
    public static void saveNotes(String accountId, String textBody, String newSocial, String newFamily,String newDiagnosis, String medicationsToSave, String carePlanDataParent , String labOrdersToSave,String problemsToSave, String diagToSave , String vitalsToSave, List<Prescription_Order__c> prescriptionsToSave){
        //Note added-START
        system.debug('accountId ' + accountId);
        Notes__c note = new Notes__c();
        try{
        note.Account__c = accountId;
        note.Notes__c = textBody;
        if(Schema.sObjectType.Notes__c.isCreateable() &&
        Schema.sObjectType.Notes__c.fields.Account__c.isCreateable() &&
        Schema.sObjectType.Notes__c.fields.Notes__c.isCreateable()){
            insert note;
        }
        }
        catch(Exception e){
            ExceptionLog.logError(e);
        }
        //Note added-END
        
        system.debug('json' + medicationsToSave);
        medicines med = (medicines) JSON.deserialize(medicationsToSave, medicines.class);
        system.debug('med' + med);
        
        if(med.medications!=null && med.medications.size()>0){
            List<Prescription_Order__c> medicationsToInsert = new List<Prescription_Order__c>(); 
            try{
            for(deserializeWrapper medication :med.medications){
                Prescription_Order__c medToInsert = new Prescription_Order__c();
                medToInsert.Drug_Name__c = medication.FieldName;
                medToInsert.Account__c  = accountId;
                medToInsert.Ferquency__c  = medication.Description;
                medicationsToInsert.add(medToInsert);
            }
            if(Schema.sObjectType.Prescription_Order__c.isCreateable() &&
            Schema.sObjectType.Prescription_Order__c.fields.Ferquency__c.isCreateable() &&
            Schema.sObjectType.Prescription_Order__c.fields.Drug_Name__c.isCreateable()){
                insert medicationsToInsert;
            }
            }
            catch(Exception e){
            ExceptionLog.logError(e);
        }
        }
        system.debug('lab' + problemsToSave);
        labOrders lab = (labOrders) JSON.deserialize(labOrdersToSave, labOrders.class);
        if(lab.labOrders!=null && lab.labOrders.size()>0){
            List<UA_Sample_Details__c> ordersToInsert = new List<UA_Sample_Details__c>(); 
            try{
            for(deserializeWrapper labOrder :lab.labOrders){
                UA_Sample_Details__c orderToInsert = new UA_Sample_Details__c();
                orderToInsert.Account__c = accountId;
                orderToInsert.Medical_Test__c = labOrder.FieldName;
                orderToInsert.Frequency__c = labOrder.Description;
                ordersToInsert.add(orderToInsert);
            }
            if(Schema.sObjectType.UA_Sample_Details__c.isCreateable() &&
            Schema.sObjectType.UA_Sample_Details__c.fields.Frequency__c.isCreateable() &&
            Schema.sObjectType.UA_Sample_Details__c.fields.Account__c.isCreateable() &&
            Schema.sObjectType.UA_Sample_Details__c.fields.Medical_Test__c.isCreateable()){
                insert ordersToInsert;
            }
            }
            catch(Exception e){
            ExceptionLog.logError(e);
        }
        }
        problems prob = (problems) JSON.deserialize(problemsToSave, problems.class);
        if(prob.problems!=null && prob.problems.size()>0){
            List<Dataset1__c> problemsToInsert = new List<Dataset1__c>(); 
            try{
            for(deserializeWrapper problem :prob.problems){
                Dataset1__c orderToInsert = new Dataset1__c();
                orderToInsert.Account__c = accountId;
                //orderToInsert.Care_Plan_Template_Problem__c  = problem.Id;
                //orderToInsert.Problem_Name__c  = problem.FieldName;
                //orderToInsert.Notes__c  = problem.Description;
                problemsToInsert.add(orderToInsert);
            }
            if(Schema.sObjectType.Dataset1__c.isCreateable() &&
            Schema.sObjectType.Dataset1__c.fields.Account__c.isCreateable()){
                insert problemsToInsert;
            }
            }
            catch(Exception e){
            ExceptionLog.logError(e);
        }
        }
        diagnosis diag = (diagnosis) JSON.deserialize(diagToSave, diagnosis.class);
        if(diag.diagnosis!=null && diag.diagnosis.size()>0){
            List<ICD_Codes__c> ordersToInsert = new List<ICD_Codes__c>(); 
            try{
            for(deserializeWrapper labOrder :diag.diagnosis){
                ICD_Codes__c orderToInsert = new ICD_Codes__c();
                //orderToInsert.Account__c = accountId;
                orderToInsert.Name  = labOrder.FieldName;
                // orderToInsert.Notes__c = labOrder.Description;
                ordersToInsert.add(orderToInsert);
            }
            if(Schema.sObjectType.ICD_Codes__c.isCreateable() &&
            Schema.sObjectType.ICD_Codes__c.fields.Name.isCreateable()){
                insert ordersToInsert;
            }
            }
            catch(Exception e){
            ExceptionLog.logError(e);
        }
        }
        
        system.debug('vitalsToSave '+vitalsToSave);
        vitals vitalSign = (vitals) JSON.deserialize(vitalsToSave, vitals.class);
        system.debug('vitalSign '+vitalSign);
        VitalWrapper vitalValues = vitalSign.vitals;
        system.debug(vitalValues);
        if(vitalValues!=null){          
            Medical_Examination__c vitalToInsert = new Medical_Examination__c();
            try{
            vitalToInsert.Account__c  = accountId;
            vitalToInsert.Blood_Pressure_Systolic__c  = vitalValues.bpsys!=''?string.valueOf(vitalValues.bpsys):null;
            vitalToInsert.Start_Time__c = System.now().addMinutes(-10);
            vitalToInsert.End_Time__c = System.now();
            //vitalToInsert.height__c = vitalValues.height!=''?Integer.valueOf(vitalValues.height):null;
            //vitalToInsert.weight__c = vitalValues.weight!=''?Integer.valueOf(vitalValues.weight):null;
            vitalToInsert.Blood_Pressure_Diasystolic__c = vitalValues.bpDias!=''?string.valueOf(vitalValues.bpDias):null;
            vitalToInsert.Temperature__c = vitalValues.temp!=''?string.valueOf(vitalValues.temp):null;
            vitalToInsert.Oxygen_Saturation__c  = vitalValues.oxySat!=''?string.valueOf(vitalValues.oxySat):null;
            vitalToInsert.Pulse__c  = vitalValues.pulse!=''?string.valueOf(vitalValues .pulse):null;
            if(Schema.sObjectType.Medical_Examination__c.isCreateable() &&
            Schema.sObjectType.Medical_Examination__c.fields.Account__c.isCreateable() &&
            Schema.sObjectType.Medical_Examination__c.fields.Blood_Pressure_Systolic__c.isCreateable() &&
            Schema.sObjectType.Medical_Examination__c.fields.Start_Time__c.isCreateable() &&
            Schema.sObjectType.Medical_Examination__c.fields.End_Time__c.isCreateable() &&
            Schema.sObjectType.Medical_Examination__c.fields.Blood_Pressure_Diasystolic__c.isCreateable() &&
            Schema.sObjectType.Medical_Examination__c.fields.Temperature__c.isCreateable() &&
            Schema.sObjectType.Medical_Examination__c.fields.Oxygen_Saturation__c.isCreateable() &&
            Schema.sObjectType.Medical_Examination__c.fields.Pulse__c.isCreateable()){
                insert vitalToInsert;
            }
            }
            catch(Exception e){
            ExceptionLog.logError(e);
        }
        }
        
        //Prescriptions To Save
        List<Prescription_Order__c> finalPRList = new List<Prescription_Order__c>();
        Prescription_Order__c preOrder = new Prescription_Order__c();
        Boolean ordFlag = false;
        if(prescriptionsToSave != null && prescriptionsToSave.size()>0)
        {
            for(Prescription_Order__c pr : prescriptionsToSave)
            {
                Prescription_Order__c newObj = new Prescription_Order__c();
                if(pr.Drug_Name__c != '')
                {
                    if(ordFlag == false)
                    {
                        // preOrder.Account__c = pr.Account__c;
                        ordFlag = true;
                    }
                    // newObj.HealthCloudGA__MedicationName__c = pr.HealthCloudGA__MedicationName__c;
                    //newObj.Frequency_for_jumpstartmd__c = pr.Frequency_for_jumpstartmd__c;
                    //newObj.HealthCloudGA__Account__c = pr.HealthCloudGA__Account__c;
                    newObj.Type__c = 'PRN';
                    
                    finalPRList.add(newObj);
                }
            }
            try
            {
                if(Schema.sObjectType.Prescription_Order__c.isCreateable() &&
                Schema.sObjectType.Prescription_Order__c.fields.Type__c.isCreateable()){
                insert preOrder;
                }
                for(Prescription_Order__c pr : finalPRList)
                {
                    pr.Prescription_Order__c = preOrder.Id;
                }
                if(Schema.sObjectType.Prescription_Order__c.isCreateable() &&
                Schema.sObjectType.Prescription_Order__c.fields.Prescription_Order__c.isCreateable()){
                    insert finalPRList;
                }
            }
            catch(Exception e)
            {
                ExceptionLog.logError(e);
                system.debug('#### Error : ' + e.getMessage());
            }
        }
    }
    @AuraEnabled
    public static String getNotesData(String recordVal){
        Notes__c allNotes = new Notes__c();
        allNotes = [SELECT Id, Name, RecordTypeId, CreatedDate, Account__c, Notes__c,Note__c, Parent_Account__c FROM Notes__c
                    WHERE id=:recordVal WITH SECURITY_ENFORCED];
        return allNotes.Notes__c ;
        
    }
    
    @AuraEnabled
    public static String addChiefComplaintsRec(List<Dataset1__c> ehrCondList)
    {
       /* List<Dataset1__c> problemsToInsert = new List<Dataset1__c>();
        if(ehrCondList != null && ehrCondList.size()>0)
        {
            for(Dataset1__c ehr : ehrCondList)
            {
                Dataset1__c obj = new Dataset1__c();
                if(ehr.Problem_Name__c != '')
                {
                    //obj.Problem_Name__c = ehr.Problem_Name__c;
                    // obj.HealthCloudGA__Notes__c = ehr.HealthCloudGA__Notes__c;
                    obj.Account__c = ehr.Account__c;
                    problemsToInsert.add(obj);
                }
                
            }
            try
            {
                System.debug('#### problemsToInsert : ' + problemsToInsert);
                if(Schema.sObjectType.Dataset1__c.isCreateable() &&
                Schema.sObjectType.Dataset1__c.fields.Account__c.isCreateable()){
                    insert problemsToInsert;
                }
                return 'SUCCESS';
            }
            catch(Exception ex)
            {
                return 'Error : ' + ex.getMessage();
            }
        }*/
        return null;
    }
    
    public class medicines{
        List<deserializeWrapper> medications;
    }
    public class labOrders{
        List<deserializeWrapper> labOrders;
    }
    public class problems{
        List<deserializeWrapper> problems;
    }
    public class diagnosis{
        List<deserializeWrapper> diagnosis;
    }
    public class deserializeWrapper{
        public String Id;
        public String FieldName;
        public String Description;
    }
    
    //For vitals
    public class vitals{
        public VitalWrapper vitals;
    }
    public class VitalWrapper{
        public String height;
        public String Weight;
        public String bpsys;
        public String bpDias;
        public String temp;
        public String pulse;
        public String oxySat;  
    }
    public static void dummyMethod(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;       
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;       
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;        
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;       
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}