force-app/main/default/objects/Clinician_Report__c/Clinician_Report__c.object-meta.xml
<CustomObject>
    <label>Clinician Report</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Clinician Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinician Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clinician_Report__c/fields/Clinical_Report_ID__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Report_ID__c</fullName>
    <externalId>true</externalId>
    <label>Clinical Report ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clinician_Report__c/fields/isDownloaded__c.field-meta.xml
<CustomField>
    <fullName>isDownloaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isDownloaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinician_Report__c/fields/isReportAvailable__c.field-meta.xml
<CustomField>
    <fullName>isReportAvailable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isReportAvailable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GetHL7UnsolicitedBatch.cls
global with sharing class GetHL7UnsolicitedBatch extends getHL7 implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query   = 'SELECT Id, Clinical_Report_ID__c,isReportAvailable__c FROM Clinician_Report__c Where isDownloaded__c=false';
        
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Clinician_Report__c> clinicianReportIds){
        
        
    }
    
    
    global void finish(Database.BatchableContext BC) {
        
    }
}