force-app/main/default/objects/Clinician_Report__c/Clinician_Report__c.object-meta.xml
<CustomObject>
    <label>Clinician Report</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Clinician Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinician Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clinician_Report__c/fields/Clinical_Report_ID__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Report_ID__c</fullName>
    <externalId>true</externalId>
    <label>Clinical Report ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clinician_Report__c/fields/PlacerOrder__c.field-meta.xml
<CustomField>
    <fullName>PlacerOrder__c</fullName>
<description>This field is used to store placer order number (CHC LabOrder Identification Number)</description>
    <label>PlacerOrder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Test</label>
    <nameField>
        <displayFormat>LabOrder-{0000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Lab_Order_Req__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order_Req__c</fullName>
<description>This field used to store placer order number</description>
    <label>Lab Order Req</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetHL7UnsolicitedBatchTest.cls
@isTest
private class GetHL7UnsolicitedBatchTest {
    
    @isTest static void testGetHL7Unsolicited() {
        /*Clinician_Report__c cc = new Clinician_Report__c();
        cc.ElixirSuite__isDownloaded__c = false;
        cc.Clinical_Report_ID__c = '12546';
        cc.PlacerOrder__c = '12365';
        insert cc;
        
        Lab_Order__c labOrder = new Lab_Order__c(
            Lab_Order_Req__c = 'ABC'
        );
        insert labOrder;
         Lab_Order__c labOrder2 = new Lab_Order__c(
            Lab_Order_Req__c = 'XYZ'
        );
        insert labOrder2;
        
        Test.setMock(HttpCalloutMock.class, new getHL7_Mock());
        
        Test.startTest();
        GetHL7UnsolicitedBatch unsolicited = new GetHL7UnsolicitedBatch();
        Database.executeBatch(unsolicited, 50);
        System.assertEquals(1, 1, ''); 
        Test.stopTest();*/
        System.assertEquals(1, 1, ''); 
    }
}