force-app/main/default/objects/Medical_Examination__c/Medical_Examination__c.object-meta.xml
<CustomObject>
    <label>Medical Examination</label>
    <nameField>
        <displayFormat>ME-{000}</displayFormat>
        <label>Medical Examination</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Examinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Examination__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Medical Examinations</relationshipLabel>
    <relationshipName>Medical_Examinations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Examination__c/fields/Blood_Pressure_Diasystolic__c.field-meta.xml
<CustomField>
    <fullName>Blood_Pressure_Diasystolic__c</fullName>
    <label>Blood Pressure Diastolic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medical_Examination__c/fields/Blood_Pressure_Systolic__c.field-meta.xml
<CustomField>
    <fullName>Blood_Pressure_Systolic__c</fullName>
    <label>Blood Pressure Systolic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medical_Examination__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Medical_Examination__c/fields/Form_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Form_Unique_ID__c</fullName>
    <label>Form Unique ID</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Medical_Examination__c/fields/Oxygen_Saturation__c.field-meta.xml
<CustomField>
    <fullName>Oxygen_Saturation__c</fullName>
    <label>SpO2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medical_Examination__c/fields/Pulse__c.field-meta.xml
<CustomField>
    <fullName>Pulse__c</fullName>
    <label>Pulse</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medical_Examination__c/fields/Respiration__c.field-meta.xml
<CustomField>
    <fullName>Respiration__c</fullName>
    <label>Respiration Rate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medical_Examination__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASSESSMENT</fullName>
            </value>
            <value>
                <fullName>RECORD DETAIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medical_Examination__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Medical_Examination__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/vitalSignsController.cls
public with sharing class vitalSignsController {
    
    @AuraEnabled
    public static List<Medical_Examination__c> getVitalSignsRecords(String AccID){
        system.debug('AccountId'+ AccID);
        Id devRecordTypeId = Schema.SObjectType.Medical_Examination__c.getRecordTypeInfosByName().get('Vital Sign').getRecordTypeId();
        List<Medical_Examination__c> vitalSigns = [select id,Respiration__c,Oxygen_Saturation__c, Blood_Pressure_Systolic__c,Blood_Pressure_diasystolic__c,
                                                   Temperature__c, Pulse__c, createdDate  ,CreatedBy.Name  from Medical_Examination__c 
                                                   where Account__c=:AccID AND RecordTypeId=:devRecordTypeId  
                                                   WITH SECURITY_ENFORCED
                                                   order by createdDate desc ];// And createdDate>TODAY and createdDate<TOMORROW];HealthCloudGA__ValueSampledDataOriginCodeLabel__cHealthCloudGA__ValueSampledDataOriginValue__cHealthCloudGA__ValueSampledDataOriginValue__c
        //system.debug('Account'+vitalSigns[0].createdDate.time());
        return vitalSigns;
    }
    @AuraEnabled
    public static User getCurrentlyLoggedInUser(){
        return [SELECT ID,Name from User where id=: UserInfo.getUserId() WITH SECURITY_ENFORCED];
    }
    
    @AuraEnabled
    public static List<Medical_Examination__c> saveVitalSignRecord(Medical_Examination__c ObservationRec, String AccID){
        system.debug('the obser are'+ ObservationRec);
 		system.debug('time' + system.now() + ' END ' + System.now().AddDays(-1)); 
        Id devRecordTypeId = Schema.SObjectType.Medical_Examination__c.getRecordTypeInfosByName().get('Vital Sign').getRecordTypeId();
        ObservationRec.Account__c=AccID;
        ObservationRec.RecordTypeId=devRecordTypeId;
        ObservationRec.Source__c = 'ASSESSMENT';
        ObservationRec.Start_Time__c = system.now();
        ObservationRec.End_Time__c = System.now().AddDays(-1);
        try{
        if(Schema.sObjectType.Medical_Examination__c.isAccessible() && Schema.sObjectType.Medical_Examination__c.isCreateable()
            && Schema.sObjectType.Medical_Examination__c.fields.Account__c.isCreateable()
            && Schema.sObjectType.Medical_Examination__c.fields.RecordTypeId.isCreateable()
            && Schema.sObjectType.Medical_Examination__c.fields.Source__c.isCreateable()
            && Schema.sObjectType.Medical_Examination__c.fields.Start_Time__c.isCreateable()
            && Schema.sObjectType.Medical_Examination__c.fields.End_Time__c.isCreateable()){
                insert ObservationRec;
            }
            }
            catch(Exception e){
            ExceptionLog.logError(e);
        
            }
       
       
        system.debug('ObservationRec--'+ObservationRec.Id);
        List<Medical_Examination__c> vitalSigns = [select id,Respiration__c,Oxygen_Saturation__c, Blood_Pressure_Systolic__c,Blood_Pressure_diasystolic__c,
                                                   Temperature__c, Pulse__c, createdDate,CreatedBy.Name from Medical_Examination__c where 
                                                   Account__c=:AccID AND RecordTypeId=:devRecordTypeId 
                                                   WITH SECURITY_ENFORCED
                                                   order by createdDate desc ];// And createdDate>TODAY and createdDate<TOMORROW];
        
        return vitalSigns ;
    }
    
    @AuraEnabled
    public static List<Medical_Examination__c> deleteVital(String vitalId , String AccID)
    {
        Medical_Examination__c delAccount=[Select Id , Account__c from Medical_Examination__c 
        where id=:vitalId WITH SECURITY_ENFORCED];
        if (Schema.sObjectType.Medical_Examination__c.isDeletable()) {
            delete delAccount;
        }
        return getVitalSignsRecords(AccID);
    }
    @AuraEnabled
    public static List<Medical_Examination__c> saveVitalSignRecord_AddedFromForm(Medical_Examination__c ObservationRec, String AccID,String formUniqueID){
        system.debug('the obser are'+ ObservationRec);
        Id devRecordTypeId = Schema.SObjectType.Medical_Examination__c.getRecordTypeInfosByName().get('Vital Sign').getRecordTypeId();
        ObservationRec.Account__c=AccID;
        ObservationRec.RecordTypeId=devRecordTypeId;
        ObservationRec.Source__c = 'ASSESSMENT';
        ObservationRec.Form_Unique_ID__c = formUniqueID;
        ObservationRec.Start_Time__c = system.now().adddays(1);
        ObservationRec.End_Time__c = system.now().adddays(2) ;
        system.debug('time' + ObservationRec.End_Time__c + ' ' + ObservationRec.Start_Time__c);
        try{
        if(Schema.sObjectType.Medical_Examination__c.isAccessible() &&
         Schema.sObjectType.Medical_Examination__c.isCreateable() &&
         Schema.sObjectType.Medical_Examination__c.fields.Account__c.isCreateable() &&
         Schema.sObjectType.Medical_Examination__c.fields.RecordTypeId.isCreateable() &&
         Schema.sObjectType.Medical_Examination__c.fields.Source__c.isCreateable() &&
         Schema.sObjectType.Medical_Examination__c.fields.Form_Unique_ID__c.isCreateable() &&
         Schema.sObjectType.Medical_Examination__c.fields.Start_Time__c.isCreateable() &&
         Schema.sObjectType.Medical_Examination__c.fields.End_Time__c.isCreateable()
         ){
            insert ObservationRec;
        }
        }
        catch(Exception e){
            ExceptionLog.logError(e);
        }
        
        system.debug('ObservationRec--'+ObservationRec.Id);
        List<Medical_Examination__c> vitalSigns = [select id,Respiration__c,Oxygen_Saturation__c, Blood_Pressure_Systolic__c,Blood_Pressure_diasystolic__c,
        Temperature__c, Pulse__c, createdDate,CreatedBy.Name from Medical_Examination__c 
        WHERE Account__c=:AccID AND RecordTypeId=:devRecordTypeId
        WITH SECURITY_ENFORCED
        ORDER BY CreatedDate DESC ];// And createdDate>TODAY and createdDate<TOMORROW]; 
        return vitalSigns ;
    }
}