force-app/main/default/objects/Elixir_Pluggable_Classes__mdt/Elixir_Pluggable_Classes__mdt.object-meta.xml
<CustomObject>
    <label>Elixir Pluggable Class</label>
    <pluralLabel>Elixir Pluggable Classes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Elixir_Pluggable_Classes__mdt/fields/Virtual_Class__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Class__c</fullName>
    <label>Virtual Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetClaimERAIDBatch.cls
/*Author name           :  Rohit Singh
* Purpose               :  To automatically create Integration data records to store ERA Id for specific claims
* Schedule              :  Scheduling on daily basis
* Test Class            :  
* Schedular class       :   
*/
public with sharing class GetClaimERAIDBatch {
    
    @AuraEnabled
    public static void entryPointCallout(){
        List<Elixir_Pluggable_Classes__mdt> pluggableClass = new List<Elixir_Pluggable_Classes__mdt>();
        String virtualClassName;
        pluggableClass = [SELECT DeveloperName,Virtual_Class__c FROM Elixir_Pluggable_Classes__mdt WHERE DeveloperName='NewClaimMDIntegration' WITH SECURITY_ENFORCED];
        if(pluggableClass != null && !pluggableClass.isEmpty()){
            
            virtualClassName = pluggableClass[0].Virtual_Class__c;
            
        }
        if(virtualClassName != '' && virtualClassName !=null && !Test.isRunningTest()){
             Callable calloutclaimMd = (Callable) Type.forName(virtualClassName).newInstance();
            calloutclaimMd.call('GetERA', new Map<String, Object> {
                });
            
        }else if(!Test.isRunningTest()){
            throw new AuraHandledException('Please configure a clearing house to get the ERA');
        }
    }  
    @AuraEnabled
    public static Id viewId(){
        List<ListView> views = [SELECT Id, DeveloperName, SobjectType 
        FROM ListView 
        WHERE DeveloperName='All_Claims' WITH SECURITY_ENFORCED LIMIT 1];
        system.debug(views);
        Id viewId = null;
        if(views!=null && views.size()>0){ 
            viewId = views[0].Id;
        }
        return viewId;
    }
}