force-app/main/default/objects/Elixir_Pluggable_Classes__mdt/Elixir_Pluggable_Classes__mdt.object-meta.xml
<CustomObject>
    <label>Elixir Pluggable Class</label>
    <pluralLabel>Elixir Pluggable Classes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Elixir_Pluggable_Classes__mdt/fields/Virtual_Class__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Class__c</fullName>
    <label>Virtual Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ChangeStatusHelper.cls
/**
* @description       : 
* @author            : ChangeMeIn@UserSettingsUnder.SFDoc
* @group             : 
* @last modified on  : 02-13-2023
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class ChangeStatusHelper {
    
    @AuraEnabled
    public static void checkClaimStatus(String claimId)
    {
        List<Elixir_Pluggable_Classes__mdt> pluggableClass = new List<Elixir_Pluggable_Classes__mdt>();
        String virtualClassName;
        pluggableClass = [SELECT DeveloperName,Virtual_Class__c FROM Elixir_Pluggable_Classes__mdt WHERE DeveloperName='NewClaimMDIntegration' WITH SECURITY_ENFORCED];
        if(pluggableClass != null && !pluggableClass.isEmpty()){
            
            virtualClassName = pluggableClass[0].Virtual_Class__c;
            
        }
        if(virtualClassName != '' && virtualClassName !=null){
            Callable calloutGetPayer = (Callable) Type.forName(virtualClassName).newInstance();
            calloutGetPayer.call('GetpayerStatusClaimMD', new Map<String, Object> {
                'claimId' => claimId
                    });
            
        }else{
           throw new AuraHandledException('Please configure a clearing house to get the payer status');
        }
    }
    
    
    
}