force-app/main/default/objects/Elixir_Pluggable_Classes__mdt/Elixir_Pluggable_Classes__mdt.object-meta.xml
<CustomObject>
    <label>Elixir Pluggable Class</label>
    <pluralLabel>Elixir Pluggable Classes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Elixir_Pluggable_Classes__mdt/fields/Virtual_Class__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Class__c</fullName>
    <label>Virtual Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message_Details__c/Message_Details__c.object-meta.xml
<CustomObject>
    <label>Message Details</label>
    <nameField>
        <displayFormat>MD-{0000000}</displayFormat>
        <label>Message Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Message Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Message_Details__c/fields/lookup_Message_Subject__c.field-meta.xml
<CustomField>
    <fullName>lookup_Message_Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate Message Subject with the Message Subject.</description>
    <label>Message Subject</label>
    <referenceTo>Message_Subject__c</referenceTo>
    <relationshipLabel>Message Details (Message Subject)</relationshipLabel>
    <relationshipName>Message_Details_lookup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message_Details__c/fields/Message_Body__c.field-meta.xml
<CustomField>
    <fullName>Message_Body__c</fullName>
    <description>This field is used to store the details of the Message.</description>
    <label>Message Body</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Message_Subject__c/Message_Subject__c.object-meta.xml
<CustomObject>
    <label>Message Subject</label>
    <nameField>
        <displayFormat>MS-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Message Subjects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Message_Subject__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate Account with the Message Subject.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Message Subjects</relationshipLabel>
    <relationshipName>Message_Subjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message_Subject__c/fields/Grand_Parent_Message__c.field-meta.xml
<CustomField>
    <fullName>Grand_Parent_Message__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Original Message to which all the child Messages have been originated and linked.</description>
    <label>Grand Parent Message</label>
    <referenceTo>Message_Subject__c</referenceTo>
    <relationshipLabel>Message Subjects (Message Subject)</relationshipLabel>
    <relationshipName>Message_Subjects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message_Subject__c/fields/IsPortal__c.field-meta.xml
<CustomField>
    <fullName>IsPortal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to determine whether the message is from portal or CRM.</description>
    <label>IsPortal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message_Subject__c/fields/Parent_Message__c.field-meta.xml
<CustomField>
    <fullName>Parent_Message__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Immediate parent of the current record.</description>
    <label>Parent Message</label>
    <referenceTo>Message_Subject__c</referenceTo>
    <relationshipLabel>Message Subjects</relationshipLabel>
    <relationshipName>Message_Subjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message_Subject__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>This field is used for storing the message subject value.</description>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message_Subject__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate User with the Message Subject.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Message_Subjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ReplyBoxCmpController.cls
public with sharing class ReplyBoxCmpController {
    @AuraEnabled
    public static string insertSubjectAndMessage(String patientId,List<Message_Subject__c> message,String messageBody,List<String> base64Data, String fileName, Boolean isPHI){
        
            List<String> fileNameLst = new  List<String>();
            //List<String> base64Lst = new  List<String>();
            List<ContentDocumentLink> conDocLinkLst= new  List<ContentDocumentLink>();

            Message_Subject__c oldMessage = message[0];
            //User ur = [Select Id,IsPortalEnabled,AccountId from User where Id=:UserInfo.getUserId() LIMIT 1];
            String userId = UserInfo.getUserId();
        List<User> users = Database.query('Select Id,IsPortalEnabled,AccountId from User where Id=:userId LIMIT 1');
       
        Boolean isPortalEnabled = (Boolean) users[0].get('IsPortalEnabled');
       
            Message_Subject__c messageSubject = new Message_Subject__c();
            if(isPortalEnabled){
                patientId = (String)users[0].get('AccountId');
                messageSubject.IsPortal__c = isPortalEnabled;
                messageSubject.Account__c = patientId;
            }else{
                messageSubject.IsPortal__c = false;
                messageSubject.Account__c = patientId;
            messageSubject.User__c = userId;
            }
            messageSubject.Subject__c = oldMessage.Subject__c;
            
            //messageSubject.User__c= oldMessage.CreatedBy.Id;
            String parentMsgId = oldMessage.Parent_Message__c;
            String grandMsgId = oldMessage.Grand_Parent_Message__c;
            if(parentMsgId==null && grandMsgId==null){
                messageSubject.Parent_Message__c = oldMessage.Id;
                messageSubject.Grand_Parent_Message__c = oldMessage.Id;
            }else if(parentMsgId!=null && grandMsgId!=null){
                messageSubject.Parent_Message__c = oldMessage.Id;
                messageSubject.Grand_Parent_Message__c = grandMsgId;
            }
        if(isPortalEnabled){
            Message_Subject__c user = [Select id, User__c from Message_Subject__c where Id =: messageSubject.Grand_Parent_Message__c WITH SECURITY_ENFORCED LIMIT 1];
            messageSubject.User__c = user.User__c;
        }
            insert messageSubject;
            
            Message_Details__c messageDetails = new Message_Details__c();
            messageDetails.Message_Body__c = messageBody;
            messageDetails.lookup_Message_Subject__c = messageSubject.Id;
            insert messageDetails;

        if(!isPortalEnabled){
            String virtualClassName = 'Messaging_Utility';
            List<Elixir_Pluggable_Classes__mdt> pluggableClass = new List<Elixir_Pluggable_Classes__mdt>();
            pluggableClass = [SELECT
                              DeveloperName,
                              Virtual_Class__c
                              FROM Elixir_Pluggable_Classes__mdt
                              WHERE DeveloperName='ReplyBoxCmpController'];
            if(!pluggableClass.isEmpty()){
                virtualClassName = pluggableClass[0].Virtual_Class__c;
            }
            Type t = Type.forName(virtualClassName);
            Messaging_Utility msgUtility = (Messaging_Utility) t.newInstance(); 
            msgUtility.sendEmail(oldMessage.Subject__c, messageBody, patientId, base64Data, fileName, isPHI);
        }
            
            List<ImageWrapper> files = (List<ImageWrapper>)JSON.deserialize(fileName , List<ImageWrapper>.class);
            for(ImageWrapper img :files){
                ContentDocumentLink cdl = new ContentDocumentLink();
                cdl.ContentDocumentId = img.value;
                cdl.LinkedEntityId = messageDetails.id;
                cdl.Visibility = 'AllUsers';
                conDocLinkLst.add(cdl);
        
                ContentDocumentLink cdlAccount = new ContentDocumentLink();
                cdlAccount.ContentDocumentId = img.value;
                cdlAccount.LinkedEntityId = patientId;
                cdlAccount.Visibility = 'AllUsers';
                conDocLinkLst.add(cdlAccount);
            }
            upsert conDocLinkLst;
        return 'success';
    }
    @AuraEnabled
    public static String getPatient(){
        String userId = UserInfo.getUserId();
        String patientId = '';
        List<User> users = Database.query('Select Id,AccountId from User where Id=:userId AND AccountId!= null');
        if(users!=null && users.size()>0){
            patientId = (String) users[0].get('AccountId');
        }
        return patientId;
        
    }
    public class ImageWrapper{
        public String name;
        public String value;
    }
}