force-app/main/default/objects/Frequency__c/Frequency__c.object-meta.xml
<CustomObject>
    <label>Frequency</label>
    <nameField>
        <displayFormat>Frequency-{0000}</displayFormat>
        <label>Frequency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Frequency</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Frequency__c/fields/Prescription_Order__c.field-meta.xml
<CustomField>
    <fullName>Prescription_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prescription Order</label>
    <referenceTo>Prescription_Order__c</referenceTo>
    <relationshipLabel>Frequency</relationshipLabel>
    <relationshipName>Frequency</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/Prescription_Order__c.object-meta.xml
<CustomObject>
    <label>Prescription Order</label>
    <nameField>
        <displayFormat>Prescription Order-{0000}</displayFormat>
        <label>Prescription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescription Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prescription_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Prescription Order</relationshipLabel>
    <relationshipName>Prescription_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/fields/Drug_Name__c.field-meta.xml
<CustomField>
    <fullName>Drug_Name__c</fullName>
    <label>Drug Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/fields/Ferquency__c.field-meta.xml
<CustomField>
    <fullName>Ferquency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Repeat</fullName>
            </value>
            <value>
                <fullName>Number Of Times</fullName>
            </value>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Weeks</fullName>
            </value>
            <value>
                <fullName>After every &apos;n’ hours</fullName>
            </value>
            <value>
                <fullName>After lunch</fullName>
            </value>
            <value>
                <fullName>After supper/Dinner</fullName>
            </value>
            <value>
                <fullName>Before Breakfast</fullName>
            </value>
            <value>
                <fullName>Custom pheno</fullName>
            </value>
            <value>
                <fullName>Once a day (AM)</fullName>
            </value>
            <value>
                <fullName>Once a day (HS)</fullName>
            </value>
            <value>
                <fullName>Once a day midday</fullName>
            </value>
            <value>
                <fullName>Once a day (Qam)</fullName>
            </value>
            <value>
                <fullName>Once a day (QHS)</fullName>
            </value>
            <value>
                <fullName>At a specific time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to select the master data of type = Frequency</description>
    <label>Frequency Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Master_Object__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Frequency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Object__c</referenceTo>
    <relationshipLabel>Prescription Order (Frequency)</relationshipLabel>
    <relationshipName>Prescription_Order2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/fields/Prescription_Order__c.field-meta.xml
<CustomField>
    <fullName>Prescription_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prescription Order</label>
    <referenceTo>Prescription_Order__c</referenceTo>
    <relationshipLabel>Prescription Order</relationshipLabel>
    <relationshipName>Prescription_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PRN</fullName>
            </value>
            <value>
                <fullName>Taper</fullName>
            </value>
            <value>
                <fullName>Action Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/recordTypes/Medication.recordType-meta.xml
<RecordType>
    <fullName>Medication</fullName>
    <active>true</active>
    <label>Medication</label>
</RecordType>

force-app/main/default/objects/Prescription_Order__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Order</label>
</RecordType>

force-app/main/default/classes/TestEditMedicationApexController.cls
@isTest
public class TestEditMedicationApexController {
    
    @istest
    public static void Test() {
        
        Account acct = new Account(Name='Test Account'); 
        acct.Name='Test acc';
        insert acct;
        
        list<id> lis1 = new list<id>();
        Prescription_Order__c medication = new Prescription_Order__c();
        medication.Account__c=acct.Id;
        medication.Drug_Name__c='Demo';
        insert medication;
        
        lis1.add(medication.id);
        String demoJSON = '{"jsonListForTaper":[],"jsonListForPRN":[{"medicationName":"Demo ","types":"PRN","startDate":"2020-02-19","dispenseExpectedSupplyDuration":1,"afterDischarge":true,"Route":"im","dosageForm":"film","endDate":"2020-02-20","singleRecForPrn":[{"UnitsForPrn":"Tablet Therapy Pack","StrengthForPrn":"10mg","DosageForPrn":"12","Repeat":"Once a day (HS)","Dosage_Instruction":"2","textMessage":""}],"reasonLabel":"For pain"}]}';
        String demoJSONTaper  = '{"jsonListForTaper":[{"medicationName":"DEMO TAPER","types":"Taper","startDate":"2020-02-19","dispenseExpectedSupplyDuration":1,"afterDischarge":true,"Route":"injection","Warning":"DEMO WARNING","dosageForm":"film","reasonLabel":"DEMO REASON","endDate":"2020-02-20","Days":[{"times":["00:00:00.000"],"Strength":["5mg"],"Units":["film"],"Dosage":["1"],"Repeat":"n times a day","Dosage_Instruction":1,"textMessage":"1 times a day"}]}],"jsonListForPRN":[]}';
        String demoJSONActionOrder = '{"jsonListForAOrder":[{"medicationName":"DEMO action order","types":"Action Order","startDate":"2020-02-19","afterDischarge":true,"endDate":"2020-02-20","dispenseExpectedSupplyDuration":1,"PRNdisplay":false,"MARdisplay":true,"Justification":"DEMO WARNING","singleRecForActionOrder":[{"StartTime":["00:00:00.000"],"Repeat":"n times a day","Dosage_Instruction":1,"textMessage":"1 times a day"}]}],"jsonListForPRN":[]}';
        
        string dateTimeValue=string.valueof(system.now());
        
        
        
        Prescription_Order__c medicationPRN = new Prescription_Order__c();
        medicationPRN.Drug_Name__c='Demo';
        medicationPRN.Ferquency__c='Days';
        medicationPRN.type__c='PRN';
        insert medicationPRN;
        
        frequency__c freq= new frequency__c();
        freq.Prescription_Order__c= medicationPRN.Id;
        insert freq;
        
        Prescription_Order__c medicationTaper = new Prescription_Order__c();
        medicationTaper.Account__c=acct.Id;
        medicationTaper.Drug_Name__c='Demo';
        medicationTaper.type__c='Taper';
        insert medicationTaper;
        
        frequency__c freqTaper= new frequency__c();
        freqTaper.Prescription_Order__c= medicationTaper.Id;
        insert freqTaper;
        
        
        Prescription_Order__c medicationAC = new Prescription_Order__c();
        medicationAC.Account__c=acct.Id;
        medicationAC.Drug_Name__c='Demo';
        medicationAC.type__c='Action Order';
        insert medicationAC;
        
        
        frequency__c freq1= new frequency__c();
        freq1.Prescription_Order__c= medicationAC.Id;
        insert freq1;
        
        EditMedicationApexController.fetchData(lis1);
        EditMedicationApexController.saveData(demoJSON, 'kishan', 'Fax', acct.id,dateTimeValue,dateTimeValue);
        EditMedicationApexController.saveData(demoJSONTaper, 'kishan', 'Fax', acct.id,dateTimeValue,dateTimeValue);
        //EditMedicationApexController.saveData(demoJSONActionOrder, 'kishan', 'Fax', acct.id,dateTimeValue,dateTimeValue);
        // EditMedicationApexController.utilityTaper(listOfDays, newIds, freqMap, freq1, medicationAC)
        EditPrescriptionOrderController.fetchMedications();
        System.assert(   acct.Name!=null,''); 
        
    }
    
}