force-app/main/default/objects/Form_Field__c/Form_Field__c.object-meta.xml
<CustomObject>
    <label>Form Field</label>
    <nameField>
        <displayFormat>Data-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Field__c/fields/Form_Field__c.field-meta.xml
<CustomField>
    <fullName>Form_Field__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Field</label>
    <referenceTo>Form_Field__c</referenceTo>
    <relationshipLabel>Form Fields</relationshipLabel>
    <relationshipName>Form_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Field__c/fields/Sequence_Order__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Order__c</fullName>
    <label>Sequence Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FormFieldsWrapperTest.cls
@isTest
private class FormFieldsWrapperTest {
    @isTest
    static void testCompareTo() {
        Form_Field__c oppy1 = new Form_Field__c(Sequence_Order__c=1);
        Form_Field__c oppy2 = new Form_Field__c(Sequence_Order__c=2);
        FormFieldsWrapper wrapper1 = new FormFieldsWrapper(oppy1);
        FormFieldsWrapper wrapper2 = new FormFieldsWrapper(oppy2);
        
         Integer expectedResult = -1;
        Integer actualResult = wrapper1.compareTo(wrapper2);
        System.assertEquals(expectedResult, actualResult, 'Test case 1 failed');
      
        expectedResult = 1;
        actualResult = wrapper2.compareTo(wrapper1);
        System.assertEquals(expectedResult, actualResult, 'Test case 2 failed');
        
        oppy1.Sequence_Order__c = 2;
        expectedResult = 0;
        actualResult = wrapper1.compareTo(wrapper2);
        System.assertEquals(expectedResult, actualResult, 'Test case 3 failed');
    }
}