force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>This object stores both template and patient providers. Providers in elixir are facilties.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Represents patient-provider relationship.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents self-relationship.</description>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.Account__r.Id</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserLocation__c/UserLocation__c.object-meta.xml
<CustomObject>
    <description>Practitioner Location stores all the practitioners working in a particular location  (location here represents a record saved in the Provider Object)</description>
    <label>Practitioner Location</label>
    <nameField>
        <label>UserLocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Practitioner Location</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UserLocation__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Template_Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>UserLocation</relationshipLabel>
    <relationshipName>UserLocation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserLocation__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserLocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProviderPermissionHelper.cls
public without sharing class ProviderPermissionHelper implements Queueable{
    public void execute(QueueableContext context) {}
    public static void dummyMethod(){}
    /*List<Provider__c> newAccountsToPermit = new List<Provider__c>();
    public ProviderPermissionHelper(List<Provider__c> newAccountsToPermit){
        this.newAccountsToPermit = newAccountsToPermit;
    }
    public void execute(QueueableContext context) {
        Set<Id> accountIds = new Set<Id>();
        Set<Id> allProviders = new Set<Id>();
        for(Provider__c provider :newAccountsToPermit){
            if(String.isNotBlank(provider.Provider__c)){
                allProviders.add(provider.Provider__c);
            }
            accountIds.add(provider.Account__c);
        }
        system.debug(allProviders);                                    
        system.debug(accountIds);                                    
        if(accountIds.size()==0){
            return;
        }
        List<UserLocation__c> userLocations = [SELECT Id, User__c, Provider__c FROM UserLocation__c
                                                WHERE Provider__c IN :allProviders 
                                                WITH SECURITY_ENFORCED
                                                LIMIT 10000];
        system.debug(userLocations);                                    
        Set<Id> impactedUsers = new Set<Id>();
        for(UserLocation__c userLocation :userLocations){
            impactedUsers.add(userLocation.User__c);
        }
        Map<Id,List<Id>> userAllLocationsAccess = new Map<Id,List<Id>>();
        List<UserLocation__c> impactedUsersAllLocations = [SELECT Id, User__c,Provider__c FROM UserLocation__c 
                                            WHERE User__c IN :impactedUsers 
                                            WITH SECURITY_ENFORCED
                                            LIMIT 20000];

        for(UserLocation__c userLocation :impactedUsersAllLocations){
            if(userAllLocationsAccess.containsKey(userLocation.User__c)){
                userAllLocationsAccess.get(userLocation.User__c).add(userLocation.Provider__c);
            }else{
                userAllLocationsAccess.put(userLocation.User__c, new List<Id> {userLocation.Provider__c});
            }
        }
        system.debug(userAllLocationsAccess);                                    
        Set<Id> usersId = new Set<Id>();
        usersId = userAllLocationsAccess.keySet();
        List<AccountShare> newRecords = new List<AccountShare>();
        try{
        for(Account acc :[SELECT Id,(SELECT Id,Provider__c FROM Providers__r) FROM Account 
        WHERE Id IN :accountIds WITH SECURITY_ENFORCED]){
            for(Id userId :usersId){
                for(Provider__c provider :acc.Providers__r){
                    Id providerId = provider.Provider__c;
                    List<Id> allowedProviders = userAllLocationsAccess.get(userId);
                    if(allowedProviders.contains(providerId)){
                        AccountShare accountShare = new AccountShare();
                        accountShare.AccountId = acc.Id;
                        accountShare.UserOrGroupId = userId;
                        accountShare.RowCause = Schema.AccountShare.RowCause.Manual;
                        accountShare.AccountAccessLevel = 'Edit';
                        accountShare.OpportunityAccessLevel = 'Edit';
                        newRecords.add(accountShare);
                        system.debug(acc.Id);                                    
                        break;
                    }
                }
            }
        }
        if(newRecords!=null && newRecords.size()>0){
            insert newRecords;
        }
        }
        catch(Exception e){
            ExceptionLog.logError(e);
        }
    }*/
}