force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>This object stores both template and patient providers. Providers in elixir are facilties.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Represents patient-provider relationship.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents self-relationship.</description>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.Account__r.Id</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SharingRuleBatchableAccountProviders.cls
public without sharing class SharingRuleBatchableAccountProviders implements Database.Batchable<sObject>, Database.Stateful{
    public Map<Id,List<Id>> userAllLocationsAccess = new Map<Id,List<Id>>();
    public SharingRuleBatchableAccountProviders(Map<Id,List<Id>> userAllLocationsAccess) {
        this.userAllLocationsAccess = userAllLocationsAccess;
    }
    public Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id,(SELECT Id,Provider__c FROM Providers__r) FROM Account';
        return Database.getQueryLocator(query);
    }
   public void execute(Database.BatchableContext BC, List<sObject> scope){
       List<Account> accounts = (List<Account>) scope;
       Map<Id,Account> accountMap = new Map<Id,Account>(accounts);
       Set<Id> accountIds = accountMap.keySet();
       List<AccountShare> sharedAccounts = [SELECT Id,AccountId, UserOrGroupId FROM AccountShare 
                                            WHERE AccountId IN :accountIds AND RowCause='Manual'];
       Set<Id> sharedRecordToDel = new Set<Id>(); 
       for(AccountShare sharedAccount :sharedAccounts){
            Id userId = sharedAccount.UserOrGroupId;
            Id accountId = sharedAccount.AccountId;
            if(userAllLocationsAccess.containsKey(userId)){
            List<Id> userPermittedLocations = userAllLocationsAccess.get(userId);
                if(accountMap.containsKey(accountId)){
                    List<Provider__c> relatedProviders = accountMap.get(accountId).Providers__r;
                    Boolean found = false;
                    for(Provider__c provider :relatedProviders){
                        Id providerId = provider.Provider__c;
                        if(userPermittedLocations.contains(providerId)){
                            found = true;
                        }
                    }
                    if(!found){
                        sharedRecordToDel.add(sharedAccount.Id);
                    }
                }
            }
       }
       if(sharedRecordToDel!=null && sharedRecordToDel.size()>0){
            List<AccountShare> records = [SELECT Id FROM AccountShare WHERE Id IN :sharedRecordToDel 
                                            AND RowCause='Manual'
                                            WITH SECURITY_ENFORCED
                                            LIMIT 10000];
            if(Schema.sObjectType.AccountShare.isDeletable()){                                
            delete records;
            }
       }
    }
    public void finish(Database.BatchableContext BC){
        Database.executeBatch(new SharingRuleBatchableVOBDelete(userAllLocationsAccess),2000);
    }
}