force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>This object stores both template and patient providers. Providers in elixir are facilties.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Represents patient-provider relationship.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents self-relationship.</description>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.Account__r.Id</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GlobalVirtualProviderTriggerHelper.cls
global virtual class GlobalVirtualProviderTriggerHelper {
    Set<Id> accountIds = new Set<Id>();
    
    global virtual void beforeInsert(List<Provider__c> providerLst){
        ProviderTriggerHelper.populateProviders(providerLst);
    }
    global virtual void beforeUpdate(List<Provider__c> providerLst){
        ProviderTriggerHelper.populateProviders(providerLst);
    }
    global virtual void afterInsert(List<Provider__c> providerLst){
        /* for(Provider__c provider :providerLst){
            accountIds.add(provider.Account__c);
        }
        system.enqueueJob(new ProviderPermissionHelper(providerLst));*/
    }
    global virtual void afterUpdate(List<Provider__c> providerLst){
        /*  for(Provider__c provider :providerLst){
            accountIds.add(provider.Account__c);
        }
        system.enqueueJob(new ProviderPermissionHelper(providerLst));*/
    }
    global virtual void afterDelete(List<Provider__c> oldProviderLst){
        /* for(Provider__c provider :oldProviderLst){
                accountIds.add(provider.Account__c);
            }
        system.enqueueJob(new ProviderPermissionDeletion(oldProviderLst));*/
    }
    
    
}