force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>This object stores both template and patient providers. Providers in elixir are facilties.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents self-relationship.</description>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.Account__r.Id</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserLocation__c/UserLocation__c.object-meta.xml
<CustomObject>
    <description>Practitioner Location stores all the practitioners working in a particular location  (location here represents a record saved in the Provider Object)</description>
    <label>Practitioner Location</label>
    <nameField>
        <label>UserLocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Practitioner Location</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UserLocation__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Template_Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>UserLocation</relationshipLabel>
    <relationshipName>UserLocation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserLocation__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserLocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserProviderDeleteBatch.cls
public with sharing class UserProviderDeleteBatch implements Queueable{
    public List<UserLocation__c> locations = new List<UserLocation__c>();
    public Map<String,List<Id>> userToLocations = new Map<String,List<Id>>();
    public UserProviderDeleteBatch(List<UserLocation__c> locations) {
        this.locations = locations;
    }
    public void execute(QueueableContext context) {
        Set<Id> userIds = new Set<Id>();
        Set<Id> locationIds = new Set<Id>();
        if(locations==null){
            return;
        }
        for(UserLocation__c userLocation :locations) {
            Id userId = userLocation.User__c;
            Id locationId = userLocation.Provider__c;
            if(userToLocations.containsKey(userId)){
                userToLocations.get(userId).add(locationId);
            }else{
                userToLocations.put(userId, new List<String>{locationId});
            }
            userIds.add(userId);
            locationIds.add(locationId);
        }
        List<Provider__Share> recordsToDel = new List<Provider__Share>();
        List<Provider__Share> sharedProviders = [SELECT Id, UserOrGroupId,ParentId FROM Provider__Share
                                                WHERE RowCause='Manual' AND UserOrGroupId IN :userIds AND ParentId IN :locationIds];
        if(sharedProviders!=null && sharedProviders.size()>0){
            for(Provider__Share providerShare :sharedProviders){
                Id userId = providerShare.UserOrGroupId;
                Id locationId = providerShare.ParentId;
                if(userToLocations.containsKey(userId)){
                    List<String> locations = userToLocations.get(userId);
                    if(locations.contains(locationId)){
                        recordsToDel.add(providerShare);
                    }
                }
            }
        }
        if(recordsToDel!=null && recordsToDel.size()>0){
            delete recordsToDel;
        }
    }
}