force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>This object stores both template and patient providers. Providers in elixir are facilties.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents self-relationship.</description>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.Account__r.Id</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserLocation__c/UserLocation__c.object-meta.xml
<CustomObject>
    <description>Practitioner Location stores all the practitioners working in a particular location  (location here represents a record saved in the Provider Object)</description>
    <label>Practitioner Location</label>
    <nameField>
        <label>UserLocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Practitioner Location</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UserLocation__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Template_Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>UserLocation</relationshipLabel>
    <relationshipName>UserLocation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserLocation__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserLocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserLocationInsertBatch.cls
public without sharing class UserLocationInsertBatch implements Queueable{
    public List<UserLocation__c> locations = new List<UserLocation__c>();
    public String action;
    public UserLocationInsertBatch(List<UserLocation__c> locations, String action) {
        this.locations = locations;
        this.action = action;
    }
   public void execute(QueueableContext context) {
       if(locations==null){
        return;
       }
       Set<Id> userIds = new Set<Id>();
       Set<Id> locationIds = new Set<Id>();
       Map<Id, List<Id>> userToLocations = new  Map<Id, List<Id>>();
       for(UserLocation__c userLocation :locations) {
           Id userId = userLocation.User__c;
           Id locationId = userLocation.Provider__c;
            userIds.add(userId);
            locationIds.add(locationId);
       }
       system.debug(action);
       system.debug(userIds);
        Map<Id,List<Id>> userAllLocationsAccess = new Map<Id,List<Id>>();
        List<UserLocation__c> userLocations = [SELECT Id, User__c,Provider__c FROM UserLocation__c 
                                            WHERE User__c IN :userIds
                                            WITH SECURITY_ENFORCED
                                            LIMIT 49000];
        //Creating Map of User vs Access to All Locations
        for(UserLocation__c userLocation :userLocations){
            if(userAllLocationsAccess.containsKey(userLocation.User__c)){
                userAllLocationsAccess.get(userLocation.User__c).add(userLocation.Provider__c);
            }else{
                userAllLocationsAccess.put(userLocation.User__c, new List<Id> {userLocation.Provider__c});
            }
        }
        system.debug(action);
        if(action == 'INSERT'){
            Database.executeBatch(new SharingRuleBatchableAccountInsert(userAllLocationsAccess), 2000);
        }else if(action == 'DELETE'){
            Database.executeBatch(new SharingRuleBatchableAccountProviders(userAllLocationsAccess), 2000);
        }
    }
}