force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>This object stores both template and patient providers. Providers in elixir are facilties.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents self-relationship.</description>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.Account__r.Id</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserLocation__c/UserLocation__c.object-meta.xml
<CustomObject>
    <description>Practitioner Location stores all the practitioners working in a particular location  (location here represents a record saved in the Provider Object)</description>
    <label>Practitioner Location</label>
    <nameField>
        <label>UserLocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Practitioner Location</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UserLocation__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Template_Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>UserLocation</relationshipLabel>
    <relationshipName>UserLocation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserLocation__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserLocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserProviderInsertBatch.cls
public with sharing class UserProviderInsertBatch implements Queueable{
    public List<UserLocation__c> locations = new List<UserLocation__c>();
    public UserProviderInsertBatch(List<UserLocation__c> locations) {
        this.locations = locations;
    }
    public void execute(QueueableContext context) {
        List<Provider__Share> providerShares = new List<Provider__Share>();
        for(UserLocation__c userLocation :locations) {
            Id userId = userLocation.User__c;
            Id locationId = userLocation.Provider__c;
            system.debug(locationId);
            Provider__Share providerShare = new Provider__Share(
                UserOrGroupId = userId,
                ParentId = locationId,
                RowCause = Schema.AccountShare.RowCause.Manual,
                AccessLevel = 'Edit'
            );
            providerShares.add(providerShare);
        }
        Database.insert(providerShares,false);
    }
}