force-app/main/default/objects/VOB__c/VOB__c.object-meta.xml
<CustomObject>
    <description>This object tracks the verification of benefits/Patient Insurance details.</description>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VOB__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associated the patient with Account.</description>
    <label>Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurance</relationshipLabel>
    <relationshipName>VOB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UB04ClaimFormControllerTest.cls
@isTest
public class UB04ClaimFormControllerTest {
    @isTest
    static void testGetAccountDetails() {
        // Create test data for Account and VOB__c records
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        
        VOB__c testVOB = new VOB__c(Account__c = testAccount.Id);
        insert testVOB;
        
        Test.startTest();
        UB04ClaimFormController.wrapper result = UB04ClaimFormController.getAccountDetails(testAccount.Id, testVOB.Id);
        Test.stopTest();
        System.assertEquals(1, 1,'');
    }
    
    @isTest
    static void testFetchVOBRecord() {
        // Create a test VOB__c record
        VOB__c testVOB = new VOB__c();
        insert testVOB;
        
        Test.startTest();
        List<ElixirSuite__VOB__c> result = UB04ClaimFormController.fetchVOBRecord(testVOB.Id);
        Test.stopTest();
        System.assertEquals(1, 1,'');
        
    }
}