force-app/main/default/objects/MAR_MOR__c/MAR_MOR__c.object-meta.xml
<CustomObject>
    <label>MAR MOR</label>
    <nameField>
        <label>MAR MOR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mars Mors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MAR_MOR__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mars Mors</relationshipLabel>
    <relationshipName>Mars_Mors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MAR_MOR__c/fields/Administered_By__c.field-meta.xml
<CustomField>
    <fullName>Administered_By__c</fullName>
    <label>Administered By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MAR_MOR__c/fields/Administration_Status__c.field-meta.xml
<CustomField>
    <fullName>Administration_Status__c</fullName>
    <label>Administration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Taken</fullName>
            </value>
            <value>
                <fullName>Not taken</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Refused &amp; Destroyed</fullName>
            </value>
            <value>
                <fullName>Not required</fullName>
            </value>
            <value>
                <fullName>Made available</fullName>
            </value>
            <value>
                <fullName>Hospitalized</fullName>
            </value>
            <value>
                <fullName>Social Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MAR_MOR__c/fields/Dosage_Time__c.field-meta.xml
<CustomField>
    <fullName>Dosage_Time__c</fullName>
    <label>Dosage Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MAR_MOR__c/fields/Medication_Name__c.field-meta.xml
<CustomField>
    <fullName>Medication_Name__c</fullName>
    <label>Medication Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MAR_MOR__c/fields/Medication_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Medication_Quantity__c</fullName>
    <label>Medication Quantity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MAR_MOR__c/fields/Reasons__c.field-meta.xml
<CustomField>
    <fullName>Reasons__c</fullName>
    <label>Reasons</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MAR_MOR__c/fields/Scheduled_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Time__c</fullName>
    <label>Scheduled Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/MAR_MOR__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MAR_MOR__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dosage</fullName>
            </value>
            <value>
                <fullName>Vaccine</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MAR_MOR__c/fields/Was_Missed__c.field-meta.xml
<CustomField>
    <fullName>Was_Missed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Was Missed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/MARStatementController.cls
public with sharing class MARStatementController {
    @AuraEnabled
    public static Data_Wrapper getMORDetails(String accountId){ 
        Data_Wrapper obj ;
        try{
        if(schema.sobjecttype.MAR_MOR__c.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Name.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.CreatedDate.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Scheduled_Time__c.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Account__c.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Drug_Name__c.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Administered_By__c.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Dosage_Time__c.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Status__c.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Medication_Name__c.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Reasons__c.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Medication_Quantity__c.isAccessible()){
               List<MAR_MOR__c> marState = [SELECT Id, Name, CreatedDate,Scheduled_Time__c, Account__c, Drug_Name__c,
                                            Administered_By__c, Dosage_Time__c, Status__c,Medication_Name__c, Reasons__c, Medication_Quantity__c
                                            FROM MAR_MOR__c where Account__c=: accountId and type__c ='Dosage' WITH SECURITY_ENFORCED];
               string nameSpace = Elixir_Utility.getNamespace();
               obj = new Data_Wrapper(marState,nameSpace);
               
           }
        }
        catch(Exception e){
        ExceptionLog.logError(e);
        }
        return obj;
    }
    
    @AuraEnabled
    public static Data_Wrapper getMARForRangeApex(String fromDate, String toDate, String recordVal){
        system.debug('new val' + fromDate);
        Date fDate = Date.valueOf(fromDate);
        Date tDate = Date.valueOf(toDate);
        Data_Wrapper obj ; 
        try{
        if(schema.sobjecttype.MAR_MOR__c.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Name.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.CreatedDate.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Scheduled_Time__c.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Account__c.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Drug_Name__c.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Administered_By__c.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Dosage_Time__c.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Status__c.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Administration_Status__c.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Medication_Name__c.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Reasons__c.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Medication_Quantity__c.isAccessible()
           && schema.sobjecttype.MAR_MOR__c.fields.Was_Missed__c.isAccessible()){
        List<MAR_MOR__c> marStatement = [SELECT Id, Name, CreatedDate,Scheduled_Time__c, Account__c,Was_Missed__c, Drug_Name__c,Administered_By__c,Medication_Name__c, Dosage_Time__c,Administration_Status__c, Status__c, Reasons__c, Medication_Quantity__c
                                                                       FROM MAR_MOR__c
                                                                      WHERE DAY_ONLY(CreatedDate) >= :fDate AND DAY_ONLY(CreatedDate) <= :tDate AND Account__c=: recordVal and type__c ='Dosage' WITH SECURITY_ENFORCED];
        
        string nameSpace = Elixir_Utility.getNamespace();
        obj = new Data_Wrapper(marStatement,nameSpace );
         }
        }
        catch(Exception e){
        ExceptionLog.logError(e);
        }
        return obj;
        
    }
    
    public class Data_Wrapper{
        @AuraEnabled public List<MAR_MOR__c> statList;
         @AuraEnabled public string nameSpace;
        
        public Data_Wrapper(List<MAR_MOR__c> statLists, string NameSpace ){
            this.statList = statLists.clone();
            this.nameSpace = NameSpace;
        }
    }

}