force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>This object is used to store Claim related data for a patient.</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>CS{YYMMDD}{000000}</displayFormat>
        <label>Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <description>Represents self relationship.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim_Line_Items__c/Claim_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This object is used to store procedure level details related to a claim.</description>
    <label>Claim Procedure Line Item</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>Claim Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Procedure Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim_Line_Items__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents claim associated with claim line item.</description>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claim Line Items</relationshipLabel>
    <relationshipName>Claim_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Elixir_Custom_Setting__c/Elixir_Custom_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Elixir Custom Setting</label>
</CustomObject>

force-app/main/default/classes/GlobalReconciliationSummary.cls
global with sharing virtual class GlobalReconciliationSummary {
set<id> parentsIds=new set<id>();
global virtual void afterUndelete(List<Claim_Line_Items__c> claimLstRecords){
    Elixir_Custom_Setting__c customSetting = Elixir_Custom_Setting__c.getOrgDefaults();
    if(customSetting!=null && customSetting.ElixirSuite__ClaimLineItemTrigger_Active__c){
    
        for(Claim_Line_Items__c tc:claimLstRecords)
            parentsIds.add(tc.Claim__c);
    
    }
    if(parentsIds != null && parentsIds.size()>0){ 
        UpdateReconciliationSummaryOnClaimsCls.updateParentClaims(parentsIds);
        //UpdateReconciliationSummaryOnClaimsCls.deniedStatusUpdate(parentsIds);
        UpdateReconciliationSummaryOnClaimsCls.paidAndPatientResponseSec(parentsIds);
    }

}
global virtual void afterUpdate(List<Claim_Line_Items__c> claimListRecords){
    Elixir_Custom_Setting__c customSetting = Elixir_Custom_Setting__c.getOrgDefaults();
    if(customSetting!=null && customSetting.ElixirSuite__ClaimLineItemTrigger_Active__c){
    
        for(Claim_Line_Items__c tc:claimListRecords)
            parentsIds.add(tc.Claim__c);
    
    }
    if(parentsIds != null && parentsIds.size()>0){ 
        UpdateReconciliationSummaryOnClaimsCls.updateParentClaims(parentsIds);
        //UpdateReconciliationSummaryOnClaimsCls.deniedStatusUpdate(parentsIds);
        UpdateReconciliationSummaryOnClaimsCls.paidAndPatientResponseSec(parentsIds);
    }

}
global virtual void afterDelete(List<Claim_Line_Items__c> oldClaimLstRecords){
    
        for(Claim_Line_Items__c tc:oldClaimLstRecords)
            parentsIds.add(tc.Claim__c);
            if(parentsIds != null && parentsIds.size()>0){ 
                UpdateReconciliationSummaryOnClaimsCls.updateParentClaims(parentsIds);
                //UpdateReconciliationSummaryOnClaimsCls.deniedStatusUpdate(parentsIds);
                UpdateReconciliationSummaryOnClaimsCls.paidAndPatientResponseSec(parentsIds);
            }
    
}

}