force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>This object is used to store Claim related data for a patient.</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>CS{YYMMDD}{000000}</displayFormat>
        <label>Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Denotes claim generated for which patient(Account).</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <description>Total amount paid by the primary payer for the services rendered.</description>
    <inlineHelpText>Please use numbers between 1-9 only</inlineHelpText>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <description>Represents self relationship.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claim_Status__c.field-meta.xml
<CustomField>
    <fullName>Claim_Status__c</fullName>
    <description>Represents the current status of claim processing.</description>
    <label>Claim Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Ready to Submit</fullName>
            </value>
            <value>
                <fullName>Sent to Clearing house</fullName>
            </value>
            <value>
                <fullName>Clearing house accepted</fullName>
            </value>
            <value>
                <fullName>Clearing house rejected</fullName>
            </value>
            <value>
                <fullName>Payer Accepted</fullName>
            </value>
            <value>
                <fullName>Payer Rejected</fullName>
            </value>
            <value>
                <fullName>ERA Received</fullName>
            </value>
            <value>
                <fullName>Claim Validation Error</fullName>
            </value>
            <value>
                <fullName>Paid and Patient Responsibility</fullName>
            </value>
            <value>
                <fullName>Paid and resolved</fullName>
            </value>
            <value>
                <fullName>Paid with Patient Responsibility – Ready to submit Secondary Insurance</fullName>
            </value>
            <value>
                <fullName>Overpaid</fullName>
            </value>
            <value>
                <fullName>Underpaid</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Paid and patient responsibility with Secondary</fullName>
            </value>
            <value>
                <fullName>ERA Received - Transferred to Secondary</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Generated</fullName>
                <isActive>false</isActive>
                <label>Generated</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
                <isActive>false</isActive>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Processed</fullName>
                <isActive>false</isActive>
                <label>Processed</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Transmitted</fullName>
                <isActive>false</isActive>
                <label>Transmitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/ClaimNotificationParameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Claim Notification Parameters</label>
</CustomObject>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Claringhouse_Accepted__c.field-meta.xml
<CustomField>
    <fullName>Claringhouse_Accepted__c</fullName>
    <label>Clearinghouse Accepted (Notify Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Clearinghouse_Accepted_Records_Days__c.field-meta.xml
<CustomField>
    <fullName>Clearinghouse_Accepted_Records_Days__c</fullName>
    <label>Clearinghouse Accepted (Records Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Clearinghouse_Rejected__c.field-meta.xml
<CustomField>
    <fullName>Clearinghouse_Rejected__c</fullName>
    <label>Clearinghouse Rejected (Notify Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Clearinghouse_Rejected_Records_Days__c.field-meta.xml
<CustomField>
    <fullName>Clearinghouse_Rejected_Records_Days__c</fullName>
    <label>Clearinghouse Rejected (Records Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Payer_Accepted_Records_Days__c.field-meta.xml
<CustomField>
    <fullName>Payer_Accepted_Records_Days__c</fullName>
    <label>Payer Accepted (Records Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Ready_to_submit_Records_Days__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_submit_Records_Days__c</fullName>
    <label>Ready to submit (Records Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Send_to_Clearinghouse_Records_Days__c.field-meta.xml
<CustomField>
    <fullName>Send_to_Clearinghouse_Records_Days__c</fullName>
    <label>Send to Clearinghouse (Records Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestSendNotificationsForClaims.cls
@isTest
private class TestSendNotificationsForClaims {
    static testmethod void test() {
        ClaimNotificationParameters__c clp = new ClaimNotificationParameters__c();
        clp.Clearinghouse_Accepted_Records_Days__c = 0;
        clp.Claringhouse_Accepted__c = 0;
        clp.Clearinghouse_Rejected__c = 0;
        clp.Clearinghouse_Rejected_Records_Days__c = 0;
        clp.Payer_Accepted_Records_Days__c = 0;
        clp.Ready_to_submit_Records_Days__c = 0;
        clp.Send_to_Clearinghouse_Records_Days__c =0;
        insert clp;
        Account pa = new Account();
        pa.Name = 'Test';
        insert pa;
        
        List<Claim__c> lstClaims= new List<Claim__c>();
        for(Integer i=0 ;i <2;i++)
        {
            Claim__c cl = new Claim__c();
            cl.Amount_Paid__c =i;
            cl.Account__c = pa.Id;
            cl.Claim_Status__c = 'Clearing house rejected';
            lstClaims.add(cl);
        } 
    		Claim__c c = new Claim__c();
            c.Amount_Paid__c =10;
            c.Account__c = pa.Id;
            c.Claim_Status__c = 'Sent to Clearing house';
            lstClaims.add(c);
        
        Claim__c c1 = new Claim__c();
            c1.Amount_Paid__c =10;
            c1.Account__c = pa.Id;
            c1.Claim_Status__c = 'Ready to Submit';
            lstClaims.add(c1);
        
        Claim__c c2 = new Claim__c();
            c2.Amount_Paid__c =10;
            c2.Account__c = pa.Id;
            c2.Claim_Status__c = 'Clearing house accepted';
            lstClaims.add(c2);
        
        insert lstClaims;
        Test.startTest();
        
       // if(!Test.isRunningTest()){
            SendNotificationsForClaims snc = new SendNotificationsForClaims();
            Database.executeBatch(snc);
        //}
        System.assertEquals(1, 1, ' ');
        Test.stopTest();
    }
}