force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>This object is used to store Claim related data for a patient.</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>CS{YYMMDD}{000000}</displayFormat>
        <label>Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <description>Represents self relationship.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claim_Status__c.field-meta.xml
<CustomField>
    <fullName>Claim_Status__c</fullName>
    <description>Represents the current status of claim processing.</description>
    <label>Claim Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Ready to Submit</fullName>
            </value>
            <value>
                <fullName>Sent to Clearing house</fullName>
            </value>
            <value>
                <fullName>Clearing house accepted</fullName>
            </value>
            <value>
                <fullName>Clearing house rejected</fullName>
            </value>
            <value>
                <fullName>Payer Accepted</fullName>
            </value>
            <value>
                <fullName>Payer Rejected</fullName>
            </value>
            <value>
                <fullName>ERA Received</fullName>
            </value>
            <value>
                <fullName>Claim Validation Error</fullName>
            </value>
            <value>
                <fullName>Paid and Patient Responsibility</fullName>
            </value>
            <value>
                <fullName>Paid and resolved</fullName>
            </value>
            <value>
                <fullName>Paid with Patient Responsibility – Ready to submit Secondary Insurance</fullName>
            </value>
            <value>
                <fullName>Overpaid</fullName>
            </value>
            <value>
                <fullName>Underpaid</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Paid and patient responsibility with Secondary</fullName>
            </value>
            <value>
                <fullName>ERA Received - Transferred to Secondary</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Generated</fullName>
                <isActive>false</isActive>
                <label>Generated</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
                <isActive>false</isActive>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Processed</fullName>
                <isActive>false</isActive>
                <label>Processed</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Transmitted</fullName>
                <isActive>false</isActive>
                <label>Transmitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/ClaimNotificationParameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Claim Notification Parameters</label>
</CustomObject>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Claringhouse_Accepted__c.field-meta.xml
<CustomField>
    <fullName>Claringhouse_Accepted__c</fullName>
    <label>Clearinghouse Accepted (Notify Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Clearinghouse_Accepted_Records_Days__c.field-meta.xml
<CustomField>
    <fullName>Clearinghouse_Accepted_Records_Days__c</fullName>
    <label>Clearinghouse Accepted (Records Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Clearinghouse_Rejected__c.field-meta.xml
<CustomField>
    <fullName>Clearinghouse_Rejected__c</fullName>
    <label>Clearinghouse Rejected (Notify Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Clearinghouse_Rejected_Records_Days__c.field-meta.xml
<CustomField>
    <fullName>Clearinghouse_Rejected_Records_Days__c</fullName>
    <label>Clearinghouse Rejected (Records Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Denied_Notify_Days__c.field-meta.xml
<CustomField>
    <fullName>Denied_Notify_Days__c</fullName>
    <label>Denied (Notify Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Denied_Records_Days__c.field-meta.xml
<CustomField>
    <fullName>Denied_Records_Days__c</fullName>
    <label>Denied (Records Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Payer_Accepted__c.field-meta.xml
<CustomField>
    <fullName>Payer_Accepted__c</fullName>
    <label>Payer Accepted (Notify Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Payer_Accepted_Records_Days__c.field-meta.xml
<CustomField>
    <fullName>Payer_Accepted_Records_Days__c</fullName>
    <label>Payer Accepted (Records Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Payer_Rejected_Notify_Days__c.field-meta.xml
<CustomField>
    <fullName>Payer_Rejected_Notify_Days__c</fullName>
    <label>Payer Rejected (Notify Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Payer_Rejected_Records_Days__c.field-meta.xml
<CustomField>
    <fullName>Payer_Rejected_Records_Days__c</fullName>
    <label>Payer Rejected (Records Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Ready_to_submit__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_submit__c</fullName>
    <label>Ready to submit (Notify Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Ready_to_submit_Records_Days__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_submit_Records_Days__c</fullName>
    <label>Ready to submit (Records Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Send_to_ClaringHouse__c.field-meta.xml
<CustomField>
    <fullName>Send_to_ClaringHouse__c</fullName>
    <label>Send to Clearinghouse (Notify Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Send_to_Clearinghouse_Records_Days__c.field-meta.xml
<CustomField>
    <fullName>Send_to_Clearinghouse_Records_Days__c</fullName>
    <label>Send to Clearinghouse (Records Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Underpaid_Notify_Days__c.field-meta.xml
<CustomField>
    <fullName>Underpaid_Notify_Days__c</fullName>
    <label>Underpaid (Notify Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimNotificationParameters__c/fields/Underpaid_Records_Days__c.field-meta.xml
<CustomField>
    <fullName>Underpaid_Records_Days__c</fullName>
    <label>Underpaid (Records Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SendNotificationsForClaims_Test.cls
@isTest
public class SendNotificationsForClaims_Test 
{
    public static testMethod void sendNotif()
    {
        ClaimNotificationParameters__c cusSet = new ClaimNotificationParameters__c();
        cusSet.Claringhouse_Accepted__c=-1;
        cusSet.Clearinghouse_Accepted_Records_Days__c=-1;
        cusSet.Clearinghouse_Rejected__c=-1;
        cusSet.Payer_Accepted__c=-1;
        cusSet.Clearinghouse_Rejected_Records_Days__c=-1;
        cusSet.Ready_to_submit__c=-1;
        cusSet.Send_to_ClaringHouse__c=-1;
        cusSet.Payer_Accepted_Records_Days__c=-1;
        cusSet.Ready_to_submit_Records_Days__c=-1;
        cusSet.Denied_Notify_Days__c=-1;
        cusSet.Denied_Records_Days__c=-1;
        cusSet.Payer_Rejected_Notify_Days__c=-1;
        cusSet.Payer_Rejected_Records_Days__c=-1;
        cusSet.Underpaid_Notify_Days__c=-1;
        cusSet.Underpaid_Records_Days__c=-1;
        cusSet.Send_to_Clearinghouse_Records_Days__c=-1;
        insert cusSet;
        
        
        Claim__c cl1 = new Claim__c();
        cl1.Claim_Status__c = 'Payer Accepted';          
        insert cl1;
        
        
        Claim__c cl2 = new Claim__c();
        cl2.Claim_Status__c = 'Payer Rejected';
        insert cl2;
        
        Claim__c cl3 = new Claim__c();
        cl3.Claim_Status__c = 'Ready to Submit';
        insert cl3;
        
        Claim__c cl4 = new Claim__c();
        cl4.Claim_Status__c = 'Sent to Clearing house';
        insert cl4;
        
        Claim__c cl5 = new Claim__c();
        cl5.Claim_Status__c = 'Clearing house accepted';
        insert cl5;
        
        Claim__c cl6 = new Claim__c();
        cl6.Claim_Status__c = 'Clearing house rejected';
        insert cl6;
        
        Claim__c cl7 = new Claim__c();
        cl7.Claim_Status__c = 'Denied';
        insert cl7;
        
        Claim__c cl8 = new Claim__c();
        cl8.Claim_Status__c = 'Underpaid';
        insert cl8;
        
        Test.startTest();
        SendNotificationsForClaims obj=new SendNotificationsForClaims(); 
        DataBase.executeBatch(obj,200);
        Test.stopTest();  
        system.assert( cl1.Claim_Status__c !=null,''); 
    }
}