force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>This object is used to store Claim related data for a patient.</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>CS{YYMMDD}{000000}</displayFormat>
        <label>Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Billing_Provider_Info_NPI__c.field-meta.xml
<CustomField>
    <fullName>Billing_Provider_Info_NPI__c</fullName>
    <description>Indicates standardized identification of Billing Provider</description>
    <label>Billing Provider Info- NPI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <description>Represents self relationship.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claim_Status__c.field-meta.xml
<CustomField>
    <fullName>Claim_Status__c</fullName>
    <description>Represents the current status of claim processing.</description>
    <label>Claim Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Ready to Submit</fullName>
            </value>
            <value>
                <fullName>Sent to Clearing house</fullName>
            </value>
            <value>
                <fullName>Clearing house accepted</fullName>
            </value>
            <value>
                <fullName>Clearing house rejected</fullName>
            </value>
            <value>
                <fullName>Payer Accepted</fullName>
            </value>
            <value>
                <fullName>Payer Rejected</fullName>
            </value>
            <value>
                <fullName>ERA Received</fullName>
            </value>
            <value>
                <fullName>Claim Validation Error</fullName>
            </value>
            <value>
                <fullName>Paid and Patient Responsibility</fullName>
            </value>
            <value>
                <fullName>Paid and resolved</fullName>
            </value>
            <value>
                <fullName>Paid with Patient Responsibility – Ready to submit Secondary Insurance</fullName>
            </value>
            <value>
                <fullName>Overpaid</fullName>
            </value>
            <value>
                <fullName>Underpaid</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Paid and patient responsibility with Secondary</fullName>
            </value>
            <value>
                <fullName>ERA Received - Transferred to Secondary</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Generated</fullName>
                <isActive>false</isActive>
                <label>Generated</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
                <isActive>false</isActive>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Processed</fullName>
                <isActive>false</isActive>
                <label>Processed</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Transmitted</fullName>
                <isActive>false</isActive>
                <label>Transmitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient_s_State__c.field-meta.xml
<CustomField>
    <fullName>Patient_s_State__c</fullName>
    <description>Used to store patient's state.</description>
    <label>Patient’s State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Payor__c.field-meta.xml
<CustomField>
    <fullName>Payor__c</fullName>
    <description>Refer payer of the insurance.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payor</label>
    <referenceTo>Payor__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim_Line_Items__c/Claim_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This object is used to store procedure level details related to a claim.</description>
    <label>Claim Procedure Line Item</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>Claim Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Procedure Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim_Line_Items__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents claim associated with claim line item.</description>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claim Line Items</relationshipLabel>
    <relationshipName>Claim_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim_Line_Items__c/fields/Integration_Order__c.field-meta.xml
<CustomField>
    <fullName>Integration_Order__c</fullName>
    <label>Integration Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Elixir_Pluggable_Classes__mdt/Elixir_Pluggable_Classes__mdt.object-meta.xml
<CustomObject>
    <label>Elixir Pluggable Class</label>
    <pluralLabel>Elixir Pluggable Classes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Elixir_Pluggable_Classes__mdt/fields/Virtual_Class__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Class__c</fullName>
    <label>Virtual Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payor__c/Payor__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the List of Payers in elixir.</description>
    <label>Payor</label>
    <nameField>
        <label>Payor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payor__c/fields/Payer_Code__c.field-meta.xml
<CustomField>
    <fullName>Payer_Code__c</fullName>
    <description>Represents a unique identifier for the payer.</description>
    <label>Payer Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SendClaimController.cls
/**
* @description       : 
* @author            : ChangeMeIn@UserSettingsUnder.SFDoc
* @group             : 
* @last modified on  : 02-16-2023
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class SendClaimController {
    @AuraEnabled
    public static string updateClaims(String claimLst){
String toastMsg;
        List<Elixir_Pluggable_Classes__mdt> pluggableClass = new List<Elixir_Pluggable_Classes__mdt>();
        String virtualClassName;
        pluggableClass = [SELECT DeveloperName,Virtual_Class__c FROM Elixir_Pluggable_Classes__mdt WHERE DeveloperName='NewClaimMDIntegration'];
        if(pluggableClass != null && !pluggableClass.isEmpty()){
            
            virtualClassName = pluggableClass[0].Virtual_Class__c;
            
        }
        if(virtualClassName != '' && virtualClassName !=null){
            Callable calloutclaimMd = (Callable) Type.forName(virtualClassName).newInstance();
            calloutclaimMd.call('RefreshClaimMDCallout', new Map<String, Object> {
                'claimLst' => claimLst
                    });
            
        }else{
            if(!Test.isRunningTest()){
            throw new AuraHandledException('Please configure a clearing house to send this claim.Contact your admin for more details');
            }
        }
        toastMsg =Label.Claim_custom_error;
        return toastMsg;
    }
    @AuraEnabled
    public static Duplicate isDuplicateError(String claimLst){
        Boolean duplicate = false;
        List<String> claimIdsSet = splitIds(claimLst);
        List<Claim__c> allClaims = new List<Claim__c>([SELECT Id,Claim_Status__c
                                                       FROM Claim__c 
                                                       WHERE Id IN :claimIdsSet WITH SECURITY_ENFORCED 
                                                       LIMIT 50000]);
        for(Claim__c c :allClaims){  
            if(String.isBlank(c.Claim_Status__c) ||  c.Claim_Status__c== 'Sent to Clearing house'){     
                c.Claim_Status__c = 'Ready to Submit';
                duplicate = true;       
            }       
        }
        
        DMLManager.updateAsUser(allClaims);
        
        Id viewId;
        List<ListView> views = [SELECT Id, DeveloperName, SobjectType 
                                FROM ListView 
                                WHERE DeveloperName='Ready_To_Submit_Claims' WITH SECURITY_ENFORCED LIMIT 1];
        if(views!=null && views.size()>0){
            viewId = views[0].Id;
        }
        Duplicate dup = new Duplicate();
        dup.duplicate = duplicate;
        dup.viewId = viewId;
        return dup;
    }
    @AuraEnabled
    public static Id viewId(){
        List<ListView> views = [SELECT Id, DeveloperName, SobjectType 
                                FROM ListView 
                                WHERE DeveloperName='Ready_To_Submit_Claims' WITH SECURITY_ENFORCED LIMIT 1];
        system.debug(views);
        Id viewId = null;
        if(views!=null && views.size()>0){
            viewId = views[0].Id;
        }
        return viewId;
    }
    public class Duplicate{
        @AuraEnabled public Boolean duplicate;
        @AuraEnabled public String viewId;
    }
    @AuraEnabled
    public static Id viewIdAll(){
        List<ListView> views = [SELECT Id, DeveloperName, SobjectType 
                                FROM ListView 
                                WHERE DeveloperName='All_Claims' WITH SECURITY_ENFORCED LIMIT 1];
        system.debug(views);
        Id viewId = null;
        if(views!=null && views.size()>0){ 
            viewId = views[0].Id;
        }
        return viewId;
    }
    public static void ClaimsValidationforAutoCreation(String claimLst){
       
        List<Claim__c> toSendClaims = new  List<Claim__c>();
        List<String> claimIdsSet = splitIds(claimLst);
        Map<String,Integer> countItems = new Map<String,Integer>();
        List<Claim__c> AllClaims = new List<Claim__c>([SELECT Id,Claim_Status__c,patient_s_state__c,Billing_Provider_Info_NPI__c,payor__r.ElixirSuite__Claim_Processing_via__c
                                                       FROM Claim__c 
                                                       WHERE Id IN :claimIdsSet WITH SECURITY_ENFORCED 
                                                       LIMIT 50000]);
        if(AllClaims.size() > 0){
            Map<Id,List<Claim_Line_Items__c>> mapOfClaimIdToLineItems = lineItems(toSendClaims);
            List<Claim_Line_Items__c> lineItems = new List<Claim_Line_Items__c>();
            try{
                for(List<Claim_Line_Items__c> lineItem :mapOfClaimIdToLineItems.values()){
                    if(lineItem!=null){
                        lineItems.addAll(lineItem);
                    }
                }
                 DMLManager.updateAsUser(lineItems);
            }
            catch(Exception e){
                ExceptionLog.logError(e);
            }
        }
        if(AllClaims.size() > 0){
                            SendClaimController.postClaimsToClearingHouse(claimLst);   
            } 
        }
        public static void postClaimsToClearingHouse(String claimLst){       
        List<String> claimIdsSet = splitIds(claimLst);
        Schema.DescribeSObjectResult result = Claim__c.sObjectType.getDescribe();
        List<String> apiNames =  new List<String>(result.fields.getMap().keySet());
        apiNames.add('ElixirSuite__Account__r.ElixirSuite__First_Name__c');
        apiNames.add('ElixirSuite__Account__r.ElixirSuite__Last_Name__c');
        String query = 'SELECT ' +String.escapeSingleQuotes(String.join(apiNames,','))  + ',payor__r.Payer_Code__c' + ' FROM Claim__c ';
        if(!Test.isRunningTest()){
            query+= 'WHERE Id in: claimIdsSet';
        }   
        List<Claim__c> listOfClaims = (List<Claim__c>)Database.query(query);
        Map<Id,List<Claim_Line_Items__c>> mapOfClaimIdToLineItems = new Map<Id,List<Claim_Line_Items__c>>();
        if(listOfClaims!=null && listOfClaims.size()>0){
            mapOfClaimIdToLineItems = lineItems(listOfClaims);
        } 
        
        if(mapOfClaimIdToLineItems!=null && mapOfClaimIdToLineItems.size()>0){
            validationCheck(mapOfClaimIdToLineItems, listOfClaims);
        }
    }  
    private static void validationCheck(Map<Id,List<Claim_Line_Items__c>> mapOfClaimIdToLineItems, List<Claim__c> listOfClaims){
                Map<Id,Claim__c> mapOfClaims = new Map<Id,Claim__c>(listOfClaims);
        Map<Id,List<Claim_Line_Items__c>> claimWithClaimLineItem = new  Map<Id,List<Claim_Line_Items__c>>();
                for(Id claimId :mapOfClaimIdToLineItems.keySet()){
                        Claim__c claimRecord = mapOfClaims.get(claimId);
            List<Claim__c> claimLstRec = new List<Claim__c>();
            claimLstRec.add(claimRecord);
                        String validationMessage = claimValidationHelper.validate1(claimLstRec,mapOfClaimIdToLineItems.get(claimId)); //Anusha - Start -09/11/22 
            
        }
    }
     
    public static Map<Id,List<Claim_Line_Items__c>> lineItems(List<Claim__c> listOfClaims){
        Map<Id,List<Claim_Line_Items__c>> mapOfClaimIdToLineItems = new Map<Id,List<Claim_Line_Items__c>>();
        try{
            if(listOfClaims!=null && listOfClaims.size()>0){
                Schema.DescribeSObjectResult result = Claim_Line_Items__c.sObjectType.getDescribe();
                List<String> apiNames =  new List<String>(result.fields.getMap().keySet());
                String queryForLineItems = 'SELECT ' +String.escapeSingleQuotes(String.join(apiNames,','))  + ' FROM  Claim_Line_Items__c '+
                    'WHERE ElixirSuite__Claim__c IN :listOfClaims ORDER BY CreatedDate DESC';
                // Creation of map for Claim to List of Claim Line Items 
                for(Claim_Line_Items__c lineItemRecord :Database.query(queryForLineItems)){ // Queried directly in loop to avoid LIMIT 50000 error
                    Id keyForMapOfClaimIdToLineItems = lineItemRecord.Claim__c;
                    system.debug(keyForMapOfClaimIdToLineItems);
                    if(mapOfClaimIdToLineItems.containsKey(keyForMapOfClaimIdToLineItems)){
                        List<Claim_Line_Items__c> itemsToAdd = mapOfClaimIdToLineItems.get(keyForMapOfClaimIdToLineItems);
                        Integer totalItems = itemsToAdd.size() + 1;
                        lineItemRecord.Integration_Order__c = totalItems;
                        itemsToAdd.add(lineItemRecord);
                    }else{
                        lineItemRecord.Integration_Order__c = 1;
                        mapOfClaimIdToLineItems.put(keyForMapOfClaimIdToLineItems,new List<Claim_Line_Items__c>{lineItemRecord});
                    }
                }
            } 
            if(mapOfClaimIdToLineItems.size()==0){
                if(listOfClaims!=null && listOfClaims.size()>0){
                    for(Claim__c claim :listOfClaims){
                        mapOfClaimIdToLineItems.put(claim.Id, new List<Claim_Line_Items__c>{});
                    }
                }
            }
        }
        catch(Exception e){
            ExceptionLog.logError(e);
        }
        return mapOfClaimIdToLineItems;
    }
    public static List<String> splitIds(String claims){
        List<String> listOfClaims = new List<String>();
        try{
            for(String lineItemId : claims.split(',')){
                listOfClaims.add(lineItemId.trim());
            }
        }
        catch(Exception e){
            ExceptionLog.logError(e);
        }
        return listOfClaims;
    }
}