force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>This object is used to store Claim related data for a patient.</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>CS{YYMMDD}{000000}</displayFormat>
        <label>Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <description>Represents self relationship.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Manual_ERA__c.field-meta.xml
<CustomField>
    <fullName>Manual_ERA__c</fullName>
    <description>Refers Era Generation Method</description>
    <defaultValue>false</defaultValue>
    <label>Manual ERA?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Total_Charge__c.field-meta.xml
<CustomField>
    <fullName>Total_Charge__c</fullName>
    <description>Indicates total amount billed by the healthcare provider for the services.</description>
    <defaultValue>0</defaultValue>
    <label>Total Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Total_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Paid__c</fullName>
    <description>Indicates total paid amount of claim.</description>
    <defaultValue>0</defaultValue>
    <label>Total Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EOB__c/EOB__c.object-meta.xml
<CustomObject>
    <description>This object stores the Parent ERA and child ERA.
Parent ERA is an orphan record whereas Child ERA is associated to a self lookup field to Parent ERA.</description>
    <label>ERA</label>
    <nameField>
        <displayFormat>ERA-{0000}</displayFormat>
        <label>ERA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EOB__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipName>EOB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EOB__c/fields/Copy_Of_Original_ERA__c.field-meta.xml
<CustomField>
    <fullName>Copy_Of_Original_ERA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Copy Of Original ERA?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EOB__c/fields/EOB__c.field-meta.xml
<CustomField>
    <fullName>EOB__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ERA</label>
    <referenceTo>EOB__c</referenceTo>
    <relationshipLabel>ERA</relationshipLabel>
    <relationshipName>EOB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EOB__c/fields/Manual_ERA__c.field-meta.xml
<CustomField>
    <fullName>Manual_ERA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual ERA?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EOB__c/fields/Total_Charge__c.field-meta.xml
<CustomField>
    <fullName>Total_Charge__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>By Provider</inlineHelpText>
    <label>Total Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EOB__c/fields/Total_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ERACustomWidgetCtrl.cls
public with sharing class ERACustomWidgetCtrl {
	@AuraEnabled
    public static List<EOB__c> fetchOriginalERA(String claimId)
    {
        List<EOB__c> eraLst = new List<EOB__c>([Select id, name, Total_Charge__c, Total_Paid__c 
        from EOB__c where Claim__c =: claimId AND Copy_Of_Original_ERA__c = false AND
         Claim__r.Manual_ERA__c = false WITH SECURITY_ENFORCED LIMIT 50000]);
        
        return eraLst;
    }
}