force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>This object is used to store Claim related data for a patient.</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>CS{YYMMDD}{000000}</displayFormat>
        <label>Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Accept_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Accept_Assignment__c</fullName>
    <description>Explain that they accept the Medicare-approved amount as the full payment for covered services.</description>
    <label>Accept Assignment</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Auto_Accident_Related__c.field-meta.xml
<CustomField>
    <fullName>Auto_Accident_Related__c</fullName>
    <description>Represents where an auto accident occurred</description>
    <label>Place of auto Accident</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/bill_taxid__c.field-meta.xml
<CustomField>
    <fullName>bill_taxid__c</fullName>
    <label>Bill_tax ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Billing_Provider_Tax_ID_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Provider_Tax_ID_Type__c</fullName>
    <description>Indicates the Category under which the Tax Id falls.</description>
    <label>Billing Provider Tax ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EIN</fullName>
            </value>
            <value>
                <fullName>SSN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <description>Represents self relationship.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claim_Status__c.field-meta.xml
<CustomField>
    <fullName>Claim_Status__c</fullName>
    <description>Represents the current status of claim processing.</description>
    <label>Claim Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Ready to Submit</fullName>
            </value>
            <value>
                <fullName>Sent to Clearing house</fullName>
            </value>
            <value>
                <fullName>Clearing house accepted</fullName>
            </value>
            <value>
                <fullName>Clearing house rejected</fullName>
            </value>
            <value>
                <fullName>Payer Accepted</fullName>
            </value>
            <value>
                <fullName>Payer Rejected</fullName>
            </value>
            <value>
                <fullName>ERA Received</fullName>
            </value>
            <value>
                <fullName>Claim Validation Error</fullName>
            </value>
            <value>
                <fullName>Paid and Patient Responsibility</fullName>
            </value>
            <value>
                <fullName>Paid and resolved</fullName>
            </value>
            <value>
                <fullName>Paid with Patient Responsibility – Ready to submit Secondary Insurance</fullName>
            </value>
            <value>
                <fullName>Overpaid</fullName>
            </value>
            <value>
                <fullName>Underpaid</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Paid and patient responsibility with Secondary</fullName>
            </value>
            <value>
                <fullName>ERA Received - Transferred to Secondary</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Generated</fullName>
                <isActive>false</isActive>
                <label>Generated</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
                <isActive>false</isActive>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Processed</fullName>
                <isActive>false</isActive>
                <label>Processed</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Transmitted</fullName>
                <isActive>false</isActive>
                <label>Transmitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Employment_Related__c.field-meta.xml
<CustomField>
    <fullName>Employment_Related__c</fullName>
    <description>Used to indicate that the patient's condition or the healthcare services provided are associated with their employment.</description>
    <inlineHelpText>Y=Yes
N=No</inlineHelpText>
    <label>Employment Related</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insured_Address__c.field-meta.xml
<CustomField>
    <fullName>Insured_Address__c</fullName>
    <description>Indicates the Address of the insured person.</description>
    <label>Insured Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insured_City__c.field-meta.xml
<CustomField>
    <fullName>Insured_City__c</fullName>
    <description>Indicated the City of the insured person.</description>
    <label>Insured City</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insured_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Insured_Country_Code__c</fullName>
    <description>Indicated the Country code of the Insured person.</description>
    <label>Insured Country Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insured_DOB__c.field-meta.xml
<CustomField>
    <fullName>Insured_DOB__c</fullName>
    <description>Date Of Birth of Insured person.</description>
    <label>Insured DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insured_s_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>Insured_s_ID_Number__c</fullName>
    <description>Captures the insured individual's identification number assigned by the insurance plan.</description>
    <inlineHelpText>The Insured’s ID Number is the identification number of the insured. This information identifies the insured to the payer. This field allows for entry of 29 characters.</inlineHelpText>
    <label>Insured’s ID Number</label>
    <length>29</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insured_s_Name__c.field-meta.xml
<CustomField>
    <fullName>Insured_s_Name__c</fullName>
    <description>Enter the insured’s full last name, first name, and middle initial. If the insured uses a last name suffix (e.g., Jr, Sr),  enter it after the last name and before the first name.  Titles (e.g., Sister, Capt, Dr) and professional suffixes (e.g., PhD, MD, Esq) should not be included with the name.Use commas to separate the last name, first name, and middle initial. A hyphen can be used for hyphenated names. Do not use periods within the name.</description>
    <label>Insured&apos;s Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insured_Sex__c.field-meta.xml
<CustomField>
    <fullName>Insured_Sex__c</fullName>
    <description>Sex/Gender of the isnured person.</description>
    <label>Insured Sex</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insured_State__c.field-meta.xml
<CustomField>
    <fullName>Insured_State__c</fullName>
    <description>Used to store state of insured person.</description>
    <label>Insured State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insured_Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Insured_Zipcode__c</fullName>
    <label>Insured Zipcode</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/NPI__c.field-meta.xml
<CustomField>
    <fullName>NPI__c</fullName>
    <description>The NPI ID number of the referring, ordering, or supervising provider is the unique identifier of the professional.</description>
    <label>NPI</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Other_Payer_Name__c.field-meta.xml
<CustomField>
    <fullName>Other_Payer_Name__c</fullName>
    <description>Used to indicate the name and address of the primary payer for the claim on UB04 Form.</description>
    <label>Payer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Patient_Country_Code__c</fullName>
    <description>Indicates the Country Code of the patient.</description>
    <label>Patient Country Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient_DOB__c.field-meta.xml
<CustomField>
    <fullName>Patient_DOB__c</fullName>
    <description>Used to store patient's date of birth.</description>
    <label>Patient DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Patient_First_Name__c</fullName>
    <description>Used to store patient's first name.</description>
    <label>Patient First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Patient_Last_Name__c</fullName>
    <description>Used to store patient's last name.</description>
    <label>Patient Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient_Relationship_to_Insured__c.field-meta.xml
<CustomField>
    <fullName>Patient_Relationship_to_Insured__c</fullName>
    <description>Code that reflects the patient's relationship to the insured person of Primary.</description>
    <label>Patient Relationship to Insured</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient_s_Address__c.field-meta.xml
<CustomField>
    <fullName>Patient_s_Address__c</fullName>
    <description>Used to store patient's address.</description>
    <label>Patient’s Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient_s_City__c.field-meta.xml
<CustomField>
    <fullName>Patient_s_City__c</fullName>
    <description>Used to store patient's city name.</description>
    <label>Patient’s City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient_s_State__c.field-meta.xml
<CustomField>
    <fullName>Patient_s_State__c</fullName>
    <description>Used to store patient's state.</description>
    <label>Patient’s State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient_s_Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Patient_s_Zipcode__c</fullName>
    <description>Used to store patient's zipcode.</description>
    <label>Patient’s Zipcode</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient_Sex__c.field-meta.xml
<CustomField>
    <fullName>Patient_Sex__c</fullName>
    <description>Refer patient's gender.</description>
    <label>Patient Sex</label>
    <length>29</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Payer_ID__c.field-meta.xml
<CustomField>
    <fullName>Payer_ID__c</fullName>
    <description>Used to store payer Id.</description>
    <label>Payer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Payer_Order__c.field-meta.xml
<CustomField>
    <fullName>Payer_Order__c</fullName>
    <description>Represents type of claim.</description>
    <label>Payer Order</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Pcn__c.field-meta.xml
<CustomField>
    <fullName>Pcn__c</fullName>
    <label>Pcn</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Place_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Place_of_Service__c</fullName>
    <description> Indicates the location where a healthcare service was provided.</description>
    <label>Place of Service</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim_Line_Items__c/Claim_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This object is used to store procedure level details related to a claim.</description>
    <label>Claim Procedure Line Item</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>Claim Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Procedure Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim_Line_Items__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents claim associated with claim line item.</description>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claim Line Items</relationshipLabel>
    <relationshipName>Claim_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim_Line_Items__c/fields/Place_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Place_of_Service__c</fullName>
    <description>Indicates the location where the healthcare service was provided</description>
    <label>Place of Service</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ClaimGetRequestNightlyBatch_Test.cls
@isTest
private class ClaimGetRequestNightlyBatch_Test {
    @TestSetup
    private static void createData(){
        //Claim Creation START
        Claim__c claimRecord = new Claim__c();
        claimRecord.claim_status__c = 'Ready to Submit';
        claimRecord.pcn__c = 'John';
        claimRecord.patient_first_Name__c = 'David';
        claimRecord.patient_last_Name__c = 'Beckam';
        claimRecord.npi__c = '1831234939';
        claimRecord.payer_id__c = '20413';
        claimRecord.other_payer_name__c = 'LIC';
        claimRecord.Insured_s_ID_Number__c = '1232';
        claimRecord.patient_dob__c = System.today().addYears(-40);
        claimRecord.patient_sex__c = 'M';
        claimRecord.insured_s_name__c = 'David';
        claimRecord.insured_s_name__c = 'Beckam';
        claimRecord.payer_order__c = 'Primary';
        claimRecord.patient_s_address__c = 'Noida';
        claimRecord.patient_s_city__c = 'Noida';
        claimRecord.patient_country_code__c = 'IN';
        claimRecord.patient_s_state__c = 'UP';
        claimRecord.patient_s_zipcode__c = 201301;
        claimRecord.Patient_Relationship_to_Insured__c = 'Father';
        claimRecord.insured_address__c = 'Noida';
        claimRecord.insured_city__c = 'Noida';
        claimRecord.insured_country_code__c = 'IN';
        claimRecord.insured_state__c = 'UP';
        claimRecord.insured_zipcode__c = 201301;
        claimRecord.employment_related__c = 'No';
        claimRecord.Auto_Accident_Related__c = 'No';
        claimRecord.insured_dob__c = System.today().addYears(-10);
        claimRecord.insured_sex__c = 'M';
        claimRecord.Place_of_Service__c = 'Delhi';
        claimRecord.bill_taxid__c = '123656789';
        claimRecord.Billing_Provider_Tax_ID_Type__c = 'E';
        claimRecord.Accept_Assignment__c = 'Y';
        claimRecord.total_charge__c = 900;
        claimRecord.amount_paid__c = 0;
        claimRecord.Billing_Provider_Name__c = 'ATHENA';
        claimRecord.Billing_Provider_Address_1__c = 'Watertown';
        claimRecord.Billing_Provider_State__c = 'CA';
        claimRecord.Billing_Provider_Zip__c = '232329998';
        claimRecord.Bill_Phone__c = '4152155300';
        claimRecord.Billing_Provider_City__c = 'Watertown';
        claimRecord.Diag_1__c = 'B86';
        insert claimRecord;
        //Claim Line Item Creation START
        Claim_Line_Items__c rec = new Claim_Line_Items__c();
        rec.CPT_HCPCS_Code__c = '38525';
        rec.Days_Units__c = 2;
        rec.From_Date__c = System.today().adddays(-10);
        rec.To_Date__c = System.today().adddays(-8);
        rec.procedure_charge__c = 900;
        rec.diag_ref__c = 'A';
        rec.claim__c = claimRecord.Id;
        insert rec;
    }
    @isTest
    private static void callingBatch(){
        ClaimsGetRequestNightlyBatch callOutBatch = new ClaimsGetRequestNightlyBatch();
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new ClaimsPostRequestNightlyMock()); 
        Database.executeBatch(callOutBatch, 1);
        system.assertEquals([SELECT Id, payer_id__c FROM claim__c LIMIT 1].payer_id__c, '20413','');
        Test.stopTest();
    }
}