force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>This object is used to store Claim related data for a patient.</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>CS{YYMMDD}{000000}</displayFormat>
        <label>Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Denotes claim generated for which patient(Account).</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>Batch_Id__c</fullName>
    <description>Used to store batchid attribute coming from ClaimMD.</description>
    <label>Batch ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Bill_Phone__c.field-meta.xml
<CustomField>
    <fullName>Bill_Phone__c</fullName>
    <description>Used to store Phone of billing provider.</description>
    <label>Bill Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <description>Represents self relationship.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claimid__c.field-meta.xml
<CustomField>
    <fullName>Claimid__c</fullName>
    <description>Used to store batchid attribute coming from ClaimMD.</description>
    <label>Claim ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PatientlistViewcontroller.cls
public with sharing class PatientlistViewcontroller {
    @AuraEnabled
    public static List<Account> fetchPatientlist() {
        list<Account> AccountList = [Select id, name, AccountNumber,AnnualRevenue from Account WHERE ID!=NULL
        WITH SECURITY_ENFORCED];
        return AccountList;
    }
    @AuraEnabled
    public static List<Claim__c> fetchClaims(string pid) {
        list<Claim__c> ClaimList = [Select id, Batch_Id__c, Bill_Phone__c,Claimid__c,Account__c from Claim__c where 
                                    Account__c =: pid WITH SECURITY_ENFORCED];
        return ClaimList;
    }
    /*@AuraEnabled
public static List<Payment> fetchPayment() {
list<Payment> PaymentList = [Select id,Amount,Email,Balance from Payment limit 10];
return PaymentList;
}
*/
}