force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>This object is used to store Claim related data for a patient.</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>CS{YYMMDD}{000000}</displayFormat>
        <label>Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Accept_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Accept_Assignment__c</fullName>
    <description>Explain that they accept the Medicare-approved amount as the full payment for covered services.</description>
    <label>Accept Assignment</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Billing_Provider_Tax_ID_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Provider_Tax_ID_Type__c</fullName>
    <description>Indicates the Category under which the Tax Id falls.</description>
    <label>Billing Provider Tax ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EIN</fullName>
            </value>
            <value>
                <fullName>SSN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <description>Represents self relationship.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claim_Status__c.field-meta.xml
<CustomField>
    <fullName>Claim_Status__c</fullName>
    <description>Represents the current status of claim processing.</description>
    <label>Claim Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Ready to Submit</fullName>
            </value>
            <value>
                <fullName>Sent to Clearing house</fullName>
            </value>
            <value>
                <fullName>Clearing house accepted</fullName>
            </value>
            <value>
                <fullName>Clearing house rejected</fullName>
            </value>
            <value>
                <fullName>Payer Accepted</fullName>
            </value>
            <value>
                <fullName>Payer Rejected</fullName>
            </value>
            <value>
                <fullName>ERA Received</fullName>
            </value>
            <value>
                <fullName>Claim Validation Error</fullName>
            </value>
            <value>
                <fullName>Paid and Patient Responsibility</fullName>
            </value>
            <value>
                <fullName>Paid and resolved</fullName>
            </value>
            <value>
                <fullName>Paid with Patient Responsibility – Ready to submit Secondary Insurance</fullName>
            </value>
            <value>
                <fullName>Overpaid</fullName>
            </value>
            <value>
                <fullName>Underpaid</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Paid and patient responsibility with Secondary</fullName>
            </value>
            <value>
                <fullName>ERA Received - Transferred to Secondary</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Generated</fullName>
                <isActive>false</isActive>
                <label>Generated</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
                <isActive>false</isActive>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Processed</fullName>
                <isActive>false</isActive>
                <label>Processed</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Transmitted</fullName>
                <isActive>false</isActive>
                <label>Transmitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient_Relationship_to_Insured__c.field-meta.xml
<CustomField>
    <fullName>Patient_Relationship_to_Insured__c</fullName>
    <description>Code that reflects the patient's relationship to the insured person of Primary.</description>
    <label>Patient Relationship to Insured</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Payerid__c.field-meta.xml
<CustomField>
    <fullName>Payerid__c</fullName>
    <description>Primary payer's health plan ID.</description>
    <label>Payerid</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Resubmission_Code__c.field-meta.xml
<CustomField>
    <fullName>Resubmission_Code__c</fullName>
    <description>Used to indicate if the submitted claim is a resubmission, a correction, or a void/replacement of an earlier claim. </description>
    <label>Resubmission Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resubmission_Codes__mdt/Resubmission_Codes__mdt.object-meta.xml
<CustomObject>
    <label>Resubmission Codes</label>
    <pluralLabel>Resubmission Codes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Resubmission_Codes__mdt/fields/Quotes__c.field-meta.xml
<CustomField>
    <fullName>Quotes__c</fullName>
    <label>Quotes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/dualBoxcontroller.cls
public with sharing class dualBoxcontroller {
    
    @AuraEnabled
    public static wrapper getselectOptions(String Cid) { 
        string Qutes ;
        wrapper objwrap = new wrapper();
        try{
        Resubmission_Codes__mdt[] obj = [SELECT MasterLabel, QualifiedApiName, Quotes__c 
                                         FROM Resubmission_Codes__mdt 
                                         WHERE MasterLabel = 'DualboxValues'
                                         WITH SECURITY_ENFORCED];
        for(Resubmission_Codes__mdt rsc : obj){
            Qutes = rsc.Quotes__c;
        }
        List < String > allOpts = Qutes.split(',');
        Claim__c ClaimData = new Claim__c();
        ClaimData=[Select Id,Patient_Relationship_to_Insured__c,Claim_Status__c,Payerid__c,
                   Billing_Provider_Tax_ID_Type__c,Accept_Assignment__c  from Claim__c where id =: Cid
                   WITH SECURITY_ENFORCED];
        //  return ClaimData;
        //  
        objwrap.claimRecord = ClaimData ;
        objwrap.ListOfCodes = allOpts ;
        }
        catch(Exception e){
        ExceptionLog.logError(e);
        }
         return objwrap ; 
      }    
    @AuraEnabled
    public static void getValues(Id claimid, List<string> selectedoptions) {
        system.debug('clmid'+claimid);
        system.debug('clmid'+selectedoptions.size());
        string values = '' ;
        
        for(integer i=0 ; i<selectedoptions.size() ;i++ ){
            if(values == ''){
                values = selectedoptions[i];
            }
            else{
                values = values + ',' + selectedoptions[i] ;
                // values = selectedoptions[i]+',';
            } 
        }
        
        Claim__c obj = [Select id , name,Resubmission_Code__c,claim_status__c 
                        from Claim__c where id=: claimid WITH SECURITY_ENFORCED];
        obj.Resubmission_Code__c = values;
        obj.claim_status__c = 'Ready to Submit';
        if(Schema.sObjectType.Claim__c.fields.Resubmission_Code__c.isUpdateable() &&
           Schema.sObjectType.Claim__c.fields.claim_status__c.isUpdateable()){
               update obj;
           }
    }
    
    public class wrapper{
        @AuraEnabled public Claim__c claimRecord;
        @AuraEnabled public List<String> ListOfCodes;
    }
    
}