force-app/main/default/objects/Actual_Price__c/Actual_Price__c.object-meta.xml
<CustomObject>
    <description>Indicates the List price for a procedure w.r.t the Provider.</description>
    <label>Actual Price</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Actual Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actual Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Actual_Price__c/fields/Procedure__c.field-meta.xml
<CustomField>
    <fullName>Procedure__c</fullName>
    <description>This field is used to associate the procedure codes with contracted price.</description>
    <label>Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Procedure__c.Account__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Procedure__c.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Patient_Procedure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Procedure__c</referenceTo>
    <relationshipLabel>Actual Price</relationshipLabel>
    <relationshipName>Actual_Price</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Actual_Price__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <description>This field is used to associate the provider with contracted price.</description>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Template_Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>Actual Price</relationshipLabel>
    <relationshipName>Actual_Price</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>This object is used to store Claim related data for a patient.</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>CS{YYMMDD}{000000}</displayFormat>
        <label>Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Denotes claim generated for which patient(Account).</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <description>Represents self relationship.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claimid__c.field-meta.xml
<CustomField>
    <fullName>Claimid__c</fullName>
    <description>Used to store batchid attribute coming from ClaimMD.</description>
    <label>Claim ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Manual_ERA__c.field-meta.xml
<CustomField>
    <fullName>Manual_ERA__c</fullName>
    <description>Refers Era Generation Method</description>
    <defaultValue>false</defaultValue>
    <label>Manual ERA?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Total_Charge__c.field-meta.xml
<CustomField>
    <fullName>Total_Charge__c</fullName>
    <description>Indicates total amount billed by the healthcare provider for the services.</description>
    <defaultValue>0</defaultValue>
    <label>Total Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim_Line_Items__c/Claim_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This object is used to store procedure level details related to a claim.</description>
    <label>Claim Procedure Line Item</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>Claim Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Procedure Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim_Line_Items__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents claim associated with claim line item.</description>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claim Line Items</relationshipLabel>
    <relationshipName>Claim_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim_Line_Items__c/fields/Procedure__c.field-meta.xml
<CustomField>
    <fullName>Procedure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate the procedure with the Claim line item.</description>
    <label>Procedure</label>
    <referenceTo>Procedure__c</referenceTo>
    <relationshipLabel>Claim Line Items</relationshipLabel>
    <relationshipName>Claim_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EOB__c/EOB__c.object-meta.xml
<CustomObject>
    <description>This object stores the Parent ERA and child ERA.
Parent ERA is an orphan record whereas Child ERA is associated to a self lookup field to Parent ERA.</description>
    <label>ERA</label>
    <nameField>
        <displayFormat>ERA-{0000}</displayFormat>
        <label>ERA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EOB__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ERA</relationshipLabel>
    <relationshipName>ERA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EOB__c/fields/Check_Number__c.field-meta.xml
<CustomField>
    <fullName>Check_Number__c</fullName>
    <label>Check Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EOB__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipName>EOB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EOB__c/fields/Copy_Of_Original_ERA__c.field-meta.xml
<CustomField>
    <fullName>Copy_Of_Original_ERA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Copy Of Original ERA?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EOB__c/fields/EOB__c.field-meta.xml
<CustomField>
    <fullName>EOB__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ERA</label>
    <referenceTo>EOB__c</referenceTo>
    <relationshipLabel>ERA</relationshipLabel>
    <relationshipName>EOB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EOB__c/fields/EOB_Id__c.field-meta.xml
<CustomField>
    <fullName>EOB_Id__c</fullName>
    <label>ERA Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EOB__c/fields/Manual_ERA__c.field-meta.xml
<CustomField>
    <fullName>Manual_ERA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual ERA?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EOB__c/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <label>Provider Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EOB__c/fields/Total_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Total_Allowed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Allowed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EOB__c/fields/Total_Charge__c.field-meta.xml
<CustomField>
    <fullName>Total_Charge__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>By Provider</inlineHelpText>
    <label>Total Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ERA_Line_Item__c/ERA_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This object is used to track the line level details of each Child ERA record.</description>
    <label>ERA Procedure Line Item</label>
    <nameField>
        <displayFormat>ELI-{0000}</displayFormat>
        <label>ERA Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERA Procedure Line Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ERA_Line_Item__c/fields/Claim_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>Claim_Line_Items__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate the Claim line item with the ERA line item.</description>
    <label>Claim Line Items</label>
    <referenceTo>Claim_Line_Items__c</referenceTo>
    <relationshipLabel>ERA Line Item</relationshipLabel>
    <relationshipName>ERA_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ERA_Line_Item__c/fields/EOB__c.field-meta.xml
<CustomField>
    <fullName>EOB__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate the ERA with the ERA line item.</description>
    <label>ERA</label>
    <referenceTo>EOB__c</referenceTo>
    <relationshipLabel>ERA Line Item</relationshipLabel>
    <relationshipName>ERA_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ERA_Line_Item__c/fields/Total_Charge__c.field-meta.xml
<CustomField>
    <fullName>Total_Charge__c</fullName>
    <description>Sum of all charges for services or procedures in the healthcare claim.</description>
    <label>Total Charge</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Procedure__c/Procedure__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the template procedures in the system. These might include lab order, medications, CPT codes, Appointment procedures.</description>
    <label>Procedure Codes</label>
    <nameField>
        <label>Code Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedure Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Procedure__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Procedures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipName>Procedures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rendering Provider</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Provider__c.Account__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipName>Procedures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>This object stores both template and patient providers. Providers in elixir are facilties.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Represents patient-provider relationship.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents self-relationship.</description>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.Account__r.Id</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ERAPaymentPostingTest.cls
/*
Created By - Sonal Agarwal
Created Date - 26-Nov-2020
Description - ERA Payment Posting Test Class
Apex Class - ERAPaymentPostingCtrl
Last Modified By: Shwetha KJ
*/
@isTest
public class ERAPaymentPostingTest {
    
    @isTest
    public static void testPaymentPosting() {
        
        Account patient = TestDataFactory.createPatientAcc();
        insert patient;
        
        Procedure__c procedureTemp = TestDataFactory.createProcedure(patient.Id);
        procedureTemp.Account__c =  null;
        insert procedureTemp;
        
        Provider__c providerTemp = TestDataFactory.createProviderTemp();
        //providerTemp.Account__c =  null; 
        insert providerTemp;
        
        Provider__c provider = TestDataFactory.createProvider(patient.Id);
        insert provider;
        
        Actual_Price__c actualPrice = TestDataFactory.createActualPrice(procedureTemp.Id, providerTemp.Id);
        insert actualPrice;
        
        Claim__c claim = TestDataFactory.createClaim(patient.Id);
        claim.Claimid__c = '12345';
        insert claim;
        
        Claim__c claim2 = TestDataFactory.createClaim(patient.Id);
        claim2.Claimid__c = '12345';
        insert claim2;
        
        Procedure__c procedure = TestDataFactory.createProcedure(patient.Id);
        procedure.Claim__c = claim.Id;
        insert procedure;
        
        Procedure__c procedure2 = TestDataFactory.createProcedure(patient.Id);
        procedure2.Claim__c = claim2.Id;
        insert procedure2;
        
        Procedure__c procedure1 = TestDataFactory.createProcedure(patient.Id);
        insert procedure1;
        
        Claim_Line_Items__c cli = TestDataFactory.createClaimLineItems(claim.Id, procedure.Id);
        insert cli;
        
        Claim_Line_Items__c cli2 = TestDataFactory.createClaimLineItems(claim2.Id, procedure.Id);
        insert cli2;
        
        Claim_Line_Items__c cli3 = TestDataFactory.createClaimLineItems(claim2.Id, procedure2.Id);
        insert cli3;
        
        EOB__c masterEra = TestDataFactory.createERA();
        insert masterEra;
        
        EOB__c subEra = TestDataFactory.createERA();
        subEra.EOB__c = masterEra.Id;
        subEra.ElixirSuite__PaidDate__c=System.today();
        subEra.Claim__c = claim.id;
        subEra.Provider_Name__c = 'Test Provider';
        subEra.Account__c = patient.id;
        subEra.Total_Allowed__c = 800;
        subEra.Total_Charge__c = 800;
        insert subEra;
        
        EOB__c subEra2 = TestDataFactory.createERA();
        subEra2.EOB__c = masterEra.Id;
        subEra2.Claim__c = claim2.id;
        subEra2.Provider_Name__c = 'Test Provider 2';
        subEra2.Account__c = patient.id;
        subEra2.ElixirSuite__PaidDate__c=System.today();
        subEra2.Total_Allowed__c = 600;
        subEra2.Total_Charge__c = 600;
        insert subEra2;
        
        ERA_Line_Item__c eli = TestDataFactory.createELI(subEra.id, cli.id);
        insert eli;
        
        ERA_Line_Item__c eli2 = TestDataFactory.createELI(subEra2.id, cli2.id);
        insert eli2;
        
        ERA_Line_Item__c eli3 = TestDataFactory.createELI(subEra2.id, cli3.id);
        insert eli3;
        
        
        
        Test.startTest();
        Integer parentERAPageNo = 1;
        Integer recordToDisplay = 20;
        Integer childERAPageNo = 1;
        ERAPaymentPostingCtrl.getParentERA(parentERAPageNo ,recordToDisplay,childERAPageNo);
        ERAPaymentPostingCtrl.getClaimERA(system.today(), system.today(), 'eraNo', 'patName', 'claimId',childERAPageNo ,recordToDisplay);
        ERAPaymentPostingCtrl.getMasterERA(system.today(), system.today(), 'paymentTrace', 'eraId', 'payerId', 'eraNo',parentERAPageNo ,recordToDisplay);
      //  ERAPaymentPostingCtrl.postERAPayments(eraItemList,masterEra.Id);
        Test.stopTest();
      //  system.assert( eraListItemRec.ProcCode!=null);
      System.assertEquals(1, 1, 'welcome to Elixir');
    }
}
   /* @isTest
    public static void testPaymentPost() {
        
        Account patient = TestDataFactory.createPatientAcc();
        insert patient;
        
        Procedure__c procedureTemp = TestDataFactory.createProcedure(patient.Id);
        procedureTemp.Account__c =  null;
        insert procedureTemp;
        
        Provider__c providerTemp = TestDataFactory.createProvider(patient.Id);
        providerTemp.Account__c =  null;
        insert providerTemp;
        
        Provider__c provider = TestDataFactory.createProvider(patient.Id);
        insert provider;
        
        Actual_Price__c actualPrice = TestDataFactory.createActualPrice(procedureTemp.Id, providerTemp.Id);
        insert actualPrice;
        
        Claim__c claim = TestDataFactory.createClaim(patient.Id);
        claim.Claimid__c = '12345';
        insert claim;
        
        Claim__c claim2 = TestDataFactory.createClaim(patient.Id);
        claim2.Claimid__c = '12345';
        insert claim2;
        
        Procedure__c procedure = TestDataFactory.createProcedure(patient.Id);
        procedure.Claim__c = claim.Id;
        insert procedure;
        
        Procedure__c procedure2 = TestDataFactory.createProcedure(patient.Id);
        procedure2.Claim__c = claim2.Id;
        insert procedure2;
        
        Procedure__c procedure1 = TestDataFactory.createProcedure(patient.Id);
        insert procedure1;
        
        Claim_Line_Items__c cli = TestDataFactory.createClaimLineItems(claim.Id, procedure.Id);
        insert cli;
        
        Claim_Line_Items__c cli2 = TestDataFactory.createClaimLineItems(claim2.Id, procedure.Id);
        insert cli2;
        
        Claim_Line_Items__c cli3 = TestDataFactory.createClaimLineItems(claim2.Id, procedure2.Id);
        insert cli3;
        
        EOB__c masterEra = TestDataFactory.createERA();
        insert masterEra;
        
        EOB__c subEra = TestDataFactory.createERA();
        subEra.EOB__c = masterEra.Id;
        subEra.Claim__c = claim.id;
        subEra.Provider_Name__c = 'Test Provider';
        subEra.Account__c = patient.id;
        subEra.Total_Allowed__c = 800;
        subEra.Total_Charge__c = 800;
        
        insert subEra;
        
        EOB__c subEra2 = TestDataFactory.createERA();
        subEra2.EOB__c = masterEra.Id;
        subEra2.Claim__c = claim2.id;
        subEra2.Provider_Name__c = 'Test Provider 2';
        subEra2.Account__c = patient.id;
        subEra2.Total_Allowed__c = 600;
        subEra2.Total_Charge__c = 600;
        subEra.Manual_ERA__c = false;
        subEra.Copy_Of_Original_ERA__c = true;
        insert subEra2;
        
        ERA_Line_Item__c eli = TestDataFactory.createELI(subEra.id, cli.id);
        insert eli;
        
        ERA_Line_Item__c eli2 = TestDataFactory.createELI(subEra2.id, cli2.id);
        insert eli2;
        
        ERA_Line_Item__c eli3 = TestDataFactory.createELI(subEra2.id, cli3.id);
        insert eli3;
        
        ERAPaymentPostingCtrl.ERAItem eraListItemRec = new ERAPaymentPostingCtrl.ERAItem();
        eraListItemRec.Id = eli.Id;
        eraListItemRec.ProcCode = '1';
        eraListItemRec.StartDate = null;
        eraListItemRec.EndDate = null;
        eraListItemRec.Mod1 = '01';
        eraListItemRec.Mod2 = '01';
        eraListItemRec.Mod3 = '01';
        eraListItemRec.Mod4 = '01';
        eraListItemRec.Charge = 1000;
        eraListItemRec.AllowedAmount = 1000;
        eraListItemRec.Deductible = 10;
        eraListItemRec.CoPay = 50;
        eraListItemRec.totalAdjustment = 100;
        eraListItemRec.ProviderPaid = 700;
        eraListItemRec.PatientResp = 200;
        
        List<ERAPaymentPostingCtrl.ERAItem> eraItemList = new List<ERAPaymentPostingCtrl.ERAItem>();
        eraItemList.add(eraListItemRec);
        
        Test.startTest();
        ERAPaymentPostingCtrl.saveERA(eraItemList,masterEra.Id);
        Test.stopTest();
        system.assert( eraListItemRec.ProcCode!=null);
    }
    
    
    
    @isTest
    public static void unitTest()
    {
        Account patient = TestDataFactory.createPatientAcc();
        insert patient;
        
        Procedure__c procedureTemp = TestDataFactory.createProcedure(patient.Id);
        procedureTemp.Account__c =  null;
        insert procedureTemp;
        
        Provider__c providerTemp = TestDataFactory.createProvider(patient.Id);
        providerTemp.Account__c =  null;
        insert providerTemp;
        
        Provider__c provider = TestDataFactory.createProvider(patient.Id);
        insert provider;
        
        Actual_Price__c actualPrice = TestDataFactory.createActualPrice(procedureTemp.Id, providerTemp.Id);
        insert actualPrice;
        
        Claim__c claim = TestDataFactory.createClaim(patient.Id);
        claim.Claimid__c = '12345';
        insert claim;
        
        Claim__c claim2 = TestDataFactory.createClaim(patient.Id);
        claim2.Claimid__c = '12345';
        insert claim2;
        
        Procedure__c procedure = TestDataFactory.createProcedure(patient.Id);
        procedure.Claim__c = claim.Id;
        insert procedure;
        
        Procedure__c procedure2 = TestDataFactory.createProcedure(patient.Id);
        procedure2.Claim__c = claim2.Id;
        insert procedure2;
        
        Procedure__c procedure1 = TestDataFactory.createProcedure(patient.Id);
        insert procedure1;
        
        Claim_Line_Items__c cli = TestDataFactory.createClaimLineItems(claim.Id, procedure.Id);
        insert cli;
        
        Claim_Line_Items__c cli2 = TestDataFactory.createClaimLineItems(claim2.Id, procedure.Id);
        insert cli2;
        
        Claim_Line_Items__c cli3 = TestDataFactory.createClaimLineItems(claim2.Id, procedure2.Id);
        insert cli3;
        
        EOB__c masterEra = TestDataFactory.createERA();
        insert masterEra;
        
        EOB__c subEra = TestDataFactory.createERA();
        subEra.EOB__c = masterEra.Id;
        subEra.Claim__c = claim.id;
        subEra.Provider_Name__c = 'Test Provider';
        subEra.Account__c = patient.id;
        subEra.Total_Allowed__c = 800;
        subEra.Total_Charge__c = 800;
        subEra.ElixirSuite__Manual_ERA__c = True;
        insert subEra;
        
        EOB__c subEra2 = TestDataFactory.createERA();
        subEra2.EOB__c = masterEra.Id;
        subEra2.Claim__c = claim2.id;
        subEra2.Provider_Name__c = 'Test Provider 2';
        subEra2.Account__c = patient.id;
        subEra2.Total_Allowed__c = 600;
        subEra2.Total_Charge__c = 600;
        subEra2.ElixirSuite__Manual_ERA__c = True;
        insert subEra2;
        
        ERA_Line_Item__c eli = TestDataFactory.createELI(subEra.id, cli.id);
        insert eli;
        
        ERA_Line_Item__c eli2 = TestDataFactory.createELI(subEra2.id, cli2.id);
        insert eli2;
        
        ERA_Line_Item__c eli3 = TestDataFactory.createELI(subEra2.id, cli3.id);
        insert eli3;
        
        
        Test.startTest();
        ERAPaymentPostingCtrl.getMasterERA(System.today().addDays(-10), System.today().addDays(10), masterEra.Check_Number__c, masterEra.EOB_Id__c);
        ERAPaymentPostingCtrl.getSelectedERAs(System.today().addDays(-10), System.today().addDays(10), subEra.Check_Number__c, masterEra.Id, subEra.Claim__r.Claimid__c);
        //ERAPaymentPostingCtrl.getSelectedERAs(null, null, '', masterEra.Id, '');
        
        ERAPaymentPostingCtrl.getERALineItems(subEra.id);
        ERAPaymentPostingCtrl.getERALineItems(subEra2.id);
        /*Id Id = eli3.Id;           
String ProcCode = 'PRocode';
Date StartDate =System.today();
Date EndDate = System.today()+5;
String Mod1= 'Mod1';
String Mod2= 'Mod2';
String Mod3= 'Mod3';
String Mod4= 'Mod4';
Decimal   Charge = 200.0;
Decimal   AllowedAmount = 300.0;
Decimal   Deductible =150.0;
Decimal   CoPay = 250.0;
Decimal   totalAdjustment = 500.0;
Decimal   ProviderPaid = 350.0;
Decimal   PatientResp = 200.0;
Decimal   Adjustment_Amount_1 = 275.0;
Decimal   Adjustment_Amount_2 = 375.0;
Decimal   Adjustment_Amount_3 = 400.0;
Decimal   Adjustment_Amount_4 = 500.0;
Decimal   Adjustment_Amount_5 = 600.0;
Decimal   Adjustment_Amount_6 = 400.0;*/
        //ERAPaymentPostingCtrl.ERAItem itm = new ERAPaymentPostingCtrl.ERAItem(Id,ProcCode,StartDate,EndDate,Mod1,Mod2,Mod3,Mod4,Charge,AllowedAmount,Deductible,CoPay,totalAdjustment,ProviderPaid,PatientResp,Adjustment_Amount_1,Adjustment_Amount_2,Adjustment_Amount_3,Adjustment_Amount_4,Adjustment_Amount_5,Adjustment_Amount_6);
        //ERAPaymentPostingCtrl.postERAPayments(null,eli3.Id);
        //Test.stopTest();
      //  system.assert( subEra2.Provider_Name__c !=null);
   // }*/