force-app/main/default/objects/Actual_Price__c/Actual_Price__c.object-meta.xml
<CustomObject>
    <description>Indicates the List price for a procedure w.r.t the Provider.</description>
    <label>Actual Price</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Actual Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actual Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Actual_Price__c/fields/Procedure__c.field-meta.xml
<CustomField>
    <fullName>Procedure__c</fullName>
    <description>This field is used to associate the procedure codes with contracted price.</description>
    <label>Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Procedure__c.Account__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Procedure__c.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Patient_Procedure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Procedure__c</referenceTo>
    <relationshipLabel>Actual Price</relationshipLabel>
    <relationshipName>Actual_Price</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Actual_Price__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <description>This field is used to associate the provider with contracted price.</description>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Template_Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>Actual Price</relationshipLabel>
    <relationshipName>Actual_Price</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Master_Transaction__c/Master_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object contains the details of payments collected from customer in form of advance payment via cash/credit card/cheque or any other mode of payment. This object also contains patient credits as well.</description>
    <label>Other Transactions</label>
    <nameField>
        <displayFormat>OT-{0000}</displayFormat>
        <label>Other Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Master_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Transaction__c/fields/Payment_Received_By__c.field-meta.xml
<CustomField>
    <fullName>Payment_Received_By__c</fullName>
    <label>Payment By</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient_Statment_GenerInterval__c/Patient_Statment_GenerInterval__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>PatientStatmentGenerInterval</label>
</CustomObject>

force-app/main/default/objects/Patient_Statment_GenerInterval__c/fields/No_of_Days__c.field-meta.xml
<CustomField>
    <fullName>No_of_Days__c</fullName>
    <label>No of Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object contains the summary of all the transactional details linked with a patient procedure. Also it contains the rollup for patient paid amount, total refund amount, total discount applied, primary insurance paid and secondary insurance paid amount.</description>
    <label>Master Transaction</label>
    <nameField>
        <displayFormat>PAYMENT-{0000}</displayFormat>
        <label>Payment Received Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Transaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Payment_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Actual_Price__c.field-meta.xml
<CustomField>
    <fullName>Actual_Price__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Actual Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Insurance_Paid__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Paid__c</fullName>
    <label>Primary Insurance Paid</label>
    <summarizedField>Transactions__c.Amount_Paid__c</summarizedField>
    <summaryFilterItems>
        <field>Transactions__c.Payment_Received_By__c</field>
        <operation>equals</operation>
        <value>Insurance</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transactions__c.Type_of_Payment__c</field>
        <operation>equals</operation>
        <value>Payment</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transactions__c.Reverse_Reconciliation__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transactions__c.Transaction_Status__c</field>
        <operation>equals</operation>
        <value>Successful</value>
    </summaryFilterItems>
    <summaryForeignKey>Transactions__c.Master_Transaction__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Master_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Master_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Transaction</label>
    <referenceTo>Master_Transaction__c</referenceTo>
    <relationshipName>Payment_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Payment_Adjustments__c.field-meta.xml
<CustomField>
    <fullName>Payment_Adjustments__c</fullName>
    <label>Payment Adjustments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Posted__c.field-meta.xml
<CustomField>
    <fullName>Posted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Posted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Procedure__c.field-meta.xml
<CustomField>
    <fullName>Procedure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Procedure</label>
    <referenceTo>Procedure__c</referenceTo>
    <relationshipName>Payment_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <referenceTo>Provider__c</referenceTo>
    <relationshipName>Payment_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Total_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Paid_Amount__c</fullName>
    <label>Total Patient Paid Amount</label>
    <summarizedField>Transactions__c.Amount_Paid__c</summarizedField>
    <summaryFilterItems>
        <field>Transactions__c.Payment_Received_By__c</field>
        <operation>equals</operation>
        <value>Patient</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transactions__c.Type_of_Payment__c</field>
        <operation>equals</operation>
        <value>Payment</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transactions__c.Reverse_Reconciliation__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transactions__c.Transaction_Status__c</field>
        <operation>equals</operation>
        <value>Successful</value>
    </summaryFilterItems>
    <summaryForeignKey>Transactions__c.Master_Transaction__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Procedure__c/Procedure__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the template procedures in the system. These might include lab order, medications, CPT codes, Appointment procedures.</description>
    <label>Procedure Codes</label>
    <nameField>
        <label>Code Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedure Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Procedure__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Procedures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/From_Date_of_Service__c.field-meta.xml
<CustomField>
    <fullName>From_Date_of_Service__c</fullName>
    <label>From Date of Service</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rendering Provider</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Provider__c.Account__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipName>Procedures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/Type_of_Procedure__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Procedure__c</fullName>
    <label>Type of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Private Payment</fullName>
            </value>
            <value>
                <fullName>Insurance Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>This object stores both template and patient providers. Providers in elixir are facilties.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Represents patient-provider relationship.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents self-relationship.</description>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.Account__r.Id</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transactions__c/Transactions__c.object-meta.xml
<CustomObject>
    <description>This object contains the details of payments, refunds, reversals, discounts, adjustments against master transaction (ElixirSuite__Payment_Transaction__c) created for a patient procedure.</description>
    <label>Transactions</label>
    <nameField>
        <displayFormat>Transaction-{0000}</displayFormat>
        <label>Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transactions__c/fields/Master_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Master_Transaction__c</fullName>
    <label>Master Transaction</label>
    <referenceTo>Payment_Transaction__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transactions__c/fields/Other_Transactions__c.field-meta.xml
<CustomField>
    <fullName>Other_Transactions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Other Transactions</label>
    <referenceTo>Master_Transaction__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transactions__c/fields/Payment_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Payment_DateTime__c</fullName>
    <label>Payment DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transactions__c/fields/Payment_Received_By__c.field-meta.xml
<CustomField>
    <fullName>Payment_Received_By__c</fullName>
    <label>Payment Received By</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
                <label>Primary Insurance</label>
            </value>
            <value>
                <fullName>Secondary Insurance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AutoPatientStatementCreationHelper.cls
public with sharing class AutoPatientStatementCreationHelper {
    Set<Id> accountIds = new Set<Id>();
    Datetime startDate;
    Datetime endDate;
    public AutoPatientStatementCreationHelper(Set<Id> accountIds, Datetime startDate, Datetime endDate){
        this.accountIds = accountIds;
        this.startDate = startDate;
        this.endDate = endDate;
    }
    public Date evaluateDOS(List<Patient_Statment_GenerInterval__c> settings){
        Date todaydate = System.today();
        Integer days = Date.daysInMonth(todaydate.year(), todaydate.month());
        if(settings!=null && settings.size()>0){
            if(settings[0].No_of_Days__c != null){
                days = (Integer) settings[0].No_of_Days__c;
            }
        }
        return todaydate.addDays(-days);
    }
    public List<Payment_Transaction__c> findPrivatePayments(Date dateOfService){
        return [SELECT Id, Posted__c, Procedure__r.Name, Procedure__r.From_Date_Of_Service__c,
                Provider__r.Name, Total_Paid_Amount__c,ElixirSuite__Total_Actual_Patient_Paid_Amount__c, Insurance_Paid__c,Actual_Price__c,
                (SELECT Id, Amount_Paid__c, CreatedDate FROM Transactions__r
                 WHERE CreatedDate>= :startDate AND CreatedDate<= :endDate)
                FROM Payment_Transaction__c
                WHERE Procedure__r.Type_Of_Procedure__c='Private Payment'
                AND Procedure__r.From_Date_Of_Service__c>= :dateOfService
                AND Account__c IN :accountIds
                WITH SECURITY_ENFORCED
                ORDER BY Procedure__r.From_Date_Of_Service__c DESC];
    }
    public List<Payment_Transaction__c> findInsurancePayments(Date dateOfService){
        return [SELECT Id, Posted__c, Procedure__r.Name, Procedure__r.From_Date_Of_Service__c,
                Provider__r.Name, Total_Paid_Amount__c,ElixirSuite__Total_Actual_Patient_Paid_Amount__c, Insurance_Paid__c, Payment_Adjustments__c,Actual_Price__c,
                (SELECT Id, Amount_Paid__c, CreatedDate FROM Transactions__r
                 WHERE CreatedDate>= :startDate AND CreatedDate<= :endDate)
                FROM Payment_Transaction__c
                WHERE Procedure__r.Type_Of_Procedure__c='Insurance Payment'
                AND Posted__c=TRUE
                AND Procedure__r.From_Date_Of_Service__c>= :dateOfService
                AND Account__c IN :accountIds
                WITH SECURITY_ENFORCED
                ORDER BY Procedure__r.From_Date_Of_Service__c DESC];
    }
    public List<Transactions__c> findProcedurePaidInMonth(Date dateOfService, Set<Id> masterTransactionIds){
        return [SELECT Id, Amount_Paid__c, Master_Transaction__c, Payment_DateTime__c, Payment_Received_By__c
                FROM Transactions__c
                WHERE ( (Master_Transaction__r.Procedure__r.Type_Of_Procedure__c='Insurance Payment' 
                         AND Master_Transaction__r.Posted__c=TRUE )
                       OR Master_Transaction__r.Procedure__r.Type_Of_Procedure__c='Private Payment')
                AND Payment_DateTime__c>= :dateOfService
                AND Master_Transaction__c NOT IN :masterTransactionIds
                AND Master_Transaction__r.Account__c IN :accountIds WITH SECURITY_ENFORCED];
    }
    public List<Payment_Transaction__c> masterTransactions(Date dateOfService, Set<Id> masterTransactionIds){
        return [SELECT Id, Posted__c, Procedure__r.Name, Procedure__r.From_Date_Of_Service__c,Procedure__r.Type_Of_Procedure__c,
                Provider__r.Name, Total_Paid_Amount__c,ElixirSuite__Total_Actual_Patient_Paid_Amount__c, Insurance_Paid__c,Actual_Price__c,
                (SELECT Id, Amount_Paid__c, CreatedDate FROM Transactions__r
                 WHERE CreatedDate>= :startDate AND CreatedDate<= :endDate)
                FROM Payment_Transaction__c
                WHERE Id IN :masterTransactionIds WITH SECURITY_ENFORCED];
    }
    public PatientStatment_ctr.PrivateProcedure privateProcedureSchema(Payment_Transaction__c payment){
        PatientStatment_ctr.PrivateProcedure privateProc = new PatientStatment_ctr.PrivateProcedure();
        privateProc.procedureName = payment.Procedure__r.Name;
        privateProc.dos = payment.Procedure__r.From_Date_Of_Service__c;
        privateProc.providerName = payment.Provider__r.Name;
        privateProc.charges = payment.Actual_Price__c;
        privateProc.patientPayments = payment.ElixirSuite__Total_Actual_Patient_Paid_Amount__c;
        privateProc.amountToPay = AutoPatientStatementCreation.refactoredAmount(privateProc.charges) - 
            						AutoPatientStatementCreation.refactoredAmount(privateProc.patientPayments);
        privateProc.transactions = payment.Transactions__r;
        return privateProc;
    }
    public PatientStatment_ctr.InsuranceProcedure insuranceProcedureSchema(Payment_Transaction__c payment){
        PatientStatment_ctr.InsuranceProcedure insuranceProc = new PatientStatment_ctr.InsuranceProcedure();
        insuranceProc.procedureName = payment.Procedure__r.Name;
        insuranceProc.dos = payment.Procedure__r.From_Date_Of_Service__c;
        insuranceProc.providerName = payment.Provider__r.Name;
        insuranceProc.charges = payment.Actual_Price__c;
        insuranceProc.patientPayments = payment.ElixirSuite__Total_Actual_Patient_Paid_Amount__c;
        insuranceProc.insurancePayments = AutoPatientStatementCreation.refactoredAmount((Double) (payment.Insurance_Paid__c)) +
            								AutoPatientStatementCreation.refactoredAmount((Double) (payment.Payment_Adjustments__c));
        insuranceProc.amountToPay = AutoPatientStatementCreation.refactoredAmount(insuranceProc.charges) - 
            						AutoPatientStatementCreation.refactoredAmount(insuranceProc.insurancePayments);
        insuranceProc.transactions = payment.Transactions__r;
        return insuranceProc;
    }
    public List<Payment_Transaction__c> findProceduresRemaining(Date dateOfService, Set<Id> masterTransactionIds){
        return [SELECT Id, Posted__c, Procedure__c,Procedure__r.Name,
                Total_Paid_Amount__c,ElixirSuite__Total_Actual_Patient_Paid_Amount__c,Insurance_Paid__c,Procedure__r.Type_Of_Procedure__c,Actual_Price__c,
                Provider__r.Name,Procedure__r.From_Date_of_Service__c,
                (SELECT Id, Amount_Paid__c, CreatedDate FROM Transactions__r
                 WHERE CreatedDate>= :startDate AND CreatedDate<= :endDate)
                FROM Payment_Transaction__c
                WHERE ( (Procedure__r.Type_Of_Procedure__c='Insurance Payment'
                         AND Posted__c=TRUE )
                       OR Procedure__r.Type_Of_Procedure__c='Private Payment')
                AND Procedure__r.From_Date_Of_Service__c>= :dateOfService
                AND ElixirSuite__PatientOutstanding__c!=0
                AND Account__c IN :accountIds
                AND Id NOT IN :masterTransactionIds WITH SECURITY_ENFORCED];
    }
    public List<AggregateResult> findPrivatePaymentsAggregate(Date dateOfService){
        return [SELECT Account__c d, Sum(Actual_Price__c) c FROM Payment_Transaction__c
                WHERE Procedure__r.Type_Of_Procedure__c='Private Payment'
                AND Procedure__r.From_Date_Of_Service__c>= :dateOfService
                AND Account__c IN :accountIds 
                WITH SECURITY_ENFORCED
                GROUP BY Account__c];
    }
    public List<AggregateResult> findInsurancePaymentsAggregate(Date dateOfService){
        return [SELECT Account__c d, Sum(Actual_Price__c) c FROM Payment_Transaction__c
                WHERE Procedure__r.Type_Of_Procedure__c='Insurance Payment'
                AND Posted__c=TRUE
                AND Procedure__r.From_Date_Of_Service__c>= :dateOfService
                AND Account__c IN :accountIds 
                WITH SECURITY_ENFORCED
                GROUP BY Account__c];
    }
    public List<AggregateResult> findProcedurePaidInMonthAggregate(Date dateOfService){
        return [SELECT Master_Transaction__r.Account__c d, SUM(Amount_Paid__c) c
                FROM Transactions__c
                WHERE ( (Master_Transaction__r.Procedure__r.Type_Of_Procedure__c='Insurance Payment' 
                         AND Master_Transaction__r.Posted__c=TRUE )
                       OR Master_Transaction__r.Procedure__r.Type_Of_Procedure__c='Private Payment')
                AND Payment_DateTime__c>= :dateOfService
                AND Master_Transaction__r.Account__c IN :accountIds 
                WITH SECURITY_ENFORCED
                GROUP BY Master_Transaction__r.Account__c];
    }
}