force-app/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Records the unique account number assigned to the account.</description>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Represents the first name of the account holder.</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Actual_Price__c/Actual_Price__c.object-meta.xml
<CustomObject>
    <description>Indicates the List price for a procedure w.r.t the Provider.</description>
    <label>Actual Price</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Actual Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actual Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object contains the summary of all the transactional details linked with a patient procedure. Also it contains the rollup for patient paid amount, total refund amount, total discount applied, primary insurance paid and secondary insurance paid amount.</description>
    <label>Master Transaction</label>
    <nameField>
        <displayFormat>PAYMENT-{0000}</displayFormat>
        <label>Payment Received Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Transaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Payment_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Actual_Price__c.field-meta.xml
<CustomField>
    <fullName>Actual_Price__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Actual Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Insurance_Payments__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Payments__c</fullName>
    <label>Insurance Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AutoPatientStatementCreation_Test.cls
@isTest
public class AutoPatientStatementCreation_Test 
{
    public static testMethod void AutoPat()
    {
        Account acc = new Account();
        acc.Name = 'Test';
        acc.Account_Number__c = '1234';
        acc.First_Name__c = 'Test';
        insert acc;
        
        List<Account> lst_Acc = new List<Account>();
        lst_Acc.add(acc);
        
        String strRecordTypeId = [Select Id From RecordType Where SobjectType = 'ElixirSuite__Payment_Transaction__c' and Name = 'Payment Transaction'].Id;
        
        String strRecordTypeId2 = [Select Id From RecordType Where SobjectType = 'ElixirSuite__Payment_Transaction__c' and Name = 'Sub Transaction'].Id;
        
        Payment_Transaction__c payTrans = new Payment_Transaction__c();
        payTrans.Account__c = acc.Id;
        payTrans.Actual_Price__c = 100;
        payTrans.Insurance_Payments__c = 200;
        payTrans.RecordTypeId = strRecordTypeId;
        insert payTrans;
        
        Payment_Transaction__c payTrans2 = new Payment_Transaction__c();
        payTrans2.Account__c = acc.Id;
        payTrans2.Actual_Price__c = 100;
        payTrans2.Insurance_Payments__c = 200;
        payTrans2.RecordTypeId = strRecordTypeId2;
        insert payTrans2;
        
        test.startTest();
        AutoPatientStatementCreation autoPat = new AutoPatientStatementCreation();
        autoPat.execute(null,lst_Acc);
        DataBase.executeBatch(autoPat,200);
        test.stopTest();
        System.assert( payTrans.Actual_Price__c !=null,'');
    }
}