force-app/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Records the unique account number assigned to the account.</description>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Represents the first name of the account holder.</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Represents the last name of the account holder.</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MRN_Number_New__c.field-meta.xml
<CustomField>
    <fullName>MRN_Number_New__c</fullName>
    <description>Represents the alphanumeric medical record number associated with the account holder.</description>
    <label>MRN Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Transaction__c/Master_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object contains the details of payments collected from customer in form of advance payment via cash/credit card/cheque or any other mode of payment. This object also contains patient credits as well.</description>
    <label>Other Transactions</label>
    <nameField>
        <displayFormat>OT-{0000}</displayFormat>
        <label>Other Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Master_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/Patient_Statement__c.object-meta.xml
<CustomObject>
    <label>Patient Statement</label>
    <nameField>
        <displayFormat>BILL-{0000}</displayFormat>
        <label>Patient Bill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Statement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Statement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient Statement</relationshipLabel>
    <relationshipName>Patient_Statement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/NewBalance__c.field-meta.xml
<CustomField>
    <fullName>NewBalance__c</fullName>
    <label>NewBalance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/NewCharges__c.field-meta.xml
<CustomField>
    <fullName>NewCharges__c</fullName>
    <label>NewCharges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/PaymentsAndAdjustmnts__c.field-meta.xml
<CustomField>
    <fullName>PaymentsAndAdjustmnts__c</fullName>
    <label>PaymentsAndAdjustmnts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/PreviousBalance__c.field-meta.xml
<CustomField>
    <fullName>PreviousBalance__c</fullName>
    <label>PreviousBalance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/Statement_Date__c.field-meta.xml
<CustomField>
    <fullName>Statement_Date__c</fullName>
    <label>Statement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/Statement_from__c.field-meta.xml
<CustomField>
    <fullName>Statement_from__c</fullName>
    <label>Statement from</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/Statement_to__c.field-meta.xml
<CustomField>
    <fullName>Statement_to__c</fullName>
    <label>Statement to</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Patient_Statment_GenerInterval__c/Patient_Statment_GenerInterval__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>PatientStatmentGenerInterval</label>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object contains the summary of all the transactional details linked with a patient procedure. Also it contains the rollup for patient paid amount, total refund amount, total discount applied, primary insurance paid and secondary insurance paid amount.</description>
    <label>Master Transaction</label>
    <nameField>
        <displayFormat>PAYMENT-{0000}</displayFormat>
        <label>Payment Received Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Transaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Payment_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Master_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Master_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Transaction</label>
    <referenceTo>Master_Transaction__c</referenceTo>
    <relationshipName>Payment_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Procedure__c.field-meta.xml
<CustomField>
    <fullName>Procedure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Procedure</label>
    <referenceTo>Procedure__c</referenceTo>
    <relationshipName>Payment_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDF_Header__c/PDF_Header__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>PDF Header</label>
</CustomObject>

force-app/main/default/objects/Procedure__c/Procedure__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the template procedures in the system. These might include lab order, medications, CPT codes, Appointment procedures.</description>
    <label>Procedure Codes</label>
    <nameField>
        <label>Code Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedure Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Procedure__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Procedures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/Type_of_Procedure__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Procedure__c</fullName>
    <label>Type of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Private Payment</fullName>
            </value>
            <value>
                <fullName>Insurance Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transactions__c/Transactions__c.object-meta.xml
<CustomObject>
    <description>This object contains the details of payments, refunds, reversals, discounts, adjustments against master transaction (ElixirSuite__Payment_Transaction__c) created for a patient procedure.</description>
    <label>Transactions</label>
    <nameField>
        <displayFormat>Transaction-{0000}</displayFormat>
        <label>Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transactions__c/fields/Master_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Master_Transaction__c</fullName>
    <label>Master Transaction</label>
    <referenceTo>Payment_Transaction__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object is used to track every single visit or encounter for a patient.</description>
    <label>Care Episode</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visits__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents the relationship b/w Patient and Care Episode.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Care Episodes</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOB__c/VOB__c.object-meta.xml
<CustomObject>
    <description>This object tracks the verification of benefits/Patient Insurance details.</description>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VOB__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associated the patient with Account.</description>
    <label>Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurance</relationshipLabel>
    <relationshipName>VOB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOB__c/fields/Payer_Name__c.field-meta.xml
<CustomField>
    <fullName>Payer_Name__c</fullName>
    <description>Name of the entity responsible for reimbursing healthcare services.</description>
    <label>Payer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOB__c/recordTypes/Secondary_VOB.recordType-meta.xml
<RecordType>
    <fullName>Secondary_VOB</fullName>
    <active>true</active>
    <label>Secondary Insurance</label>
</RecordType>

force-app/main/default/objects/VOB__c/recordTypes/VOB_record_type.recordType-meta.xml
<RecordType>
    <fullName>VOB_record_type</fullName>
    <active>true</active>
    <label>Primary Insurance</label>
</RecordType>

force-app/main/default/classes/PatientStatment_ctr.cls
public with sharing class PatientStatment_ctr {
    public String PageId{get;set;}
    public Patient_Statement__c objPatSt{get;set;}
    public List<PrivateProcedure> privateProcedures{get;set;}
    public List<InsuranceProcedure> insuranceProcedures{get;set;}
    public Datetime mainDate{get;set;} 
    public String primaryInsuranceName{get;set;}
    public String secInsuranceName{get;set;}
    public Date payFullBy{get;set;}
    public static PDF_Header__c pdfData {get; set;}
    public PatientStatment_ctr(ApexPages.StandardController controller) {
        privateProcedures = new List<PrivateProcedure>();
        insuranceProcedures = new List<InsuranceProcedure>();
        pdfData= StatementAsExportHelper.getPDFData(); 
        PageId=ApexPages.currentPage().getParameters().get('Id');
        objPatSt = new Patient_Statement__c();
        
        String patientAccountId = [SELECT Id,Account__c FROM Patient_Statement__c WHERE Id= : PageId].Account__c;
        objPatSt = [Select Id,Account_Number__c,NewBalance__c,NewCharges__c,Account__c,Account__r.Name,CreatedDate,Account__r.First_Name__c,
                    Statement_from__c,Account__r.MRN_Number_New__c,Account__r.Last_Name__c,Account__r.AccountNumber,
                    PreviousBalance__c,PaymentsAndAdjustmnts__c,Statement_Date__c,Statement_to__c
                    FROM Patient_Statement__c WHERE Id= :PageId WITH SECURITY_ENFORCED];
        Datetime dateField = objPatSt.CreatedDate;
        Integer numberOfDays = Date.daysInMonth(dateField.year(), dateField.month());
        Date lastDayOfMonth = Date.newInstance(dateField.year(), dateField.month(), numberOfDays);
        payFullBy = lastDayOfMonth;
        mainDate = objPatSt.CreatedDate;
        Account acctDetails = [SELECT Id,Name,AccountNumber,MRN_Number_New__c from Account WHERE Id= :patientAccountId WITH SECURITY_ENFORCED];
        Datetime startDate = objPatSt.Statement_from__c!=null?objPatSt.Statement_from__c:System.now();
        Datetime endDate = objPatSt.Statement_to__c!=null?objPatSt.Statement_to__c:System.now();
        
		        
        
        //ROHIT - START
        Set<Id> accountIds = new Set<Id>{patientAccountId};
        Set<Id> masterTransactionIds = new Set<Id>();
        List<Patient_Statment_GenerInterval__c> settings = Patient_Statment_GenerInterval__c.getAll().values();
        AutoPatientStatementCreationHelper helperObj = new AutoPatientStatementCreationHelper(accountIds, startDate, endDate);
        Date dateOfService = helperObj.evaluateDOS(settings);     
        
        List<Payment_Transaction__c> privatePayments = new List<Payment_Transaction__c>();
        privatePayments = helperObj.findPrivatePayments(dateOfService);
        for(Payment_Transaction__c privatePayment :privatePayments){
            privateProcedures.add(helperObj.privateProcedureSchema(privatePayment));
            masterTransactionIds.add(privatePayment.Id);
        }
        
        List<Payment_Transaction__c> insurancePayments = new List<Payment_Transaction__c>();
        insurancePayments = helperObj.findInsurancePayments(dateOfService);
          for(Payment_Transaction__c insurancePayment :insurancePayments){
            insuranceProcedures.add(helperObj.insuranceProcedureSchema(insurancePayment));
            masterTransactionIds.add(insurancePayment.Id);
        }
        
        List<Transactions__c> proceduresPaidInMonth = new List<Transactions__c>();
        proceduresPaidInMonth = helperObj.findProcedurePaidInMonth(dateOfService, masterTransactionIds);
        Set<Id> masterTransactionFromTransactions = new Set<Id>();
        for(Transactions__c trans :proceduresPaidInMonth){
            masterTransactionFromTransactions.add(trans.Master_Transaction__c);
        }
        List<Payment_Transaction__c> transactions = helperObj.masterTransactions(dateOfService, masterTransactionFromTransactions);
        for(Payment_Transaction__c payment :transactions){
            if(payment.Procedure__r.Type_Of_Procedure__c.equalsIgnoreCase('Private Payment')){
                privateProcedures.add(helperObj.privateProcedureSchema(payment));
                 masterTransactionIds.add(payment.Id);
            }
            else{//Insurance Payment
                insuranceProcedures.add(helperObj.insuranceProcedureSchema(payment));
                masterTransactionIds.add(payment.Id);
            }
        }
        
        List<Payment_Transaction__c> proceduresRemaining = helperObj.findProceduresRemaining(dateOfService, masterTransactionIds);
        for(Payment_Transaction__c payment :proceduresRemaining){
            if(payment.Procedure__r.Type_Of_Procedure__c.equalsIgnoreCase('Private Payment')){
                privateProcedures.add(helperObj.privateProcedureSchema(payment));
                 masterTransactionIds.add(payment.Id);
            }
            else{//Insurance Payment
                insuranceProcedures.add(helperObj.insuranceProcedureSchema(payment));
                masterTransactionIds.add(payment.Id);
            }
        }        
         //ROHIT - END
        List<VOB__c> primaryInsurances = [SELECT Id, Payer_Name__c, RecordType.DeveloperName
                        FROM VOB__c 
                        WHERE Account__c= :patientAccountId AND RecordType.DeveloperName='VOB_record_type'
                        WITH SECURITY_ENFORCED
                        ORDER BY CreatedDate DESC LIMIT 1];
        if(primaryInsurances!=null && primaryInsurances.size()>0){
            primaryInsuranceName = primaryInsurances[0].Payer_Name__c;
        }
        List<VOB__c> secInsurances = [SELECT Id, Payer_Name__c, RecordType.DeveloperName
                        FROM VOB__c 
                        WHERE Account__c= :patientAccountId AND RecordType.DeveloperName='Secondary_VOB'
                        WITH SECURITY_ENFORCED
                        ORDER BY CreatedDate DESC LIMIT 1];
        if(secInsurances!=null && secInsurances.size()>0){
            secInsuranceName = secInsurances[0].Payer_Name__c;
        }
    }
    public class PrivateProcedure{
        @AuraEnabled public String procedureName {get;set;}
        @AuraEnabled public Datetime dos {get;set;}
        @AuraEnabled public String providerName {get;set;}
        @AuraEnabled public double charges {get;set;}
        @AuraEnabled public double patientPayments {get;set;}
        @AuraEnabled public double discount {get;set;}
        @AuraEnabled public double amountToPay {get;set;}
        @AuraEnabled public List<Transactions__c> transactions {get;set;}
    }
    public class InsuranceProcedure{
        @AuraEnabled public String procedureName {get;set;}
        @AuraEnabled public Datetime dos {get;set;}
        @AuraEnabled public String providerName {get;set;}
        @AuraEnabled public double charges {get;set;}
        @AuraEnabled public double patientPayments {get;set;}
		@AuraEnabled public double insurancePayments {get;set;}
        @AuraEnabled public double amountToPay {get;set;}
        @AuraEnabled public List<Transactions__c> transactions {get;set;}
    }
}