force-app/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Records the unique account number assigned to the account.</description>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>Indicates the current active status of the account.</description>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Captures the birth sex or gender identity of the account holder.</description>
    <label>Birth Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Male</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>UNK</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Patient_s_Birth_Date__c.field-meta.xml
<CustomField>
    <fullName>Patient_s_Birth_Date__c</fullName>
    <description>Denotes the date of birth of the patient.</description>
    <label>Patient DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Procedure__c/Procedure__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the template procedures in the system. These might include lab order, medications, CPT codes, Appointment procedures.</description>
    <label>Procedure Codes</label>
    <nameField>
        <label>Code Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedure Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Procedure__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Procedures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/CPT_HCPCS_Code__c.field-meta.xml
<CustomField>
    <fullName>CPT_HCPCS_Code__c</fullName>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/From_Date__c.field-meta.xml
<CustomField>
    <fullName>From_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/To_Date__c.field-meta.xml
<CustomField>
    <fullName>To_Date__c</fullName>
    <label>Termination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProcedureAlertParameters__c/ProcedureAlertParameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Procedure Alert Parameters</label>
</CustomObject>

force-app/main/default/objects/ProcedureAlertParameters__c/fields/No_of_hours__c.field-meta.xml
<CustomField>
    <fullName>No_of_hours__c</fullName>
    <label>No of hours(Static procedure)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SendNotificationsForOpnProc_scheTest.cls
@isTest
public class SendNotificationsForOpnProc_scheTest {
	
    public static testMethod void notifyTestMethod()
    {
        ProcedureAlertParameters__c proAlrt = new ProcedureAlertParameters__c();
        proAlrt.Active__c = True;
        proAlrt.No_of_hours__c = 1;
        insert proAlrt;
        
		Account pat = new Account();
		pat.Name = 'test';
		pat.Gender__c = 'Female';
		pat.Patient_s_Birth_Date__c = system.today();
		pat.Account_Number__c = '123456';
		insert pat;
        
        Procedure__c pro1 = new Procedure__c();
		pro1.Name = 'test';
		pro1.From_Date__c = system.today()-2;
		pro1.To_Date__c = system.today();
		pro1.CPT_HCPCS_Code__c = '99203';
		pro1.Account__c = pat.Id;
		pro1.Name = 'test';
		insert pro1;
        
		Test.startTest();
        String CRON_EXP = '0 0 0 3 9 ? 2023';
        String jobId = System.schedule('SendNotificationsForOpnProc_schedule', CRON_EXP, new SendNotificationsForOpnProc_schedule());
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId]; 
        System.assertEquals(1, 1, ' ');
        Test.stopTest();        
    }
}