force-app/main/default/objects/Account/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountId</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (AccountId)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Signature_Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Signature_Attachment_Id__c</fullName>
    <description>Stores the unique id of the signature attachment associated with the account.</description>
    <label>Signature Attachment Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>TO BE DEPRECATED:
Form was used to store all the forms related to the patient.</description>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/Form_Value__c.object-meta.xml
<CustomObject>
    <description>Form value stores all the miscellaneous features of the saved forms like Approvals, Care Episodes and Status. All the problems, diagnoses, medications and allergies selected on the forms are also linked with this object as the record in this object is also responsible for giving one identity to the forms saved in multiple objects.</description>
    <label>Form Value</label>
    <nameField>
        <label>Form Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Value__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Form Values</relationshipLabel>
    <relationshipName>Form_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Approval_Level__c.field-meta.xml
<CustomField>
    <fullName>Approval_Level__c</fullName>
    <label>Approval Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Approved_Signature__c.field-meta.xml
<CustomField>
    <fullName>Approved_Signature__c</fullName>
    <label>Approved Signature</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Date_Of_Approval__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Approval__c</fullName>
    <label>Date Of Approval</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Form_Id__c.field-meta.xml
<CustomField>
    <fullName>Form_Id__c</fullName>
    <label>Form Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Form_Name__c.field-meta.xml
<CustomField>
    <fullName>Form_Name__c</fullName>
    <label>Form Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Is_Approver__c.field-meta.xml
<CustomField>
    <fullName>Is_Approver__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Approver</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Is_External_Signature__c.field-meta.xml
<CustomField>
    <fullName>Is_External_Signature__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is External Signature</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Is_Old__c.field-meta.xml
<CustomField>
    <fullName>Is_Old__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Old</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Signed_Patient__c.field-meta.xml
<CustomField>
    <fullName>Signed_Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Signed Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Form Values (Signed Patient)</relationshipLabel>
    <relationshipName>Form_Values1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Form_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/Object_1_css__c.object-meta.xml
<CustomObject>
    <description>Form css stores all the attributes that defines how a form will look like when you view a form. All configuration records are saved in this object from Form Configuration screen.</description>
    <label>Form css</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Object 1 css Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form css</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_1_css__c/fields/Approv__c.field-meta.xml
<CustomField>
    <fullName>Approv__c</fullName>
    <label>Approver</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Approval_Level__c.field-meta.xml
<CustomField>
    <fullName>Approval_Level__c</fullName>
    <label>Approval Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Approval_Members__c.field-meta.xml
<CustomField>
    <fullName>Approval_Members__c</fullName>
    <label>Approval Members</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Object_1_css__c.field-meta.xml
<CustomField>
    <fullName>Object_1_css__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Object 1 css</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Section_Number__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Object_1_css__c</referenceTo>
    <relationshipName>Object_1_css</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Object_2__c/Object_2__c.object-meta.xml
<CustomObject>
    <label>Object 2</label>
    <nameField>
        <label>Object 2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object 2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_2__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Object 2</relationshipLabel>
    <relationshipName>Object_2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Object_2__c/fields/Form_unique_id__c.field-meta.xml
<CustomField>
    <fullName>Form_unique_id__c</fullName>
    <label>Form unique id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Signature_Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Signature_Attachment_Id__c</fullName>
    <label>Signature Attachment Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrderApproval.cls
public with sharing class OrderApproval {
    @AuraEnabled
    public static OrderApprovalData.currentUserInfo fetchApprovalLevels(String typeOfApproval, String orderId){ // formId is formUniqueId
        try {
            typeOfApproval = String.escapeSingleQuotes(typeOfApproval);
            String approvalRecordTypeId = Schema.SObjectType.ElixirSuite__Master_Object__c.getRecordTypeInfosByDeveloperName().get('Approval_Configuration').getRecordTypeId();

            // This is configuration data about approvals(level of approvals)
            List<ElixirSuite__Master_Object__c> defaultApprovalLevels = new List<ElixirSuite__Master_Object__c>();
            SObjectAccessDecision decisionNonApproved = Security.stripInaccessible(
                AccessType.READABLE,
                [
                    //     SELECT Id, Approval_Level__c, Approv__c, Approval_Members__c, ElixirSuite__Approver_Custom_Label__c
                    //       FROM Object_1_css__c
                    //      WHERE Form__c = :recordTypeName
                    //        AND Approval_Level__c!=NULL
                    //   ORDER BY Approval_Level__c
                    SELECT Id, ElixirSuite__Approval_Level__c, ElixirSuite__Approver__c, ElixirSuite__Approval_Members__c, ElixirSuite__Approver_Custom_Label__c, ElixirSuite__Approval_Level_For__c
                      FROM ElixirSuite__Master_Object__c
                     WHERE ElixirSuite__Approval_Level__c != null
                       AND ElixirSuite__Approval_Level_For__c = :typeOfApproval
                       AND RecordTypeId = :approvalRecordTypeId
                  ORDER BY ElixirSuite__Approval_Level__c
                ]
            ); //TODO: remove hard coded Ids. They are only for testing purpose

            defaultApprovalLevels = decisionNonApproved.getRecords();

            // in new no approved values
            // List<ElixirSuite__Prescription_Order__c> approvedValues = new List<ElixirSuite__Prescription_Order__c>();
            // SObjectAccessDecision decisionApproved = Security.stripInaccessible(AccessType.READABLE,
            // // [SELECT Id, Account__c, Is_Approver__c, Date_Of_Approval__c,Is_External_Signature__c,
            // // User__r.Name, User__r.UserRole.Name, Approval_Level__c, Comment__c, Is_old__c, Form_Name__c, Approved_Signature__c,
            // // Signed_Patient__r.Name FROM Form_Value__c
            // // WHERE Is_Approver__c=true AND Form_Id__c= :formId AND Is_old__c != true
            // // ORDER BY Approval_Level__c]
            // [SELECT Id, Name FROM ElixirSuite__Prescription_Order__c WHERE Name='ObiviouslyFakeName12']
            // );
            // approvedValues = decisionApproved.getRecords();
            // system.debug('approvedValues'+approvedValues);


            // FormApprovalData.currentUserInfo userInfo = new FormApprovalData.currentUserInfo();
            // userInfo.setUserId();
            // userInfo.setProfileId(); 
            // userInfo.setRoleId();
            // userInfo.setDefaultLevels(defaultApprovalLevels);
            // userInfo.setApprovedValues(approvedValues);

            List<OrderSignatureSave.SignAndAprroveData> approvedValues = new List<OrderSignatureSave.SignAndAprroveData>();
            switch on typeOfApproval {
                when 'Prescription Order' {
                    if (String.isNotEmpty(orderId)) {
                        approvedValues = fetchPrescriptionApprovedValues(orderId);
                    }
                }

                when 'Lab Order' {
                    if (String.isNotEmpty(orderId)) {
                        approvedValues = fetchLabOrderApprovedValues(orderId);
                    }
                }
            }

            OrderApprovalData.currentUserInfo userInfo = new OrderApprovalData.currentUserInfo();
            userInfo.setUserId();
            userInfo.setProfileId(); 
            userInfo.setRoleId();
            userInfo.setDefaultLevels(defaultApprovalLevels);
            userInfo.setApprovedValues(approvedValues);

            system.debug('userInfo'+userInfo);
            
            return userInfo;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

    }

    @AuraEnabled
    public static List<OrderSignatureSave.SignAndAprroveData> fetchPrescriptionApprovedValues(String parentPrescriptionId){
        try {
            parentPrescriptionId = String.escapeSingleQuotes(parentPrescriptionId);
            List<ElixirSuite__Prescription_Order__c> parentPrescription = [
                SELECT Id,
                       ElixirSuite__Date_Of_Approval_1__c, ElixirSuite__Comment_1__c, ElixirSuite__User_1__c, ElixirSuite__User_1__r.Signature_Attachment_Id__c, ElixirSuite__User_1__r.Name, ElixirSuite__User_1__r.userrole.name,
                       ElixirSuite__Date_Of_Approval_2__c, ElixirSuite__Comment_2__c, ElixirSuite__User_2__c, ElixirSuite__User_2__r.Signature_Attachment_Id__c, ElixirSuite__User_2__r.Name, ElixirSuite__User_2__r.userrole.name,
                       ElixirSuite__Date_Of_Approval_3__c, ElixirSuite__Comment_3__c, ElixirSuite__User_3__c, ElixirSuite__User_3__r.Signature_Attachment_Id__c, ElixirSuite__User_3__r.Name, ElixirSuite__User_3__r.userrole.name
                  FROM ElixirSuite__Prescription_Order__c 
                 WHERE Id = :parentPrescriptionId WITH SECURITY_ENFORCED];

            if (parentPrescription != null && parentPrescription.size() > 0) {
                ElixirSuite__Prescription_Order__c thisParentPrescription = parentPrescription[0];

                // query master object for custom label
                String approvalRecordTypeId = Schema.SObjectType.ElixirSuite__Master_Object__c.getRecordTypeInfosByDeveloperName().get('Approval_Configuration').getRecordTypeId();
                List<ElixirSuite__Master_Object__c> prescriptionApprovalConfiguration = [
                    SELECT Id, ElixirSuite__Approval_Level__c, ElixirSuite__Approver__c, ElixirSuite__Approval_Members__c, ElixirSuite__Approver_Custom_Label__c, ElixirSuite__Approval_Level_For__c
                      FROM ElixirSuite__Master_Object__c
                     WHERE ElixirSuite__Approval_Level__c != null
                       AND ElixirSuite__Approval_Level_For__c = 'Prescription Order'
                       AND RecordTypeId = :approvalRecordTypeId WITH SECURITY_ENFORCED
                ORDER BY ElixirSuite__Approval_Level__c];

                List<OrderSignatureSave.SignAndAprroveData> allApprovedValues = new List<OrderSignatureSave.SignAndAprroveData>();
                // Approval level one
                if (thisParentPrescription.ElixirSuite__Date_Of_Approval_1__c != null && thisParentPrescription.ElixirSuite__User_1__c != null) {
                    OrderSignatureSave.SignAndAprroveData ApprovalLevelOne = new OrderSignatureSave.SignAndAprroveData();
                    ApprovalLevelOne.approvalLevel = 1;
                    ApprovalLevelOne.comments = thisParentPrescription.ElixirSuite__Comment_1__c;
                    // As prescriptionApprovalConfiguration will be sorted by approval level, we can assume 1st record crossponds to first approval level
                    ApprovalLevelOne.customLabel = prescriptionApprovalConfiguration[0].ElixirSuite__Approver_Custom_Label__c;
                    ApprovalLevelOne.dateOfApproval = thisParentPrescription.ElixirSuite__Date_Of_Approval_1__c;
                    
                    String signature = thisParentPrescription.ElixirSuite__User_1__r.Signature_Attachment_Id__c;
                    if (String.isNotEmpty(signature)) {
                        List<ContentDocument> images1 = [SELECT Id FROM ContentDocument WHERE Id= :signature];
                        if (images1 != null && images1.size() > 0) {
                            ApprovalLevelOne.signatureContentDocumentId = images1[0].Id;
                        }
                    }

                    ApprovalLevelOne.userId = thisParentPrescription.ElixirSuite__User_1__c;
                    ApprovalLevelOne.userName = thisParentPrescription.ElixirSuite__User_1__r.Name;
                    ApprovalLevelOne.userRole = thisParentPrescription.ElixirSuite__User_1__r.userrole.name;

                    allApprovedValues.add(ApprovalLevelOne);
                }

                // Approval level two
                if (thisParentPrescription.ElixirSuite__Date_Of_Approval_2__c != null && thisParentPrescription.ElixirSuite__User_2__c != null) {
                    OrderSignatureSave.SignAndAprroveData ApprovalLevelTwo = new OrderSignatureSave.SignAndAprroveData();
                    ApprovalLevelTwo.approvalLevel = 2;
                    ApprovalLevelTwo.comments = thisParentPrescription.ElixirSuite__Comment_2__c;
                    // As prescriptionApprovalConfiguration will be sorted by approval level, we can assume 1st record crossponds to first approval level
                    ApprovalLevelTwo.customLabel = prescriptionApprovalConfiguration[1].ElixirSuite__Approver_Custom_Label__c;
                    ApprovalLevelTwo.dateOfApproval = thisParentPrescription.ElixirSuite__Date_Of_Approval_2__c;
                    
                    String signature = thisParentPrescription.ElixirSuite__User_2__r.Signature_Attachment_Id__c;
                    if (String.isNotEmpty(signature)) {
                        List<ContentDocument> images2 = [SELECT Id FROM ContentDocument WHERE Id= :signature];
                        if (images2 != null && images2.size() > 0) {
                            ApprovalLevelTwo.signatureContentDocumentId = images2[0].Id;
                        }
                    }

                    ApprovalLevelTwo.userId = thisParentPrescription.ElixirSuite__User_2__c;
                    ApprovalLevelTwo.userName = thisParentPrescription.ElixirSuite__User_2__r.Name;
                    ApprovalLevelTwo.userRole = thisParentPrescription.ElixirSuite__User_2__r.userrole.name;

                    allApprovedValues.add(ApprovalLevelTwo);
                }

                // Approval level three
                if (thisParentPrescription.ElixirSuite__Date_Of_Approval_3__c != null && thisParentPrescription.ElixirSuite__User_3__c != null) {
                    OrderSignatureSave.SignAndAprroveData ApprovalLevelThree = new OrderSignatureSave.SignAndAprroveData();
                    ApprovalLevelThree.approvalLevel = 3;
                    ApprovalLevelThree.comments = thisParentPrescription.ElixirSuite__Comment_3__c;
                    // As prescriptionApprovalConfiguration will be sorted by approval level, we can assume 1st record crossponds to first approval level
                    ApprovalLevelThree.customLabel = prescriptionApprovalConfiguration[2].ElixirSuite__Approver_Custom_Label__c;
                    ApprovalLevelThree.dateOfApproval = thisParentPrescription.ElixirSuite__Date_Of_Approval_3__c;
                    
                    String signature = thisParentPrescription.ElixirSuite__User_3__r.Signature_Attachment_Id__c;
                    if (String.isNotEmpty(signature)) {
                        List<ContentDocument> images3 = [SELECT Id FROM ContentDocument WHERE Id= :signature];
                        if (images3 != null && images3.size() > 0) {
                            ApprovalLevelThree.signatureContentDocumentId = images3[0].Id;
                        }
                    }

                    ApprovalLevelThree.userId = thisParentPrescription.ElixirSuite__User_3__c;
                    ApprovalLevelThree.userName = thisParentPrescription.ElixirSuite__User_3__r.Name;
                    ApprovalLevelThree.userRole = thisParentPrescription.ElixirSuite__User_3__r.userrole.name;

                    allApprovedValues.add(ApprovalLevelThree);
                }

                return allApprovedValues;
            }
            else {
                throw new AuraHandledException('No parent prescription found with given Id');
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<OrderSignatureSave.SignAndAprroveData> fetchLabOrderApprovedValues(String labOrderId){
        try {
            labOrderId = String.escapeSingleQuotes(labOrderId);
            List<ElixirSuite__UA_Sample_Details__c> labOrder = [
                SELECT Id,
                       ElixirSuite__Date_Of_Approval_1__c, ElixirSuite__Comment_1__c, ElixirSuite__User_1__c, ElixirSuite__User_1__r.Signature_Attachment_Id__c, ElixirSuite__User_1__r.Name, ElixirSuite__User_1__r.userrole.name,
                       ElixirSuite__Date_Of_Approval_2__c, ElixirSuite__Comment_2__c, ElixirSuite__User_2__c, ElixirSuite__User_2__r.Signature_Attachment_Id__c, ElixirSuite__User_2__r.Name, ElixirSuite__User_2__r.userrole.name,
                       ElixirSuite__Date_Of_Approval_3__c, ElixirSuite__Comment_3__c, ElixirSuite__User_3__c, ElixirSuite__User_3__r.Signature_Attachment_Id__c, ElixirSuite__User_3__r.Name, ElixirSuite__User_3__r.userrole.name
                  FROM ElixirSuite__UA_Sample_Details__c 
                 WHERE Id = :labOrderId WITH SECURITY_ENFORCED];

            if (labOrder != null && labOrder.size() > 0) {
                ElixirSuite__UA_Sample_Details__c thisLabOrder = labOrder[0];

                // query master object for custom label
                String approvalRecordTypeId = Schema.SObjectType.ElixirSuite__Master_Object__c.getRecordTypeInfosByDeveloperName().get('Approval_Configuration').getRecordTypeId();
                List<ElixirSuite__Master_Object__c> labOrderApprovalConfiguration = [
                    SELECT Id, ElixirSuite__Approval_Level__c, ElixirSuite__Approver__c, ElixirSuite__Approval_Members__c, ElixirSuite__Approver_Custom_Label__c, ElixirSuite__Approval_Level_For__c
                      FROM ElixirSuite__Master_Object__c
                     WHERE ElixirSuite__Approval_Level__c != null
                       AND ElixirSuite__Approval_Level_For__c = 'Lab Order'
                       AND RecordTypeId = :approvalRecordTypeId WITH SECURITY_ENFORCED
                ORDER BY ElixirSuite__Approval_Level__c];

                List<OrderSignatureSave.SignAndAprroveData> allApprovedValues = new List<OrderSignatureSave.SignAndAprroveData>();
                // Approval level one
                if (thisLabOrder.ElixirSuite__Date_Of_Approval_1__c != null && thisLabOrder.ElixirSuite__User_1__c != null) {
                    OrderSignatureSave.SignAndAprroveData ApprovalLevelOne = new OrderSignatureSave.SignAndAprroveData();
                    ApprovalLevelOne.approvalLevel = 1;
                    ApprovalLevelOne.comments = thisLabOrder.ElixirSuite__Comment_1__c;
                    // As labOrderApprovalConfiguration will be sorted by approval level, we can assume 1st record crossponds to first approval level
                    ApprovalLevelOne.customLabel = labOrderApprovalConfiguration[0].ElixirSuite__Approver_Custom_Label__c;
                    ApprovalLevelOne.dateOfApproval = thisLabOrder.ElixirSuite__Date_Of_Approval_1__c;
                    
                    String signature = thisLabOrder.ElixirSuite__User_1__r.Signature_Attachment_Id__c;
                    if (String.isNotEmpty(signature)) {
                        List<ContentDocument> images1 = [SELECT Id FROM ContentDocument WHERE Id= :signature];
                        if (images1 != null && images1.size() > 0) {
                            ApprovalLevelOne.signatureContentDocumentId = images1[0].Id;
                        }
                    }

                    ApprovalLevelOne.userId = thisLabOrder.ElixirSuite__User_1__c;
                    ApprovalLevelOne.userName = thisLabOrder.ElixirSuite__User_1__r.Name;
                    ApprovalLevelOne.userRole = thisLabOrder.ElixirSuite__User_1__r.userrole.name;

                    allApprovedValues.add(ApprovalLevelOne);
                }

                // Approval level two
                if (thisLabOrder.ElixirSuite__Date_Of_Approval_2__c != null && thisLabOrder.ElixirSuite__User_2__c != null) {
                    OrderSignatureSave.SignAndAprroveData ApprovalLevelTwo = new OrderSignatureSave.SignAndAprroveData();
                    ApprovalLevelTwo.approvalLevel = 2;
                    ApprovalLevelTwo.comments = thisLabOrder.ElixirSuite__Comment_2__c;
                    // As labOrderApprovalConfiguration will be sorted by approval level, we can assume 1st record crossponds to first approval level
                    ApprovalLevelTwo.customLabel = labOrderApprovalConfiguration[1].ElixirSuite__Approver_Custom_Label__c;
                    ApprovalLevelTwo.dateOfApproval = thisLabOrder.ElixirSuite__Date_Of_Approval_2__c;
                    
                    String signature = thisLabOrder.ElixirSuite__User_2__r.Signature_Attachment_Id__c;
                    if (String.isNotEmpty(signature)) {
                        List<ContentDocument> images2 = [SELECT Id FROM ContentDocument WHERE Id= :signature];
                        if (images2 != null && images2.size() > 0) {
                            ApprovalLevelTwo.signatureContentDocumentId = images2[0].Id;
                        }
                    }

                    ApprovalLevelTwo.userId = thisLabOrder.ElixirSuite__User_2__c;
                    ApprovalLevelTwo.userName = thisLabOrder.ElixirSuite__User_2__r.Name;
                    ApprovalLevelTwo.userRole = thisLabOrder.ElixirSuite__User_2__r.userrole.name;

                    allApprovedValues.add(ApprovalLevelTwo);
                }

                // Approval level three
                if (thisLabOrder.ElixirSuite__Date_Of_Approval_3__c != null && thisLabOrder.ElixirSuite__User_3__c != null) {
                    OrderSignatureSave.SignAndAprroveData ApprovalLevelThree = new OrderSignatureSave.SignAndAprroveData();
                    ApprovalLevelThree.approvalLevel = 3;
                    ApprovalLevelThree.comments = thisLabOrder.ElixirSuite__Comment_3__c;
                    // As labOrderApprovalConfiguration will be sorted by approval level, we can assume 1st record crossponds to first approval level
                    ApprovalLevelThree.customLabel = labOrderApprovalConfiguration[2].ElixirSuite__Approver_Custom_Label__c;
                    ApprovalLevelThree.dateOfApproval = thisLabOrder.ElixirSuite__Date_Of_Approval_3__c;
                    
                    String signature = thisLabOrder.ElixirSuite__User_3__r.Signature_Attachment_Id__c;
                    if (String.isNotEmpty(signature)) {
                        List<ContentDocument> images3 = [SELECT Id FROM ContentDocument WHERE Id= :signature WITH SECURITY_ENFORCED];
                        if (images3 != null && images3.size() > 0) {
                            ApprovalLevelThree.signatureContentDocumentId = images3[0].Id;
                        }
                    }

                    ApprovalLevelThree.userId = thisLabOrder.ElixirSuite__User_3__c;
                    ApprovalLevelThree.userName = thisLabOrder.ElixirSuite__User_3__r.Name;
                    ApprovalLevelThree.userRole = thisLabOrder.ElixirSuite__User_3__r.userrole.name;

                    allApprovedValues.add(ApprovalLevelThree);
                }

                return allApprovedValues;
            }
            else {
                throw new AuraHandledException('No lab order found with given Id');
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


        @AuraEnabled
    public static FormApprovalData.currentUserInfo fetchApprovalLevelsOnCreate(String recordTypeName){
        try {
            system.debug('Inside fetchApprovalLevelsOnCreate');
            List<Object_1_css__c> defaultApprovalLevels = new List<Object_1_css__c>();
            SObjectAccessDecision decisionNonApproved = Security.stripInaccessible(AccessType.READABLE,
            [SELECT Id, Approval_Level__c, Approv__c, Approval_Members__c, ElixirSuite__Approver_Custom_Label__c FROM 
                            Object_1_css__c WHERE Form__c= :recordTypeName AND Approval_Level__c!=NULL
                            ORDER BY Approval_Level__c]);
            defaultApprovalLevels = decisionNonApproved.getRecords();
            List<Form_Value__c> approvedValues = new List<Form_Value__c>();
            
            FormApprovalData.currentUserInfo userInfo = new FormApprovalData.currentUserInfo();
            userInfo.setUserId();
            userInfo.setProfileId();
            userInfo.setRoleId();
            userInfo.setDefaultLevels(defaultApprovalLevels);
            userInfo.setApprovedValues(approvedValues);
            system.debug('userInfo'+userInfo);
            return userInfo;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


     //To display insert signature img for portal users - Srihari
     @AuraEnabled
     public static String getNotesFlag(String accId,String formId){
         String status='';
         string query = 'select id,AccountId__c,Is_Patient_Portal_Form__c from Object_2__c where AccountId__c =:accId AND Form_unique_id__c=:formId';
         
         List<sObject> portalStatus = Database.query(query);
         
         for(sObject obj :portalStatus){
             status=String.valueOf(obj.get('Is_Patient_Portal_Form__c'));
         }
         
         return status;
     }
}