force-app/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Records the unique account number assigned to the account.</description>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Captures the birth sex or gender identity of the account holder.</description>
    <label>Birth Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Male</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>UNK</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Actual_Price__c/Actual_Price__c.object-meta.xml
<CustomObject>
    <description>Indicates the List price for a procedure w.r.t the Provider.</description>
    <label>Actual Price</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Actual Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actual Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Statement__c/Patient_Statement__c.object-meta.xml
<CustomObject>
    <label>Patient Statement</label>
    <nameField>
        <displayFormat>BILL-{0000}</displayFormat>
        <label>Patient Bill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Statement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Statement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient Statement</relationshipLabel>
    <relationshipName>Patient_Statement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/NewBalance__c.field-meta.xml
<CustomField>
    <fullName>NewBalance__c</fullName>
    <label>NewBalance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/NewCharges__c.field-meta.xml
<CustomField>
    <fullName>NewCharges__c</fullName>
    <label>NewCharges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/Patient_Code__c.field-meta.xml
<CustomField>
    <fullName>Patient_Code__c</fullName>
    <label>Patient Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/PaymentsAdjustments_Received__c.field-meta.xml
<CustomField>
    <fullName>PaymentsAdjustments_Received__c</fullName>
    <label>Payments/Adjustments Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/PaymentsAndAdjustmnts__c.field-meta.xml
<CustomField>
    <fullName>PaymentsAndAdjustmnts__c</fullName>
    <label>PaymentsAndAdjustmnts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/PaymntTransIds__c.field-meta.xml
<CustomField>
    <fullName>PaymntTransIds__c</fullName>
    <label>PaymntTransIds</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/PreviousBalance__c.field-meta.xml
<CustomField>
    <fullName>PreviousBalance__c</fullName>
    <label>PreviousBalance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/Statement_Date__c.field-meta.xml
<CustomField>
    <fullName>Statement_Date__c</fullName>
    <label>Statement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object contains the summary of all the transactional details linked with a patient procedure. Also it contains the rollup for patient paid amount, total refund amount, total discount applied, primary insurance paid and secondary insurance paid amount.</description>
    <label>Master Transaction</label>
    <nameField>
        <displayFormat>PAYMENT-{0000}</displayFormat>
        <label>Payment Received Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Transaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Payment_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Actual_Price__c.field-meta.xml
<CustomField>
    <fullName>Actual_Price__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Actual Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Cpt_Codes__c.field-meta.xml
<CustomField>
    <fullName>Cpt_Codes__c</fullName>
    <label>CPT Codes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Insurance_Payments__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Payments__c</fullName>
    <label>Insurance Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Patient_Payments__c.field-meta.xml
<CustomField>
    <fullName>Patient_Payments__c</fullName>
    <label>Patient Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Payment_Adjustments__c.field-meta.xml
<CustomField>
    <fullName>Payment_Adjustments__c</fullName>
    <label>Payment Adjustments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transactions__c/Transactions__c.object-meta.xml
<CustomObject>
    <description>This object contains the details of payments, refunds, reversals, discounts, adjustments against master transaction (ElixirSuite__Payment_Transaction__c) created for a patient procedure.</description>
    <label>Transactions</label>
    <nameField>
        <displayFormat>Transaction-{0000}</displayFormat>
        <label>Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PatientStatment_ctr_Test.cls
@isTest
public class PatientStatment_ctr_Test 
{
    public static testMethod void testPatient()
    {
        Account pat = new Account();
        pat.Name = 'test';
        pat.Phone = '1234567890';
        pat.BillingStreet = 'test';
        pat.BillingCity = 'test';
        pat.BillingCountry = 'test';
        pat.BillingState = 'test';
        pat.BillingPostalCode = '1234' ;
        pat.Gender__c = 'Female';
        pat.AccountNumber = '123456';
        insert pat;
        
        Patient_Statement__c patSta = new Patient_Statement__c();
        patSta.Patient_Code__c = '1234';
        patSta.Statement_Date__c = System.today();
        patSta.PaymentsAdjustments_Received__c = 1000;
        patSta.Account_Number__c = '1234';
        insert patSta;
        
        Payment_Transaction__c payTran = new Payment_Transaction__c();
        payTran.Actual_Price__c = 500;
        payTran.Cpt_Codes__c = 'CPT100';
        payTran.Insurance_Payments__c = 200;
        
        payTran.Account__c = pat.Id;
        payTran.Patient_Payments__c = 300;
        payTran.Payment_Adjustments__c = 400;
        insert payTran;
        
        Patient_Statement__c patStaTwo = new Patient_Statement__c();
        patStaTwo.Patient_Code__c = '1234';
        patStaTwo.Statement_Date__c = System.today();
        patStaTwo.PaymentsAdjustments_Received__c = 1000;
        patStaTwo.Account_Number__c = '1234';
        patStaTwo.Account__c = pat.Id;
        if(patStaTwo.PaymntTransIds__c != Null)
        {
            patStaTwo.PaymntTransIds__c = patStaTwo.PaymntTransIds__c + ',' +payTran.Id;
        }
        else
        {
            patStaTwo.PaymntTransIds__c = payTran.Id;
        }
        patStaTwo.NewCharges__c = 100;
        patStaTwo.PaymentsAndAdjustmnts__c = 100;
        patStaTwo.NewBalance__c = 100;
        patStaTwo.PreviousBalance__c = 50;
        insert patStaTwo;

        List<Transactions__c> trLst = new List<Transactions__c>();
        
        test.startTest();

        PatientStatment_ctr.PrivateProcedure pv = new PatientStatment_ctr.PrivateProcedure();
        pv.amountToPay = 10;
        pv.charges = 7;
        pv.discount = 2;
        pv.dos = System.now();
        pv.patientPayments = 5;
        pv.procedureName = '99202';
        pv.providerName = 'Aetna';
        pv.transactions = trLst;
        
        PatientStatment_ctr.InsuranceProcedure ip = new PatientStatment_ctr.InsuranceProcedure();
        ip.procedureName = '99202';
        ip.dos = System.now();
        ip.providerName = 'Aetna';
        ip.amountToPay = 10;
        ip.charges = 7;
        ip.patientPayments = 5;
        ip.insurancePayments = 2;
        ip.transactions = trLst;
        
        ApexPages.StandardController stc = new ApexPages.StandardController(patStaTwo);
        ApexPages.currentPage().getParameters().put('Id',patStaTwo.id);
        PatientStatment_ctr custCont  = new PatientStatment_ctr(stc);
        
        test.stopTest();
        System.assert(pat.Name !=null); 
    }
}