force-app/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Records the unique account number assigned to the account.</description>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Admit_Date__c.field-meta.xml
<CustomField>
    <fullName>Admit_Date__c</fullName>
    <description>Captures the date when the account holder was admitted.</description>
    <label>Admit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Represents the first name of the account holder.</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Captures the birth sex or gender identity of the account holder.</description>
    <label>Birth Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Male</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>UNK</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Represents the last name of the account holder.</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProcedureListViewApexTest.cls
@isTest
public class ProcedureListViewApexTest {
    @isTest
     static void coverageAllMethods(){
         Account acc = new Account();
        acc.Name = 'Test';
        acc.Admit_Date__c = System.today().addYears(-40);
        acc.First_Name__c = 'Hannah';
        acc.Last_Name__c = 'Brown';
        acc.Gender__c = 'Female';
        acc.Account_Number__c = '235689';
        acc.BillingState = 'NY';
        acc.BillingPostalCode = '10014';
        acc.BillingCountry = 'US';
        acc.Phone = '9879879879';
        insert acc;
                ElixirSuite__Procedure__c p = new ElixirSuite__Procedure__c(Name = 'TestProc',ElixirSuite__Related_Procedure_Code_Category__c = 'HCPCS Level 2', ElixirSuite__Account__c = acc.Id,
                                                                    ElixirSuite__Code_Category__c = 'ElixirSuite__Code_Category__c',
                                                                    RecordTypeId = Schema.SObjectType.ElixirSuite__Procedure__c.getRecordTypeInfosByDeveloperName().get('Template_Procedure').getRecordTypeId());
        insert p;
          Test.startTest();
        ProcedureListViewApex.BringDataFirst(p.Id);
        ProcedureListViewApex.BringDataViewAll(p.Id);
        ProcedureListViewApex.deleteRec(p.Id);
        System.assertEquals(1, 1, ''); 
        Test.stopTest();
    }
}