force-app/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Records the unique account number assigned to the account.</description>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Actual_Price__c/Actual_Price__c.object-meta.xml
<CustomObject>
    <description>Indicates the List price for a procedure w.r.t the Provider.</description>
    <label>Actual Price</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Actual Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actual Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Statement__c/Patient_Statement__c.object-meta.xml
<CustomObject>
    <label>Patient Statement</label>
    <nameField>
        <displayFormat>BILL-{0000}</displayFormat>
        <label>Patient Bill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Statement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Statement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient Statement</relationshipLabel>
    <relationshipName>Patient_Statement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/NewBalance__c.field-meta.xml
<CustomField>
    <fullName>NewBalance__c</fullName>
    <label>NewBalance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/NewCharges__c.field-meta.xml
<CustomField>
    <fullName>NewCharges__c</fullName>
    <label>NewCharges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/Patient_Code__c.field-meta.xml
<CustomField>
    <fullName>Patient_Code__c</fullName>
    <label>Patient Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/PaymentsAdjustments_Received__c.field-meta.xml
<CustomField>
    <fullName>PaymentsAdjustments_Received__c</fullName>
    <label>Payments/Adjustments Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/PaymentsAndAdjustmnts__c.field-meta.xml
<CustomField>
    <fullName>PaymentsAndAdjustmnts__c</fullName>
    <label>PaymentsAndAdjustmnts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/PreviousBalance__c.field-meta.xml
<CustomField>
    <fullName>PreviousBalance__c</fullName>
    <label>PreviousBalance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Patient_Statement__c/fields/Statement_Date__c.field-meta.xml
<CustomField>
    <fullName>Statement_Date__c</fullName>
    <label>Statement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object contains the summary of all the transactional details linked with a patient procedure. Also it contains the rollup for patient paid amount, total refund amount, total discount applied, primary insurance paid and secondary insurance paid amount.</description>
    <label>Master Transaction</label>
    <nameField>
        <displayFormat>PAYMENT-{0000}</displayFormat>
        <label>Payment Received Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Transaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Payment_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Actual_Price__c.field-meta.xml
<CustomField>
    <fullName>Actual_Price__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Actual Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Cpt_Codes__c.field-meta.xml
<CustomField>
    <fullName>Cpt_Codes__c</fullName>
    <label>CPT Codes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Insurance_Payments__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Payments__c</fullName>
    <label>Insurance Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Patient_Payments__c.field-meta.xml
<CustomField>
    <fullName>Patient_Payments__c</fullName>
    <label>Patient Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Payment_Adjustments__c.field-meta.xml
<CustomField>
    <fullName>Payment_Adjustments__c</fullName>
    <label>Payment Adjustments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PatientStatementHelper_Test.cls
@isTest
public class PatientStatementHelper_Test 
{
    public static testMethod void patiStamnt()
    {
        Account patient = TestDataFactory.createPatientAcc();
        insert patient;
        Set<Id> accIds = new Set<Id>();
        accIds.add(patient.Id);
        
        Patient_Statement__c patSta = new Patient_Statement__c();
        patSta.Patient_Code__c = '1234';
        patSta.Statement_Date__c = System.today();
        patSta.PaymentsAdjustments_Received__c = 1000;
        patSta.Account_Number__c = '1234';
        insert patSta;
        
        Patient_Statement__c patStaTwo = new Patient_Statement__c();
        patStaTwo.Patient_Code__c = '1234';
        patStaTwo.Statement_Date__c = System.today();
        patStaTwo.PaymentsAdjustments_Received__c = 1000;
        patStaTwo.Account_Number__c = '1234';
        patStaTwo.Account__c = patient.Id;
        patStaTwo.NewCharges__c = 100;
        patStaTwo.PaymentsAndAdjustmnts__c = 100;
        patStaTwo.NewBalance__c = 100;
        patStaTwo.PreviousBalance__c = 50;
        insert patStaTwo;
        
        Payment_Transaction__c payTran = new Payment_Transaction__c();
        payTran.Actual_Price__c = 500;
        payTran.Cpt_Codes__c = 'CPT100';
        payTran.Insurance_Payments__c = 200;
        payTran.Account__c = patient.Id;
        payTran.Patient_Payments__c = 300;
        payTran.Payment_Adjustments__c = 400;
        insert payTran;
        
        
        test.startTest();
        Date StartDate = System.today();
        Date EndDate = System.today()+10;
        PatientStatementHelper.parentInitFetchDataForPatientStatement(patient.Id);
        PatientStatementHelper.filteredPaymentHistory(patient.Id,StartDate,EndDate);
        PatientStatementHelper.checkStatementExists(patient.Id, StartDate, EndDate);
        PatientStatementHelper.singleStatementRecordDetils(patStaTwo.Id);
        AutoPatientStatementCreationHelper at = new AutoPatientStatementCreationHelper(accIds,System.now(),System.now());
        at.privateProcedureSchema(payTran);
        at.insuranceProcedureSchema(payTran);
        at.findPrivatePaymentsAggregate(System.Today());
        at.findInsurancePaymentsAggregate(System.Today());
        at.findProcedurePaidInMonthAggregate(System.Today());
        test.stopTest();
        System.assert( patSta.Patient_Code__c !=null,''); 
    }
}