force-app/main/default/objects/Account/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountId</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (AccountId)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Signature_Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Signature_Attachment_Id__c</fullName>
    <description>Stores the unique id of the signature attachment associated with the account.</description>
    <label>Signature Attachment Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Verification_Code__c.field-meta.xml
<CustomField>
    <fullName>Verification_Code__c</fullName>
    <description>Stores the verification code associated with the account.</description>
    <label>Verification Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>TO BE DEPRECATED:
Form was used to store all the forms related to the patient.</description>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Value__c/Form_Value__c.object-meta.xml
<CustomObject>
    <description>Form value stores all the miscellaneous features of the saved forms like Approvals, Care Episodes and Status. All the problems, diagnoses, medications and allergies selected on the forms are also linked with this object as the record in this object is also responsible for giving one identity to the forms saved in multiple objects.</description>
    <label>Form Value</label>
    <nameField>
        <label>Form Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Value__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Form Values</relationshipLabel>
    <relationshipName>Form_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Approval_Level__c.field-meta.xml
<CustomField>
    <fullName>Approval_Level__c</fullName>
    <label>Approval Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Approved_Signature__c.field-meta.xml
<CustomField>
    <fullName>Approved_Signature__c</fullName>
    <label>Approved Signature</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Date_Of_Approval__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Approval__c</fullName>
    <label>Date Of Approval</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Form_Detail__c.field-meta.xml
<CustomField>
    <fullName>Form_Detail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Form Detail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Form_Id__c.field-meta.xml
<CustomField>
    <fullName>Form_Id__c</fullName>
    <label>Form Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Form_Name__c.field-meta.xml
<CustomField>
    <fullName>Form_Name__c</fullName>
    <label>Form Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Is_Approver__c.field-meta.xml
<CustomField>
    <fullName>Is_Approver__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Approver</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Is_Old__c.field-meta.xml
<CustomField>
    <fullName>Is_Old__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Old</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Signed_Patient__c.field-meta.xml
<CustomField>
    <fullName>Signed_Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Signed Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Form Values (Signed Patient)</relationshipLabel>
    <relationshipName>Form_Values1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Waiting For Patient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Form_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/Object_1_css__c.object-meta.xml
<CustomObject>
    <description>Form css stores all the attributes that defines how a form will look like when you view a form. All configuration records are saved in this object from Form Configuration screen.</description>
    <label>Form css</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Object 1 css Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form css</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_1_css__c/fields/Approv__c.field-meta.xml
<CustomField>
    <fullName>Approv__c</fullName>
    <label>Approver</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Approval_Level__c.field-meta.xml
<CustomField>
    <fullName>Approval_Level__c</fullName>
    <label>Approval Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Approval_Members__c.field-meta.xml
<CustomField>
    <fullName>Approval_Members__c</fullName>
    <label>Approval Members</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Approver_Custom_Label__c.field-meta.xml
<CustomField>
    <fullName>Approver_Custom_Label__c</fullName>
    <label>Approver Custom Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Object_1_css__c.field-meta.xml
<CustomField>
    <fullName>Object_1_css__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Object 1 css</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Section_Number__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Object_1_css__c</referenceTo>
    <relationshipName>Object_1_css</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Object_2__c/Object_2__c.object-meta.xml
<CustomObject>
    <label>Object 2</label>
    <nameField>
        <label>Object 2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object 2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_2__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Object 2</relationshipLabel>
    <relationshipName>Object_2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Object_2__c/fields/Form_unique_id__c.field-meta.xml
<CustomField>
    <fullName>Form_unique_id__c</fullName>
    <label>Form unique id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Signature_Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Signature_Attachment_Id__c</fullName>
    <label>Signature Attachment Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Verification_Code__c.field-meta.xml
<CustomField>
    <fullName>Verification_Code__c</fullName>
    <label>Verification Code</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Verification_Code_New__c.field-meta.xml
<CustomField>
    <fullName>Verification_Code_New__c</fullName>
    <label>Verification Code New</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrderSignatureSave.cls
public with sharing class OrderSignatureSave {
    @AuraEnabled //String formName, String changedFormName, String formId,
    public static SignAndAprroveData approveOrder(String userValues, String currentLevel, String code, String comments){
        try {
            
            SignAndAprroveData currentData = new SignAndAprroveData();
            currentData.dateOfApproval = System.now();
            currentData.comments = comments;

            UserValues userDetails = (UserValues) 
                                        JSON.deserializeStrict(userValues, UserValues.class);
            String userId = userDetails.userId;
            List<User> users = [SELECT Id, Name, userrole.name, Signature_Attachment_Id__c, Verification_Code__c, Verification_Code_New__c
                                FROM User 
                                WHERE Id= :userId WITH SECURITY_ENFORCED];
            String patientId = userDetails.patientId;
            List<Account> patients = [SELECT Id, Name, Signature_Attachment_Id__c, Verification_Code__c FROM Account 
                                WHERE Id= :patientId WITH SECURITY_ENFORCED ];

            ElixirSuite__Master_Object__c defaultApprovalLevels = (ElixirSuite__Master_Object__c)
                                        JSON.deserializeStrict(currentLevel, ElixirSuite__Master_Object__c.class);
            String approvalType = defaultApprovalLevels.ElixirSuite__Approver__c;
            String allApproversText = defaultApprovalLevels.Approval_Members__c;
            Decimal approvalLevel = defaultApprovalLevels.Approval_Level__c;

            currentData.approvalLevel = Integer.valueOf(approvalLevel);
            currentData.customLabel = defaultApprovalLevels.Approver_Custom_Label__c;

            List<String> allApprovers = allApproversText.split(';');
            
            //ElixirSuite__Prescription_Order__c approvalValue = new ElixirSuite__Prescription_Order__c();
            String signature;

            switch on approvalType {
                when 'User','Profile','Role' {  
                    //approvalValue.User__c = userId;
                    String verificationCode = users[0].Verification_Code_New__c;
                    checkValidity(code, verificationCode );
                    signature = users[0].Signature_Attachment_Id__c;
                    currentData.userName = users[0].Name;
                    currentData.userRole = users[0].userrole.name;
                    currentData.userId = users[0].Id;
                }   
                when 'Patient' {        
                    //approvalValue.Signed_Patient__c = patientId;
                    String verificationCode = patients[0].Verification_Code__c;
                    checkValidity(code, verificationCode);
                    signature = patients[0].Signature_Attachment_Id__c;
                    currentData.patientName = patients[0].Name;
                    currentData.userId = users[0].Id;
                }
            }
            if(!Test.isRunningTest() && String.isBlank(signature)){
                AuraHandledException e = new AuraHandledException('Please Register Signature First!');
                e.setMessage('Please Register Signature First!');
                throw e;
            }
            List<sObject> images;
            system.debug('signature is'+signature);
            if(approvaltype.equalsIgnoreCase('Patient')){
                images = [SELECT Id FROM Attachment WHERE Id= :signature WITH SECURITY_ENFORCED];
                if (images != null && images.size() > 0) {
                    currentData.signatureAttachmentId = images[0].Id;
                }
            }else{
                images = [SELECT Id FROM ContentDocument WHERE Id= :signature WITH SECURITY_ENFORCED];
                if (images != null && images.size() > 0) {
                    currentData.signatureContentDocumentId = images[0].Id;
                }
            }
            if(!Test.isRunningTest() &&(images==null || images.size()==0)){
                AuraHandledException e = new AuraHandledException('Please Register Signature First!');
                e.setMessage('Please Register Signature First!');
                throw e;
            }

            //approvalValue.Account__c = patientId;
            //approvalValue.Form_Id__c = formId;
            //approvalValue.Form_Name__c = changedFormName;
            //approvalValue.Approval_Level__c =  String.valueof(Integer.valueOf(approvalLevel));
            //approvalValue.Comment__c = comments;
            //approvalValue.Approved_Signature__c = signature;
            //approvalValue.Date_Of_Approval__c = System.now();
            //approvalValue.Is_Approver__c = true; 
            //system.debug(approvalValue);
            // if(Schema.sObjectType.Form_Value__c.isCreateable() &&
            // Schema.sObjectType.Form_Value__c.fields.Account__c.isCreateable() &&
            // Schema.sObjectType.Form_Value__c.fields.Form_Name__c.isCreateable() &&
            // Schema.sObjectType.Form_Value__c.fields.Approval_Level__c.isCreateable() &&
            // Schema.sObjectType.Form_Value__c.fields.Form_Id__c.isCreateable() &&
            // Schema.sObjectType.Form_Value__c.fields.Comment__c.isCreateable() &&
            // Schema.sObjectType.Form_Value__c.fields.Approved_Signature__c.isCreateable() &&
            // Schema.sObjectType.Form_Value__c.fields.Is_Approver__c.isCreateable() &&
            // Schema.sObjectType.Form_Value__c.fields.Signed_Patient__c.isCreateable()){
            //     system.debug(approvalValue);
            //     insert approvalValue;
            // }
            //NotifyApprovers.sendNotification(formName, changedformName, patientId,
            //                            Integer.valueOf(approvalLevel));// Notify Approvers
            //String formStatus  = changeStatus(formId, formName);
            //system.debug('beforeDetails');
            // List<Form_Value__c> formDetails = [SELECT Id, Status__c FROM Form_Value__c 
            //                                 WHERE Form_Id__c= :formId AND Form_Detail__c=true 
            //                                 WITH SECURITY_ENFORCED ];
            // system.debug('afterDetails');
            // if(formDetails!=null && formDetails.size()>0){
            //     formDetails[0].Status__c = formStatus;
            // }else{
            //     Form_Value__c formDetail = new Form_Value__c(
            //         Status__c = formStatus,
            //         Form_Id__c = formId,
            //         Account__c = patientId,
            //         Form_Detail__c = true,
            //         Form_Name__c = changedFormName);
            //     formDetails.add(formDetail);
            // }
            
            // if(Schema.sObjectType.Form_Value__c.isUpdateable() &&
            // Schema.sObjectType.Form_Value__c.fields.Account__c.isUpdateable() &&
            // Schema.sObjectType.Form_Value__c.fields.Form_Name__c.isUpdateable() &&
            // Schema.sObjectType.Form_Value__c.fields.Form_Id__c.isUpdateable() &&
            // Schema.sObjectType.Form_Value__c.fields.Form_Detail__c.isUpdateable() &&
            // Schema.sObjectType.Form_Value__c.fields.Status__c.isUpdateable()){
            //     upsert formDetails;
            // }

            return currentData;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    private static void checkValidity(String code, String verificationCode){
        if(code != verificationCode){
            AuraHandledException e = new AuraHandledException('Verification Failed!');
                e.setMessage('Verification Failed!');
                throw e;
        }
    }
    private static String changeStatus(String formId, String recordTypeName){
        List<Object_1_css__c> defaultApprovalLevels = new List<Object_1_css__c>();
        List<Form_Value__c> approvedValues = new List<Form_Value__c>();
        defaultApprovalLevels = [SELECT Id, Approval_Level__c, Approv__c, Approval_Members__c FROM 
                        Object_1_css__c WHERE Form__c= :recordTypeName AND Approval_Level__c!=NULL
                        WITH SECURITY_ENFORCED
                        ORDER BY Approval_Level__c ];
        approvedValues = [SELECT Id, Account__c, Is_Approver__c, Date_Of_Approval__c,
                        User__r.Name, Approval_Level__c, Comment__c, Form_Name__c, Approved_Signature__c,
                        Signed_Patient__r.Name FROM Form_Value__c
                        WHERE Is_Approver__c=true AND Form_Id__c= :formId and Is_old__c != true
                        WITH SECURITY_ENFORCED
                        ORDER BY Approval_Level__c];
        Integer defaultLevels = defaultApprovalLevels.size();
        Integer approvedLevels = approvedValues.size();
        if(defaultLevels>0){
            return adminConfiguredLevels(defaultLevels, approvedLevels);
        }else{
            return 'Open';
        }
    }
    //C
    private static String adminConfiguredLevels(Integer defaultLevels, Integer approvedLevels){
        if(approvedLevels>0){
            return checkApprovedValues(defaultLevels, approvedLevels);
        }else{
            return 'Open';
        }
    }
    private static String checkApprovedValues(Integer defaultLevels, Integer approvedLevels){
        if(defaultLevels == approvedLevels){
            return 'Completed';
        }else{
            return 'In Progress';
        }
    }
    public class UserValues{
        public String userId;
        public String patientId;
        public String profileId;
        public String roleId;
    }
    
    
    @AuraEnabled
    public static List<Form_Value__c> getStatus(String formId){
          List<Form_Value__c> status = [Select Id, ElixirSuite__Status__c 
                                  from ElixirSuite__Form_Value__c 
                                 where ElixirSuite__Form_Id__c =:formId and ElixirSuite__Form_Detail__c = true WITH SECURITY_ENFORCED];
          
          return status;
    }     
    
    //To display insert signature img for portal users - Srihari
    @AuraEnabled
    public static String getPortalFlag(String accId,String formId){
        String status='';
        string query = 'select id,AccountId__c,Is_Patient_Portal_Form__c from Object_2__c where AccountId__c =:accId AND Form_unique_id__c=:formId';
        
        List<sObject> portalStatus = Database.query(query);
        
        for(sObject obj :portalStatus){
            status=String.valueOf(obj.get('Is_Patient_Portal_Form__c'));
        }
        
        return status;
    }    

    //  approvedLevel.ElixirSuite__Date_Of_Approval__c
    //   approvedLevel.ElixirSuite__User__r.Name
    //   approvedLevel.ElixirSuite__User__r.UserRole.Name

    //   approvedLevel.ElixirSuite__Approved_Signature__c
    //   approvedLevel.ElixirSuite__Signed_Patient__r.Name

    
    public class SignAndAprroveData {
       @AuraEnabled public Datetime dateOfApproval;
       @AuraEnabled public Integer approvalLevel;
       @AuraEnabled public String userName;
       @AuraEnabled public String userRole;
       @AuraEnabled public String signatureAttachmentId;
       @AuraEnabled public String signatureContentDocumentId;
       @AuraEnabled public String patientName;
       @AuraEnabled public String customLabel;
       @AuraEnabled public String comments;
       @AuraEnabled public String userId;
    }

    @AuraEnabled
    public static void attachApprovalDataToParentPrescriptionEditMode(String parentPrescriptionId, String approvedValues){
        try {
            SelectionMedicationRecordsApexController.attachApprovalDataToParentPrescription(parentPrescriptionId, approvedValues);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void attachApprovalDataToLabOrderEditMode(String labOrderId, String approvedValues){
        try {
            LabOrderController.attachApprovalDataToLabOrder(labOrderId, approvedValues);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    
}