force-app/main/default/objects/Account/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Formula to calculate the age of the account holder based on the birth date.</description>
    <formula>IF(
  MONTH(TODAY())&gt;MONTH(DOB__c),
    YEAR(TODAY())-YEAR(DOB__c),  
    IF(AND(MONTH(TODAY()) = MONTH(DOB__c), DAY(TODAY()) &gt;= DAY(DOB__c)), 
      YEAR(TODAY())-YEAR(DOB__c), 
      (YEAR(TODAY())-YEAR(DOB__c))-1)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/birthdate__c.field-meta.xml
<CustomField>
    <fullName>birthdate__c</fullName>
    <formula>IF( NOT( ISBLANK(DOB__c ) ) , CASE(MONTH( DOB__c ),
1, &quot;January&quot;,
2, &quot;February&quot;,
3, &quot;March&quot;,
4, &quot;April&quot;,
5, &quot;May&quot;,
6, &quot;June&quot;,
7, &quot;July&quot;,
8, &quot;August&quot;,
9, &quot;September&quot;,
10, &quot;October&quot;,
11, &quot;November&quot;,
12, &quot;December&quot;,
&quot;None&quot;)+ &apos; &apos;+TEXT(DAY(DOB__c))+&apos;,&apos;+&apos; &apos;+TEXT(Year(DOB__c)), &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>birthdate</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Captures the birth sex or gender identity of the account holder.</description>
    <label>Birth Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Male</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>UNK</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>This object is used to store Claim related data for a patient.</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>CS{YYMMDD}{000000}</displayFormat>
        <label>Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Denotes claim generated for which patient(Account).</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <description>Represents self relationship.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claim_Status__c.field-meta.xml
<CustomField>
    <fullName>Claim_Status__c</fullName>
    <description>Represents the current status of claim processing.</description>
    <label>Claim Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Ready to Submit</fullName>
            </value>
            <value>
                <fullName>Sent to Clearing house</fullName>
            </value>
            <value>
                <fullName>Clearing house accepted</fullName>
            </value>
            <value>
                <fullName>Clearing house rejected</fullName>
            </value>
            <value>
                <fullName>Payer Accepted</fullName>
            </value>
            <value>
                <fullName>Payer Rejected</fullName>
            </value>
            <value>
                <fullName>ERA Received</fullName>
            </value>
            <value>
                <fullName>Claim Validation Error</fullName>
            </value>
            <value>
                <fullName>Paid and Patient Responsibility</fullName>
            </value>
            <value>
                <fullName>Paid and resolved</fullName>
            </value>
            <value>
                <fullName>Paid with Patient Responsibility – Ready to submit Secondary Insurance</fullName>
            </value>
            <value>
                <fullName>Overpaid</fullName>
            </value>
            <value>
                <fullName>Underpaid</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Paid and patient responsibility with Secondary</fullName>
            </value>
            <value>
                <fullName>ERA Received - Transferred to Secondary</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Generated</fullName>
                <isActive>false</isActive>
                <label>Generated</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
                <isActive>false</isActive>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Processed</fullName>
                <isActive>false</isActive>
                <label>Processed</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Transmitted</fullName>
                <isActive>false</isActive>
                <label>Transmitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Manual_ERA__c.field-meta.xml
<CustomField>
    <fullName>Manual_ERA__c</fullName>
    <description>Refers Era Generation Method</description>
    <defaultValue>false</defaultValue>
    <label>Manual ERA?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient_DOB__c.field-meta.xml
<CustomField>
    <fullName>Patient_DOB__c</fullName>
    <description>Used to store patient's date of birth.</description>
    <label>Patient DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient_Name__c.field-meta.xml
<CustomField>
    <fullName>Patient_Name__c</fullName>
    <description>Used to store patient's  name.</description>
    <inlineHelpText>Use commas to separate the last name, first name, and middle initial.</inlineHelpText>
    <label>Patient Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient_s_Address__c.field-meta.xml
<CustomField>
    <fullName>Patient_s_Address__c</fullName>
    <description>Used to store patient's address.</description>
    <label>Patient’s Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient_s_City__c.field-meta.xml
<CustomField>
    <fullName>Patient_s_City__c</fullName>
    <description>Used to store patient's city name.</description>
    <label>Patient’s City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient_s_Phone__c.field-meta.xml
<CustomField>
    <fullName>Patient_s_Phone__c</fullName>
    <description>Used to store patient's phone.</description>
    <label>Patient&apos;s Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient_s_State__c.field-meta.xml
<CustomField>
    <fullName>Patient_s_State__c</fullName>
    <description>Used to store patient's state.</description>
    <label>Patient’s State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient_s_Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Patient_s_Zipcode__c</fullName>
    <description>Used to store patient's zipcode.</description>
    <label>Patient’s Zipcode</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient_Sex__c.field-meta.xml
<CustomField>
    <fullName>Patient_Sex__c</fullName>
    <description>Refer patient's gender.</description>
    <label>Patient Sex</label>
    <length>29</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EOB__c/EOB__c.object-meta.xml
<CustomObject>
    <description>This object stores the Parent ERA and child ERA.
Parent ERA is an orphan record whereas Child ERA is associated to a self lookup field to Parent ERA.</description>
    <label>ERA</label>
    <nameField>
        <displayFormat>ERA-{0000}</displayFormat>
        <label>ERA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EOB__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ERA</relationshipLabel>
    <relationshipName>ERA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EOB__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipName>EOB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EOB__c/fields/Copy_Of_Original_ERA__c.field-meta.xml
<CustomField>
    <fullName>Copy_Of_Original_ERA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Copy Of Original ERA?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EOB__c/fields/EOB__c.field-meta.xml
<CustomField>
    <fullName>EOB__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ERA</label>
    <referenceTo>EOB__c</referenceTo>
    <relationshipLabel>ERA</relationshipLabel>
    <relationshipName>EOB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EOB__c/fields/Manual_ERA__c.field-meta.xml
<CustomField>
    <fullName>Manual_ERA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual ERA?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ERACustomWidgetCtrl_Test.cls
@isTest
public class ERACustomWidgetCtrl_Test 
{
    public static testMethod void eraTest()
    {
        Account pat = new Account();
        pat.Name = 'test';
        //	pat.Age__c = '18';
        pat.Phone = '1234567890';
        pat.BillingStreet = 'test';
        pat.BillingCity = 'test';
        pat.BillingCountry = 'test';
        pat.BillingState = 'test';
        pat.BillingPostalCode = '123456';
        pat.Gender__c = 'Female';
        //pat.birthdate__c = system.today();
        pat.AccountNumber = '123456';
        insert pat;
        
        Claim__c claim = new Claim__c();
        claim.Claim_Status__c = 'Saved';
        claim.Account__c = pat.Id;
        claim.Patient_s_Phone__c = '1234567890';
        claim.Patient_DOB__c = system.today();
        claim.Patient_Sex__c = 'M';
        claim.Patient_Name__c = pat.Name;
        claim.Patient_s_Address__c = pat.BillingStreet;
        claim.Patient_s_State__c = pat.BillingState;
        claim.Patient_s_City__c = pat.BillingCity;
        claim.Manual_ERA__c = false;
        claim.Patient_s_Zipcode__c = decimal.valueOf(pat.BillingPostalCode) ;
        insert claim;
        
        EOB__c objEb = new EOB__c();
        objEb.Account__c = pat.Id;
        objEb.Copy_Of_Original_ERA__c = false;
        objEb.Claim__c = claim.Id;
        insert objEb;
        
        test.startTest();
        ERACustomWidgetCtrl.fetchOriginalERA(claim.Id);
        test.stopTest();
        System.assert(	claim.Claim_Status__c!=null,'');
    }
}