force-app/main/default/objects/Account/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Formula to calculate the age of the account holder based on the birth date.</description>
    <formula>IF(
  MONTH(TODAY())&gt;MONTH(DOB__c),
    YEAR(TODAY())-YEAR(DOB__c),  
    IF(AND(MONTH(TODAY()) = MONTH(DOB__c), DAY(TODAY()) &gt;= DAY(DOB__c)), 
      YEAR(TODAY())-YEAR(DOB__c), 
      (YEAR(TODAY())-YEAR(DOB__c))-1)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/birthdate__c.field-meta.xml
<CustomField>
    <fullName>birthdate__c</fullName>
    <formula>IF( NOT( ISBLANK(DOB__c ) ) , CASE(MONTH( DOB__c ),
1, &quot;January&quot;,
2, &quot;February&quot;,
3, &quot;March&quot;,
4, &quot;April&quot;,
5, &quot;May&quot;,
6, &quot;June&quot;,
7, &quot;July&quot;,
8, &quot;August&quot;,
9, &quot;September&quot;,
10, &quot;October&quot;,
11, &quot;November&quot;,
12, &quot;December&quot;,
&quot;None&quot;)+ &apos; &apos;+TEXT(DAY(DOB__c))+&apos;,&apos;+&apos; &apos;+TEXT(Year(DOB__c)), &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>birthdate</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Represents the first name of the account holder.</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Captures the birth sex or gender identity of the account holder.</description>
    <label>Birth Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Male</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>UNK</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Installment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Installment_Amount__c</fullName>
    <label>Installment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Represents the last name of the account holder.</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MRN_Number__c.field-meta.xml
<CustomField>
    <fullName>MRN_Number__c</fullName>
    <description>Denotes the medical record number assigned to the account.</description>
    <label>MRN Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Outstanding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Amount__c</fullName>
    <description>Denotes the outstanding financial balance that the patient currently owes for healthcare services.</description>
    <label>Outstanding Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Profile_Picture__c.field-meta.xml
<CustomField>
    <fullName>Profile_Picture__c</fullName>
    <description>Stores a reference or link to the profile picture associated with the account.</description>
    <label>Profile Picture</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Patient_Responsibility__c.field-meta.xml
<CustomField>
    <fullName>Total_Patient_Responsibility__c</fullName>
    <description>Records the total financial responsibility assigned to the patient.</description>
    <label>Total Patient Responsibility</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Unallocated_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Amount__c</fullName>
    <description>Denotes the unallocated financial amount associated with the account.</description>
    <label>Unallocated Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Initial_Agreement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Initial_Agreement_Amount__c</fullName>
    <label>Initial Agreement Amount</label>
    <summarizedField>OpportunityLineItem.TotalPrice</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Instalments_by_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Instalments_by_Frequency__c</fullName>
    <label>Instalments by Frequency</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LOC__c.field-meta.xml
<CustomField>
    <fullName>LOC__c</fullName>
    <label>LOC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>IOP</fullName>
            </value>
            <value>
                <fullName>OP</fullName>
            </value>
            <value>
                <fullName>Detox</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Patient_Responsibility__c.field-meta.xml
<CustomField>
    <fullName>Patient_Responsibility__c</fullName>
    <label>Patient Responsibility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Amount_curr__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount_curr__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_frequency__c</fullName>
    <label>Payment frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Profile_Picture__c.field-meta.xml
<CustomField>
    <fullName>Profile_Picture__c</fullName>
    <label>Profile Picture</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>To be Deprecated: This object is used to store both master and sub payment schedules for a patient.</description>
    <label>Master Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Payment Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Payment Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Schedule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Payment_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Net_Balance__c.field-meta.xml
<CustomField>
    <fullName>Net_Balance__c</fullName>
    <label>Patient Responsibility/Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Pay_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Pay_Frequency__c</fullName>
    <label>Pay Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Payment Schedule</label>
    <referenceTo>Payment_Schedule__c</referenceTo>
    <relationshipLabel>Sub Payment Schedule</relationshipLabel>
    <relationshipName>Payment_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Plan_description__c.field-meta.xml
<CustomField>
    <fullName>Plan_description__c</fullName>
    <label>Plan description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Remaining_Amount__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Amount__c</fullName>
    <label>Remaining Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/recordTypes/Master_Payment_Schedule.recordType-meta.xml
<RecordType>
    <fullName>Master_Payment_Schedule</fullName>
    <active>true</active>
    <label>Master Payment Schedule</label>
</RecordType>

force-app/main/default/objects/Payment_Schedule__c/recordTypes/Sub_Payment_Schedule.recordType-meta.xml
<RecordType>
    <fullName>Sub_Payment_Schedule</fullName>
    <active>true</active>
    <label>Sub Payment Schedule</label>
</RecordType>

force-app/main/default/classes/PaymentScheduleApex.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-21-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing  class PaymentScheduleApex {
    @AuraEnabled
    public static void fetchData( string accId){
        
        
    }
    @AuraEnabled
    public static List<opportunity> FetchOppdataForPayment( string opid ){
        //Query payment responsibility
        //Now Query Products Total and Initial Agreement Amount
        List<Opportunity> Opplist=new List<Opportunity>();
        if(Schema.sobjecttype.opportunity.isAccessible()
                          && Schema.sObjectType.opportunity.fields.Instalments_by_Frequency__c.isAccessible()
           && Schema.sObjectType.opportunity.fields.Patient_Responsibility__c.isAccessible() && Schema.sObjectType.opportunity.fields.Initial_Agreement_Amount__c.isAccessible()){ 
        Opplist=[select id,Instalments_by_Frequency__c,Patient_Responsibility__c,ElixirSuite__Initial_Agreement_Amount__c,Payment_Amount_curr__c,Payment_Date__c,Payment_Frequency__c,LOC__c from opportunity where id=:opid];
        }
            for(Opportunity o:Opplist){
            if(o.LOC__c=='Sober Living'){
                 o.addError('For Sober Living Level of Care, the Payment Schedule can not be Generated');
            }
        }
        return Opplist;
    }
    @AuraEnabled
    public static Account getOutstanding(String accountId){
        Account patient = new Account();
        patient = [SELECT id , 	Name,	Age__c , AccountNumber,	First_Name__c,	Gender__c,	Last_Name__c,	MRN_Number__c,	Outstanding_Amount__c,
                   birthdate__c,	Phone,	Unallocated_Amount__c,Profile_Picture__c,Total_Patient_Responsibility__c
                   FROM  Account where id=: accountId 
                   WITH SECURITY_ENFORCED
                   limit 1];
       
        return patient ;
    }
    
     @AuraEnabled
    public static License_Class LicensBasdPermission()
    {
        Id currentUid = UserInfo.getUserId();
        String AvailLicense = [Select Id,ElixirSuite__License_Type__c,Username,Name
         from User 
         where Id =:currentUid
         WITH SECURITY_ENFORCED].ElixirSuite__License_Type__c;
        List<String> lst_availLicense = new List<String>();
        lst_availLicense = AvailLicense.split(';');
        License_Class lCls = new License_Class();
        for(String str : lst_availLicense)
        {
            if(str == 'Elixir EHR')
            {
                lCls.isEhr = True;
                continue;
            }
           
            if(str == 'Elixir Contact Center')
            {
                lCls.isContactCenter = True;
                continue;
            }
             
            if(str == 'Elixir RCM')
            {
                lCls.isRcm = True;
                continue;
            }
        }
        return lCls;
    }
    public class License_Class
    {
        @AuraEnabled public Boolean isEhr;
        @AuraEnabled public Boolean isRcm;
        @AuraEnabled public Boolean isContactCenter;
    }
    
    
    @AuraEnabled
    public static void saveData(string ids  , String scheduleData , String totalPlanAmount , String frequencyRate , String installmentAmt , Boolean isCheck){
        system.debug('recordId'+totalPlanAmount);
        system.debug('recordId'+frequencyRate);
        system.debug('recordId'+installmentAmt);
        system.debug('recordId'+scheduleData);
        List<Payment_Schedule__c> allSchedules = new List<Payment_Schedule__c>();
        Id masterRecordTypeId = Schema.SObjectType.Payment_Schedule__c.getRecordTypeInfosByDeveloperName().get('Master_Payment_Schedule').getRecordTypeId();
        Id childRecordTypeId = Schema.SObjectType.Payment_Schedule__c.getRecordTypeInfosByDeveloperName().get('Sub_Payment_Schedule').getRecordTypeId();
        
        Map<String, Object> jsonSchedule =(Map<String, Object>)JSON.deserializeUntyped(scheduleData);
        List<Object> listOfPatSchedules = (List<Object>) jsonSchedule.get('keysToSaveSchedule');
        
        Payment_Schedule__c masterSched = new Payment_Schedule__c();
        masterSched.Installment_Amount__c = Decimal.valueOf(installmentAmt) ;
        masterSched.Pay_Frequency__c = frequencyRate;
        masterSched.Net_Balance__c = Decimal.valueOf(totalPlanAmount);
        masterSched.Remaining_Amount__c = Decimal.valueOf(totalPlanAmount);
        masterSched.RecordTypeId = masterRecordTypeId;
        masterSched.Payment_Status__c = 'Active';
        System.debug('isCheck*****'+isCheck); 
        if(isCheck == true)
        {
            masterSched.Status__c = 'Active';
        }
        else
        {
            masterSched.Status__c = 'Inactive';
        }
        
        masterSched.Account__c = ids ;
        if(Schema.sObjectType.Payment_Schedule__c.isCreateable() &&
        Schema.sObjectType.Payment_Schedule__c.fields.Installment_Amount__c.isCreateable() &&
        Schema.sObjectType.Payment_Schedule__c.fields.Pay_Frequency__c.isCreateable() &&
        Schema.sObjectType.Payment_Schedule__c.fields.Net_Balance__c.isCreateable() &&
        Schema.sObjectType.Payment_Schedule__c.fields.Remaining_Amount__c.isCreateable() &&
        Schema.sObjectType.Payment_Schedule__c.fields.RecordTypeId.isCreateable() &&
        Schema.sObjectType.Payment_Schedule__c.fields.Account__c.isCreateable() &&
        Schema.sObjectType.Payment_Schedule__c.fields.Status__c.isCreateable() &&
        Schema.sObjectType.Payment_Schedule__c.fields.Payment_Status__c.isCreateable()){
        insert masterSched;
            }
    
        
        system.debug('bsjqn' + listOfPatSchedules);
        
        for(Object payScheded : listOfPatSchedules){
            system.debug('wdb' + payScheded);
             Payment_Schedule__c paySched = new Payment_Schedule__c();
            Map<String, Object> mapofSchedules = (Map<String, Object>)payScheded;
            system.debug('the map is' + mapofSchedules);
            paySched.Installment_Amount__c = Decimal.valueOf(String.valueOf(mapofSchedules.get('instAmt'))); 
            paySched.Net_Balance__c = Decimal.valueOf(totalPlanAmount);
            paySched.Payment_Schedule__c = masterSched.id ; 
            paySched.Remaining_Amount__c = Decimal.valueOf(String.valueOf(mapofSchedules.get('instAmt')));
            paySched.Account__c = ids ;
            paySched.RecordTypeId = childRecordTypeId;
            paySched.ElixirSuite__Payment_Status__c = 'Active';
            if(isCheck == true)
            {
                paySched.Status__c = 'Active';
            }
            else
            {
                paySched.Status__c = 'Inactive';
            }
            if(String.isNotBlank((String)mapofSchedules.get('DD'))){
                List<String> dateSplit = (List<String>) String.valueOf(mapofSchedules.get('DD')).split('/');
                system.debug('dateSplit' +dateSplit);
                if(dateSplit.size() > 0)
                {
                    //Added by sagili siva
                    integer myIntDate=integer.valueOf(dateSplit[1]);
                    integer myIntMonth=integer.valueOf(dateSplit[0]);
                    integer myIntYear=integer.valueOf(dateSplit[2]);
                    Date mydate=date.newInstance(myIntYear, myIntMonth, myIntDate);
                   //Commented by sagili siva because it accepting only MM/DD/YYYY values
                  // Date mydate = date.parse(dateSplit[0]+'/'+dateSplit[1]+'/'+dateSplit[2]);
                    system.debug('mydate' +mydate);
                	paySched.ElixirSuite__Due_Date__c = mydate;
                }
               
            }
            allSchedules.add(paySched);
        }
        system.debug('the list is' + allSchedules);
        if(Schema.sObjectType.Payment_Schedule__c.isCreateable() &&
        Schema.sObjectType.Payment_Schedule__c.fields.Installment_Amount__c.isCreateable() &&
        Schema.sObjectType.Payment_Schedule__c.fields.Pay_Frequency__c.isCreateable() &&
        Schema.sObjectType.Payment_Schedule__c.fields.Net_Balance__c.isCreateable() &&
        Schema.sObjectType.Payment_Schedule__c.fields.Remaining_Amount__c.isCreateable() &&
        Schema.sObjectType.Payment_Schedule__c.fields.RecordTypeId.isCreateable() &&
        Schema.sObjectType.Payment_Schedule__c.fields.ElixirSuite__Due_Date__c.isCreateable() &&
        Schema.sObjectType.Payment_Schedule__c.fields.Status__c.isCreateable() &&
        Schema.sObjectType.Payment_Schedule__c.fields.Account__c.isCreateable() &&
        Schema.sObjectType.Payment_Schedule__c.fields.Payment_Schedule__c.isCreateable() &&
        Schema.sObjectType.Payment_Schedule__c.fields.ElixirSuite__Payment_Status__c.isCreateable()){
        insert allSchedules;
         }
    }
        
        //  system.debug('abc'+scheduleData);
        /*   system.debug('recordId'+ids);

List<Opportunity> OppoList=[select id,Installments_Per_Month__c,Patient_Responsibility__c,Initial_Agreement_Amount__c,Products_Total__c,Payment_Amount__c,Payment_Date__c,Payment_Frequency__c,LOC__c,AVSFQB__Total_Amount__c from Opportunity where id=:ids];
// Change here to change between Patient Responsibility vs QuickBook Total Amount
// Change here between patient responsibility vs Products total
Decimal remainingAmount=(OppoList[0].Products_Total__c-OppoList[0].Initial_Agreement_Amount__c); //Change Patient_Responsibility__c from AVSFQB__Total_Amount__c
//Change Products total from Patient_Responsibility__c
Decimal TotalDuration=remainingAmount/OppoList[0].Installments_Per_Month__c;
integer modulo=math.mod(remainingAmount.intValue(), OppoList[0].Installments_Per_Month__c.intvalue());
integer iteration=TotalDuration.round(system.RoundingMode.FLOOR).intValue();
integer iteration1=TotalDuration.round(system.RoundingMode.CEILING).intValue();

//TotalDuration
system.debug('TotalTime'+TotalDuration);

List<Payment_Schedule__c> PaymentList=[select id,Admission__c,Due_Date__c,Installment_Amount__c,LOC__c,Status__c from Payment_Schedule__c where Admission__c =:ids];
system.debug('paymentlist'+PaymentList);
List<Payment_Schedule__c> PaymentListUpdate=new List<Payment_Schedule__c>();

if(PaymentList.size()>0){
for(opportunity o: OppoList){
o.addError('Payment is already scheduled for this patient' );

}

}
else { 
if(OppoList[0].Initial_Agreement_Amount__c!=0){
Payment_schedule__c p=new Payment_schedule__c();
p.Admission__c=OppoList[0].id;
p.Installment_Amount__c=OppoList[0].Initial_Agreement_Amount__c;
p.Due_Date__c=OppoList[0].payment_Date__c;
p.LOC__c=OppoList[0].LOC__c;
p.Status__c='Paid';
p.Plan_description__c='Upfront Collected By Admission';
PaymentListUpdate.add(p);
}
for(Opportunity o:OppoList){

system.debug('inside for opportunity');
for(Integer i=1;i<=iteration;i+=1){
system.debug('inside iteration');
if(o.Payment_Frequency__c=='Daily'){

system.debug('isnide daily if');
Payment_Schedule__c p=new Payment_Schedule__c();
p.Admission__c=o.id;
p.Due_Date__c=system.today().addDays(i);
p.Installment_Amount__c=o.Installments_Per_Month__c;
p.LOC__c=o.LOC__c;
p.Status__c='Active';

PaymentListUpdate.add(p);
}
if(o.Payment_Frequency__c=='Weekly'){

system.debug('isnide Weekly if');
Payment_Schedule__c p=new Payment_Schedule__c();
p.Admission__c=o.id;
p.Due_Date__c=system.today().addDays(7*i);
p.Installment_Amount__c=o.Installments_Per_Month__c;
p.LOC__c=o.LOC__c;
p.Status__c='Active';
PaymentListUpdate.add(p);
}
if(o.Payment_Frequency__c=='Monthly'){

system.debug('isnide Monthly if');
Payment_Schedule__c p=new Payment_Schedule__c();
p.Admission__c=o.id;
p.Due_Date__c=system.today().addDays(30*i);
p.Installment_Amount__c=o.Installments_Per_Month__c;
p.LOC__c=o.LOC__c;
p.Status__c='Active';
PaymentListUpdate.add(p);

}
}
if(modulo!=0){
Decimal residue=remainingAmount-iteration*o.Installments_Per_Month__c;           
Payment_Schedule__c p=new Payment_Schedule__c();

if(o.Payment_Frequency__c=='Daily'){
p.Due_Date__c=system.today().addDays(iteration1);  
}
if(o.Payment_Frequency__c=='Weekly'){
p.Due_Date__c=system.today().addDays(iteration1*7); 
}
if(o.Payment_Frequency__c=='Monthly'){
p.Due_Date__c=system.today().addDays(iteration1*30);   
}
p.Admission__c=o.id;
p.LOC__c=o.LOC__c;
p.Status__c='Active';
p.Installment_Amount__c=residue;
p.Plan_description__c='N/A';
PaymentListUpdate.add(p);
}
// system.debug('Payment Schedule'+PaymentListUpdate);
if(PaymentListUpdate.size()>0){
insert PaymentListUpdate;
}
}
} 
}*/
 }
    