force-app/main/default/objects/Account/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Formula to calculate the age of the account holder based on the birth date.</description>
    <formula>IF(
  MONTH(TODAY())&gt;MONTH(DOB__c),
    YEAR(TODAY())-YEAR(DOB__c),  
    IF(AND(MONTH(TODAY()) = MONTH(DOB__c), DAY(TODAY()) &gt;= DAY(DOB__c)), 
      YEAR(TODAY())-YEAR(DOB__c), 
      (YEAR(TODAY())-YEAR(DOB__c))-1)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Blood_Group__c.field-meta.xml
<CustomField>
    <fullName>Blood_Group__c</fullName>
    <description>Represents the blood group of the account holder.</description>
    <label>Blood Group</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DOB__c.field-meta.xml
<CustomField>
    <fullName>DOB__c</fullName>
    <description>Represents the date of birth of the account holder.</description>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Captures the birth sex or gender identity of the account holder.</description>
    <label>Birth Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Male</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>UNK</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MRN_Number__c.field-meta.xml
<CustomField>
    <fullName>MRN_Number__c</fullName>
    <description>Denotes the medical record number assigned to the account.</description>
    <label>MRN Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guarantor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Notes__c/Notes__c.object-meta.xml
<CustomObject>
    <label>Notes</label>
    <nameField>
        <displayFormat>NT-{0000}</displayFormat>
        <label>Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notes__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notes__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Notes__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Doctor Notes</fullName>
            </value>
            <value>
                <fullName>Nursing Notes</fullName>
            </value>
            <value>
                <fullName>Clinician Notes</fullName>
            </value>
            <value>
                <fullName>Session Notes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/Sample_Analysis__c.object-meta.xml
<CustomObject>
    <label>Sample Analysis</label>
    <nameField>
        <label>UA Analysis Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sample Analysis</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Analysis__c/fields/Appearance__c.field-meta.xml
<CustomField>
    <fullName>Appearance__c</fullName>
    <label>Appearance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Clear</fullName>
            </value>
            <value>
                <fullName>Hazy</fullName>
            </value>
            <value>
                <fullName>Cloudy</fullName>
            </value>
            <value>
                <fullName>Turbid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Picklist__c.field-meta.xml
<CustomField>
    <fullName>Picklist__c</fullName>
    <label>Picklist</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Colourless</fullName>
            </value>
            <value>
                <fullName>yellow</fullName>
            </value>
            <value>
                <fullName>Amber</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Specimen_Status__c.field-meta.xml
<CustomField>
    <fullName>Specimen_Status__c</fullName>
    <label>Specimen Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>Laboratory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/UA_Sample_Details__c.field-meta.xml
<CustomField>
    <fullName>UA_Sample_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UA Sample Details</label>
    <referenceTo>UA_Sample_Details__c</referenceTo>
    <relationshipLabel>Sample Analysis</relationshipLabel>
    <relationshipName>Sample_Analysis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/UA_Sample_Details__c.object-meta.xml
<CustomObject>
    <label>UA Sample Detail</label>
    <nameField>
        <displayFormat>Lab Order-{0000}</displayFormat>
        <label>Lab Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UA Sample Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/UA_Sample_Details__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>UA Sample Details</relationshipLabel>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Additives_if_Any__c.field-meta.xml
<CustomField>
    <fullName>Additives_if_Any__c</fullName>
    <label>Additives,if Any</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Collection_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Collection_Datetime__c</fullName>
    <label>Collection Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Container_Description__c.field-meta.xml
<CustomField>
    <fullName>Container_Description__c</fullName>
    <label>Container Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/ContainerSize__c.field-meta.xml
<CustomField>
    <fullName>ContainerSize__c</fullName>
    <label>ContainerSize</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/ContainerType__c.field-meta.xml
<CustomField>
    <fullName>ContainerType__c</fullName>
    <label>ContainerType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Lab_Code__c.field-meta.xml
<CustomField>
    <fullName>Lab_Code__c</fullName>
    <label>Lab Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Lab_email__c.field-meta.xml
<CustomField>
    <fullName>Lab_email__c</fullName>
    <label>Lab email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Lab_Location__c.field-meta.xml
<CustomField>
    <fullName>Lab_Location__c</fullName>
    <label>Lab Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Lab_Name__c.field-meta.xml
<CustomField>
    <fullName>Lab_Name__c</fullName>
    <label>Lab Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Name_of_container__c.field-meta.xml
<CustomField>
    <fullName>Name_of_container__c</fullName>
    <label>Name of container</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Order_By__c.field-meta.xml
<CustomField>
    <fullName>Order_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UA_Sample_Details1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Order_to__c.field-meta.xml
<CustomField>
    <fullName>Order_to__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order to</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Sample_Type__c.field-meta.xml
<CustomField>
    <fullName>Sample_Type__c</fullName>
    <label>Sample Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>Laboratory</fullName>
            </value>
            <value>
                <fullName>LabOrder</fullName>
                <isActive>false</isActive>
                <label>LabOrder</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Specimen_Collector__c.field-meta.xml
<CustomField>
    <fullName>Specimen_Collector__c</fullName>
    <label>Specimen Collector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Specimen_Condition__c.field-meta.xml
<CustomField>
    <fullName>Specimen_Condition__c</fullName>
    <label>Specimen Condition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Specimen_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Specimen_Quantity__c</fullName>
    <label>Specimen Quantity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Results Received</fullName>
            </value>
            <value>
                <fullName>Final Order</fullName>
            </value>
            <value>
                <fullName>Draft Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/UA_Sample_Details__c.field-meta.xml
<CustomField>
    <fullName>UA_Sample_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UA Sample Details</label>
    <referenceTo>UA_Sample_Details__c</referenceTo>
    <relationshipLabel>UA Sample Details</relationshipLabel>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ElixirHC_SampleAmalysisApexController.cls
public with sharing class ElixirHC_SampleAmalysisApexController {
    @AuraEnabled
    public static wrapper getAccountDetails(String accountId , String sampleId) {
        Wrapper wrpr = new Wrapper();
        List<String> picklistValues = new List<String>();
        Map<String,List<String>> mapOfNameToField = new  Map<String,List<String>>();
        Map<String, Schema.SObjectType> global_describe = Schema.getGlobalDescribe();
        Map<String, Schema.SObjectField> object_fields_map = global_describe.get('ElixirSuite__Sample_Analysis__c').getDescribe().fields.getMap();
        try{
        for(Schema.SObjectField sfield : object_fields_map.values()){
            Schema.DescribeFieldResult dfield = sfield.getDescribe();
            if(String.valueof(dfield.getType())=='PICKLIST'){
                picklistValues = new List<String>();
                for(Schema.PicklistEntry pickListVal : dfield.getPicklistValues()){
                    picklistValues.add(String.valueOf(pickListVal.getLabel()));
                }             
                mapOfNameToField.put(dfield.getName(),picklistValues);
            }
        }
        }
        catch(Exception e){
            ExceptionLog.logError(e);
        }
        wrpr.mapOfNameToField = mapOfNameToField;
        //HealthCloudGA__MedicalRecordNumber__c
        List<Account> listOfAccount = [SELECT Id, Name, Age__c, DOB__c, Gender__c,Blood_Group__c,MRN_Number__c FROM Account
         WHERE Id= :accountId WITH SECURITY_ENFORCED];
        Contact con=[select Id,name,birthdate from contact where AccountId=:listOfAccount[0].id 
        WITH SECURITY_ENFORCED limit 1];
                                      
        Integer age ;
        try{
          if(con.birthdate!=null){
                Date birthdate1=con.birthdate;
                Integer days = birthdate1.daysBetween(Date.Today());
                age = Integer.valueOf(days/365);
          }
        
        List<User> listOfUsers = [SELECT Id, Name FROM User WITH SECURITY_ENFORCED];
        List<UA_Sample_Details__c> listOfSampleDetails = [SELECT Name,Name_of_container__c,Sample_Type__c, ContainerType__c, Container_Description__c, 
                                                          ContainerSize__c, Specimen_Quantity__c, Specimen_Condition__c,
                                                          Additives_if_Any__c, Notes__c, Collection_Datetime__c, Specimen_Collector__c,
                                                          Order_to__c, Order_By__c, Lab_Name__c, Lab_Code__c, Lab_Location__c,
                                                          Lab_email__c, Account__c, Comments__c FROM UA_Sample_Details__c
                                                          WHERE Id= :sampleId AND Sample_Type__c = 'Physical' WITH SECURITY_ENFORCED];
        if(listOfSampleDetails!=null && listOfSampleDetails.size()>0 ){
            wrpr.sampleDetails = listOfSampleDetails[0];
            List<Sample_Analysis__c> listOfPhysiSampleAnalysis = [SELECT Id, Name,Specimen_Status__c, Picklist__c, Appearance__c,
                                                                  Notes__c, Status__c, Comments__c, Examined_By__c, Bilesalt__c,Yeast_Cells__c,
                                                                  Examined_Datetime__c, Specific_Gravity__c, PH__c, Leukocyte__c,Spermatozoa__c,
                                                                  Protein__c, Urobilinogen__c, Glucose__c, Puss_Cells_W_B_C__c,Epithelial_Cells__c, 
                                                                  Bilrubin__c, Red_Cells_R_B_C__c, Mucus__c, Casts__c, Crystal__c,Colour__c,Ketone__c,
                                                                  Bacteria__c, Trichomonas__c, Schistosoma_Eggs__c, Type__c FROM Sample_Analysis__c
                                                                  WHERE UA_Sample_Details__c= :listOfSampleDetails[0].Id WITH SECURITY_ENFORCED]; 
            if(listOfPhysiSampleAnalysis!=null && listOfPhysiSampleAnalysis.size()>0 ){
                wrpr.physicalSampleAnalysis = listOfPhysiSampleAnalysis[0]; 
                List<UA_Sample_Details__c> listOfLabSampleDetails = [SELECT Sample_Type__c, Name_of_container__c,ContainerType__c, Container_Description__c, 
                                                                     ContainerSize__c, Specimen_Quantity__c, Specimen_Condition__c,UA_Sample_Details__c,
                                                                     Additives_if_Any__c, Notes__c, Collection_Datetime__c, Specimen_Collector__c,
                                                                     Order_to__c, Order_By__c, Lab_Name__c, Lab_Code__c, Lab_Location__c,
                                                                     Lab_email__c, Account__c, Comments__c FROM UA_Sample_Details__c
                                                                     WHERE UA_Sample_Details__c= :sampleId AND Sample_Type__c = 'Laboratory' WITH SECURITY_ENFORCED];
                if(listOfLabSampleDetails!=null && listOfLabSampleDetails.size()>0 ){
                    wrpr.labDetails = listOfLabSampleDetails[0];
                    List<Sample_Analysis__c> labAnalysis = [SELECT Id, Name, Specimen_Status__c, Picklist__c, Appearance__c,
                                                            Notes__c, Status__c, Comments__c, Examined_By__c, Bilesalt__c,Yeast_Cells__c,
                                                            Examined_Datetime__c, Specific_Gravity__c, PH__c, Leukocyte__c,Spermatozoa__c,
                                                            Protein__c, Urobilinogen__c, Glucose__c, Puss_Cells_W_B_C__c,Epithelial_Cells__c,Ketone__c, 
                                                            Bilrubin__c, Red_Cells_R_B_C__c, Mucus__c, Casts__c, Crystal__c,Colour__c,
                                                            Bacteria__c, Trichomonas__c, Schistosoma_Eggs__c, Type__c, Lab_Sample_Examined_Datetime__c FROM Sample_Analysis__c
                                                            WHERE UA_Sample_Details__c= :listOfLabSampleDetails[0].Id WITH SECURITY_ENFORCED]; 
                    if(labAnalysis!=null && labAnalysis.size()>0){
                        wrpr.labAnalysis = labAnalysis[0];
                    }    
                }                                      
                
            }                              
        }                               
        
        wrpr.accountRec = listOfAccount[0];
        wrpr.listOfUsers = listOfUsers;
        wrpr.patientAge = age ;
        wrpr.patientBirthdate = con.Birthdate ;
        wrpr.nameSpace = Elixir_Utility.getNamespace();
        }
        catch(Exception e){
            ExceptionLog.logError(e);
        }
        return wrpr;
    }
    @AuraEnabled
    public static void saveDetails(Sample_Analysis__c physicalSampleAnalysis ,UA_Sample_Details__c labDetails ,
                                   Sample_Analysis__c labSampleAnalysis,String patientId,String emailOutSectionIdentifier,
                                   String stringifiedPhysicalSample,String stringifiedLabSample){
                                       try{
                                       if(physicalSampleAnalysis != null){
                                           DMLManager.upsertAsUser(physicalSampleAnalysis);   
                                       }
                                       if(labDetails != null){
                                           DMLManager.upsertAsUser(labDetails);
                                       }
                                       if(labSampleAnalysis != null){
                                           DMLManager.upsertAsUser(labSampleAnalysis);
                                       }
                                       if(emailOutSectionIdentifier=='PhysicalSampleAnalysis'){
                                           if(!String.isBlank(physicalSampleAnalysis.Id)) {
                                               if(physicalSampleAnalysis.Status__c=='Positive'){
                                                   ElixirHC_UAListViewController.sendPdfForUA('PhysicalAnalysis',physicalSampleAnalysis.Id,patientId,stringifiedPhysicalSample);
                                               }
                                           }
                                           
                                       }
                                       if(emailOutSectionIdentifier=='LabSampleAnalysis'){
                                           if(!String.isBlank(labSampleAnalysis.Id)) {
                                               if(labSampleAnalysis.Status__c=='Positive'){
                                                   ElixirHC_UAListViewController.sendPdfForUA('LabSampleAnalysis',labSampleAnalysis.Id,patientId,stringifiedLabSample);
                                               }
                                           }
                                       }
                                       
                                       
                                   }
                                       catch(Exception e){
                                     ExceptionLog.logError(e);
                                                }
                                   }
    public class wrapper{
        @AuraEnabled public Account accountRec;
        @AuraEnabled public UA_Sample_Details__c sampleDetails;
        @AuraEnabled public UA_Sample_Details__c labDetails;
        @AuraEnabled public Sample_Analysis__c physicalSampleAnalysis;
        @AuraEnabled public Sample_Analysis__c labAnalysis;
        @AuraEnabled public List<User> listOfUsers;
        @AuraEnabled public Map<String,List<String>> mapOfNameToField ;
        @AuraEnabled public integer patientAge ;
        @AuraEnabled public date patientBirthdate ;
        @AuraEnabled public String nameSpace ;
    }
}