force-app/main/default/objects/Account/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Formula to calculate the age of the account holder based on the birth date.</description>
    <formula>IF(
  MONTH(TODAY())&gt;MONTH(DOB__c),
    YEAR(TODAY())-YEAR(DOB__c),  
    IF(AND(MONTH(TODAY()) = MONTH(DOB__c), DAY(TODAY()) &gt;= DAY(DOB__c)), 
      YEAR(TODAY())-YEAR(DOB__c), 
      (YEAR(TODAY())-YEAR(DOB__c))-1)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Blood_Group__c.field-meta.xml
<CustomField>
    <fullName>Blood_Group__c</fullName>
    <description>Represents the blood group of the account holder.</description>
    <label>Blood Group</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DOB__c.field-meta.xml
<CustomField>
    <fullName>DOB__c</fullName>
    <description>Represents the date of birth of the account holder.</description>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Captures the birth sex or gender identity of the account holder.</description>
    <label>Birth Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Male</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>UNK</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/UA_Sample_Details__c/UA_Sample_Details__c.object-meta.xml
<CustomObject>
    <label>UA Sample Detail</label>
    <nameField>
        <displayFormat>Lab Order-{0000}</displayFormat>
        <label>Lab Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UA Sample Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/UA_Sample_Details__c/fields/Order_to__c.field-meta.xml
<CustomField>
    <fullName>Order_to__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order to</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/UA_Sample_Details__c.field-meta.xml
<CustomField>
    <fullName>UA_Sample_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UA Sample Details</label>
    <referenceTo>UA_Sample_Details__c</referenceTo>
    <relationshipLabel>UA Sample Details</relationshipLabel>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ElixirHC_UAanalysisApexConroller.cls
public with sharing class ElixirHC_UAanalysisApexConroller {
    @AuraEnabled
    public static Wrapper getAccountDetails(String accountId) {
        //Medical Record Number is Removed because it is Health Cloud field
        List<Account> listOfAccount = [SELECT Id, Name, Age__c, DOB__c, Gender__c,Blood_Group__c,elixirsuite__mrn_number_new__c 
                                       FROM Account WHERE Id= :accountId WITH SECURITY_ENFORCED];
        Contact con=[select Id,name,birthdate from contact where AccountId=:listOfAccount[0].id WITH SECURITY_ENFORCED limit 1];
                                       Wrapper wrpr = new Wrapper();
        Integer age ;
        try{
          if(con.birthdate!=null){
                Date birthdate1=con.birthdate;
                Integer days = birthdate1.daysBetween(Date.Today());
                age = Integer.valueOf(days/365);
          }
        
        List<User> listOfUsers = [SELECT Id, Name FROM User WITH SECURITY_ENFORCED];
        wrpr.accountRec = listOfAccount[0];
        wrpr.listOfUsers = listOfUsers;
        wrpr.patientAge = age ;
        wrpr.patientBirthdate = con.Birthdate ;
        wrpr.nameSpace = Elixir_Utility.getNamespace();
        }
        catch(Exception e){
            ExceptionLog.logError(e);
        }
        return wrpr;
    }
    @AuraEnabled
    public static Boolean savePhysicalDetail(UA_Sample_Details__c dataToSave) {
        Id recordTypeIdAsFetched = Schema.SObjectType.UA_Sample_Details__c.getRecordTypeInfosByName().get('Urine Analysis').getRecordTypeId();
        dataToSave.RecordTypeId = recordTypeIdAsFetched;
        mDebugUntruncated(String.valueOf(dataToSave));
        Boolean getEmailValidationValue = false;
        try{
        if(dataToSave != null){           
            DMLManager.upsertAsUser(dataToSave);
             getEmailValidationValue  =  ElixirHC_UAListViewController.sendEmailNotificationToUAMember(dataToSave.Order_to__c,dataToSave.id);
        }
        }
        catch(Exception e){
            ExceptionLog.logError(e);
        }
        return getEmailValidationValue;
    }
    public static void mDebugUntruncated(String sMsg) {
    for (Integer i = 0; i < sMsg.length(); i=i+300) {
        Integer iEffectiveEnd = (i+300 > (sMsg.length()-1) ? sMsg.length()-1 : i+300);
        
    }
}
    public class Wrapper{
        @AuraEnabled public Account accountRec;
        @AuraEnabled public List<User> listOfUsers;
        @AuraEnabled public integer patientAge ;
        @AuraEnabled public date patientBirthdate ;
        @AuraEnabled public String nameSpace;
    }
}