force-app/main/default/objects/Account/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Formula to calculate the age of the account holder based on the birth date.</description>
    <formula>IF(
  MONTH(TODAY())&gt;MONTH(DOB__c),
    YEAR(TODAY())-YEAR(DOB__c),  
    IF(AND(MONTH(TODAY()) = MONTH(DOB__c), DAY(TODAY()) &gt;= DAY(DOB__c)), 
      YEAR(TODAY())-YEAR(DOB__c), 
      (YEAR(TODAY())-YEAR(DOB__c))-1)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DOB__c.field-meta.xml
<CustomField>
    <fullName>DOB__c</fullName>
    <description>Represents the date of birth of the account holder.</description>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Frequency__c/Frequency__c.object-meta.xml
<CustomObject>
    <label>Frequency</label>
    <nameField>
        <displayFormat>Frequency-{0000}</displayFormat>
        <label>Frequency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Frequency</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab__c/Lab__c.object-meta.xml
<CustomObject>
    <label>Lab</label>
    <nameField>
        <label>Lab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Labs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UA_Sample_Details__c/UA_Sample_Details__c.object-meta.xml
<CustomObject>
    <label>UA Sample Detail</label>
    <nameField>
        <displayFormat>Lab Order-{0000}</displayFormat>
        <label>Lab Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UA Sample Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/UA_Sample_Details__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>UA Sample Details</relationshipLabel>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Once</fullName>
                <default>true</default>
                <label>Once</label>
            </value>
            <value>
                <fullName>Every Day</fullName>
            </value>
            <value>
                <fullName>Every 2 Days</fullName>
            </value>
            <value>
                <fullName>Every 3 Days</fullName>
            </value>
            <value>
                <fullName>Every 5 Days</fullName>
            </value>
            <value>
                <fullName>Every 7 Days</fullName>
            </value>
            <value>
                <fullName>Every 2 weeks</fullName>
            </value>
            <value>
                <fullName>Once a month</fullName>
            </value>
            <value>
                <fullName>On return from pass or outing</fullName>
            </value>
            <value>
                <fullName>When attending IOP/OP group</fullName>
            </value>
            <value>
                <fullName>Confirm positive analyzer results</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Lab__c.field-meta.xml
<CustomField>
    <fullName>Lab__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lab</label>
    <referenceTo>Lab__c</referenceTo>
    <relationshipLabel>UA Sample Details</relationshipLabel>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Medical_Test__c.field-meta.xml
<CustomField>
    <fullName>Medical_Test__c</fullName>
    <label>Medical Test</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Necessity_Details__c.field-meta.xml
<CustomField>
    <fullName>Necessity_Details__c</fullName>
    <label>Necessity Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/On_Admission__c.field-meta.xml
<CustomField>
    <fullName>On_Admission__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Admission</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Order_By__c.field-meta.xml
<CustomField>
    <fullName>Order_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UA_Sample_Details1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Ordered_By__c.field-meta.xml
<CustomField>
    <fullName>Ordered_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordered By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EHR_Procedure_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Ordered_Via__c.field-meta.xml
<CustomField>
    <fullName>Ordered_Via__c</fullName>
    <label>Ordered Via</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Phone, read back and verified</fullName>
            </value>
            <value>
                <fullName>Verbal, read back and verified</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
            <value>
                <fullName>Previously prescribed medication approved by doctor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Signature_Comments__c.field-meta.xml
<CustomField>
    <fullName>Signature_Comments__c</fullName>
    <label>Signature Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Signature_Link__c.field-meta.xml
<CustomField>
    <fullName>Signature_Link__c</fullName>
    <label>Signature Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>Signed_Date__c</fullName>
    <label>Signed Date</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Results Received</fullName>
            </value>
            <value>
                <fullName>Final Order</fullName>
            </value>
            <value>
                <fullName>Draft Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/UA_Sample_Details__c.field-meta.xml
<CustomField>
    <fullName>UA_Sample_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UA Sample Details</label>
    <referenceTo>UA_Sample_Details__c</referenceTo>
    <relationshipLabel>UA Sample Details</relationshipLabel>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object is used to track every single visit or encounter for a patient.</description>
    <label>Care Episode</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visits__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents the relationship b/w Patient and Care Episode.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Care Episodes</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visits__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field denotes the status of the care episode.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DataDisplayController.cls
public with sharing class DataDisplayController {
    // Test class name : DataDisplayControllerTest
    public UA_Sample_Details__c labOrder {get;set;}
    public Account accounts {get;set;}
	public static  Contact contacts {get;set;}
    public static Integer age{get;set;}
    public String PDFData {get;set;} 
    public String approvalString {get;set;}
   
    public DataDisplayController(){
        approvalString = '/servlet/servlet.FileDownload?file=';
        String orderId = ApexPages.currentPage().getParameters().get('orderId').escapeHtml4();
         System.debug('orderId---' + orderId);    
        getlabOrderInfo(orderId);
      //  Apexpages.currentPage().getHeaders().put('content-disposition', 'attachment; filename=Laborder'+labOrder.Name +'.pdf');
              
    }
   
    public  void getlabOrderInfo(Id orderId){    
       System.debug('list answer '+orderId);
        List<UA_Sample_Details__c> orderList = [select Id,Name,Order_By__r.name,Medical_Test__c,Fax__c,Ordered_Via__c,Signature_Comments__c,Signed_Date__c, Signature_Link__c,Status__c,
                                                                 Account__r.Name ,Ordered_By__c,Ordered_By__r.Name,Frequency__c,Necessity_Details__c,On_Admission__c,Account__c,Start_Date__c
                                                                 from UA_Sample_Details__c  where id=:orderId
                                                                 WITH SECURITY_ENFORCED] ;
        
        System.debug('list answer '+orderList[0].On_Admission__c);
        labOrder = orderList[0];
        //getSampleInfo(orderId);
       // getLabInfo(labOrder.Lab__c);
        getAccountInfo(labOrder.Account__c);
    }
    public  void getAccountInfo(Id accountId){
        try{
        List<Account> accountList = [select Id, name, Age__c,DOB__c from account where id=:accountId
        WITH SECURITY_ENFORCED];
         List<Contact> con=[select Id,name,birthdate from contact where AccountId=:accountId  
         WITH SECURITY_ENFORCED limit 1];
        system.debug('djd' + accountList);
        accounts = accountList.get(0);
        contacts = con.get(0);
        if(con[0].birthdate!=null){
                Integer days = con[0].birthdate.daysBetween(Date.Today());
                age = Integer.valueOf(days/365);
        }
        }
        catch(Exception e){
            ExceptionLog.logError(e);
        }
    }
   

	
}