force-app/main/default/objects/Account/fields/Bed__c.field-meta.xml
<CustomField>
    <fullName>Bed__c</fullName>
    <description>This field is used to associate the account with a specific bed.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bed</label>
    <referenceTo>Bed__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Reservation__c.field-meta.xml
<CustomField>
    <fullName>Reservation__c</fullName>
    <description>This field is used to associate the reservation with the account.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reservation ID</label>
    <referenceTo>Reservation__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bed__c/Bed__c.object-meta.xml
<CustomObject>
    <label>Bed</label>
    <nameField>
        <displayFormat>BD{0000}</displayFormat>
        <label>Bed Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bed__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <label>Room ID</label>
    <referenceTo>Rooms__c</referenceTo>
    <relationshipLabel>Beds</relationshipLabel>
    <relationshipName>Beds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Location stores all the Master Data related to the reservations. It can hold building, suite, room and bed separated by record types.</description>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Building</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Suite__c.field-meta.xml
<CustomField>
    <fullName>Suite__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Building</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Procedure__c/Procedure__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the template procedures in the system. These might include lab order, medications, CPT codes, Appointment procedures.</description>
    <label>Procedure Codes</label>
    <nameField>
        <label>Code Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedure Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Procedure__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Procedures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/Charges__c.field-meta.xml
<CustomField>
    <fullName>Charges__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Charges ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/From_Date_of_Service__c.field-meta.xml
<CustomField>
    <fullName>From_Date_of_Service__c</fullName>
    <label>From Date of Service</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>Is_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Procedure Codes (Location)</relationshipLabel>
    <relationshipName>Procedure_Codes3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/Reservation_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reservation Line Item</label>
    <referenceTo>Reservation_Line_Item__c</referenceTo>
    <relationshipLabel>Procedure</relationshipLabel>
    <relationshipName>Procedure_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/To_Date_of_Service__c.field-meta.xml
<CustomField>
    <fullName>To_Date_of_Service__c</fullName>
    <label>To Date of Service</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/Type_of_Procedure__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Procedure__c</fullName>
    <label>Type of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Private Payment</fullName>
            </value>
            <value>
                <fullName>Insurance Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Procedure__c/recordTypes/Patient_Procedure.recordType-meta.xml
<RecordType>
    <fullName>Patient_Procedure</fullName>
    <active>true</active>
    <label>Patient Procedure</label>
</RecordType>

force-app/main/default/objects/Procedure__c/recordTypes/Template_Procedure.recordType-meta.xml
<RecordType>
    <fullName>Template_Procedure</fullName>
    <active>true</active>
    <label>Template Procedure</label>
</RecordType>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Reservation stores all the transactional reservations related to the patients.</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Reservation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>primary patient to book the reservation</description>
    <label>Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Stores the End time of a reservation.</description>
    <label>End Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Stores the Start time of a reservation.</description>
    <label>Start Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Reservation_Line_Item__c/Reservation_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Reservation Line Item stores the bed level record related to a reservation. Patient is assigned on a bed using this record.</description>
    <label>Reservation Line Item</label>
    <nameField>
        <displayFormat>RLI-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservation Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation_Line_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>used to allocate patient on a bed</description>
    <label>Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reservation Line Items</relationshipLabel>
    <relationshipName>Reservation_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation_Line_Item__c/fields/Bed__c.field-meta.xml
<CustomField>
    <fullName>Bed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the bed for line item.</description>
    <label>Bed</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Reservation Line Items (Bed)</relationshipLabel>
    <relationshipName>Reservation_Line_Items3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation_Line_Item__c/fields/Bed_Status__c.field-meta.xml
<CustomField>
    <fullName>Bed_Status__c</fullName>
    <description>Status related to Bed will be update here based on the parent reservation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reservation_Line_Item__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>This field is used to store end time of a line item.</description>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Reservation_Line_Item__c/fields/isBillable__c.field-meta.xml
<CustomField>
    <fullName>isBillable__c</fullName>
    <description>Used to tell if the line item is the top level billable entity.</description>
    <label>isBillable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>False</fullName>
                <default>true</default>
                <label>False</label>
            </value>
            <value>
                <fullName>True</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reservation_Line_Item__c/fields/Reservation__c.field-meta.xml
<CustomField>
    <fullName>Reservation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reservation lookup to interlink the line items with reservation</description>
    <label>Reservation</label>
    <referenceTo>Reservation__c</referenceTo>
    <relationshipLabel>Reservation Line Items</relationshipLabel>
    <relationshipName>Reservation_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation_Line_Item__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the Room for line item</description>
    <label>Room</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Reservation Line Items (Room)</relationshipLabel>
    <relationshipName>Reservation_Line_Items2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation_Line_Item__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>stores the start time of line item</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Reservation_Line_Item__c/fields/Suite__c.field-meta.xml
<CustomField>
    <fullName>Suite__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to store the suite for line item.</description>
    <label>Suite</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Reservation Line Items (Suite)</relationshipLabel>
    <relationshipName>Reservation_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation_Line_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <description>The actual/contractual price selected on review reservation screen will be saved in this field.</description>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ReservationProcedureCreation_Batch.cls
public with sharing class ReservationProcedureCreation_Batch implements Database.Batchable<sObject> {
    
    public String lineItemQuery;
    public Date dateFilter;
    public List<String> statusFilter;
    public String isBillable;
    
    
    public ReservationProcedureCreation_Batch(){
        dateFilter  = System.today();
        String reservationStatus = System.Label.ReservationStatus;
        statusFilter = reservationStatus.split(',');
        isBillable = 'True';   
        lineItemQuery = 'SELECT Id, Name, Suite__c, Room__c, Bed__c, Reservation__c, Unit_Price__c, Reservation__r.Account__c FROM Reservation_line_item__c WHERE isBillable__c =: isBillable AND Bed_Status__c IN: statusFilter AND DAY_ONLY(Start_Date__c)<=: dateFilter AND DAY_ONLY(End_Date__c)>=: dateFilter ';
    }
    
    public ReservationProcedureCreation_Batch(Date customDateTime){
        dateFilter = customDateTime;
        String reservationStatus = System.Label.ReservationStatus;
        statusFilter = reservationStatus.split(',');
        isBillable = 'True';
        
        lineItemQuery = 'SELECT Id, Name, Suite__c, Room__c, Bed__c, Reservation__c, Unit_Price__c, Reservation__r.Account__c FROM Reservation_line_item__c WHERE isBillable__c =: isBillable AND Bed_Status__c IN: statusFilter AND DAY_ONLY(Start_Date__c)<=: dateFilter AND DAY_ONLY(End_Date__c)>=: dateFilter ';
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(lineItemQuery);
    }
    
    public void execute(Database.BatchableContext bc, List<ElixirSuite__Reservation_line_item__c> lineItems){
        
        Set<Id> reservationIds = new Set<Id>();
        Set<Id> locationIds = new Set<Id>();
        Set<Id> accIds = new Set<Id>();
        //Map<Id, Procedure__c> accountToProcedure = new Map<Id, Procedure__c>(); //Map to check patient procedure of that account
        Map<Id, Set<Id>> accountToProcedure = new Map<Id, Set<Id>>(); //Map to check patient procedure of that account
        for(ElixirSuite__Reservation_line_item__c item : lineItems){
            reservationIds.add(item.Reservation__c);
            accIds.add(item.Reservation__r.Account__c);
            if(item.Suite__c != null){
                locationIds.add(item.Suite__c);
            }
            if(item.Room__c != null){
                locationIds.add(item.Room__c);                    
            }
            if(item.Bed__c != null){
                locationIds.add(item.Bed__c);                   
            }
        }
        Id recordTypId = Schema.SObjectType.ElixirSuite__Procedure__c.getRecordTypeInfosByDeveloperName().get('Template_Procedure').getRecordTypeId();
        List<ElixirSuite__Procedure__c> procedureOfLocation = [SELECT Id, Name,Type_of_Procedure__c, ElixirSuite__Location__r.Name, ElixirSuite__Location__r.Id FROM ElixirSuite__Procedure__c WHERE ElixirSuite__Location__r.Id IN: locationIds AND RecordTypeId =: recordTypId WITH SECURITY_ENFORCED];
        
        Map<String, String> locationToName = new Map<String, String>();
        Map<String, String> locationToProcedureType = new Map<String, String>(); //addded by sivasai
        for(ElixirSuite__Procedure__c pro : procedureOfLocation){
            locationToName.put(pro.ElixirSuite__Location__r.Id, pro.Name);
            locationToProcedureType.put(pro.ElixirSuite__Location__r.Id, pro.Type_of_Procedure__c);
        }
        
        Id recordTypeId = Schema.SObjectType.ElixirSuite__Procedure__c.getRecordTypeInfosByDeveloperName().get('Patient_Procedure').getRecordTypeId();
        
        List<Procedure__c> todaysProcedures = [SELECT Id, Name, Account__c, Location__c 
                                               FROM Procedure__c
                                               WHERE Account__c IN: accIds AND DAY_ONLY(CreatedDate) =: dateFilter
                                               AND Location__c!=NULL
                                               WITH SECURITY_ENFORCED];
        Set<String> locations = new Set<String>();
        
        if(todaysProcedures!=null && todaysProcedures.size()>0){
            for(Procedure__c procedure : todaysProcedures){
                if(accountToProcedure.containsKey(procedure.Account__c)){
                    accountToProcedure.get(procedure.Account__c).add(procedure.location__c);
                }else{
                    accountToProcedure.put(procedure.Account__c, new Set<Id>{procedure.location__c});
                }         
            }
        }        
        
        List<ElixirSuite__Procedure__c> procedureList = new List<ElixirSuite__Procedure__c>();
        for(ElixirSuite__Reservation_line_item__c item : lineItems){
            String patientId = item.Reservation__r.Account__c;
            if(accountToProcedure!=null && accountToProcedure.containsKey(patientId))
            {
                Set<Id> proceduredLocations = accountToProcedure.get(item.Reservation__r.Account__c);
                if(item.Suite__c != null && proceduredLocations.contains(item.Suite__c)){
                    continue;
                }
                if(item.Room__c != null && proceduredLocations.contains(item.Room__c)){
                    continue;                     
                }
                if(item.Bed__c != null  && proceduredLocations.contains(item.Bed__c)){
                    continue;                   
                }
            }
            else{
                ElixirSuite__Procedure__c procedure = new ElixirSuite__Procedure__c();
                procedure.RecordTypeId = recordTypeId;
                procedure.Account__c = patientId;
                if(item.Id != null){
                procedure.ElixirSuite__Reservation_Line_Item__c = item.Id; 
                }
                if(item.Suite__c != null){
                    procedure.Location__c = item.Suite__c;
                    procedure.Name = locationToName.get(item.Suite__c);
                    procedure.Type_of_Procedure__c =locationToProcedureType.get(item.Suite__c);
                }
                if(item.Room__c != null){
                    procedure.Location__c = item.Room__c;
                    procedure.Name = locationToName.get(item.Room__c);
                    procedure.Type_of_Procedure__c =locationToProcedureType.get(item.Room__c);                    
                }
                if(item.Bed__c != null){
                    procedure.Location__c = item.Bed__c;
                    procedure.Name = locationToName.get(item.Bed__c);
                    procedure.Type_of_Procedure__c =locationToProcedureType.get(item.Bed__c);                   
                }
                procedure.Charges__c = item.Unit_Price__c;
                procedure.From_Date_of_Service__c = System.now();
                procedure.To_Date_of_Service__c = System.now(); 
                //procedure.Type_of_Procedure__c = 'Private Payment';
                procedure.Is_Billable__c = true;
                procedureList.add(procedure);
            }
            
        }
        if(procedureList.size()>0){
           // insert procedureList;
           DMLManager.insertAsUser(procedureList);
            }        
    }
    
    public void finish(Database.BatchableContext bc) {}
}