force-app/main/default/objects/Account/fields/Blood_Group__c.field-meta.xml
<CustomField>
    <fullName>Blood_Group__c</fullName>
    <description>Represents the blood group of the account holder.</description>
    <label>Blood Group</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DOB__c.field-meta.xml
<CustomField>
    <fullName>DOB__c</fullName>
    <description>Represents the date of birth of the account holder.</description>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Captures the birth sex or gender identity of the account holder.</description>
    <label>Birth Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Male</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>UNK</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Notes__c/Notes__c.object-meta.xml
<CustomObject>
    <label>Notes</label>
    <nameField>
        <displayFormat>NT-{0000}</displayFormat>
        <label>Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notes__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notes__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/Sample_Analysis__c.object-meta.xml
<CustomObject>
    <label>Sample Analysis</label>
    <nameField>
        <label>UA Analysis Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sample Analysis</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Analysis__c/fields/Appearance__c.field-meta.xml
<CustomField>
    <fullName>Appearance__c</fullName>
    <label>Appearance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Clear</fullName>
            </value>
            <value>
                <fullName>Hazy</fullName>
            </value>
            <value>
                <fullName>Cloudy</fullName>
            </value>
            <value>
                <fullName>Turbid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Colour__c.field-meta.xml
<CustomField>
    <fullName>Colour__c</fullName>
    <label>Colour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Colourless</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Amber</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Examined_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Examined_Datetime__c</fullName>
    <label>Examined Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Specimen_Status__c.field-meta.xml
<CustomField>
    <fullName>Specimen_Status__c</fullName>
    <label>Specimen Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/UA_Sample_Details__c.field-meta.xml
<CustomField>
    <fullName>UA_Sample_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UA Sample Details</label>
    <referenceTo>UA_Sample_Details__c</referenceTo>
    <relationshipLabel>Sample Analysis</relationshipLabel>
    <relationshipName>Sample_Analysis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/UA_Sample_Details__c.object-meta.xml
<CustomObject>
    <label>UA Sample Detail</label>
    <nameField>
        <displayFormat>Lab Order-{0000}</displayFormat>
        <label>Lab Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UA Sample Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/UA_Sample_Details__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>UA Sample Details</relationshipLabel>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Additives_if_Any__c.field-meta.xml
<CustomField>
    <fullName>Additives_if_Any__c</fullName>
    <label>Additives,if Any</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Collection_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Collection_Datetime__c</fullName>
    <label>Collection Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Container_Description__c.field-meta.xml
<CustomField>
    <fullName>Container_Description__c</fullName>
    <label>Container Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/ContainerSize__c.field-meta.xml
<CustomField>
    <fullName>ContainerSize__c</fullName>
    <label>ContainerSize</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/ContainerType__c.field-meta.xml
<CustomField>
    <fullName>ContainerType__c</fullName>
    <label>ContainerType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Sample_Type__c.field-meta.xml
<CustomField>
    <fullName>Sample_Type__c</fullName>
    <label>Sample Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>Laboratory</fullName>
            </value>
            <value>
                <fullName>LabOrder</fullName>
                <isActive>false</isActive>
                <label>LabOrder</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Specimen_Collector__c.field-meta.xml
<CustomField>
    <fullName>Specimen_Collector__c</fullName>
    <label>Specimen Collector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Specimen_Condition__c.field-meta.xml
<CustomField>
    <fullName>Specimen_Condition__c</fullName>
    <label>Specimen Condition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Specimen_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Specimen_Quantity__c</fullName>
    <label>Specimen Quantity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Results Received</fullName>
            </value>
            <value>
                <fullName>Final Order</fullName>
            </value>
            <value>
                <fullName>Draft Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/UA_Sample_Details__c.field-meta.xml
<CustomField>
    <fullName>UA_Sample_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UA Sample Details</label>
    <referenceTo>UA_Sample_Details__c</referenceTo>
    <relationshipLabel>UA Sample Details</relationshipLabel>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestElixirHC_SampleAmalysisController.cls
@isTest
public class TestElixirHC_SampleAmalysisController {
    
    public  static testMethod void allCoverageParentMethod(){
        
        Account forIns = new Account();
        forIns.Name='Test Demo';
        forIns.DOB__c= System.today();
        forIns.Gender__c = 'Male';
        forIns.Blood_Group__c = 'O+';
        insert forIns;
        
        Contact c = new Contact(LastName='RSB', AccountId = forIns.Id);
        insert c;
        
        List<User> getEmail  = [select id,email from user LIMIT 1];
        UA_Sample_Details__c ua = new UA_Sample_Details__c();
        ua.Sample_Type__c='Physical';
        ua.ContainerType__c='Test';
        ua.Container_Description__c='Des';
        ua.ContainerSize__c='Test';
        ua.Specimen_Quantity__c= 'Test';
        ua.Additives_if_Any__c = 'Test';
        ua.Specimen_Condition__c = 'Test';
        ua.Notes__c= 'Test';
        ua.Status__c = 'Open';
        ua.Collection_Datetime__c = System.now();
        ua.Specimen_Collector__c='Test';
        ua.Account__c = forIns.id;
        insert ua;
        
        Sample_Analysis__c sa  = new Sample_Analysis__c();
        //sa.Account__c  = forIns.Id;
        sa.Appearance__c = 'Clear';
        sa.Colour__c = 'Colourless';
        sa.Comments__c = 'Cooments';
        sa.Examined_Datetime__c = System.now();
        sa.Notes__c = 'Notes';
        sa.Specimen_Status__c = 'Active';
        sa.Status__c = 'Positive';
        sa.UA_Sample_Details__c = ua.Id;
        insert sa;
        
        Test.startTest();
        ElixirHC_SampleAmalysisApexController.getAccountDetails(forIns.Id,ua.Id);
        ElixirHC_SampleAmalysisApexController.saveDetails(sa,ua,sa,forIns.Id,'PhysicalSampleAnalysis','','');
        Test.stopTest();
        System.assertEquals(1, 1, ' ');
        
    }
    public class wrapper{
        public Account accountRec;
        public UA_Sample_Details__c sampleDetails;
        public UA_Sample_Details__c labDetails;
        public Sample_Analysis__c physicalSampleAnalysis;
        public Sample_Analysis__c labAnalysis;
        public List<User> listOfUsers;
        public Map<String,List<String>> mapOfNameToField ;
    }
}