force-app/main/default/objects/Account/fields/DOB__c.field-meta.xml
<CustomField>
    <fullName>DOB__c</fullName>
    <description>Represents the date of birth of the account holder.</description>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DOB__c.field-meta.xml
<CustomField>
    <fullName>DOB__c</fullName>
    <inlineHelpText>Client&apos;s Date of Birth</inlineHelpText>
    <label>DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Pre_assessment__c/Pre_assessment__c.object-meta.xml
<CustomObject>
    <label>Pre Assessment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Pre-Asessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Pre_assessment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to record the full name of the patient.</description>
    <inlineHelpText>If You Choose Patient Name than &quot;DOB,Subscriber DOB,Phone,Policy Subscriber Name&quot; will auto fill after save of record</inlineHelpText>
    <label>Name of Patient</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Pre Assessments</relationshipLabel>
    <relationshipName>Pre_assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pre_assessment__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>This field is used to record the phone number of the patient.</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/testInsertPreAssessment.cls
@istest
public class testInsertPreAssessment {
    @istest
    public static void InsertPreAssessment()
    {
        test.startTest();
        Account a=new Account();
        a.Name='test';
        insert a;
        
        Opportunity o=new Opportunity();
        o.Name='a';
        o.AccountId=a.id;
        o.StageName='Prospecting';
        o.CloseDate=Date.today();
        o.Phone__c='123456';
        o.DOB__c= Date.today();
        insert o;
        
        Pre_assessment__c p=new Pre_assessment__c();
        p.Opportunity__c= o.Id;
        insert p;
        
        InsertPreAssessment.InsertPreAssessmentid(o.id);
        test.stopTest();
        System.assertEquals(1, 1, ' ');
    }

}