force-app/main/default/objects/Account/fields/DOB__c.field-meta.xml
<CustomField>
    <fullName>DOB__c</fullName>
    <description>Represents the date of birth of the account holder.</description>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <description>Represents the email address associated with the account.</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Represents the first name of the account holder.</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Captures the birth sex or gender identity of the account holder.</description>
    <label>Birth Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Male</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>UNK</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Represents the last name of the account holder.</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Patient_s_Birth_Date__c.field-meta.xml
<CustomField>
    <fullName>Patient_s_Birth_Date__c</fullName>
    <description>Denotes the date of birth of the patient.</description>
    <label>Patient DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description>Represents the Social Security Number (SSN) associated with the account.</description>
    <label>SSN</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Elixir_Custom_Setting__c/Elixir_Custom_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Elixir Custom Setting</label>
</CustomObject>

force-app/main/default/objects/Elixir_Custom_Setting__c/fields/Elixir_portal_url__c.field-meta.xml
<CustomField>
    <fullName>Elixir_portal_url__c</fullName>
    <label>Elixir portal url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Elixir_Custom_Setting__c/fields/Lab_Order__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Lab Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Test</label>
    <nameField>
        <displayFormat>LabOrder-{0000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Order_result_received__c.field-meta.xml
<CustomField>
    <fullName>Order_result_received__c</fullName>
    <label>Order result received</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>E</fullName>
                <label>Entered</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Transmitted</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Results Received (Partial)</fullName>
            </value>
            <value>
                <fullName>Results Received</fullName>
            </value>
            <value>
                <fullName>Final Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab_Order__c/recordTypes/eLab.recordType-meta.xml
<RecordType>
    <fullName>eLab</fullName>
    <active>true</active>
    <label>eLab</label>
</RecordType>

force-app/main/default/classes/LabNotificationHandlerTest.cls
@isTest
public class LabNotificationHandlerTest {
    @isTest
    public static void notificationHandler() {

        Account testAccount = new Account();
        testAccount.Last_name__c='Test';
        testAccount.First_Name__c='Account';
        testAccount.Name='Test Account';
        testAccount.BillingStreet='NewDelhi';
        testAccount.BillingCity = 'Ghaziabad';
        testAccount.BillingState='DE';
        testAccount.BillingPostalCode='23456'; 
        testAccount.BillingCountry='IN';
        testAccount.Gender__c='Male';
        testAccount.SSN__c='3465432';
        testAccount.Phone='3456222224';
        testAccount.Patient_s_Birth_Date__c=Date.newInstance(2017, 12, 9);
        testAccount.DOB__c=Date.newInstance(2016, 12, 9);
        testAccount.Email_Id__c = 'himanshu.tajne@mirketa.com';
        insert testAccount;

        Map<Id, String> accToEMail = new Map<Id, String>();
        accToEMail.put(testAccount.Id, testAccount.Email_Id__c);

        Lab_Order__c order = new Lab_Order__c();
        order.Status__c='E';
        order.Account_Id__c = testAccount.Id;
        order.Order_result_received__c = system.now();
        insert order;
        
        Elixir_Custom_Setting__c cust = new Elixir_Custom_Setting__c();
        cust.Elixir_portal_url__c = 'https://java-customer-9087-dev-ed.scratch.my.salesforce.com';
        insert cust;

        Blob b = Blob.valueOf('Test Data');
    	
    	Attachment attachment = new Attachment();
    	attachment.ParentId = order.Id;
    	attachment.Name = 'Test Attachment for Parent';
    	attachment.Body = b;
    	insert attachment;

        EmailTemplate template = new EmailTemplate();
        template.isActive = true;
        template.Name = 'Notification for eLab';
        template.DeveloperName = 'Notification_for_eLab';
        template.TemplateType = 'text';
        template.FolderId = UserInfo.getUserId();
        //insert template;

        Test.startTest();
        //LabNotificationHandler.labNotifications(accToEMail);
        System.enqueueJob(new LabNotificationHandler(accToEMail));
        System.assertEquals(1,1,' ');
        Test.stopTest();
    
    }
}