force-app/main/default/objects/Account/fields/DOB__c.field-meta.xml
<CustomField>
    <fullName>DOB__c</fullName>
    <description>Represents the date of birth of the account holder.</description>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Represents the first name of the account holder.</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Captures the birth sex or gender identity of the account holder.</description>
    <label>Birth Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Male</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>UNK</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Represents the last name of the account holder.</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Patient_s_Birth_Date__c.field-meta.xml
<CustomField>
    <fullName>Patient_s_Birth_Date__c</fullName>
    <description>Denotes the date of birth of the patient.</description>
    <label>Patient DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description>Represents the Social Security Number (SSN) associated with the account.</description>
    <label>SSN</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Elixir_Custom_Setting__c/Elixir_Custom_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Elixir Custom Setting</label>
</CustomObject>

force-app/main/default/objects/Elixir_Custom_Setting__c/fields/Lab_Order__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Lab Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <label>Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility__c/fields/Facility_Id__c.field-meta.xml
<CustomField>
    <fullName>Facility_Id__c</fullName>
    <label>Facility Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Facility__c/fields/Lab_ID__c.field-meta.xml
<CustomField>
    <fullName>Lab_ID__c</fullName>
    <label>Lab ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guarantor__c/Guarantor__c.object-meta.xml
<CustomObject>
    <label>Guarantor</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Guarantor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guarantors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Guarantor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Guarantors</relationshipLabel>
    <relationshipName>Guarantors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guarantor__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>Ambiguous</fullName>
                <isActive>false</isActive>
                <label>Ambiguous</label>
            </value>
            <value>
                <fullName>Female</fullName>
                <isActive>false</isActive>
                <label>Female</label>
            </value>
            <value>
                <fullName>Male</fullName>
                <isActive>false</isActive>
                <label>Male</label>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
                <isActive>false</isActive>
                <label>Not Applicable</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Unknown</fullName>
                <isActive>false</isActive>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ICD__c/ICD__c.object-meta.xml
<CustomObject>
    <description>TO BE DEPRECATED:
ICD used to store the Master Data of Diagnoses that is visible as an option to choose on the Lab order screen.</description>
    <label>ICD</label>
    <nameField>
        <label>ICD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ICDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ICD__c/fields/ICD_Id__c.field-meta.xml
<CustomField>
    <fullName>ICD_Id__c</fullName>
    <label>ICD Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICD_Codes__c/ICD_Codes__c.object-meta.xml
<CustomObject>
    <description>Diagnosis Code stores diagnosis code along with their ICDs.
Both template and patient related diagnosis are stored in this object differentiated by the record type.</description>
    <label>Diagnosis Code</label>
    <nameField>
        <label>Code Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diagnoses Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ICD_Codes__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate the diagnosis with the Patient.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Diagnosis Code</relationshipLabel>
    <relationshipName>Diagnosis_Code</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab__c/Lab__c.object-meta.xml
<CustomObject>
    <label>Lab</label>
    <nameField>
        <label>Lab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Labs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab__c/fields/Lab_Id__c.field-meta.xml
<CustomField>
    <fullName>Lab_Id__c</fullName>
    <label>Lab Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Test</label>
    <nameField>
        <displayFormat>LabOrder-{0000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Collection_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Collection_Date_Time__c</fullName>
    <label>Collection Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Facility_Id__c.field-meta.xml
<CustomField>
    <fullName>Facility_Id__c</fullName>
    <label>Facility Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/ICD_Id__c.field-meta.xml
<CustomField>
    <fullName>ICD_Id__c</fullName>
    <label>ICD Id</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Lab_Id__c.field-meta.xml
<CustomField>
    <fullName>Lab_Id__c</fullName>
    <label>Lab Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Physician_Name__c.field-meta.xml
<CustomField>
    <fullName>Physician_Name__c</fullName>
    <label>Physician Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It is used to connect the test to the lab order.</description>
    <label>Test</label>
    <referenceTo>Test__c</referenceTo>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Test_Id__c.field-meta.xml
<CustomField>
    <fullName>Test_Id__c</fullName>
    <label>Test Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test__c/Test__c.object-meta.xml
<CustomObject>
    <label>Test</label>
    <nameField>
        <displayFormat>Id-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test__c/fields/Lab_Id__c.field-meta.xml
<CustomField>
    <fullName>Lab_Id__c</fullName>
    <label>Lab Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test__c/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Users are able to select only package tests.</errorMessage>
        <filterItems>
            <field>Test__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Package</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Test__c</referenceTo>
    <relationshipLabel>Tests</relationshipLabel>
    <relationshipName>Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test__c/fields/Test_Id__c.field-meta.xml
<CustomField>
    <fullName>Test_Id__c</fullName>
    <label>Test Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VOB__c/VOB__c.object-meta.xml
<CustomObject>
    <description>This object tracks the verification of benefits/Patient Insurance details.</description>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VOB__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associated the patient with Account.</description>
    <label>Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurance</relationshipLabel>
    <relationshipName>VOB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOB__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>The gender of the individual insured under the policy.</description>
    <label>Insured Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>F</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>UN</fullName>
                <label>Unknown</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Male</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VOB__c/fields/Insurance_Providers__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Providers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate the Primary Insurance Provider with payor.</description>
    <label>Primary Insurance Provider</label>
    <referenceTo>Payor__c</referenceTo>
    <relationshipLabel>Insurance (Primary Insurance Provider)</relationshipLabel>
    <relationshipName>VOBS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderAPICalloutTest.cls
@isTest
public class OrderAPICalloutTest {
    
    
    @isTest
    static void testOrderAPICallouts(){
        Account acc = TestDataFactoryOrderAPI.createAccount();
        insert acc;
        
        Account testAccount = TestDataFactoryOrderAPI.createAccount();
        testAccount.Last_name__c='Testpatient';
        testAccount.First_Name__c='Account';
        testAccount.Name='Test Patient Account';
        testAccount.BillingStreet='Hyd';
        testAccount.BillingCity = 'HYD';
        testAccount.BillingState='DA';
        testAccount.BillingPostalCode='23456'; 
        testAccount.BillingCountry='US';
        testAccount.Gender__c='Male';
        testAccount.SSN__c='7569467';
        testAccount.Phone='3456789013';
        testAccount.Patient_s_Birth_Date__c=Date.today();
        testAccount.DOB__c=Date.today();
        insert testAccount;
        
        Payor__c payor = TestDataFactoryOrderAPI.createPayor();
        insert payor;
        
        VOB__c vobData = TestDataFactoryOrderAPI.createVob();
        vobData.Insurance_Providers__c = payor.Id;
        vobData.Account__c=acc.Id;
        insert vobData;
        Elixir_Custom_Setting__c conRectype = new Elixir_Custom_Setting__c();
        conRectype.ElixirSuite__Contact_RecordType__c = 'Contact';
        conRectype.ElixirSuite__Practitioner_Contact_Recordtype__c = 'Practitioner';
        insert conRectype;
        String contactRecType = conRectype.ElixirSuite__Contact_RecordType__c; 
        Id conRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get(contactRecType).getRecordTypeId();
        
        Contact guarantor = new Contact();
        guarantor.FirstName = 'Test';
        guarantor.LastName = 'Test';
        guarantor.AccountId = testAccount.Id;
        guarantor.ElixirSuite__Gender__c = 'M';
        guarantor.Phone = '9618974732';
        guarantor.Birthdate = System.today();
        guarantor.ElixirSuite__Is_Active__c = true;
        guarantor.ElixirSuite__Type__c = 'Guarantor';
        guarantor.RecordTypeId = conRecTypeId;
        guarantor.MailingCity = 'Test';
        guarantor.MailingPostalCode = '51500';
        insert guarantor;
        
        
        AccountContactRelation acr = new AccountContactRelation();
        acr.ElixirSuite__Relationship__c = 'PAR';
        acr.AccountId = acc.Id;
        acr.ContactId = guarantor.Id;
        insert acr;
        
        Lab__c  lab= TestDataFactoryOrderAPI.createLab();
        insert lab;
        
        Facility__c facData = TestDataFactoryOrderAPI.createFacility();
        facData.Lab_ID__c=lab.Lab_Id__c;
        insert facData;
        
        String contactRecTyp = conRectype.ElixirSuite__Practitioner_Contact_Recordtype__c; 
        Id practitionerRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get(contactRecTyp).getRecordTypeId();
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Test';
        con.RecordTypeId = practitionerRecTypeId;
        con.ElixirSuite__Is_Active__c = true;
        insert con;
        
        List<Test__c> testList = new List<Test__c>();
        List<ICD__c> ICDList = new List<ICD__c>();
        
        Test__c testData = TestDataFactoryOrderAPI.createTest();
        testData.Lab_Id__c=lab.Lab_Id__c;
        insert testData;
        testList.add(testData);
        
        DateTime dateData = DateTime.now();
        ICD__c icdData = TestDataFactoryOrderAPI.createICD();
        insert icdData;
        ICDList.add(icdData);
        
        List<String> selectedTest = new List<String>();
        List<String> selectedLabOrder = new List<String>();
        List<String> selectedICD = new List<String>();
        For(Integer i=0;i<testList.size();i++){
            selectedTest.add(testList[i].Test_Id__c);
        }
        For(Integer i=0;i<ICDList.size();i++){
            selectedICD.add(ICDList[i].ICD_Id__c);
        }
        Lab_Order__c labOrder = TestDataFactoryOrderAPI.createLabOrder();
        labOrder.Account_Id__c=acc.Id;
        labOrder.Collection_Date_Time__c  =dateData;
        labOrder.Facility_Id__c = facData.Facility_Id__c;
        labOrder.Facility_Name__c = facData.Name;
        labOrder.ICD_Id__c = icdData.ICD_Id__c;
        labOrder.Lab_Id__c  =lab.Lab_Id__c;
        labOrder.Physician_Name__c = con.LastName+','+con.FirstName;
        labOrder.Test_Id__c = testData.Test_Id__c;
        labOrder.Test_Name__c=testData.Test_Name__c;
        labOrder.ICD_Id__c = icdData.Name;
        labOrder.Lab_Order_Number__c = '3005022370';
        labOrder.Lab_Order_Req__c = '105968';
        insert labOrder;
        selectedLabOrder.add(labOrder.Lab_Order_Number__c); 
        String phyName = con.LastName+','+con.FirstName;
        String searchKey='300';
        String CollDatetime='2022-01-20T21:04:00Z';
        String personBody = 'request=<?xml version=\'1.0\'?><OBJECT name="person" op="put_partial"><birth_date>10/27/1924</birth_date><first_name>Florence</first_name><last_name>Edwards</last_name><middle_name>E</middle_name><suffix></suffix><ssn>558936729</ssn><address_1>2401 N Abram Rd 85</address_1><address_2></address_2><city>Mission</city><state>TX</state><sex>F</sex><zip>78572</zip><hsi_value>955001</hsi_value><hsilabel>7930723</hsilabel><home_phone_area_code>956</home_phone_area_code><home_phone_number>5856449</home_phone_number></OBJECT></REQUEST>';
        
        Test.setMock(HttpCalloutMock.class, new OrderAPICalloutMock());
        
        test.startTest();
        
        //HttpResponse response = new HttpResponse();
        //response = OrderAPICallouts.makeHTTPXMLPost(personBody);
        //String parsing  = OrderAPICallouts.retrieveFromXMLDom(response,'person');
        //CHCCredentials__mdt creChc = OrderAPICallouts.getCredentials();
        OrderAPICallouts.getCredentials();
        List<VOB__c> vobList = OrderAPICallouts.getVOBList(acc.Id);
        //Guarantor__c guarantorData = OrderAPICallouts.getGuarantorDetails(acc.Id,guarantor.Id);
        //Contact guarantorDetails = OrderAPICallouts.getGuarantorDetailsPicklist(acc.Id,guarantor.Id);
        List<Contact> guarantorList = OrderAPICallouts.getGuarantorList(acc.Id);
        Account account = OrderAPICallouts.getAccountDetails(acc.Id);
       	//Account insuranceAccount = OrderAPICallouts.getInsuranceDetails(acc.Id);
        VOB__c vodDetail = OrderAPICallouts.getVOBDetail(acc.Id,vobData.Id);        
        //Payor__c payorDetail = OrderAPICallouts.getPayorDetail();  
        //String collectionDate  = OrderAPICallouts.xmlDateTime(CollDatetime);
        String currentDateTime  =OrderAPICallouts.dateTimeNow(); 
        String expectedDateTime  =OrderAPICallouts.dateTimeNow();
        //DateTime dateTimeExpected = OrderAPICallouts.dateTimeNow();
        DateTime newDateTime = DateTime.newInstance(2022, 2, 11, 8, 6, 16);
        //dateTime newDateTimeExpected = dateTimeExpected.addDays(1);
        List<lab__c> getLabs = OrderAPICallouts.getLabs();
        List<facility__c> getFacilities = OrderAPICallouts.getFacilities(lab.Lab_Id__c);
        //List<Contact> getPhysicians = OrderAPICallouts.getPhysicians();
        List<Test__c> getTests = OrderAPICallouts.getTests(lab.Lab_Id__c);
        List<ICD_Codes__c> getICDs  = OrderAPICallouts.getICDs(acc.Id);
        List<Test__c> getTestList = OrderAPICallouts.getTestList(searchKey, lab.Lab_Id__c, '', 100);
        //List<ICD_Codes__c> getICDList = OrderAPICallouts.getICDList(searchKey);
        OrderAPICallouts.updateOrderStatus(selectedLabOrder,new List<String>{labOrder.Id});
        //String orderID = OrderAPICallouts.addOrder('Standard',acc.Id, 'T', lab.Lab_Id__c, facData.Facility_Id__c, phyName, selectedTest,selectedICD , CollDatetime, dateData,expectedDateTime,null, payor.Payer_Code__c, vobData.Insurance_Policy_ID__c, vobData.Group_Number__c, vobData.Id, guarantor.Id);
        //OrderAPICallouts.updateRecordStatus(selectedLabOrder, acc.Id);
        System.assertEquals(1, 1, ''); 
        test.stopTest();
        
        //String contentType = response.getHeader('Content-Type');
        //System.assert(contentType == 'application/json');
        //System.assertEquals(200, response.getStatusCode());
    }
    
    
    
    
    
}