force-app/main/default/objects/Account/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <description>Represents the email address associated with the account.</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Verification_Code__c.field-meta.xml
<CustomField>
    <fullName>Verification_Code__c</fullName>
    <description>Stores the verification code associated with the account.</description>
    <label>Verification Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>TO BE DEPRECATED:
Form was used to store all the forms related to the patient.</description>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/Form_Value__c.object-meta.xml
<CustomObject>
    <description>Form value stores all the miscellaneous features of the saved forms like Approvals, Care Episodes and Status. All the problems, diagnoses, medications and allergies selected on the forms are also linked with this object as the record in this object is also responsible for giving one identity to the forms saved in multiple objects.</description>
    <label>Form Value</label>
    <nameField>
        <label>Form Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Value__c/fields/Approval_Level__c.field-meta.xml
<CustomField>
    <fullName>Approval_Level__c</fullName>
    <label>Approval Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Form_Id__c.field-meta.xml
<CustomField>
    <fullName>Form_Id__c</fullName>
    <label>Form Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Is_Approver__c.field-meta.xml
<CustomField>
    <fullName>Is_Approver__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Approver</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Signed_Patient__c.field-meta.xml
<CustomField>
    <fullName>Signed_Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Signed Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Form Values (Signed Patient)</relationshipLabel>
    <relationshipName>Form_Values1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Form_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/Object_1_css__c.object-meta.xml
<CustomObject>
    <description>Form css stores all the attributes that defines how a form will look like when you view a form. All configuration records are saved in this object from Form Configuration screen.</description>
    <label>Form css</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Object 1 css Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form css</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_1_css__c/fields/Approv__c.field-meta.xml
<CustomField>
    <fullName>Approv__c</fullName>
    <label>Approver</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Approval_Level__c.field-meta.xml
<CustomField>
    <fullName>Approval_Level__c</fullName>
    <label>Approval Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Approval_Members__c.field-meta.xml
<CustomField>
    <fullName>Approval_Members__c</fullName>
    <label>Approval Members</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Object_1_css__c.field-meta.xml
<CustomField>
    <fullName>Object_1_css__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Object 1 css</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Section_Number__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Object_1_css__c</referenceTo>
    <relationshipName>Object_1_css</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Verification_Code__c.field-meta.xml
<CustomField>
    <fullName>Verification_Code__c</fullName>
    <label>Verification Code</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Verification_Code_New__c.field-meta.xml
<CustomField>
    <fullName>Verification_Code_New__c</fullName>
    <label>Verification Code New</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SignatureSaveTest.cls
@isTest
public with sharing class SignatureSaveTest {
    @TestSetup
    public static void testData() {
        Id currentUser = UserInfo.getUserId();
        User users = [SELECT Id, Verification_Code_New__c FROM User WHERE Id= :currentUser];
        users.Verification_Code_New__c = '1234';
        users.Email = 'rohit@mirketa.com';
        Profile profiles = [SELECT Id FROM Profile WHERE Name ='System Administrator' LIMIT 1];
        users.ProfileId = profiles.Id;
        UserRole roles = [SELECT Id FROM UserRole WHERE Name ='CEO' LIMIT 1];
        users.UserRoleId = roles.Id;
        update users;
        System.runAs (users) {
            Account newAccount = new Account(Name='Stefan Salvatore', 
                                             Verification_Code__c = '1234',
                                             Email_Id__c = 'rohit@mirketa.com');
            
            insert newAccount;
            Object_1_css__c  level1 = new Object_1_css__c
                (Approval_Level__c = 1,
                 Form__c = 'ABC',
                 Approv__c = 'User',
                 Approval_Members__c = currentUser);
            insert level1;
            Object_1_css__c  level2 = new Object_1_css__c
                (Approval_Level__c = 2,
                 Form__c = 'ABC',
                 Approv__c = 'Patient',
                 Approval_Members__c = newAccount.Id);
            insert level2;
            Object_1_css__c  level3 = new Object_1_css__c
                (Approval_Level__c = 3,
                 Form__c = 'ABC',
                 Approv__c = 'Profile',
                 Approval_Members__c = users.ProfileId);
            insert level3;
            Object_1_css__c  level4 = new Object_1_css__c
                (Approval_Level__c = 4,
                 Form__c = 'ABC',
                 Approv__c = 'Role',
                 Approval_Members__c = users.UserRoleId);
            insert level4;
            Object_1_css__c  level5 = new Object_1_css__c
                (Approval_Level__c = 5,
                 Form__c = 'ABC',
                 Approv__c = 'User',
                 Approval_Members__c = currentUser);
            insert level5;
            
            Form_Value__c approvedValue = new Form_Value__c
                (Is_Approver__c = true,
                 Approval_Level__c = '1',
                 User__c = currentUser,
                 Form_Id__c = '##');
            insert approvedValue;
        }
    }
    @isTest
    public static void approveLevel2(){
        Test.startTest();
        Id currentUser = UserInfo.getUserId();
        Id profileId = UserInfo.getProfileId();
        Id roleId = UserInfo.getUserRoleId();
        List<Account> accounts = [SELECT Id FROM Account];
        String patientId = accounts[0].Id;
        String formName = 'ABC';
        String changedFormName = 'ABC';
        String formId = '##';
        SignatureSave.UserValues userDetails = new SignatureSave.UserValues();
        userDetails.userId = currentUser;
        userDetails.patientId = patientId;
        userDetails.profileId = profileId;
        userDetails.roleId = roleId;
        List<Object_1_css__c> currentLevels = [SELECT Id, Approval_Level__c, Approv__c, Approval_Members__c
                                               FROM Object_1_css__c
                                               WHERE Form__c= :formName AND Approval_Level__c!=NULL
                                               AND Approval_Level__c=2];
        Object_1_css__c currentLevel = currentLevels[0];
        SignatureSave.approveForm(formName, changedFormName, formId, JSON.serialize(userDetails)
                                  , JSON.serialize(currentLevel), '1234', 'xxx');
        List<Form_Value__c> approvedLevels =         
            [SELECT Id, Is_Approver__c, Approval_Level__c FROM Form_Value__c
             WHERE Is_Approver__c=true AND Form_Id__c= :formId AND Approval_Level__c= '2'];
        system.assertEquals(true, approvedLevels[0].Is_Approver__c);    
        Test.stopTest();
    }
    @isTest
    public static void approveLevel3(){
        Test.startTest();
        Id currentUser = UserInfo.getUserId();
        Id profileId = UserInfo.getProfileId();
        Id roleId = UserInfo.getUserRoleId();
        User users = [SELECT Id, Verification_Code_New__c FROM User WHERE Id= :currentUser];
        List<Account> accounts = [SELECT Id FROM Account];
        String patientId = accounts[0].Id;
        String formName = 'ABC';
        String changedFormName = 'ABC';
        String formId = '##';
        SignatureSave.UserValues userDetails = new SignatureSave.UserValues();
        userDetails.userId = currentUser;
        userDetails.patientId = patientId;
        userDetails.profileId = profileId;
        userDetails.roleId = roleId;
        System.runAs (users) {
            Form_Value__c approvedValue = new Form_Value__c
                (Is_Approver__c = true,
                 Approval_Level__c = '2',
                 Signed_Patient__c = patientId,
                 Form_Id__c = '##');
            insert approvedValue;
        }
        List<Object_1_css__c> currentLevels = [SELECT Id, Approval_Level__c, Approv__c, Approval_Members__c
                                               FROM Object_1_css__c
                                               WHERE Form__c= :formName AND Approval_Level__c!=NULL
                                               AND Approval_Level__c=3];
        Object_1_css__c currentLevel = currentLevels[0];
        SignatureSave.approveForm(formName, changedFormName, formId, JSON.serialize(userDetails)
                                  , JSON.serialize(currentLevel), '1234', 'xxx');
        List<Form_Value__c> approvedLevels =         
            [SELECT Id, Is_Approver__c, Approval_Level__c FROM Form_Value__c
             WHERE Is_Approver__c=true AND Form_Id__c= :formId AND Approval_Level__c= '3'];
        system.assertEquals(true, approvedLevels[0].Is_Approver__c);    
        Test.stopTest();
    }
    
    @isTest
    public static void approveLevel4(){
        Test.startTest();
        Id currentUser = UserInfo.getUserId();
        Id profileId = UserInfo.getProfileId();
        Id roleId = UserInfo.getUserRoleId();
        User users = [SELECT Id, Verification_Code_New__c FROM User WHERE Id= :currentUser];
        List<Account> accounts = [SELECT Id FROM Account];
        String patientId = accounts[0].Id;
        String formName = 'ABC';
        String changedFormName = 'ABC';
        String formId = '##';
        SignatureSave.UserValues userDetails = new SignatureSave.UserValues();
        userDetails.userId = currentUser;
        userDetails.patientId = patientId;
        userDetails.profileId = profileId;
        userDetails.roleId = roleId;
        List<Object_1_css__c> currentLevels = [SELECT Id, Approval_Level__c, Approv__c, Approval_Members__c
                                               FROM Object_1_css__c
                                               WHERE Form__c= :formName AND Approval_Level__c!=NULL
                                               AND Approval_Level__c=4];
        Object_1_css__c currentLevel = currentLevels[0];
        System.runAs(Users){
            Form_Value__c approvedValue = new Form_Value__c
                (Is_Approver__c = true,
                 Approval_Level__c = '2',
                 Signed_Patient__c = patientId,
                 Form_Id__c = '##');
            insert approvedValue;
            Form_Value__c approvedLevel3 = new Form_Value__c
                (Is_Approver__c = true,
                 Approval_Level__c = '3',
                 Signed_Patient__c = patientId,
                 Form_Id__c = '##');
            insert approvedLevel3;
                }
                    SignatureSave.approveForm(formName, changedFormName, formId, JSON.serialize(userDetails)
                                              , JSON.serialize(currentLevel), '1234', 'xxx');
        List<Form_Value__c> approvedLevels =         
            [SELECT Id, Approval_Level__c, Is_Approver__c FROM Form_Value__c
             WHERE Is_Approver__c=true AND Form_Id__c= :formId AND Approval_Level__c= '4'];
        system.assertEquals(true, approvedLevels[0].Is_Approver__c);      
        Test.stopTest();
    }
    @isTest
    public static void approveLevel5(){
        Test.startTest();
        Id currentUser = UserInfo.getUserId();
        Id profileId = UserInfo.getProfileId();
        Id roleId = UserInfo.getUserRoleId();
        User users = [SELECT Id, Verification_Code_New__c FROM User WHERE Id= :currentUser];
        List<Account> accounts = [SELECT Id FROM Account];
        String patientId = accounts[0].Id;
        String formName = 'ABC';
        String changedFormName = 'ABC';
        String formId = '##';
        SignatureSave.UserValues userDetails = new SignatureSave.UserValues();
        userDetails.userId = currentUser;
        userDetails.patientId = patientId;
        userDetails.profileId = profileId;
        userDetails.roleId = roleId;
        List<Object_1_css__c> currentLevels = [SELECT Id, Approval_Level__c, Approv__c, Approval_Members__c
                                               FROM Object_1_css__c
                                               WHERE Form__c= :formName AND Approval_Level__c!=NULL
                                               AND Approval_Level__c=5];
        Object_1_css__c currentLevel = currentLevels[0];
        System.runAs(users){
            Form_Value__c approvedValueLevel2 = new Form_Value__c
                (Is_Approver__c = true,
                 Approval_Level__c = '2',
                 Signed_Patient__c = patientId,
                 Form_Id__c = '##');
            insert approvedValueLevel2;
            Form_Value__c approvedValueLevel3 = new Form_Value__c
                (Is_Approver__c = true,
                 Approval_Level__c = '3',
                 User__c = currentUser,
                 Form_Id__c = '##');
            insert approvedValueLevel3;
            Form_Value__c approvedValueLevel4 = new Form_Value__c
                (Is_Approver__c = true,
                 Approval_Level__c = '4',
                 User__c = currentUser,
                 Form_Id__c = '##');
            insert approvedValueLevel4;
        }
        SignatureSave.approveForm(formName, changedFormName, formId, JSON.serialize(userDetails)
                                  , JSON.serialize(currentLevel), '1234', 'xxx');
        List<Form_Value__c> approvedLevels =         
            [SELECT Id, Approval_Level__c, Is_Approver__c FROM Form_Value__c
             WHERE Is_Approver__c=true AND Form_Id__c= :formId AND Approval_Level__c= '5'];
        system.assertEquals(true, approvedLevels[0].Is_Approver__c);    
        Test.stopTest();
    }
    
}