force-app/main/default/objects/Account/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Represents the first name of the account holder.</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Represents the last name of the account holder.</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <label>Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility__c/fields/Facility_Id__c.field-meta.xml
<CustomField>
    <fullName>Facility_Id__c</fullName>
    <label>Facility Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Facility__c/fields/Lab_ID__c.field-meta.xml
<CustomField>
    <fullName>Lab_ID__c</fullName>
    <label>Lab ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guarantor__c/Guarantor__c.object-meta.xml
<CustomObject>
    <label>Guarantor</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Guarantor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guarantors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Guarantor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Guarantors</relationshipLabel>
    <relationshipName>Guarantors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ICD__c/ICD__c.object-meta.xml
<CustomObject>
    <description>TO BE DEPRECATED:
ICD used to store the Master Data of Diagnoses that is visible as an option to choose on the Lab order screen.</description>
    <label>ICD</label>
    <nameField>
        <label>ICD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ICDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ICD__c/fields/ICD_Id__c.field-meta.xml
<CustomField>
    <fullName>ICD_Id__c</fullName>
    <label>ICD Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab__c/Lab__c.object-meta.xml
<CustomObject>
    <label>Lab</label>
    <nameField>
        <label>Lab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Labs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab__c/fields/Lab_Id__c.field-meta.xml
<CustomField>
    <fullName>Lab_Id__c</fullName>
    <label>Lab Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Test</label>
    <nameField>
        <displayFormat>LabOrder-{0000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Collection_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Collection_Date_Time__c</fullName>
    <label>Collection Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Facility_Id__c.field-meta.xml
<CustomField>
    <fullName>Facility_Id__c</fullName>
    <label>Facility Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/ICD_Id__c.field-meta.xml
<CustomField>
    <fullName>ICD_Id__c</fullName>
    <label>ICD Id</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Lab_Id__c.field-meta.xml
<CustomField>
    <fullName>Lab_Id__c</fullName>
    <label>Lab Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Lab_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order_Number__c</fullName>
<description>This field is used for storing Order ID</description>
    <label>Lab Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Lab_Order_Req__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order_Req__c</fullName>
<description>This field used to store placer order number</description>
    <label>Lab Order Req</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Physician_Name__c.field-meta.xml
<CustomField>
    <fullName>Physician_Name__c</fullName>
    <label>Physician Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It is used to connect the test to the lab order.</description>
    <label>Test</label>
    <referenceTo>Test__c</referenceTo>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Test_Id__c.field-meta.xml
<CustomField>
    <fullName>Test_Id__c</fullName>
    <label>Test Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payor__c/Payor__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the List of Payers in elixir.</description>
    <label>Payor</label>
    <nameField>
        <label>Payor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Physician__c/Physician__c.object-meta.xml
<CustomObject>
    <description>TO BE DEPRECATED:
Physician stores all the practitioners that user can choose while creating a lab order.</description>
    <label>Physician</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Physician Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Physicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test__c/Test__c.object-meta.xml
<CustomObject>
    <label>Test</label>
    <nameField>
        <displayFormat>Id-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test__c/fields/Lab_Id__c.field-meta.xml
<CustomField>
    <fullName>Lab_Id__c</fullName>
    <label>Lab Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test__c/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Users are able to select only package tests.</errorMessage>
        <filterItems>
            <field>Test__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Package</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Test__c</referenceTo>
    <relationshipLabel>Tests</relationshipLabel>
    <relationshipName>Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test__c/fields/Test_Id__c.field-meta.xml
<CustomField>
    <fullName>Test_Id__c</fullName>
    <label>Test Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VOB__c/VOB__c.object-meta.xml
<CustomObject>
    <description>This object tracks the verification of benefits/Patient Insurance details.</description>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VOB__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associated the patient with Account.</description>
    <label>Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurance</relationshipLabel>
    <relationshipName>VOB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOB__c/fields/Insurance_Providers__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Providers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate the Primary Insurance Provider with payor.</description>
    <label>Primary Insurance Provider</label>
    <referenceTo>Payor__c</referenceTo>
    <relationshipLabel>Insurance (Primary Insurance Provider)</relationshipLabel>
    <relationshipName>VOBS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/onCreateOrderTest.cls
@isTest public class onCreateOrderTest {
    @isTest static void testTrigger(){
        Account acc = TestDataFactoryOrderAPI.createAccount();
        insert acc;
        Payor__c payor = TestDataFactoryOrderAPI.createPayor();
        insert payor;
        VOB__c vobData = TestDataFactoryOrderAPI.createVob();
        vobData.Insurance_Providers__c = payor.Id;
        vobData.Account__c=acc.Id;
        insert vobData;
        Guarantor__c guarantor  =TestDataFactoryOrderAPI.createGuarantor();
        guarantor.Account__c =acc.Id;
        insert guarantor;
        Lab__c  lab= TestDataFactoryOrderAPI.createLab();
        insert lab;
        Facility__c facData = TestDataFactoryOrderAPI.createFacility();
        facData.Lab_ID__c=lab.Lab_Id__c;
        insert facData;
        
        Physician__c phyData =  TestDataFactoryOrderAPI.createPhysician();
        insert phyData;
        
        List<Test__c> testList = new List<Test__c>();
        List<ICD__c> ICDList = new List<ICD__c>();
        
        Test__c testData1 = TestDataFactoryOrderAPI.createTest();
        testData1.Lab_Id__c=lab.Lab_Id__c;
        insert testData1;
        testList.add(testData1);
        
        DateTime dateData = DateTime.now();
        ICD__c icdData = TestDataFactoryOrderAPI.createICD();
        insert icdData;
        ICDList.add(icdData);
        
        List<String> selectedTest = new List<String>();
        List<String> selectedLabOrder = new List<String>();
        List<String> selectedICD = new List<String>();
        For(Integer i=0;i<testList.size();i++){
            selectedTest.add(testList[i].Test_Id__c);
        }
        For(Integer i=0;i<ICDList.size();i++){
            selectedICD.add(ICDList[i].ICD_Id__c);
        }
        Lab_Order__c labOrder = TestDataFactoryOrderAPI.createLabOrder();
        labOrder.Account_Id__c=acc.Id;
        labOrder.Collection_Date_Time__c  =dateData;
        labOrder.Facility_Id__c = facData.Facility_Id__c;
        labOrder.ICD_Id__c = icdData.ICD_Id__c;
        labOrder.Lab_Id__c  =lab.Lab_Id__c;
        labOrder.Physician_Name__c = phyData.Last_Name__c+','+phyData .First_Name__c;
        labOrder.Test_Id__c = testData1.Test_Id__c;
        labOrder.ICD_Id__c = icdData.Name;
        labOrder.Lab_Order_Number__c = '3005022370';
        labOrder.Lab_Order_Req__c = '105968';
        insert labOrder;
       /* labOrder.Lab_Id__c  =lab2.Lab_Id__c;
        labOrder.Facility_Id__c = facData1.Facility_Id__c;
        labOrder.Test_Id__c = testData2.Test_Id__c;
        update labOrder;*/
        
        System.assertEquals(1, 1, '');
    }
}