force-app/main/default/objects/Account/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Represents the first name of the account holder.</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Captures the birth sex or gender identity of the account holder.</description>
    <label>Birth Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Male</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>UNK</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Represents the last name of the account holder.</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description>Represents the Social Security Number (SSN) associated with the account.</description>
    <label>SSN</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Test</label>
    <nameField>
        <displayFormat>LabOrder-{0000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Lab_Order_Req__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order_Req__c</fullName>
<description>This field used to store placer order number</description>
    <label>Lab Order Req</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>E</fullName>
                <label>Entered</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Transmitted</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Results Received (Partial)</fullName>
            </value>
            <value>
                <fullName>Results Received</fullName>
            </value>
            <value>
                <fullName>Final Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LabOrderRecordsTest.cls
@isTest
public class LabOrderRecordsTest {
    @isTest static void getLabOrderList(){
        Account acc = new Account(Last_name__c='Test', First_Name__c='Account',Name='Test Account',BillingStreet='NewDelhi',BillingCity = 'Ghaziabad',BillingState='DE',BillingPostalCode='23456', BillingCountry='IN', Gender__c='Male',SSN__c='3465432',Phone='3456222224');
        insert acc;
        string searchkey='300';
        test.startTest();
        List<Lab_Order__c> getLabsList = LabOrderRecords.getLabOrderList(searchkey, acc.Id,'','','');
        //List<Lab_Order__c> getLabsList1 = LabOrderRecords.getLabOrderList(searchkey, acc.Id,'','','','lab_order_req__c','LIKE','10');
       // List<Lab_Order__c> getLabsList2 = LabOrderRecords.getLabOrderList(searchkey, acc.Id,'status__c','LIKE','E','lab_order_req__c','LIKE','10');
        LabOrderRecords.countLabOrders();
        //map<string,string> Map1=LabOrderRecords.getObjectFields();
        System.assertEquals(1, 1, '');
        test.stopTest(); 
    }
   /* @isTest static void getLabOrderList1(){
        Account acc1 = new Account(Last_name__c='Test', First_Name__c='Account',Name='Test Account',BillingStreet='NewDelhi',BillingCity = 'Ghaziabad',BillingState='DE',BillingPostalCode='23456', BillingCountry='IN', Gender__c='Male',SSN__c='3465432',Phone='3456222224');
        insert acc1;
       // string searchkey1='300';
        test.startTest();
        List<Lab_Order__c> getLabsList1 = LabOrderRecords.getLabOrderList('', acc1.Id,'status__c','LIKE','Entered');
        test.stopTest();
       
    }*/
    @isTest static void getLabOrderList2(){
        Account acc2 = new Account(Last_name__c='Test', First_Name__c='Account',Name='Test Account',BillingStreet='NewDelhi',BillingCity = 'Ghaziabad',BillingState='DE',BillingPostalCode='23456', BillingCountry='IN', Gender__c='Male',SSN__c='3465432',Phone='3456222224');
        insert acc2;
       // string searchkey1='300';
        test.startTest();
        List<Lab_Order__c> getLabsList2 = LabOrderRecords.getLabOrderList('', acc2.Id,'status__c','=','Entered');
        System.assertEquals(1, 1, '');
        test.stopTest();
       
    }
     @isTest static void getLabOrderList3(){
        Account acc2 = new Account(Last_name__c='Test', First_Name__c='Account',Name='Test Account',BillingStreet='NewDelhi',BillingCity = 'Ghaziabad',BillingState='DE',BillingPostalCode='23456', BillingCountry='IN', Gender__c='Male',SSN__c='3465432',Phone='3456222224');
        insert acc2;
       // string searchkey1='300';
        test.startTest();
        List<Lab_Order__c> getLabsList7 = LabOrderRecords.getLabOrderList('', acc2.Id,'status__c','=','Entered');
        System.assertEquals(1, 1, '');
        test.stopTest();
     }
}