force-app/main/default/objects/Account/fields/Insurance_provider__c.field-meta.xml
<CustomField>
    <fullName>Insurance_provider__c</fullName>
    <label>Insurance provider</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aetna</fullName>
            </value>
            <value>
                <fullName>Ambetter</fullName>
            </value>
            <value>
                <fullName>AmeriGroup</fullName>
            </value>
            <value>
                <fullName>AmeriHealth</fullName>
            </value>
            <value>
                <fullName>Anthem</fullName>
            </value>
            <value>
                <fullName>Avmed</fullName>
            </value>
            <value>
                <fullName>BCBS</fullName>
            </value>
            <value>
                <fullName>Beacon/Value Options</fullName>
            </value>
            <value>
                <fullName>Carefirst</fullName>
            </value>
            <value>
                <fullName>Cigna</fullName>
            </value>
            <value>
                <fullName>ConnectiCare</fullName>
            </value>
            <value>
                <fullName>Conventry</fullName>
            </value>
            <value>
                <fullName>Empire BCBS</fullName>
            </value>
            <value>
                <fullName>Federal BCBS</fullName>
            </value>
            <value>
                <fullName>Florida BCBS</fullName>
            </value>
            <value>
                <fullName>GEHA</fullName>
            </value>
            <value>
                <fullName>GHI</fullName>
            </value>
            <value>
                <fullName>Harvard Pilgrim</fullName>
            </value>
            <value>
                <fullName>Health Net</fullName>
            </value>
            <value>
                <fullName>Highmark</fullName>
            </value>
            <value>
                <fullName>Humana</fullName>
            </value>
            <value>
                <fullName>Magellan</fullName>
            </value>
            <value>
                <fullName>Magna Care</fullName>
            </value>
            <value>
                <fullName>Med Mutual</fullName>
            </value>
            <value>
                <fullName>MHNet</fullName>
            </value>
            <value>
                <fullName>Multiplan</fullName>
            </value>
            <value>
                <fullName>New Directions</fullName>
            </value>
            <value>
                <fullName>Optum</fullName>
            </value>
            <value>
                <fullName>Qualcare</fullName>
            </value>
            <value>
                <fullName>The Empire Plan (NYSHIP)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Provider__c/Insurance_Provider__c.object-meta.xml
<CustomObject>
    <label>Insurance Provider</label>
    <nameField>
        <label>Insurance Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Provider__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Insurance Providers</relationshipLabel>
    <relationshipName>Insurance_Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Insurance_Policy_ID__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Policy_ID__c</fullName>
    <description>Capture Insurance Policy Id</description>
    <label>Primary Insurance Policy ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Insurance_Providor__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Providor__c</fullName>
    <label>Insurance Provider</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BCBS</fullName>
            </value>
            <value>
                <fullName>Aetna</fullName>
            </value>
            <value>
                <fullName>United Healthcare</fullName>
            </value>
            <value>
                <fullName>Cigna</fullName>
            </value>
            <value>
                <fullName>Avmed</fullName>
            </value>
            <value>
                <fullName>Amerihealth</fullName>
            </value>
            <value>
                <fullName>Harvard Pilgrim</fullName>
            </value>
            <value>
                <fullName>GEHA</fullName>
            </value>
            <value>
                <fullName>Humana</fullName>
            </value>
            <value>
                <fullName>Anthem</fullName>
            </value>
            <value>
                <fullName>Medical Mutual</fullName>
            </value>
            <value>
                <fullName>Value Options</fullName>
            </value>
            <value>
                <fullName>Coventry</fullName>
            </value>
            <value>
                <fullName>MultiPlan</fullName>
            </value>
            <value>
                <fullName>Health Net</fullName>
            </value>
            <value>
                <fullName>GHI</fullName>
            </value>
            <value>
                <fullName>Optum</fullName>
            </value>
            <value>
                <fullName>UMR</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VOB__c/VOB__c.object-meta.xml
<CustomObject>
    <description>This object tracks the verification of benefits/Patient Insurance details.</description>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VOB__c/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <description>Unique identifier for the insurance record.</description>
    <label>ID#</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOB__c/fields/Ins_Comp__c.field-meta.xml
<CustomField>
    <fullName>Ins_Comp__c</fullName>
    <description>Insurance company associate with the insurance record.</description>
    <label>Ins Comp</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOB__c/fields/Insurance_Policy_ID__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Policy_ID__c</fullName>
    <label>Primary Insurance Policy ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOB__c/fields/Insurance_Provider__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate the Insurance Provider with Insurance Provider.</description>
    <label>Insurance Provider</label>
    <referenceTo>Insurance_Provider__c</referenceTo>
    <relationshipLabel>Insurance</relationshipLabel>
    <relationshipName>VOBS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOB__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate the Patient Name with Opportunity.</description>
    <label>Patient Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Insurance</relationshipLabel>
    <relationshipName>VOB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_CreateVOB.cls
@isTest
public class Test_CreateVOB {
    
    public static testMethod void testmethod1(){
    
    Account acc = new Account();
    acc.Name = 'Aruacc';
    insert acc;
    
    Opportunity opp = new Opportunity();
    opp.Name = 'Aru';
    opp.AccountId = acc.Id;
    opp.StageName = 'VOB';
    opp.CloseDate = System.today();
  //  opp.Insurance_Provider__c = ins.id;
    opp.Insurance_Policy_ID__c = '123asddfd';
    insert opp;
        
        VOB__c v = new VOB__c();
        v.Opportunity__c = opp.Id;
        v.ID__c = opp.Insurance_Policy_ID__c;
        v.Ins_Comp__c = opp.Insurance_Providor__c;
        v.ElixirSuite__Insured_Address__c = 'ABC';
        v.ElixirSuite__Date_Of_Birth__c = date.valueOf('2000-04-10');
        insert v;
        System.assertEquals('1', '1','');
    }
}