force-app/main/default/objects/Account/fields/MRN_Number__c.field-meta.xml
<CustomField>
    <fullName>MRN_Number__c</fullName>
    <description>Denotes the medical record number assigned to the account.</description>
    <label>MRN Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Patient_s_Birth_Date__c.field-meta.xml
<CustomField>
    <fullName>Patient_s_Birth_Date__c</fullName>
    <description>Denotes the date of birth of the patient.</description>
    <label>Patient DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Elixir_Custom_Setting__c/Elixir_Custom_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Elixir Custom Setting</label>
</CustomObject>

force-app/main/default/objects/Elixir_Custom_Setting__c/fields/Enable_email_for_Approvers__c.field-meta.xml
<CustomField>
    <fullName>Enable_email_for_Approvers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable email for Approvers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Elixir_Custom_Setting__c/fields/Enable_Tasks_for_approvers__c.field-meta.xml
<CustomField>
    <fullName>Enable_Tasks_for_approvers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Tasks for approvers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>TO BE DEPRECATED:
Form was used to store all the forms related to the patient.</description>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/Object_1_css__c.object-meta.xml
<CustomObject>
    <description>Form css stores all the attributes that defines how a form will look like when you view a form. All configuration records are saved in this object from Form Configuration screen.</description>
    <label>Form css</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Object 1 css Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form css</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_1_css__c/fields/Approv__c.field-meta.xml
<CustomField>
    <fullName>Approv__c</fullName>
    <label>Approver</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Approval_Level__c.field-meta.xml
<CustomField>
    <fullName>Approval_Level__c</fullName>
    <label>Approval Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Approval_Members__c.field-meta.xml
<CustomField>
    <fullName>Approval_Members__c</fullName>
    <label>Approval Members</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_1_css__c/fields/Object_1_css__c.field-meta.xml
<CustomField>
    <fullName>Object_1_css__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Object 1 css</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Section_Number__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Object_1_css__c</referenceTo>
    <relationshipName>Object_1_css</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NotifyApproversTest.cls
@isTest
public class NotifyApproversTest {
    @isTest 
    public static void testSendNotification(){
        
        Account patient = new Account();
        patient.name = 'Test Patient';
        patient.ElixirSuite__Email_Id__c = 'kj@gmail.com';
        patient.Patient_s_Birth_Date__c = System.today().addyears(-20);
        patient.MRN_Number__c = 1234567;
        patient.ElixirSuite__First_Name__c ='fname';
        patient.ElixirSuite__Last_Name__c ='lname';
        patient.ElixirSuite__SSN__c ='1234';
        patient.ElixirSuite__Gender__c='Male';
        patient.Phone ='9919850735';
        patient.BillingPostalCode='27440';
        patient.ElixirSuite__Deceased__c =true;
        insert patient; 
        
        String recordTypeName = 'Test Record Type';
        String changedFormName = 'Test Form';
        Integer currentLevel = 1;
        
        Object_1_css__c obj = new Object_1_css__c(Approval_Level__c = 2,
                                                  Approv__c = 'User',
                                                  Approval_Members__c = UserInfo.getUserId(),
                                                  Form__c = 'Test Record Type'
                                                 );
        insert obj;
        
        Object_1_css__c obj2 = new Object_1_css__c(Approval_Level__c = 3,
                                                   Approv__c = 'Profile',
                                                   Approval_Members__c = UserInfo.getUserId(),
                                                   Form__c = 'Test Record Type'
                                                  );
        insert obj2;
        
        Object_1_css__c obj3 = new Object_1_css__c(Approval_Level__c = 4,
                                                   Approv__c = 'Role',
                                                   Approval_Members__c = UserInfo.getUserId(),
                                                   Form__c = 'Test Record Type'
                                                  );
        insert obj3;
        
        Object_1_css__c obj4 = new Object_1_css__c(Approval_Level__c = 5,
                                                   Approv__c = 'Patient',
                                                   Approval_Members__c = UserInfo.getUserId(),
                                                   Form__c = 'Test Record Type'
                                                  );
        insert obj4;
        
        Elixir_Custom_Setting__c customSetting = Elixir_Custom_Setting__c.getOrgDefaults();
        customSetting.Name = 'Test Custom Settings';
        customSetting.Enable_email_for_Approvers__c = true;
        customSetting.Enable_Tasks_for_approvers__c = true;
        insert customSetting; 
        
        Test.startTest();
        NotifyApprovers.sendNotification(recordTypeName, changedFormName, patient.Id, 1);
        NotifyApprovers.sendNotification(recordTypeName, changedFormName, patient.Id, 2);  
        NotifyApprovers.sendNotification(recordTypeName, changedFormName, patient.Id, 3);
        NotifyApprovers.sendNotification(recordTypeName, changedFormName, patient.Id, 4);
        System.assertEquals(1,1,' ');
        Test.stopTest();
        system.assertEquals(1,1,'Hello');
        
    }
}