force-app/main/default/objects/Account/fields/MRN_Number__c.field-meta.xml
<CustomField>
    <fullName>MRN_Number__c</fullName>
    <description>Denotes the medical record number assigned to the account.</description>
    <label>MRN Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>This object stores both template and patient providers. Providers in elixir are facilties.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Represents patient-provider relationship.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Used to store address of provider.</description>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents self-relationship.</description>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.Account__r.Id</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Provider_Code__c.field-meta.xml
<CustomField>
    <fullName>Provider_Code__c</fullName>
    <description>This field denotes the provider NPI code information.</description>
    <label>Provider NPI</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GenerateUpfrontPaymentReceiptCtrl.cls
/*
Developed By  - Sonal Agarwal
Test Class - GenerateUpfrontPaymentReceiptTest
Description - Class for printing Payment receipt when the User selects upfront as payment type through 
*/
public with sharing class GenerateUpfrontPaymentReceiptCtrl 
{
    public Decimal amountPaid {get;set;}
    public Id patientId {get;set;}
    
    public Provider__c providerData {get;set;}
    public Account patientData {get;set;}
    public String paymentDate {get;set;}
    
    public GenerateUpfrontPaymentReceiptCtrl()
    {
        amountPaid = Decimal.valueOf(ApexPages.currentPage().getParameters().get('amountPaid').escapeHtml4());
        patientId = ApexPages.currentPage().getParameters().get('patientId').escapeHtml4();
        paymentDate = ApexPages.currentPage().getParameters().get('paymentDate').escapeHtml4();
        providerData = getProviderDetails(patientId);
        patientData = getPatientDetails(patientId);
        Apexpages.currentPage().getHeaders().put('content-disposition', 'attachment; filename=Payment-'+patientData.Name +'.pdf');
    }
    
    public Provider__c getProviderDetails(String accId)
    {
        Provider__c providerObj = new Provider__c();
        try{
        providerObj = [Select id, Name, Address__c, Provider_Code__c from Provider__c 
        where Account__c =: patientId 
        WITH SECURITY_ENFORCED
        LIMIT 1];
        }
        catch(Exception e){
            ExceptionLog.logError(e);
        }
        return providerObj;
    }
    
    public Account getPatientDetails(String accId)
    {
        Account patientObj = new Account();
        patientObj = [Select id, Name, MRN_Number__c, Phone from Account where Id =: patientId 
        WITH SECURITY_ENFORCED
        LIMIT 1];
        
        return patientObj;
    }
}