force-app/main/default/objects/Account/fields/MRN_Number__c.field-meta.xml
<CustomField>
    <fullName>MRN_Number__c</fullName>
    <description>Denotes the medical record number assigned to the account.</description>
    <label>MRN Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Patient_s_Birth_Date__c.field-meta.xml
<CustomField>
    <fullName>Patient_s_Birth_Date__c</fullName>
    <description>Denotes the date of birth of the patient.</description>
    <label>Patient DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Location stores all the Master Data related to the reservations. It can hold building, suite, room and bed separated by record types.</description>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Template Provider</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Active Care Episode Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referral_Type__c.field-meta.xml
<CustomField>
    <fullName>Referral_Type__c</fullName>
    <inlineHelpText>Select &quot;Inbound&quot; if client was referred to us from another facility. Select &quot;Outbound&quot; if we are referring client out</inlineHelpText>
    <label>Referral Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referred_In_Organization__c.field-meta.xml
<CustomField>
    <fullName>Referred_In_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred In Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Patient Account</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Referred In Organization)</relationshipLabel>
    <relationshipName>Opportunities5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>This object stores both template and patient providers. Providers in elixir are facilties.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Represents patient-provider relationship.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Patient_Provider__c.field-meta.xml
<CustomField>
    <fullName>Patient_Provider__c</fullName>
    <description>Describes whether the record is patient provider or not.</description>
    <formula>IF( RecordType.Name = &apos;Patient Provider&apos;, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Patient Provider</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents self-relationship.</description>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.Account__r.Id</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provider__c/fields/Provider_Code__c.field-meta.xml
<CustomField>
    <fullName>Provider_Code__c</fullName>
    <description>This field denotes the provider NPI code information.</description>
    <label>Provider NPI</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProviderTriggerHelperTest.cls
@isTest
public class ProviderTriggerHelperTest {
    @isTest
    public static void evaluateOpportunityLocation(){      
        Set<Id> accSet = new Set<Id>();
        Account patient = new Account();
        patient.name = 'Test Patient';
        patient.ElixirSuite__Email_Id__c = 'kj@gmail.com';
        patient.Patient_s_Birth_Date__c = System.today().addyears(-20);
        patient.MRN_Number__c = 1234567;
        patient.ElixirSuite__First_Name__c ='fname';
        patient.ElixirSuite__Last_Name__c ='lname';
        patient.ElixirSuite__SSN__c ='1234';
        patient.ElixirSuite__Gender__c='Male';
        patient.Phone ='9919850735';
        patient.BillingPostalCode='27440';
        patient.ElixirSuite__Deceased__c =true;         
        insert patient;                      
        accSet.add(patient.Id); 
        
        Provider__c providerRec = new Provider__c();
        providerRec.Account__c = patient.Id;
        providerRec.Provider_Code__c  = 'Test123';
        providerRec.Name = 'TestProvider'; 
        providerRec.Id=null;
        insert providerRec;
        
        Opportunity op=new Opportunity();
        op.Name='a';
        op.AccountId=patient.Id;        
        op.CloseDate=System.today();     
        op.Referred_In_Organization__c=patient.id;
        op.Referral_Type__c='Inbound';
        op.StageName='Prospecting';
        insert op;
        
        List<Opportunity> oppoList = [Select Id , Location__c from Opportunity where  Location__c =:Null];
        update oppoList;    
        Test.startTest();
        ProviderTriggerHelper.evaluateOpportunityLocation( accSet  );       
        Test.stopTest();
        system.assertEquals(1,1,'Hello');
    }
    @isTest
    public static void evaluateOpportunityLocation2(){      
        Set<Id> accSet = new Set<Id>();
        Account patient = new Account();       
        patient.name = 'Test Patient';
        patient.ElixirSuite__Email_Id__c = 'kj@gmail.com';
        patient.Patient_s_Birth_Date__c = System.today().addyears(-20);
        patient.MRN_Number__c = 1234567;
        patient.ElixirSuite__First_Name__c ='fname';
        patient.ElixirSuite__Last_Name__c ='lname';
        patient.ElixirSuite__SSN__c ='1234';
        patient.ElixirSuite__Gender__c='Male';
        patient.Phone ='9919850735';
        patient.BillingPostalCode='27440';
        patient.ElixirSuite__Deceased__c =true;         
        insert patient;                      
        accSet.add(patient.Id);    
        
        List<Provider__c> providerReclist = new List<Provider__c>();
        
        Provider__c providerRec2 = new Provider__c();
        providerRec2.Account__c = null;
        providerRec2.Provider_Code__c  = 'Test1223';
        providerRec2.Name = 'TestProvider2';        
        insert providerRec2;
        
        
        Provider__c providerRec3 = new Provider__c();
        providerRec3.Account__c = null;
        providerRec3.Provider_Code__c  = 'Test1223';
        providerRec3.Name = 'TestProvider2';        
        insert providerRec3;
        
        Opportunity op=new Opportunity();
        op.Name='a';
        op.AccountId=patient.Id;        
        op.CloseDate=System.today();     
        op.Referred_In_Organization__c=patient.id;
        op.Referral_Type__c='Inbound';
        op.StageName='Prospecting';
        insert op;  
        
        List<Provider__c> providers = [SELECT Id, Patient_Provider__c, Provider_Code__c, Account__c, Provider__c FROM Provider__c];
        
        Test.startTest();
        ProviderTriggerHelper.evaluateOpportunityLocation( accSet  );
        ProviderTriggerHelper.populateProviders(providerReclist);
        Test.stopTest();
        system.assertEquals(1,1,'Hello');
    }

    @isTest
    public static void testUpdate(){ 
        Test.startTest();
        Account patient = new Account();
        patient.name = 'Test Patient';
        patient.ElixirSuite__Email_Id__c = 'kj@gmail.com';
        patient.Patient_s_Birth_Date__c = System.today().addyears(-20);
        patient.MRN_Number__c = 1234567;
        patient.ElixirSuite__First_Name__c ='fname';
        patient.ElixirSuite__Last_Name__c ='lname';
        patient.ElixirSuite__SSN__c ='1234';
        patient.ElixirSuite__Gender__c='Male';
        patient.Phone ='9919850735';
        patient.BillingPostalCode='27440';
        patient.ElixirSuite__Deceased__c =true;         
        insert patient;     
        
        Provider__c providerRec = new Provider__c();
        providerRec.Account__c = patient.Id;
        providerRec.Provider_Code__c  = 'Test123';
        providerRec.Name = 'TestProvider'; 
        insert providerRec;
        
        update providerRec;
        
        system.assertEquals(1,1);     
        Test.stopTest();
        
    }
    
    @isTest
    public static void testDelete(){ 
        Test.startTest();
        Account patient = new Account();
        patient.name = 'Test Patient';
        patient.ElixirSuite__Email_Id__c = 'kj@gmail.com';
        patient.Patient_s_Birth_Date__c = System.today().addyears(-20);
        patient.MRN_Number__c = 1234567;
        patient.ElixirSuite__First_Name__c ='fname';
        patient.ElixirSuite__Last_Name__c ='lname';
        patient.ElixirSuite__SSN__c ='1234';
        patient.ElixirSuite__Gender__c='Male';
        patient.Phone ='9919850735';
        patient.BillingPostalCode='27440';
        patient.ElixirSuite__Deceased__c =true;         
        insert patient;     
        
        Provider__c providerRec = new Provider__c();
        providerRec.Account__c = patient.Id;
        providerRec.Provider_Code__c  = 'Test123';
        providerRec.Name = 'TestProvider'; 
        insert providerRec;
        
        delete providerRec;
        
        system.assertEquals(1,1);     
        Test.stopTest();
        
    }
    
    @isTest
    public static void testDummy(){ 
        Test.startTest();
        
        ProviderPermissionDeletion.dummyMethod();
        ProviderPermissionDeletion py = new ProviderPermissionDeletion();
        System.enqueueJob(py);
        ProviderPermissionHelper.dummyMethod();
        ProviderPermissionHelper ty = new ProviderPermissionHelper();
        System.enqueueJob(ty);
         system.assertEquals(1,1);     
        Test.stopTest();
        
    }
}