force-app/main/default/objects/Account/fields/Payment_frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Instalments_by_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Instalments_by_Frequency__c</fullName>
    <label>Instalments by Frequency</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LOC__c.field-meta.xml
<CustomField>
    <fullName>LOC__c</fullName>
    <label>LOC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>IOP</fullName>
            </value>
            <value>
                <fullName>OP</fullName>
            </value>
            <value>
                <fullName>Detox</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_frequency__c</fullName>
    <label>Payment frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Information__c/Payment_Information__c.object-meta.xml
<CustomObject>
    <label>Payment Information</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Payment Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Information__c/fields/Patient_Name__c.field-meta.xml
<CustomField>
    <fullName>Patient_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Information</relationshipLabel>
    <relationshipName>Payment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>To be Deprecated: This object is used to store both master and sub payment schedules for a patient.</description>
    <label>Master Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Payment Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Payment Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Schedule__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Payment_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Payment Schedule</label>
    <referenceTo>Payment_Schedule__c</referenceTo>
    <relationshipLabel>Sub Payment Schedule</relationshipLabel>
    <relationshipName>Payment_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestPaymentSchedule.cls
@isTest
public class TestPaymentSchedule {
    
    static testMethod void CheckPaymentSchedule(){
        
        Account a=new Account(name='TEST');
        
        insert a;
        Opportunity o=new Opportunity();
        o.Name='test';
        o.AccountId=a.id;
        o.StageName='Prospecting';
        o.CloseDate=system.today();
        
        o.Instalments_by_Frequency__c=100;
        o.LOC__c='IOP';
        o.Payment_Frequency__c='Daily';
        
        insert o;
        Product2 p=new Product2(name='Admit Fee');
        insert p;
        PricebookEntry pe=new PricebookEntry(Product2Id=p.id,UnitPrice=200,Pricebook2Id=Test.getStandardPricebookId(),isactive=true);
        insert pe;
        OpportunityLineitem oli=new OpportunityLineitem(OpportunityId=o.id,quantity=2,Product2Id=p.id,PricebookEntryId=pe.id);
        oli.UnitPrice=200;
        insert oli;
        Payment_Information__c pi =new Payment_Information__c(Patient_Name__c = o.id, Amount__c=10);
        insert pi;
        string id1=o.id;
        Test.startTest();
        //     PaymentScheduleApex.InsertRecordFromOppCreatePayment(id1);
        
        Test.stopTest();
        list<Payment_Schedule__c> paymentschedulelist=[select id,Opportunity__r.name from Payment_Schedule__c];
        System.assertEquals(1, 1, ' ');
        
        
    }
    static testMethod void CheckPaymentSchedule2(){
        
        Account a=new Account(name='TEST');
        
        insert a;
        Opportunity o=new Opportunity();
        o.Name='test';
        o.AccountId=a.id;
        o.StageName='Prospecting';
        o.CloseDate=system.today();
        
        o.Instalments_by_Frequency__c=100;
        o.LOC__c='IOP';
        o.Payment_Frequency__c='Monthly';
        
        insert o;
        Product2 p=new Product2(name='Admit Fee');
        insert p;
        PricebookEntry pe=new PricebookEntry(Product2Id=p.id,UnitPrice=200,Pricebook2Id=Test.getStandardPricebookId(),isactive=true);
        insert pe;
        OpportunityLineitem oli=new OpportunityLineitem(OpportunityId=o.id,quantity=2,Product2Id=p.id,PricebookEntryId=pe.id);
        oli.UnitPrice=200;
        insert oli;
        Payment_Information__c pi =new Payment_Information__c(Patient_Name__c = o.id, Amount__c=10);
        insert pi;
        string id1=o.id;
        Test.startTest();
        // PaymentScheduleApex.InsertRecordFromOppCreatePayment(id1);
        Test.stopTest();
        list<Payment_Schedule__c> paymentschedulelist=[select id,Opportunity__r.name from Payment_Schedule__c];
        System.assertEquals(1, 1, ' ');
        
    }
    static testMethod void CheckPaymentSchedule3(){
        
        Account a=new Account(name='TEST');
        
        insert a;
        Opportunity o=new Opportunity();
        o.Name='test';
        o.AccountId=a.id;
        o.StageName='Prospecting';
        o.CloseDate=system.today();
        
        o.Instalments_by_Frequency__c=100;
        o.LOC__c='IOP';
        o.Payment_Frequency__c='Weekly';
        
        insert o;
        Product2 p=new Product2(name='Admit Fee');
        insert p;
        PricebookEntry pe=new PricebookEntry(Product2Id=p.id,UnitPrice=200,Pricebook2Id=Test.getStandardPricebookId(),isactive=true);
        insert pe;
        OpportunityLineitem oli=new OpportunityLineitem(OpportunityId=o.id,quantity=2,Product2Id=p.id,PricebookEntryId=pe.id);
        oli.UnitPrice=200;
        insert oli;
        Payment_Information__c pi =new Payment_Information__c(Patient_Name__c = o.id, Amount__c=10);
        insert pi;
        string id1=o.id;
        Test.startTest();
        //  PaymentScheduleApex.InsertRecordFromOppCreatePayment(id1);
        Test.stopTest();
        list<Payment_Schedule__c> paymentschedulelist=[select id,Opportunity__r.name from Payment_Schedule__c];
        System.assertEquals(1, 1, ' ');
        
        
    }
    static testMethod void CheckPaymentSchedule4(){
        Account a=new Account(name='TEST');
        
        insert a;
        Opportunity o=new Opportunity();
        o.Name='test';
        o.AccountId=a.id;
        o.StageName='Prospecting';
        o.CloseDate=system.today();
        
        o.Instalments_by_Frequency__c=100;
        o.LOC__c='IOP';
        o.Payment_Frequency__c='Daily';
        
        insert o;
        Payment_Information__c p =new Payment_Information__c(Patient_Name__c = o.id, Amount__c=10);
        insert p;
        string id1=o.id;
        
        Test.startTest();
        //   PaymentScheduleApex.FetchOppdataForPayment(id1);
        Test.stopTest();
        System.assertEquals(1, 1, ' ');
        
    }
    
}