force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Notes__c/Notes__c.object-meta.xml
<CustomObject>
    <label>Notes</label>
    <nameField>
        <displayFormat>NT-{0000}</displayFormat>
        <label>Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notes__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notes__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/Sample_Analysis__c.object-meta.xml
<CustomObject>
    <label>Sample Analysis</label>
    <nameField>
        <label>UA Analysis Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sample Analysis</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Analysis__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Examined_By__c.field-meta.xml
<CustomField>
    <fullName>Examined_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Examined By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sample_Analysis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Examined_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Examined_Datetime__c</fullName>
    <label>Examined Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Lab_Sample_Examined_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Lab_Sample_Examined_Datetime__c</fullName>
    <label>Lab Sample Examined Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/UA_Sample_Details__c.field-meta.xml
<CustomField>
    <fullName>UA_Sample_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UA Sample Details</label>
    <referenceTo>UA_Sample_Details__c</referenceTo>
    <relationshipLabel>Sample Analysis</relationshipLabel>
    <relationshipName>Sample_Analysis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/UA_Sample_Details__c.object-meta.xml
<CustomObject>
    <label>UA Sample Detail</label>
    <nameField>
        <displayFormat>Lab Order-{0000}</displayFormat>
        <label>Lab Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UA Sample Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/UA_Sample_Details__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>UA Sample Details</relationshipLabel>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Additives_if_Any__c.field-meta.xml
<CustomField>
    <fullName>Additives_if_Any__c</fullName>
    <label>Additives,if Any</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Analysis_Result__c.field-meta.xml
<CustomField>
    <fullName>Analysis_Result__c</fullName>
    <label>Analysis Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Collection_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Collection_Datetime__c</fullName>
    <label>Collection Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Container_Description__c.field-meta.xml
<CustomField>
    <fullName>Container_Description__c</fullName>
    <label>Container Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/ContainerSize__c.field-meta.xml
<CustomField>
    <fullName>ContainerSize__c</fullName>
    <label>ContainerSize</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/ContainerType__c.field-meta.xml
<CustomField>
    <fullName>ContainerType__c</fullName>
    <label>ContainerType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Lab_Code__c.field-meta.xml
<CustomField>
    <fullName>Lab_Code__c</fullName>
    <label>Lab Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Lab_email__c.field-meta.xml
<CustomField>
    <fullName>Lab_email__c</fullName>
    <label>Lab email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Lab_Location__c.field-meta.xml
<CustomField>
    <fullName>Lab_Location__c</fullName>
    <label>Lab Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Lab_Name__c.field-meta.xml
<CustomField>
    <fullName>Lab_Name__c</fullName>
    <label>Lab Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Laboratory_Analysis_Date__c.field-meta.xml
<CustomField>
    <fullName>Laboratory_Analysis_Date__c</fullName>
    <label>Laboratory Analysis Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Order_By__c.field-meta.xml
<CustomField>
    <fullName>Order_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UA_Sample_Details1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Order_to__c.field-meta.xml
<CustomField>
    <fullName>Order_to__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order to</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Ordering_Physician__c.field-meta.xml
<CustomField>
    <fullName>Ordering_Physician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordering Physician</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Practitioner</value>
        </filterItems>
        <filterItems>
            <field>Contact.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>UA Sample Details</relationshipLabel>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Physical_Analysis_Date__c.field-meta.xml
<CustomField>
    <fullName>Physical_Analysis_Date__c</fullName>
    <label>Physical Analysis Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Sample_Type__c.field-meta.xml
<CustomField>
    <fullName>Sample_Type__c</fullName>
    <label>Sample Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>Laboratory</fullName>
            </value>
            <value>
                <fullName>LabOrder</fullName>
                <isActive>false</isActive>
                <label>LabOrder</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Specimen_Collector__c.field-meta.xml
<CustomField>
    <fullName>Specimen_Collector__c</fullName>
    <label>Specimen Collector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Specimen_Condition__c.field-meta.xml
<CustomField>
    <fullName>Specimen_Condition__c</fullName>
    <label>Specimen Condition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Specimen_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Specimen_Quantity__c</fullName>
    <label>Specimen Quantity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Results Received</fullName>
            </value>
            <value>
                <fullName>Final Order</fullName>
            </value>
            <value>
                <fullName>Draft Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/UA_Sample_Details__c.field-meta.xml
<CustomField>
    <fullName>UA_Sample_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UA Sample Details</label>
    <referenceTo>UA_Sample_Details__c</referenceTo>
    <relationshipLabel>UA Sample Details</relationshipLabel>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ElixirHC_UAListViewController.cls
public with sharing class ElixirHC_UAListViewController {
    
    @AuraEnabled
    public static wrapperForUARecords fetchAllRelatedUrineAnalysisRecordsForAccount(String accountId) {
        List<UA_Sample_Details__c> recordsLstUA = [SELECT CreatedById,CreatedDate,Account__c,Additives_if_Any__c,Collection_Datetime__c,Comments__c,
                                                              ContainerSize__c,ContainerType__c,Container_Description__c,Lab_Code__c,Lab_email__c,
                                                              Lab_Location__c,Lab_Name__c,Notes__c,Order_By__c,Order_to__c,Sample_Type__c
                                                              ,Specimen_Collector__c,Specimen_Condition__c,Specimen_Quantity__c,Id,IsDeleted,LastModifiedDate,
                                                              Name,Analysis_Result__c,Physical_Analysis_Date__c,Laboratory_Analysis_Date__c,OwnerId,Status__c,
                                                              (select id,Examined_Datetime__c,Status__c,LastModifiedDate from Sample_Analysis__r  ORDER BY CreatedDate DESC ),
                                                              (select id,LastModifiedDate from UA_Sample_Details__r ORDER BY CreatedDate DESC limit 1) FROM UA_Sample_Details__c 
                                                              WHERE Account__c= :accountId AND Sample_Type__c='Physical' AND RecordType.Name = 'Urine Analysis'    
                                                              WITH SECURITY_ENFORCED
                                                              ORDER BY CreatedDate DESC];
      /*  List<UA_Sample_Details__c> recordsLstUALab = [SELECT CreatedById,CreatedDate,Account__c,Additives_if_Any__c,Collection_Datetime__c,Comments__c,
                                                              Name,Analysis_Result__c,Physical_Analysis_Date__c,Laboratory_Analysis_Date__c,OwnerId,Status__c,
                                                              (select id,Lab_Sample_Examined_Datetime__c,Status__c from Sample_Analysis__r  ORDER BY CreatedDate DESC ),
                                                              (select id,LastModifiedDate from UA_Sample_Details__r ORDER BY CreatedDate DESC limit 1) FROM UA_Sample_Details__c 
                                                              WHERE Account__c= :accountId AND Sample_Type__c='Laboratory'     
                                                              ORDER BY CreatedDate DESC]; */
        Map<String,DateTime> relatedRecordsForLab = new Map<String,DateTime>();
        List<String> relatedLabAnalysisIDs = new List<String>();
        wrapperForUARecords dataReturn  = new wrapperForUARecords();
        try{
        for(UA_Sample_Details__c rec : recordsLstUA){
            if(rec.UA_Sample_Details__r.size()>0 && rec.UA_Sample_Details__r!=null){
                relatedLabAnalysisIDs.add(rec.UA_Sample_Details__r[0].Id);
            }
        }
        System.debug('related lab analysis ID '+relatedLabAnalysisIDs);
        List<Sample_Analysis__c> labAnalysisRecords = [SELECT id,Examined_Datetime__c,UA_Sample_Details__c,Lab_Sample_Examined_Datetime__c,
                                                                  UA_Sample_Details__r.UA_Sample_Details__r.Id from Sample_Analysis__c 
                                                                  where UA_Sample_Details__c in : relatedLabAnalysisIDs
                                                                  WITH SECURITY_ENFORCED];
        for(Sample_Analysis__c arrangeData : labAnalysisRecords){
            System.debug('parent id '+arrangeData.UA_Sample_Details__c);
            System.debug('datetime '+arrangeData.Examined_Datetime__c);
            relatedRecordsForLab.put(arrangeData.UA_Sample_Details__r.UA_Sample_Details__r.Id,arrangeData.Lab_Sample_Examined_Datetime__c);
            
        }
        System.debug('MAP VALUE '+relatedRecordsForLab);
        //wrapperForUARecords dataReturn  = new wrapperForUARecords();
        dataReturn.toReturnList = recordsLstUA ; 
        dataReturn.nameSpace=Elixir_Utility.getNamespace();
     //   dataReturn.toReturnListLab = recordsLstUALab ;
        dataReturn.toReturnMap = relatedRecordsForLab ; 
        }
        catch(Exception e){
            ExceptionLog.logError(e);
        }
        return dataReturn;
    }
    public class wrapperForUARecords {
        @AuraEnabled public List<UA_Sample_Details__c> toReturnList {get;set;}
        @AuraEnabled public List<UA_Sample_Details__c> toReturnListLab {get;set;}
        @AuraEnabled public  Map<String,DateTime> toReturnMap = new Map<String,DateTime>();
         @AuraEnabled public string nameSpace;
    }
    @AuraEnabled
    public static Boolean deleteRecords(List<String> lstRecordId) {
        Boolean flag = true;
        List<String> finalRecords = new List<String>(); 
        List<UA_Sample_Details__c> filterRecordsNotTodelete = [select id,Status__c 
        from UA_Sample_Details__c where id in : lstRecordId
        WITH SECURITY_ENFORCED];
        for(UA_Sample_Details__c rec : filterRecordsNotTodelete){
            System.debug('rec status '+rec.Status__c);
            if(rec.Status__c=='Open' || String.isEmpty(rec.Status__c)){
                finalRecords.add(rec.Id);
            }
        }
        List<String> oErrorMsg = new List<String> ();
        // Query Records for delete where id in lstRecordId [which is pass from client side controller] 
        List <UA_Sample_Details__c> lstDeleteRec = [select Id from UA_Sample_Details__c 
        where id IN: finalRecords
        WITH SECURITY_ENFORCED];
         Database.DeleteResult[] DR_Dels;
        if (Schema.sObjectType.UA_Sample_Details__c.isDeletable()) {
        DR_Dels = Database.delete(lstDeleteRec, false);
        }
        // Iterate through each returned result
        for (Database.DeleteResult dr: DR_Dels) {
            if (dr.isSuccess()) {
                system.debug('successful delete contact');
                // Operation was successful
            } else {
                flag = false;
                // Operation failed, so get all errors   
                oErrorMsg.add('');
                for (Database.Error err: dr.getErrors()) {
                    // add Error message to oErrorMsg list and return the list
                    oErrorMsg.add(err.getStatusCode() + ': ' + err.getMessage());
                }
            }
        }
        return flag;  
    }
    
    @AuraEnabled
    public static Boolean sendEmailNotificationToUAMember(String toSendEmailFaux,String detailPageRecordID) {
        Boolean emaiNotExistsOrDirtyEmail = false;
        Boolean allowProceed = true;
        List<User> getEmail  = [select id,email from user where id=:toSendEmailFaux WITH SECURITY_ENFORCED];
        String toValidate  = getEmail[0].email;
        if(!String.isEmpty(toValidate)){
            allowProceed = ElixirHC_UAListViewController.validateEmail(toValidate); 
        }
        else {
            emaiNotExistsOrDirtyEmail = true; 
        }
        if(allowProceed){
            String baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
            //String orgWideValid  = Elixir_utility.getNamespace();  kishan comments not needed right now
            System.debug('base url '+baseUrl);
            String orgWideValid  = '';
            List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();   
            for(User forEmail :  getEmail) {
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();                        
                mail.setSaveAsActivity(false);
                // mail.setTemplateId(theTemplate);
                // mail.setWhatId(poId);
                mail.setSenderDisplayName('Salesforce ELIXIR Support');
                mail.setSubject('UA CREATED!');                       
                mail.setPlainTextBody('UA has been created.');
                mail.setHtmlBody('UA has been created.'+ 
                                 'To view  <a href='+baseUrl+'/lightning/r/'+orgWideValid+'Create_Sample/'+detailPageRecordID+'/view>Click here.</a>');                     
                mail.setTargetObjectId(forEmail.Id);
                mail.setToAddresses(new String[] {forEmail.Email});  //add other emails here.
                emails.add(mail); 
            }
            Messaging.sendEmail(emails); 
        }
        else {
            emaiNotExistsOrDirtyEmail= !allowProceed;
        }
        // ElixirHC_UAListViewController.sendPDf(detailPageRecordID,'tanveer.ahmed@mirketa.com');
        return emaiNotExistsOrDirtyEmail; 
        
    }
    @AuraEnabled
    public static Boolean validateEmail(String email) {
        Boolean res = true;
        String emailRegex = '^[a-zA-Z0-9._|\\\\%#~`=?&/$^*!}{+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$'; 
        Pattern MyPattern = Pattern.compile(emailRegex);
        Matcher MyMatcher = MyPattern.matcher(email);
        if (!MyMatcher.matches()) 
            res = false;
        return res;	
    }
    @AuraEnabled
    public static void sendPdfForUA(String pdfName,String record,String patientId,String forpdf){
         System.debug('pdf name '+pdfName);
          System.debug('pART 2 '+pdfName);
        String patientName = '';
        List<Account> forPatientName = [select id,name from Account where id  = : patientId WITH SECURITY_ENFORCED];
        if(forPatientName.size()>0 && forPatientName!=null){
            patientName = forPatientName[0].Name;
        }
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        PageReference pdf ;
        if(pdfName=='PhysicalAnalysis'){
            pdf = Page.ElixirHC_PhysicalAnalysisPDFGenerator; 
            System.debug('for pdf data '+forpdf);
        pdf.getParameters().put('orderId',forpdf);
        }
        if(pdfName=='LabSampleAnalysis'){
            System.debug('INSIDE LAB ANLYSIS');
            pdf = Page.ElixirHC_LabAnalysisPDFGenerator;
            pdf.getParameters().put('orderId',forpdf);
        }
       
        // goToNextPage('email');
        Blob body;                
        try{
            body = pdf.getContent();
        }catch(VisualforceException e){
            body=Blob.valueOf('Some text');
        }
        Boolean emaiNotExistsOrDirtyEmail = false;
        Boolean allowProceed = true;
        List<String> allEmailAdd = new List<String>();
       // List<User> getAllUsers  = [select Id,Username,Email,profile.name,UserRole.Name,UserRole.id from user where profile.name='System Administrator' or UserRole.Name='Doctor' or UserRole.Name='Nurse'];
        List<User> getAllUsers  = [select Id,Username,Email,profile.name,UserRole.Name,UserRole.id from user where Id=: UserInfo.getUserId()
        WITH SECURITY_ENFORCED];
        for(User forEmail : getAllUsers) {
           
            System.debug('email forRepeaat '+forEmail.Email);
            if(ElixirHC_UAListViewController.validateEmail(forEmail.Email)){
                 allEmailAdd.add(forEmail.Email);
            }
           
            
        }
        Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
                attach.setContentType('application/pdf');
                attach.setFileName(pdfName+' REPORT || '+patientName +'.pdf'); 
                attach.setInline(false);
                attach.Body = body;
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setTargetObjectId( UserInfo.getUserId() );
                mail.setSaveAsActivity( false );
                mail.setUseSignature(false);
                mail.setToAddresses(allEmailAdd);
                System.debug('buffer array '+mail);
                mail.setSubject(pdfName+'REPORT');
                mail.setHtmlBody('Analysis is complete for patient '+patientName+'! Please find out the attached pdf for the results.');
                mail.setFileAttachments(new Messaging.EmailFileAttachment[] { attach }); 
        		emails.add(mail);
         		Messaging.sendEmail(emails);
       //  Messaging.sendEmail(emails);
        
    }
    
    @AuraEnabled
    public static boolean checkCareEpisode(string patientId){      
        
         //added by Anmol for LX3-7236
         Boolean result = Elixir_Utility.checkCareEpisodeUtility(patientId);
         return result;
         //end by Anmol for LX3-7236
       
    }
    
    /*  public PageReference sendPdf(){                
PageReference pdf = Page.ElixirHC_PhysicalAnalysisPDFGenerator;//mail_pdf is the name of vf page
pdf.getParameters().put('orderId','a1gN0000001pPfhIAE');
// goToNextPage('email');
Blob body;                
try{
body = pdf.getContent();
}catch(VisualforceException e){
body=Blob.valueOf('Some text');
}            
Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
attach.setContentType('application/pdf');
attach.setFileName('testPdf.pdf');
attach.setInline(false);
attach.Body = body;
Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
mail.setUseSignature(false);
mail.setToAddresses(new String[] { 'tanveer.ahmed@mirketa.com' });
mail.setSubject('PDF Email Demo');
mail.setHtmlBody('Here is the email you requested! Check the attachment!');
mail.setFileAttachments(new Messaging.EmailFileAttachment[] { attach }); 
// Send the email    
Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
// ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Email with PDF sent to '+email));
return null;
}
*/
    
}