force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notes__c/Notes__c.object-meta.xml
<CustomObject>
    <label>Notes</label>
    <nameField>
        <displayFormat>NT-{0000}</displayFormat>
        <label>Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notes__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Notes__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Doctor Notes</fullName>
            </value>
            <value>
                <fullName>Nursing Notes</fullName>
            </value>
            <value>
                <fullName>Clinician Notes</fullName>
            </value>
            <value>
                <fullName>Session Notes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/Sample_Analysis__c.object-meta.xml
<CustomObject>
    <label>Sample Analysis</label>
    <nameField>
        <label>UA Analysis Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sample Analysis</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Analysis__c/fields/Appearance__c.field-meta.xml
<CustomField>
    <fullName>Appearance__c</fullName>
    <label>Appearance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Clear</fullName>
            </value>
            <value>
                <fullName>Hazy</fullName>
            </value>
            <value>
                <fullName>Cloudy</fullName>
            </value>
            <value>
                <fullName>Turbid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Bacteria__c.field-meta.xml
<CustomField>
    <fullName>Bacteria__c</fullName>
    <label>Bacteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Bilesalt__c.field-meta.xml
<CustomField>
    <fullName>Bilesalt__c</fullName>
    <label>Bilesalt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Bilrubin__c.field-meta.xml
<CustomField>
    <fullName>Bilrubin__c</fullName>
    <label>Bilrubin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Casts__c.field-meta.xml
<CustomField>
    <fullName>Casts__c</fullName>
    <label>Casts</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Colour__c.field-meta.xml
<CustomField>
    <fullName>Colour__c</fullName>
    <label>Colour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Colourless</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Amber</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Crystal__c.field-meta.xml
<CustomField>
    <fullName>Crystal__c</fullName>
    <label>Crystal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Epithelial_Cells__c.field-meta.xml
<CustomField>
    <fullName>Epithelial_Cells__c</fullName>
    <label>Epithelial Cells</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Examined_By__c.field-meta.xml
<CustomField>
    <fullName>Examined_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Examined By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sample_Analysis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Examined_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Examined_Datetime__c</fullName>
    <label>Examined Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Glucose__c.field-meta.xml
<CustomField>
    <fullName>Glucose__c</fullName>
    <label>Glucose</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Ketone__c.field-meta.xml
<CustomField>
    <fullName>Ketone__c</fullName>
    <label>Ketone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Lab_Sample_Examined_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Lab_Sample_Examined_Datetime__c</fullName>
    <label>Lab Sample Examined Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Leukocyte__c.field-meta.xml
<CustomField>
    <fullName>Leukocyte__c</fullName>
    <label>Leukocyte</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Mucus__c.field-meta.xml
<CustomField>
    <fullName>Mucus__c</fullName>
    <label>Mucus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/PH__c.field-meta.xml
<CustomField>
    <fullName>PH__c</fullName>
    <label>PH</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Picklist__c.field-meta.xml
<CustomField>
    <fullName>Picklist__c</fullName>
    <label>Picklist</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Colourless</fullName>
            </value>
            <value>
                <fullName>yellow</fullName>
            </value>
            <value>
                <fullName>Amber</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Protein__c.field-meta.xml
<CustomField>
    <fullName>Protein__c</fullName>
    <label>Protein</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Puss_Cells_W_B_C__c.field-meta.xml
<CustomField>
    <fullName>Puss_Cells_W_B_C__c</fullName>
    <label>Puss Cells (W.B.C)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Red_Cells_R_B_C__c.field-meta.xml
<CustomField>
    <fullName>Red_Cells_R_B_C__c</fullName>
    <label>Red Cells (R.B.C)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Schistosoma_Eggs__c.field-meta.xml
<CustomField>
    <fullName>Schistosoma_Eggs__c</fullName>
    <label>Schistosoma Eggs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Specific_Gravity__c.field-meta.xml
<CustomField>
    <fullName>Specific_Gravity__c</fullName>
    <label>Specific Gravity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Specimen_Status__c.field-meta.xml
<CustomField>
    <fullName>Specimen_Status__c</fullName>
    <label>Specimen Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Spermatozoa__c.field-meta.xml
<CustomField>
    <fullName>Spermatozoa__c</fullName>
    <label>Spermatozoa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Trichomonas__c.field-meta.xml
<CustomField>
    <fullName>Trichomonas__c</fullName>
    <label>Trichomonas</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>Laboratory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/UA_Sample_Details__c.field-meta.xml
<CustomField>
    <fullName>UA_Sample_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UA Sample Details</label>
    <referenceTo>UA_Sample_Details__c</referenceTo>
    <relationshipLabel>Sample Analysis</relationshipLabel>
    <relationshipName>Sample_Analysis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Urobilinogen__c.field-meta.xml
<CustomField>
    <fullName>Urobilinogen__c</fullName>
    <label>Urobilinogen</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/fields/Yeast_Cells__c.field-meta.xml
<CustomField>
    <fullName>Yeast_Cells__c</fullName>
    <label>Yeast Cells</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/UA_Sample_Details__c.object-meta.xml
<CustomObject>
    <label>UA Sample Detail</label>
    <nameField>
        <displayFormat>Lab Order-{0000}</displayFormat>
        <label>Lab Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UA Sample Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/UA_Sample_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Results Received</fullName>
            </value>
            <value>
                <fullName>Final Order</fullName>
            </value>
            <value>
                <fullName>Draft Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/UA_Sample_Details__c.field-meta.xml
<CustomField>
    <fullName>UA_Sample_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UA Sample Details</label>
    <referenceTo>UA_Sample_Details__c</referenceTo>
    <relationshipLabel>UA Sample Details</relationshipLabel>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestElixirHC_LabAnalysisHelper.cls
@isTest
public class TestElixirHC_LabAnalysisHelper {
    
    
    public  static testMethod void allCoverageParentMethod(){
        ElixirHC_LabAnalysisHelper.getStringifiedDate(System.today());
        List<Sample_Analysis__c> rec = [SELECT CreatedById,CreatedDate,Appearance__c,Bacteria__c,Bilesalt__c,
                                        Bilrubin__c,Casts__c,Colour__c,Comments__c,
                                        Crystal__c,Epithelial_Cells__c,Examined_By__c,
                                        Examined_Datetime__c,Glucose__c,Ketone__c,
                                        Lab_Sample_Examined_Datetime__c,Leukocyte__c,Mucus__c,
                                        Notes__c,PH__c,Picklist__c,Protein__c,
                                        Puss_Cells_W_B_C__c,Red_Cells_R_B_C__c,Schistosoma_Eggs__c,Specific_Gravity__c,Specimen_Status__c,
                                        Spermatozoa__c,Status__c,Trichomonas__c,Type__c,UA_Sample_Details__c,Urobilinogen__c,
                                        Yeast_Cells__c,Id,IsDeleted FROM Sample_Analysis__c limit 1];
        Sample_Analysis__c instance;
        Sample_Analysis__c newInstance  = new Sample_Analysis__c();
        newInstance.Lab_Sample_Examined_Datetime__c = System.now();
        newInstance.Examined_By__c = UserInfo.getUserId();
        insert newInstance;
        
        Account acc= new Account(Name='Test');
        insert acc;
        
        //  if(rec.size()>0 && rec!=null){
        //  instance =  rec[0];
        //  }
        String jsn = JSON.serialize(newInstance);
        // String jsn = '{"CreatedDate":"2020-09-16T09:27:18.000Z","Elixir_HC__Additives_if_Any__c":"None","Elixir_HC__Collection_Datetime__c":"2020-09-16T09:26:00.000Z","Elixir_HC__ContainerSize__c":"50mL","Elixir_HC__ContainerType__c":"Normal","Elixir_HC__Container_Description__c":"T-Cup","Elixir_HC__Sample_Type__c":"Physical","Elixir_HC__Specimen_Collector__c":"Provider","Elixir_HC__Specimen_Condition__c":"Good","Elixir_HC__Specimen_Quantity__c":"30mL","IsDeleted":false,"LastModifiedDate":"2020-09-16T09:27:18.000Z","Name":"UA-0747","Elixir_HC__Status__c":"Open","Elixir_HC__Lab_Sample_Examined_Datetime__c" : "2020-09-16T09:27:18.000Z","Examined_By__c" : ""}';
        // PageReference pageRef = Page.LabAnalysisPDFGenerator;
        // Test.setCurrentPage(pageRef);
        // ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(jsn);
        ApexPages.currentPage().getParameters().put('orderId',jsn);
        ElixirHC_LabAnalysisHelper inititate = new ElixirHC_LabAnalysisHelper(); 
        inititate.getAccountInfo(acc.Id);
        system.assert( acc.Name!=null); 
    }
    
}