force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Unallocated_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unallocated_Amount__c</fullName>
    <description>Denotes the unallocated financial amount associated with the account.</description>
    <label>Unallocated Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Actual_Price__c/Actual_Price__c.object-meta.xml
<CustomObject>
    <description>Indicates the List price for a procedure w.r.t the Provider.</description>
    <label>Actual Price</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Actual Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actual Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Transaction__c/Master_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object contains the details of payments collected from customer in form of advance payment via cash/credit card/cheque or any other mode of payment. This object also contains patient credits as well.</description>
    <label>Other Transactions</label>
    <nameField>
        <displayFormat>OT-{0000}</displayFormat>
        <label>Other Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Master_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Transaction__c/fields/Allocated_Amount__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Amount__c</fullName>
    <label>Allocated Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object contains the summary of all the transactional details linked with a patient procedure. Also it contains the rollup for patient paid amount, total refund amount, total discount applied, primary insurance paid and secondary insurance paid amount.</description>
    <label>Master Transaction</label>
    <nameField>
        <displayFormat>PAYMENT-{0000}</displayFormat>
        <label>Payment Received Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Transaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Payment_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Actual_Price__c.field-meta.xml
<CustomField>
    <fullName>Actual_Price__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Actual Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Date_Of_Service__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Service__c</fullName>
    <label>Date Of Service</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Master_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Master_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Transaction</label>
    <referenceTo>Master_Transaction__c</referenceTo>
    <relationshipName>Payment_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Payment_Sub_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Payment_Sub_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Transaction</label>
    <referenceTo>Payment_Transaction__c</referenceTo>
    <relationshipName>Payment_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Debit Card</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Net Banking</fullName>
            </value>
            <value>
                <fullName>UPI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Received_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Received Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>UnPaid</fullName>
            </value>
            <value>
                <fullName>Payment Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdatePaymentTransaction.cls
public with sharing class UpdatePaymentTransaction {
    
    public static void updateTxn(Id accId, Decimal amountPaid, Decimal amountAllocated, Date payDate, List<Id> payTrans) {
        if(accId != null) {
            if(payTrans.size() > 0 && amountPaid > 0) {
                
                Master_Transaction__c newMasterTxnAllo = new Master_Transaction__c();
                try{
                newMasterTxnAllo.Allocated_Amount__c = amountPaid;
                newMasterTxnAllo.Payment_Type__c = 'Allocated';
                if(Schema.sObjectType.Master_Transaction__c.fields.Allocated_Amount__c.isCreateable() &&
                Schema.sObjectType.Master_Transaction__c.fields.Payment_Type__c.isCreateable()){
                    insert newMasterTxnAllo;
                }
                }
                catch(Exception e){
            ExceptionLog.logError(e);
                   }
                Decimal amtLeftToAllocate = amountPaid;
                List<Payment_Transaction__c> paymentTxnsToInsert = new List<Payment_Transaction__c>();
                
                List<Payment_Transaction__c> paymentTxnsToUpdate =  [Select ElixirSuite__PatientOutstanding__c,
                                                                     Received_Amount__c,
                                                                     Account__c,
                                                                     status__c,
                                                                     Actual_Price__c 
                                                                     from  Payment_Transaction__c 
                                                                     where Id in :PayTrans
                                                                     WITH SECURITY_ENFORCED
                                                                     Order By Date_Of_Service__c];
                
                
                for(Payment_Transaction__c paymentTxnRec : paymentTxnsToUpdate) {
                    if(amtLeftToAllocate > 0) {
                        
                        if(amtLeftToAllocate >= paymentTxnRec.ElixirSuite__PatientOutstanding__c) {
                            
                            Payment_Transaction__c newPaymentTxn = new Payment_Transaction__c();
                            newPaymentTxn.Payment_Date__c = payDate;
                            newPaymentTxn.Received_Amount__c = paymentTxnRec.ElixirSuite__PatientOutstanding__c;
                            newPaymentTxn.Payment_Sub_Transaction__c = paymentTxnRec.Id;
                            newPaymentTxn.Master_Transaction__c = newMasterTxnAllo.Id;
                            paymentTxnsToInsert.add(newPaymentTxn);
                            
                            paymentTxnRec.Received_Amount__c = paymentTxnRec.Received_Amount__c + paymentTxnRec.ElixirSuite__PatientOutstanding__c;
                            paymentTxnRec.Status__c = 'Paid';
                            
                            amtLeftToAllocate = amtLeftToAllocate - newPaymentTxn.Received_Amount__c;
                            
                        } else {
                            
                            Payment_Transaction__c newPaymentTxn = new Payment_Transaction__c();
                            newPaymentTxn.Payment_Date__c = payDate;
                            newPaymentTxn.Received_Amount__c = amtLeftToAllocate;
                            newPaymentTxn.Payment_Sub_Transaction__c = paymentTxnRec.Id;
                            newPaymentTxn.Master_Transaction__c = newMasterTxnAllo.Id;
                            paymentTxnsToInsert.add(newPaymentTxn);
                            
                            paymentTxnRec.Received_Amount__c = paymentTxnRec.Received_Amount__c + amtLeftToAllocate;
                            paymentTxnRec.Status__c = 'Payment Started';
                            
                            amtLeftToAllocate = 0;
                        }
                    }
                    
                }
                
                if(amtLeftToAllocate > 0) {                   
                    Master_Transaction__c newMasterTxnUnallo = new Master_Transaction__c();
                    try{
                    newMasterTxnUnallo.Allocated_Amount__c = amtLeftToAllocate;
                    newMasterTxnUnallo.Payment_Type__c = 'Unallocated';
                    if(Schema.sObjectType.Master_Transaction__c.fields.Allocated_Amount__c.isCreateable() &&
                    Schema.sObjectType.Master_Transaction__c.fields.Payment_Type__c.isCreateable()){
                    insert newMasterTxnUnallo;
                    }
                    }
                    catch(Exception e){
                     ExceptionLog.logError(e);
                          }
                    Account patientAcc = [Select Unallocated_Amount__c FROM Account WHERE ID =:accId WITH SECURITY_ENFORCED];
                    if(Schema.sObjectType.Account.fields.Unallocated_Amount__c.isUpdateable()){
                    patientAcc.Unallocated_Amount__c = patientAcc.Unallocated_Amount__c + newMasterTxnUnallo.Allocated_Amount__c;
                    update patientAcc;
                    }
                }
                
                if(paymentTxnsToInsert.size() > 0) {
                    try{
                    if(Schema.sObjectType.Payment_Transaction__c.fields.Payment_Date__c.isCreateable() &&
                    Schema.sObjectType.Payment_Transaction__c.fields.Received_Amount__c.isCreateable() &&
                    Schema.sObjectType.Payment_Transaction__c.fields.Payment_Sub_Transaction__c.isCreateable() &&
                    Schema.sObjectType.Payment_Transaction__c.fields.Master_Transaction__c.isCreateable() &&
                    Schema.sObjectType.Payment_Transaction__c.fields.Received_Amount__c.isCreateable() &&
                    Schema.sObjectType.Payment_Transaction__c.fields.Status__c.isCreateable()){
                    insert paymentTxnsToInsert;
                    }
                    }
                    catch(Exception e){
                    ExceptionLog.logError(e);
                   }
                }
                try{
                if(paymentTxnsToUpdate.size() > 0) {
                    if(Schema.sObjectType.Payment_Transaction__c.fields.Payment_Date__c.isUpdateable() &&
                    Schema.sObjectType.Payment_Transaction__c.fields.Received_Amount__c.isUpdateable() &&
                    Schema.sObjectType.Payment_Transaction__c.fields.Payment_Sub_Transaction__c.isUpdateable() &&
                    Schema.sObjectType.Payment_Transaction__c.fields.Master_Transaction__c.isUpdateable() &&
                    Schema.sObjectType.Payment_Transaction__c.fields.Received_Amount__c.isUpdateable() &&
                    Schema.sObjectType.Payment_Transaction__c.fields.Status__c.isUpdateable()){
                    update paymentTxnsToUpdate;
                    }
                }
                    
                }
                catch(Exception e){
            ExceptionLog.logError(e);
        }
                
            } else if(payTrans.size() == 0 && amountPaid > 0) {
                
                Master_Transaction__c newMasterTxnUnallo = new Master_Transaction__c();
                newMasterTxnUnallo.Allocated_Amount__c = amountPaid;
                newMasterTxnUnallo.Payment_Type__c = 'Unallocated';
                if(Schema.sObjectType.Master_Transaction__c.fields.Allocated_Amount__c.isCreateable() &&
                Schema.sObjectType.Master_Transaction__c.fields.Payment_Type__c.isCreateable()){
                insert newMasterTxnUnallo;
                }
                
                Account patientAcc = [Select Unallocated_Amount__c FROM Account WHERE ID =:accId WITH SECURITY_ENFORCED];
                if(Schema.sObjectType.Account.fields.Unallocated_Amount__c.isUpdateable()){
                patientAcc.Unallocated_Amount__c = patientAcc.Unallocated_Amount__c + newMasterTxnUnallo.Allocated_Amount__c;
                update patientAcc;
                }
                
            } else if(payTrans.size() > 0 && amountAllocated > 0) {
                
                Master_Transaction__c newMasterTxnAllo = new Master_Transaction__c();
                newMasterTxnAllo.Allocated_Amount__c = amountAllocated;
                newMasterTxnAllo.Payment_Type__c = 'Allocated';
                if(Schema.sObjectType.Master_Transaction__c.fields.Allocated_Amount__c.isCreateable() &&
                Schema.sObjectType.Master_Transaction__c.fields.Payment_Type__c.isCreateable()){
                insert newMasterTxnAllo;
                }
                
                Decimal amtLeftToAllocate = amountAllocated;
                List<Payment_Transaction__c> paymentTxnsToInsert = new List<Payment_Transaction__c>();
                
                List<Payment_Transaction__c> paymentTxnsToUpdate =  [Select ElixirSuite__PatientOutstanding__c,
                                                                     Received_Amount__c,
                                                                     Account__c,
                                                                     status__c,
                                                                     Actual_Price__c 
                                                                     from  Payment_Transaction__c 
                                                                     where Id in :PayTrans
                                                                     WITH SECURITY_ENFORCED
                                                                     Order By Date_Of_Service__c];
                
                
                for(Payment_Transaction__c paymentTxnRec : paymentTxnsToUpdate) {
                    if(amtLeftToAllocate > 0) {
                        
                        if(amtLeftToAllocate >= paymentTxnRec.ElixirSuite__PatientOutstanding__c) {
                            
                            Payment_Transaction__c newPaymentTxn = new Payment_Transaction__c();
                            newPaymentTxn.Payment_Date__c = payDate;
                            newPaymentTxn.Received_Amount__c = paymentTxnRec.ElixirSuite__PatientOutstanding__c;
                            newPaymentTxn.Payment_Sub_Transaction__c = paymentTxnRec.Id;
                            newPaymentTxn.Master_Transaction__c = newMasterTxnAllo.Id;
                            paymentTxnsToInsert.add(newPaymentTxn);
                  
                            paymentTxnRec.Received_Amount__c = paymentTxnRec.Received_Amount__c + paymentTxnRec.ElixirSuite__PatientOutstanding__c;
                            paymentTxnRec.Status__c = 'Paid';
                            
                            amtLeftToAllocate = amtLeftToAllocate - newPaymentTxn.Received_Amount__c;
                            
                        } else {
                            
                            Payment_Transaction__c newPaymentTxn = new Payment_Transaction__c();
                            newPaymentTxn.Payment_Date__c = payDate;
                            newPaymentTxn.Received_Amount__c = amtLeftToAllocate;
                            newPaymentTxn.Payment_Sub_Transaction__c = paymentTxnRec.Id;
                            newPaymentTxn.Master_Transaction__c = newMasterTxnAllo.Id;
                            paymentTxnsToInsert.add(newPaymentTxn);
                            
                            paymentTxnRec.Received_Amount__c = paymentTxnRec.Received_Amount__c + amtLeftToAllocate;
                            paymentTxnRec.Status__c = 'Payment Started';
                            
                            amtLeftToAllocate = 0;
                        }
                    }
                    
                }
                
                Account patientAcc = [Select Unallocated_Amount__c 
                                    FROM Account 
                                    WHERE ID =:accId
                                    WITH SECURITY_ENFORCED];
                if(Schema.sObjectType.Account.fields.Unallocated_Amount__c.isUpdateable()){
                patientAcc.Unallocated_Amount__c = patientAcc.Unallocated_Amount__c - amountAllocated + amtLeftToAllocate;
                update patientAcc;
                }
            }
        }
    }
}