force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Verification_Code__c.field-meta.xml
<CustomField>
    <fullName>Verification_Code__c</fullName>
    <description>Stores the verification code associated with the account.</description>
    <label>Verification Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Frequency__c/Frequency__c.object-meta.xml
<CustomObject>
    <label>Frequency</label>
    <nameField>
        <displayFormat>Frequency-{0000}</displayFormat>
        <label>Frequency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Frequency</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UA_Sample_Details__c/UA_Sample_Details__c.object-meta.xml
<CustomObject>
    <label>UA Sample Detail</label>
    <nameField>
        <displayFormat>Lab Order-{0000}</displayFormat>
        <label>Lab Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UA Sample Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/UA_Sample_Details__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>UA Sample Details</relationshipLabel>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Once</fullName>
                <default>true</default>
                <label>Once</label>
            </value>
            <value>
                <fullName>Every Day</fullName>
            </value>
            <value>
                <fullName>Every 2 Days</fullName>
            </value>
            <value>
                <fullName>Every 3 Days</fullName>
            </value>
            <value>
                <fullName>Every 5 Days</fullName>
            </value>
            <value>
                <fullName>Every 7 Days</fullName>
            </value>
            <value>
                <fullName>Every 2 weeks</fullName>
            </value>
            <value>
                <fullName>Once a month</fullName>
            </value>
            <value>
                <fullName>On return from pass or outing</fullName>
            </value>
            <value>
                <fullName>When attending IOP/OP group</fullName>
            </value>
            <value>
                <fullName>Confirm positive analyzer results</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Medical_Test__c.field-meta.xml
<CustomField>
    <fullName>Medical_Test__c</fullName>
    <label>Medical Test</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/On_Admission__c.field-meta.xml
<CustomField>
    <fullName>On_Admission__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Admission</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Ordered_By__c.field-meta.xml
<CustomField>
    <fullName>Ordered_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordered By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EHR_Procedure_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Ordered_Via__c.field-meta.xml
<CustomField>
    <fullName>Ordered_Via__c</fullName>
    <label>Ordered Via</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Phone, read back and verified</fullName>
            </value>
            <value>
                <fullName>Verbal, read back and verified</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
            <value>
                <fullName>Previously prescribed medication approved by doctor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Results Received</fullName>
            </value>
            <value>
                <fullName>Final Order</fullName>
            </value>
            <value>
                <fullName>Draft Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/UA_Sample_Details__c.field-meta.xml
<CustomField>
    <fullName>UA_Sample_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UA Sample Details</label>
    <referenceTo>UA_Sample_Details__c</referenceTo>
    <relationshipLabel>UA Sample Details</relationshipLabel>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestLabOrderController.cls
@isTest
public class TestLabOrderController { 
    @isTest
    public static  void  method1(){
        Account a  = new Account();
        a.name='testAccount';
        a.Verification_Code__c = '101';
        a.Phone='0123456789';
        a.BillingPostalCode='85212';
        insert a;
        Account acc  = new Account();
        acc.name='testAccount1';
        acc.Verification_Code__c = '1101';
        acc.Phone='01234567819';
        acc.BillingPostalCode='185212';
        insert acc;
        UA_Sample_Details__c testDelete  = new UA_Sample_Details__c();
        testDelete.Account__c = a.id;
        insert testDelete;
        LabOrderController.getLabOrder(testDelete.id);
        LabOrderController.deleteLabOrderRecord(testDelete.id);
        List<UA_Sample_Details__c> lstDemo = new  List<UA_Sample_Details__c>();
        for (Integer i=0;i<10;i++) {
            UA_Sample_Details__c p = new UA_Sample_Details__c();
            p.Account__c=a.id;       
            lstDemo.add(p);
        }
        insert lstDemo;
        List<String> recToDelete  = new List<String>();
        for (UA_Sample_Details__c temp :  lstDemo){
            recToDelete.add(temp.id);         
        }
        LabOrderController.deleteRecords(recToDelete);
        LabOrderController.getCode(a.Id);
        LabOrderController.getRelatedLabOrder(a.id);
        UA_Sample_Details__c forSave  = new UA_Sample_Details__c();
        forsave.Start_Date__c=system.today();
        forSave.On_Admission__c=true;
        forSave.Frequency__c='Every 3 Days';
        forSave.Fax__c='011INDIA';
        forSave.Medical_Test__c='';
        forSave.Ordered_Via__c='Verbal, read back and verified';
        forSave.Ordered_By__c=UserInfo.getUserId();
        forSave.Account__c = a.id;

        insert forSave;
        List<String> newLit= new List<String>();
        newLit.add(forSave.id);

        //String procValue  = '{"sobjectType":"UA_Sample_Details__c","Start_Date__c":"2020-02-19","On_Admission__c":true,"Frequency__c":"Every 3 Days","Fax__c":"011","Medical_Test__c":"","Ordered_Via__c":"Verbal, read back and verified"}';
        //string necessityDetails = 'demo deails';
        //String acct  = a.id;
        //String medVal = 'Demo medicine';
        // HealthCloudGA__EHRProcedureRequest__c procReq,
        // String acct ,String starttimeProcedure , String endtimeProcedure,String attachId,String commentSign,string LabOrderID
        String stTime = String.valueOf(system.now());
        String edTime = String.valueOf(system.now() + 2);


        Attachment attach=new Attachment(); 
        attach.Name='Unit Test Attachment'; 
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body'); 
        attach.body=bodyBlob; attach.parentId=a.id;
        insert attach;
        ElixirSuite__UA_Sample_Details__c labOrder = new ElixirSuite__UA_Sample_Details__c();
        labOrder.ElixirSuite__Account__c=acc.id;
        labOrder.Status__c='In Progress';
        insert labOrder;
        
       



        // LabOrderController.saveRecord(forSave,necessityDetails,acct,medVal ,stTime , edTime );
        LabOrderController.saveRecordAfterEdit(forSave,userinfo.getUserId(),forSave.Id,stTime,edTime,attach.Id,'Demo comment','30/6/2020',forSave.Id);
        LabOrderController.saveSign(attach.Id , 'Demo comment','30/6/2020',forSave.Id);
        LabOrderController.getAllUser();
        LabOrderController.UpdateRecords(newLit);
        LabOrderController.fetchCusomMetadataRecord();
        LabOrderController.getAllPicklistValues();
        LabOrderController.checkCareEpisode(a.id);
        LabOrderController.saveRecord(lstDemo, 'necessityDetails', a.id, 'medVal','30/6/2020', '30/8/2020');
        LabOrderController.fetchAccountName(a.id);
        LabOrderController.saveColumnsApex('Text');
        //LabOrderController.attachApprovalDataToLabOrder(labOrder.id,'Completed');
        LabOrderController.getLabNames();
        LabOrderController.getAvailableTestName();
       
        system.assert(a.Name!=null); 
        
        //added by Shivank
         

       
        
        // Create test data for JSON input
        List<OrderSignatureSave.SignAndAprroveData> approvalData = new List<OrderSignatureSave.SignAndAprroveData>();
        OrderSignatureSave.SignAndAprroveData approval1 = new OrderSignatureSave.SignAndAprroveData();
        approval1.approvalLevel = 1;
        approval1.dateOfApproval = Date.today();
        approval1.comments = 'Approval 1 Comment';
        approval1.userId = UserInfo.getUserId();
        approvalData.add(approval1);
        
        OrderSignatureSave.SignAndAprroveData approval2 = new OrderSignatureSave.SignAndAprroveData();
        approval2.approvalLevel = 2;
        approval2.dateOfApproval = Date.today();
        approval2.comments = 'Approval 2 Comment';
        approval2.userId = UserInfo.getUserId();
        approvalData.add(approval2);
        
        OrderSignatureSave.SignAndAprroveData approval3 = new OrderSignatureSave.SignAndAprroveData();
        approval3.approvalLevel = 3;
        approval3.dateOfApproval = Date.today();
        approval3.comments = 'Approval 3 Comment';
        approval3.userId = UserInfo.getUserId();
        approvalData.add(approval3);
        
        // Convert approvalData to JSON string
        String approvalDataJson = JSON.serialize(approvalData);
        
        // Call the method being tested
        Test.startTest();
        String labOrderId = LabOrderController.attachApprovalDataToLabOrder(labOrder.Id, approvalDataJson);
        Test.stopTest();
        
        // Retrieve the lab order after the method call
        ElixirSuite__UA_Sample_Details__c updatedLabOrder = [SELECT Id, Status__c FROM ElixirSuite__UA_Sample_Details__c WHERE Id = :labOrderId];
        
        // Assert that the lab order was updated
        System.assertEquals('In Progress', updatedLabOrder.Status__c, 'Lab Order status should be "In Progress" after approval.');
        
    }

}