force-app/main/default/objects/Account/fields/Total_Patient_Responsibility__c.field-meta.xml
<CustomField>
    <fullName>Total_Patient_Responsibility__c</fullName>
    <description>Records the total financial responsibility assigned to the patient.</description>
    <label>Total Patient Responsibility</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/Form_Value__c.object-meta.xml
<CustomObject>
    <description>Form value stores all the miscellaneous features of the saved forms like Approvals, Care Episodes and Status. All the problems, diagnoses, medications and allergies selected on the forms are also linked with this object as the record in this object is also responsible for giving one identity to the forms saved in multiple objects.</description>
    <label>Form Value</label>
    <nameField>
        <label>Form Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Value__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Form Values</relationshipLabel>
    <relationshipName>Form_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object contains the summary of all the transactional details linked with a patient procedure. Also it contains the rollup for patient paid amount, total refund amount, total discount applied, primary insurance paid and secondary insurance paid amount.</description>
    <label>Master Transaction</label>
    <nameField>
        <displayFormat>PAYMENT-{0000}</displayFormat>
        <label>Payment Received Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Transaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Payment_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Patient_Responsibility__c.field-meta.xml
<CustomField>
    <fullName>Patient_Responsibility__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Patient Responsibility</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CalculatePatientResponsibilty.cls
public with sharing class CalculatePatientResponsibilty {
    
    public static void calculateResponsibiltyAmt(List<Payment_Transaction__c> paymentTxnRecords) {
        
        Set<Id> patientAccIdSet = new Set<Id>();
        for(Payment_Transaction__c paymentTxn : paymentTxnRecords) {
            if(paymentTxn.Account__c != null) {
                patientAccIdSet.add(paymentTxn.Account__c);
            }
        }
        
        if(patientAccIdSet.size() > 0) {
            List<Payment_Transaction__c> paymentTxnList = [Select Patient_Responsibility__c, Account__c 
            FROM Payment_Transaction__c WHERE Account__c IN :patientAccIdSet
            WITH SECURITY_ENFORCED];
            
            Map<Id, Decimal> patientAccIdToPatientRespMap = new Map<Id, Decimal>();
            
            for(Payment_Transaction__c paymentTxnRec : paymentTxnList) {
                if(paymentTxnRec.Account__c != null) {
                    if(patientAccIdToPatientRespMap.containsKey(paymentTxnRec.Account__c)) {
                        Decimal patientResp = patientAccIdToPatientRespMap.get(paymentTxnRec.Account__c);
                        System.debug(paymentTxnRec.Patient_Responsibility__c);
                        if(paymentTxnRec.Patient_Responsibility__c == null) {
                            paymentTxnRec.Patient_Responsibility__c = 0;
                        }
                        patientResp = patientResp + paymentTxnRec.Patient_Responsibility__c;
                        patientAccIdToPatientRespMap.put(paymentTxnRec.Account__c, patientResp);
                    } else {
                        if(paymentTxnRec.Patient_Responsibility__c == null) {
                            paymentTxnRec.Patient_Responsibility__c = 0;
                        }
                        patientAccIdToPatientRespMap.put(paymentTxnRec.Account__c, paymentTxnRec.Patient_Responsibility__c); 
                    }
                }
                
            }
            
            List<Account> patientAccList = [Select Total_Patient_Responsibility__c FROM Account
             WHERE ID IN :patientAccIdSet WITH SECURITY_ENFORCED];//
            
            for(Account patientAccRec : patientAccList) {
                if(patientAccIdToPatientRespMap.containsKey(patientAccRec.Id)) {
                    patientAccRec.Total_Patient_Responsibility__c = patientAccIdToPatientRespMap.get(patientAccRec.Id);
                }
            }
            if(patientAccList.size() > 0){
            try{
                if(Schema.sObjectType.Form_Value__c.isUpdateable() &&
                Schema.sObjectType.Account.fields.Total_Patient_Responsibility__c.isUpdateable()){
                update patientAccList;
                }
            } catch(Exception ex) {
                System.debug('Exception ****'+ex.getMessage());
            }
        }
            
        }
        
    }
}