force-app/main/default/objects/Account/fields/Verification_Code__c.field-meta.xml
<CustomField>
    <fullName>Verification_Code__c</fullName>
    <description>Stores the verification code associated with the account.</description>
    <label>Verification Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>TO BE DEPRECATED:
Form was used to store all the forms related to the patient.</description>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <label>Sub Category</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/Prescription_Order__c.object-meta.xml
<CustomObject>
    <label>Prescription Order</label>
    <nameField>
        <displayFormat>Prescription Order-{0000}</displayFormat>
        <label>Prescription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescription Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prescription_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Prescription Order</relationshipLabel>
    <relationshipName>Prescription_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/fields/Prescription_Order__c.field-meta.xml
<CustomField>
    <fullName>Prescription_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prescription Order</label>
    <referenceTo>Prescription_Order__c</referenceTo>
    <relationshipLabel>Prescription Order</relationshipLabel>
    <relationshipName>Prescription_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/fields/Signature_Comments__c.field-meta.xml
<CustomField>
    <fullName>Signature_Comments__c</fullName>
    <label>Signature Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Sample_Analysis__c/Sample_Analysis__c.object-meta.xml
<CustomObject>
    <label>Sample Analysis</label>
    <nameField>
        <label>UA Analysis Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sample Analysis</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Analysis__c/fields/UA_Sample_Details__c.field-meta.xml
<CustomField>
    <fullName>UA_Sample_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UA Sample Details</label>
    <referenceTo>UA_Sample_Details__c</referenceTo>
    <relationshipLabel>Sample Analysis</relationshipLabel>
    <relationshipName>Sample_Analysis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/UA_Sample_Details__c.object-meta.xml
<CustomObject>
    <label>UA Sample Detail</label>
    <nameField>
        <displayFormat>Lab Order-{0000}</displayFormat>
        <label>Lab Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UA Sample Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/UA_Sample_Details__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>UA Sample Details</relationshipLabel>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Signature_Comments__c.field-meta.xml
<CustomField>
    <fullName>Signature_Comments__c</fullName>
    <label>Signature Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/UA_Sample_Details__c.field-meta.xml
<CustomField>
    <fullName>UA_Sample_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UA Sample Details</label>
    <referenceTo>UA_Sample_Details__c</referenceTo>
    <relationshipLabel>UA Sample Details</relationshipLabel>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestLabOrderSignOff.cls
@isTest
public class TestLabOrderSignOff {
    @isTest
    public static void testMethod1(){
        //Insert test account
        Account acc = new Account();
        acc.Name = 'Test';
        acc.Verification_Code__c = '6781';
        insert acc;
        
        Prescription_Order__c po = new Prescription_Order__c();
        po.Account__c = acc.Id ; 
        po.Signature_Comments__c = 'the document has been signed';
        insert po ;
        
        UA_Sample_Details__c a = new UA_Sample_Details__c();
        a.Account__c=acc.id;
        insert a;
        
        Form__c  f= new Form__c();
        f.Account__c=acc.id;
        f.Name='new';
        f.Category__c='medical';
        f.Sub_Category__c='new';
        f.Version__c=1;
        insert f;
        
        Attachment att = new Attachment();
        att.ContentType = 'abc.pdf';
        att.Description = 'the image is for all purpose' ;
        att.Name = 'abc file';
        att.ParentId = acc.id ;
        att.Body = blob.valueOf('the image is done');
        insert att ; 
        System.assertEquals(1, 1, ' ');
    }
    
    @isTest
    public static void test1(){
        Test.startTest();
        testMethod1();
        Account accId1 = [Select Id,Verification_Code__c from Account where Name = 'Test' limit 1];
        Id accId = accId1.Id; 
        String verificationCode = accId1.Verification_Code__c ; 
        Prescription_Order__c po = new Prescription_Order__c();
        po = [Select id  ,Account__c from Prescription_Order__c];
        Id pw = po.Id ;
        UA_Sample_Details__c po1 = new UA_Sample_Details__c();
        po1 = [Select id  ,Account__c from UA_Sample_Details__c];
        Id pw2 = po1.Id ;
        Form__c fo = new Form__c();
        fo = [Select id  ,Account__c from Form__c];
        Id pw1= fo.Id ;
        Attachment att = new Attachment();
        att =[select id from attachment limit 1];
        //  Sample_Analysis__c  e= new Sample_Analysis__c();
        //   e.Account__c=accId;
        //  insert e;
        //  list<string> liste = new list<string>();
        //  liste.add(e.Id);
        //  EditPrescriptionOrderController.fetchMedications(pw);
        LabOrderSignOff.newVal(verificationCode , pw2 , '6781' , accId);
        SignOffController.newVal(verificationCode , pw , '6781' , accId);
        newApexForCode.newVal(verificationCode , pw1 , '6781' , accId ,'', '');
        // EncounterController.encounterRecords(accId);
        //EncounterController.deleteRecords(e.Id);
        // EncounterController.deleteAllEncounter(liste);
        System.assertEquals(1, 1, ' ');
        Test.stopTest();
    }
    
}