force-app/main/default/objects/Account/fields/Verification_Code__c.field-meta.xml
<CustomField>
    <fullName>Verification_Code__c</fullName>
    <description>Stores the verification code associated with the account.</description>
    <label>Verification Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataset1__c/Dataset1__c.object-meta.xml
<CustomObject>
    <label>Patient Problem</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patient Problems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dataset1__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Datasets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>TO BE DEPRECATED:
Form was used to store all the forms related to the patient.</description>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <label>Sub Category</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Form_Data__c/Form_Data__c.object-meta.xml
<CustomObject>
    <description>TO BE DEPRECATED:
Form Data was used to store all the input values related  to the ElixirSuite__Form__c. One record in this object is one input value entered by user in the form.</description>
    <label>Form Data</label>
    <nameField>
        <label>Form Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Form data</relationshipLabel>
    <relationshipName>Form_data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Data__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form data</relationshipLabel>
    <relationshipName>Form_data</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Data__c/fields/Form_Field__c.field-meta.xml
<CustomField>
    <fullName>Form_Field__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Form Field</label>
    <referenceTo>Form_Field__c</referenceTo>
    <relationshipLabel>Form data</relationshipLabel>
    <relationshipName>Form_data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Field__c/Form_Field__c.object-meta.xml
<CustomObject>
    <label>Form Field</label>
    <nameField>
        <displayFormat>Data-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Field__c/fields/Data_Entry_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Entry_Type__c</fullName>
    <label>Data Entry Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>old</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Date/Time</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area</fullName>
            </value>
            <value>
                <fullName>Text Area (Rich)</fullName>
            </value>
            <value>
                <fullName>Input</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Multipicklist</fullName>
            </value>
            <value>
                <fullName>Toggle</fullName>
            </value>
            <value>
                <fullName>Attachment</fullName>
            </value>
            <value>
                <fullName>Input :Text Area</fullName>
            </value>
            <value>
                <fullName>Multi checkbox Left</fullName>
            </value>
            <value>
                <fullName>Multi CheckBox</fullName>
            </value>
            <value>
                <fullName>checkbox Left</fullName>
            </value>
            <value>
                <fullName>Input Left</fullName>
            </value>
            <value>
                <fullName>checkbox</fullName>
                <label>Checkbox</label>
            </value>
            <value>
                <fullName>input:Date</fullName>
            </value>
            <value>
                <fullName>input:Time</fullName>
            </value>
            <value>
                <fullName>input:TextArea(Only)</fullName>
            </value>
            <value>
                <fullName>input:Text(Only)</fullName>
            </value>
            <value>
                <fullName>Line</fullName>
            </value>
            <value>
                <fullName>Button</fullName>
            </value>
            <value>
                <fullName>Picklist:Allergy</fullName>
            </value>
            <value>
                <fullName>Picklist:Medications</fullName>
            </value>
            <value>
                <fullName>Picklist:PhysicalTherapist</fullName>
            </value>
            <value>
                <fullName>Picklist:History</fullName>
            </value>
            <value>
                <fullName>Picklist:ProblemRating</fullName>
            </value>
            <value>
                <fullName>Picklist:Height</fullName>
            </value>
            <value>
                <fullName>Picklist:Weight</fullName>
            </value>
            <value>
                <fullName>Active_Users</fullName>
            </value>
            <value>
                <fullName>Vitals_signs</fullName>
            </value>
            <value>
                <fullName>Diagnosis_Code</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Field__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Fields</relationshipLabel>
    <relationshipName>Form_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Field__c/fields/Form_Field__c.field-meta.xml
<CustomField>
    <fullName>Form_Field__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Field</label>
    <referenceTo>Form_Field__c</referenceTo>
    <relationshipLabel>Form Fields</relationshipLabel>
    <relationshipName>Form_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Field__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ICD_Codes__c/ICD_Codes__c.object-meta.xml
<CustomObject>
    <description>Diagnosis Code stores diagnosis code along with their ICDs.
Both template and patient related diagnosis are stored in this object differentiated by the record type.</description>
    <label>Diagnosis Code</label>
    <nameField>
        <label>Code Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diagnoses Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ICD_Codes__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate the diagnosis with the Patient.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Diagnosis Code</relationshipLabel>
    <relationshipName>Diagnosis_Code</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ICD_Codes__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>ICD version represents the version such as ICD-9 or ICD-10.</description>
    <label>ICD Version</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ICD 10</fullName>
                <default>true</default>
                <label>ICD 10</label>
            </value>
            <value>
                <fullName>ICD 11</fullName>
            </value>
            <value>
                <fullName>ICD 9</fullName>
                <isActive>false</isActive>
                <label>ICD 9</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medical_Examination__c/Medical_Examination__c.object-meta.xml
<CustomObject>
    <label>Medical Examination</label>
    <nameField>
        <displayFormat>ME-{000}</displayFormat>
        <label>Medical Examination</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Examinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Examination__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Medical Examinations</relationshipLabel>
    <relationshipName>Medical_Examinations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Examination__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Skin Allergy</fullName>
            </value>
            <value>
                <fullName>Food Allergy</fullName>
            </value>
            <value>
                <fullName>Drug Allergy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medical_Examination__c/recordTypes/Allergy.recordType-meta.xml
<RecordType>
    <fullName>Allergy</fullName>
    <active>true</active>
    <label>Allergy</label>
</RecordType>

force-app/main/default/objects/Medical_Examination__c/recordTypes/Glucose.recordType-meta.xml
<RecordType>
    <fullName>Glucose</fullName>
    <active>true</active>
    <label>Glucose</label>
</RecordType>

force-app/main/default/objects/Medical_Examination__c/recordTypes/Vital_Sign.recordType-meta.xml
<RecordType>
    <fullName>Vital_Sign</fullName>
    <active>true</active>
    <label>Vital Sign</label>
</RecordType>

force-app/main/default/objects/Notes__c/Notes__c.object-meta.xml
<CustomObject>
    <label>Notes</label>
    <nameField>
        <displayFormat>NT-{0000}</displayFormat>
        <label>Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notes__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notes__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/Prescription_Order__c.object-meta.xml
<CustomObject>
    <label>Prescription Order</label>
    <nameField>
        <displayFormat>Prescription Order-{0000}</displayFormat>
        <label>Prescription Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescription Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prescription_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Prescription Order</relationshipLabel>
    <relationshipName>Prescription_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription_Order__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>It is used to store the code the prescription record.</description>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ElixirHC_FormsPDFGeneratorHelperTest.cls
@isTest
public class ElixirHC_FormsPDFGeneratorHelperTest {
    /*public static testMethod void  parent_CoverAllMethods(){
        Account acc = new Account();
        acc.Name ='test Acc';
        acc.Verification_Code__c='abc59c';
        insert acc;
        Form__c f = new Form__c();
        f.Name ='Risk';
        f.Account__c = acc.Id;
        f.Category__c='Medical';
        f.Sub_Category__c='Medicene';
        f.Version__c=2.3;
        //  f.Form__c=f1.id;
        insert f;
        
        Contact c  = new Contact();
        // c.name = 'test';
        c.birthdate = Date.today();
        c.AccountId=acc.id;
        c.lastName = 'Test last ';
        insert c;
        list<String> lis = new list<string>();
        
        
        
        List<Lead> leads = new List<Lead>();
        String CRON_EXP = '0 0 1 * * ?';
        for(Integer i = 0; i < 200; i++){
            Lead lead = new Lead(LastName = 'Test ' + i, LeadSource = '', Company = 'Test Company ' + i, Status = 'Open - Not Contacted');
            leads.add(lead);
        }
        insert leads;
        // Test.startTest();
        // String jobId = System.schedule('Update LeadSource to DreamForce', CRON_EXP, new DailyLeadProcessor());
        // Test.stopTest();
        Form_Field__c field = new Form_Field__c();
        field.Form__c =f.Id;
        field.Data_Entry_Type__c='Picklist:PhysicalTherapist';
        insert field;
        
        Form_Field__c field1 = new Form_Field__c();
        field1.Form__c =f.Id;
        field1.Data_Entry_Type__c='Picklist:Allergy';
        insert field1;
        
        Form_Field__c field2 = new Form_Field__c();
        field2.Form__c =f.Id;
        field2.Data_Entry_Type__c='Medication_list';
        insert field2;
        
        Form_Field__c field3 = new Form_Field__c();
        field3.Form__c =f.Id;
        field3.Data_Entry_Type__c='Medication_list';
        insert field3;
        
        Form_Field__c field4 = new Form_Field__c();
        field4.Form__c =f.Id;
        field4.Data_Entry_Type__c='Glucose_note';
        insert field4;
        
        Form_Field__c field5 = new Form_Field__c();
        field5.Form__c =f.Id;
        field5.Data_Entry_Type__c='Vitals_signs';
        insert field5;
        
        Form_Field__c field6 = new Form_Field__c();
        field6.Form__c =f.Id;
        field6.Data_Entry_Type__c='Diagnosis_Code';
        insert field6;
        
        Form_Field__c field8 = new Form_Field__c();
        field8.Form__c =f.Id;
        field8.Section__c=3;
        field8.Data_Entry_Type__c='Active_Users';
        insert field8;
        
        Form__c f1 = new Form__c();
        f1.Name ='Risk';
        f1.Category__c='Medical';
        f1.Sub_Category__c='Assessments';
        f1.Version__c=2.3;
        f1.Account__c=acc.id;
        f1.Form__c = f.id;
        insert f1;
        System.debug('f1 '+f1);
        
        Form_Data__c data = new Form_Data__c();
        data.Account__c=acc.Id;
        data.Form__c =f1.id;
        insert data;
        
        f.Form__c=f1.Id;
        update f;
        
        
        lis.add(f1.Id);
        
        List<string> lis1 = new list<string>();
        
        Dataset1__c ec = new Dataset1__c();
        //  ec.Care_Plan_Template_Problem__c = care.id;
        insert ec ;
        list<String> hdiagnosis = new list<String>();
        ICD_Codes__c hd = new ICD_Codes__c();
        hd.Name = 'diagnosis1' ;
        // hd.Care_Plan_Template_Problem__c = care.id;
        hd.Dataset1__c = ec.id;
        insert hd ;
        hdiagnosis.add(hd.id);
        List<String> lstStr = new List<String>();
        lstStr.add(ec.Id);
        list<Medical_Examination__c> oblist = new list<Medical_Examination__c>();
        list<Medical_Examination__c> obslist = new list<Medical_Examination__c>();
        Id devRecordTypeIdGlucose = Schema.SObjectType.Medical_Examination__c.getRecordTypeInfosByDeveloperName().get('Glucose').getRecordTypeId();
        Id devRecordTypeIdVital = Schema.SObjectType.Medical_Examination__c.getRecordTypeInfosByDeveloperName().get('Vital_Sign').getRecordTypeId();
        Id devRecordTypeIdAllergy = Schema.SObjectType.Medical_Examination__c.getRecordTypeInfosByDeveloperName().get('Allergy').getRecordTypeId();
        Medical_Examination__c obs = new Medical_Examination__c();
        obs.Account__c=acc.id;
        obs.RecordTypeId = devRecordTypeIdGlucose;
        obs.Start_Time__c = system.now().adddays(1);
        obs.End_Time__c = system.now().adddays(2) ;
        try
        {
            insert obs;
        }
        catch(Exception e){}
        
        oblist.add(obs);
        
        Medical_Examination__c obs1 = new Medical_Examination__c();
        obs1.Account__c=acc.id;
        obs.RecordTypeId = devRecordTypeIdVital;
        obs1.Start_Time__c = system.now().adddays(1);
        obs1.End_Time__c = system.now().adddays(2);
        try
        {
            insert obs1;
        }
        catch(Exception e){}
        
        obslist.add(obs1);
        
        list<Medical_Examination__c> alis= new list<Medical_Examination__c>(); 
        Medical_Examination__c all = new Medical_Examination__c();
        all.Allergy_Name__c='kk';
        all.Account__c=acc.id;
        all.RecordTypeId = devRecordTypeIdAllergy;
        all.Start_Time__c =system.now().adddays(1);
        all.End_Time__c = system.now().adddays(2) ;
        try
        {
            insert all;
        }
        catch(Exception e){}
        
        alis.add(all);
        
        Notes__c n = new Notes__c();
        n.Account__c = acc.Id;
        insert n;
        List<sObject> sObjLst = new List<sObject>();
        List<String> dat = new List<String>();
        
        ICD_Codes__c hd1  = new ICD_Codes__c();
        hd1.name = 'Test';
        insert hd1;
        List<String> lst  = new List<String>();
        lst.add(hd1.Id);        
        
        Medical_Examination__c ag = new Medical_Examination__c();
        ag.Allergy_Name__c = 'pollen';
        ag.Account__c = acc.id ;
        ag.End_Time__c = system.now().adddays(2);
        ag.Start_Time__c = system.now().adddays(1);
        try
        {
            insert ag ;
        }
        catch(Exception e){}
        
        List<Dataset1__c> parentProblem  = new List<Dataset1__c>();
        list<ICD_Codes__c> relatedicd = new List<ICD_Codes__c>();
        list<Notes__c> relatedNotes = new list<Notes__c>();
        Dataset1__c dataProblem = new Dataset1__c();
        //dataProblem.Problem_Name__c = 'demo';
        insert dataProblem;
        parentProblem.add(dataProblem);
        
        ICD_Codes__c diagnosis = new ICD_Codes__c();
        diagnosis.Code__c = 'CD 101';
        diagnosis.Related_Problem__c = data.id;
        relatedicd.add(diagnosis);
        
        
        Notes__c nt = new Notes__c();
        nt.Dataset1__c = data.Id;
        relatedNotes.add(nt);
        
        List<Prescription_Order__c> toSend  = new List<Prescription_Order__c>();
        Prescription_Order__c p = new Prescription_Order__c();
        p.Drug_Name__c = 'demo';
        insert p;
        Frequency__c freq = new Frequency__c();
        freq.Prescription_Order__c = p.Id;
        insert freq;
        toSend.add(p);
        
        Test.startTest();
        Test.setCurrentPage(Page.FormsPDFGenerator);
        ApexPages.currentPage().getParameters().put('formId',f.Id);
        ElixirHC_FormsPDFGeneratorHelper callConstructor = new ElixirHC_FormsPDFGeneratorHelper();
        Test.stopTest();
          System.assert(p.Drug_Name__c!=null);
        
        ElixirHC_FormsPDFGeneratorHelper.getFormDataWrapper wrpr  = ElixirHC_FormsPDFGeneratorHelper.getFormData(f.Id,acc.Id);
        // ElixirHC_FormsPDFGeneratorHelper demoObject  = new ElixirHC_FormsPDFGeneratorHelper();
        ElixirHC_FormsPDFGeneratorHelper.getFormData(f.Id,acc.Id);
        ElixirHC_FormsPDFGeneratorHelper.medicationDataJSON(toSend);
        //  ElixirHC_FormsPDFGeneratorHelper.initPage2(wrpr);   
        ElixirHC_FormsPDFGeneratorHelper.arrangeConditionDataAsParentChild(parentProblem,relatedicd,relatedNotes); 
        ElixirHC_FormsPDFGeneratorHelper.getApprovalProcessInfo(f.Id);
        ElixirHC_FormsPDFGeneratorHelper.FormDataValues(f.Id);
        ElixirHC_FormsPDFGeneratorHelper.getAllergyData(acc.Id);     
    }*/
}