force-app/main/default/objects/ICD_Codes__c/ICD_Codes__c.object-meta.xml
<CustomObject>
    <description>Diagnosis Code stores diagnosis code along with their ICDs.
Both template and patient related diagnosis are stored in this object differentiated by the record type.</description>
    <label>Diagnosis Code</label>
    <nameField>
        <label>Code Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diagnoses Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ICD_Codes__c/fields/Template_Diagnosis_Code__c.field-meta.xml
<CustomField>
    <fullName>Template_Diagnosis_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a self lookup field and is used to associate the template record to the patient diagnosis record.</description>
    <label>Diagnosis Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ICD_Codes__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Template Diagnosis Code</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>ICD_Codes__c</referenceTo>
    <relationshipLabel>Diagnosis Code</relationshipLabel>
    <relationshipName>Template_Diagnosis_Code</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ICD_Codes__c/recordTypes/Template_Diagnosis_Code.recordType-meta.xml
<RecordType>
    <fullName>Template_Diagnosis_Code</fullName>
    <active>true</active>
    <label>Template Diagnosis Code</label>
</RecordType>

force-app/main/default/objects/Template_Diagnosis_Code__c/Template_Diagnosis_Code__c.object-meta.xml
<CustomObject>
    <description>Template Problem and Diagnosis is a junction object between a template problem and a template diagnosis.</description>
    <label>Template Problem and Diagnosis</label>
    <nameField>
        <displayFormat>DC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Template Problem and Diagnosis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PopulateTempDiagnosisTest.cls
@isTest
public class PopulateTempDiagnosisTest {
    @isTest
    public static void tempDiagnosis(){
        Id recordTypeId = Schema.SObjectType.ElixirSuite__ICD_Codes__c.getRecordTypeInfosByDeveloperName().get('Template_Diagnosis_Code').getRecordTypeId();
        ICD_Codes__c diag = new ICD_Codes__c();
        diag.Name = 'Test';
        diag.ElixirSuite__Code_Description1__c = 'Test Description';
        diag.recordTypeId = recordTypeId;
        insert diag;
        
        ICD_Codes__c diag2 = new ICD_Codes__c();
        diag2.Name = 'Patient Diagnosis';
        diag2.Template_Diagnosis_Code__c = diag.Id;
        insert diag2;
        
        System.assertEquals(1, 1, '');
        
    }
}