force-app/main/default/objects/ICD_Codes__c/ICD_Codes__c.object-meta.xml
<CustomObject>
    <description>Diagnosis Code stores diagnosis code along with their ICDs.
Both template and patient related diagnosis are stored in this object differentiated by the record type.</description>
    <label>Diagnosis Code</label>
    <nameField>
        <label>Code Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diagnoses Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ICD_Codes__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate the diagnosis with the Patient.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Diagnosis Code</relationshipLabel>
    <relationshipName>Diagnosis_Code</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ICD_Codes__c/recordTypes/Patient_Diagnosis_Code.recordType-meta.xml
<RecordType>
    <fullName>Patient_Diagnosis_Code</fullName>
    <active>true</active>
    <label>Patient Diagnosis Code</label>
</RecordType>

force-app/main/default/objects/Lab__c/Lab__c.object-meta.xml
<CustomObject>
    <label>Lab</label>
    <nameField>
        <label>Lab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Labs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab__c/fields/Lab_Id__c.field-meta.xml
<CustomField>
    <fullName>Lab_Id__c</fullName>
    <label>Lab Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lab_Test_Bundle__c/Lab_Test_Bundle__c.object-meta.xml
<CustomObject>
    <label>Lab Test Bundle</label>
    <nameField>
        <label>Lab Test Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab Test Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Test_Bundle__c/fields/Diagnosis_Codes_SF_Ids__c.field-meta.xml
<CustomField>
    <fullName>Diagnosis_Codes_SF_Ids__c</fullName>
    <label>Diagnosis Codes SF Ids</label>
    <length>35000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lab_Test_Bundle__c/fields/Lab__c.field-meta.xml
<CustomField>
    <fullName>Lab__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lab</label>
    <referenceTo>Lab__c</referenceTo>
    <relationshipLabel>Lab Test Bundles</relationshipLabel>
    <relationshipName>Lab_Test_Bundles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Test_Bundle__c/fields/Lab_Tests_SF_Ids__c.field-meta.xml
<CustomField>
    <fullName>Lab_Tests_SF_Ids__c</fullName>
    <label>Lab Tests SF Ids</label>
    <length>35000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lab_Test_Bundle__c/fields/Procedure_Codes_SF_Ids__c.field-meta.xml
<CustomField>
    <fullName>Procedure_Codes_SF_Ids__c</fullName>
    <label>Procedure Codes SF Ids</label>
    <length>35000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/LabTestRecommendationsTest.cls
@isTest
public class LabTestRecommendationsTest {
 
    @isTest
    static void testLabTestRecommendations(){
        Id recordTypeId =   Schema.SObjectType.ElixirSuite__ICD_Codes__c.getRecordTypeInfosByDeveloperName().get('Patient_Diagnosis_Code').getRecordTypeId();
        Account acc = TestDataFactory.createPatientAcc();
        insert acc;


        ICD_Codes__c icd = new ICD_Codes__c();
        icd.Name = 'Test';
        icd.recordTypeId = recordTypeId;
        icd.Account__c = acc.Id;
        insert icd;

        Lab__c lab = new Lab__c();
        lab.Name = 'Test Lab';
        lab.Lab_Id__c = '123';
        insert lab;

        Lab_Test_Bundle__c ltb = new Lab_Test_Bundle__c();
        ltb.Name = 'Test';
        ltb.Procedure_Codes_SF_Ids__c = 'Test procedure codes';
        ltb.Diagnosis_Codes_SF_Ids__c = 'TestDiagnosisCodes1;TestDiagnosisCodes12';
        ltb.Lab_Tests_SF_Ids__c = 'Test lab tests';
        ltb.Lab__c = lab.Id;
        insert ltb;




        Test.startTest();
        LabTestRecommendations.testsBasedOnDiagnosis(acc.Id,lab.Lab_Id__c);
        system.assertEquals(1, 1, ' ');
        Test.stoptest();
    }

}