force-app/main/default/objects/ICD_Codes__c/ICD_Codes__c.object-meta.xml
<CustomObject>
    <description>Diagnosis Code stores diagnosis code along with their ICDs.
Both template and patient related diagnosis are stored in this object differentiated by the record type.</description>
    <label>Diagnosis Code</label>
    <nameField>
        <label>Code Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diagnoses Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ICD_Codes__c/fields/Code_Description1__c.field-meta.xml
<CustomField>
    <fullName>Code_Description1__c</fullName>
    <description>Detailed description of the diagnosis code.</description>
    <label>Code Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICD_Codes__c/fields/ICD_Description__c.field-meta.xml
<CustomField>
    <fullName>ICD_Description__c</fullName>
    <description>Provides a detailed description based on the classification of Diseases coding system.</description>
    <label>ICD Description</label>
    <length>7000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ICD_Codes__c/fields/Template_Diagnosis_Code__c.field-meta.xml
<CustomField>
    <fullName>Template_Diagnosis_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a self lookup field and is used to associate the template record to the patient diagnosis record.</description>
    <label>Diagnosis Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ICD_Codes__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Template Diagnosis Code</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>ICD_Codes__c</referenceTo>
    <relationshipLabel>Diagnosis Code</relationshipLabel>
    <relationshipName>Template_Diagnosis_Code</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ICD_Codes__c/recordTypes/Template_Diagnosis_Code.recordType-meta.xml
<RecordType>
    <fullName>Template_Diagnosis_Code</fullName>
    <active>true</active>
    <label>Template Diagnosis Code</label>
</RecordType>

force-app/main/default/objects/Template_Diagnosis_Code__c/Template_Diagnosis_Code__c.object-meta.xml
<CustomObject>
    <description>Template Problem and Diagnosis is a junction object between a template problem and a template diagnosis.</description>
    <label>Template Problem and Diagnosis</label>
    <nameField>
        <displayFormat>DC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Template Problem and Diagnosis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PopulateTempDiagnosisHelper.cls
public with sharing class PopulateTempDiagnosisHelper {
    
    public static void updateTemplateDiagnosisInfo(List<ICD_Codes__c> patientDiagnosislst){
        /*Id recordTypeId = Schema.SObjectType.ElixirSuite__ICD_Codes__c.getRecordTypeInfosByDeveloperName().get('Template_Diagnosis_Code').getRecordTypeId();
        for(ICD_Codes__c diag : patientDiagnosislst){
            if(diag.recordTypeId == recordTypeId){
                String icdDescription = diag.ICD_Description__c;
                if(icdDescription.length() < 255){
                    diag.Code_Description1__c = icdDescription;
                }
                else{
                    diag.Code_Description1__c = icdDescription.substring(0, 255);
                }
            }
        }*/
        
        Set<Id> templateDiagnosisIds = new Set<Id>();
        for (ICD_Codes__c diagnosis : patientDiagnosislst) {
            if(diagnosis.Template_Diagnosis_Code__c != null){
                templateDiagnosisIds.add(diagnosis.Template_Diagnosis_Code__c);
            }
        }
        if(templateDiagnosisIds.isEmpty()){
            return;
        }
        Map<Id, ICD_Codes__c> templateDiagnosisMap = new Map<Id, ICD_Codes__c>([
            SELECT Id, Code_Description1__c
            FROM ICD_Codes__c
            WHERE Id IN :templateDiagnosisIds
        ]);

        for (ICD_Codes__c diagnosis : patientDiagnosislst) {
            ICD_Codes__c tempDiagnosis;
            if(templateDiagnosisMap.containsKey(diagnosis.Template_Diagnosis_Code__c)){
                tempDiagnosis = templateDiagnosisMap.get(diagnosis.Template_Diagnosis_Code__c);
                if(tempDiagnosis.Code_Description1__c != null && diagnosis.Code_Description1__c == null){
                    diagnosis.Code_Description1__c = tempDiagnosis.Code_Description1__c;
                }    
            }
            
        }
    }
}