force-app/main/default/objects/Audit_Log__c/Audit_Log__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track field history in case an object requires more than 20 fields to be tracked which is Salesforce out of the box feature.</description>
    <label>Audit Log</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>Audit Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Log__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents the account associated with the audited action.</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Audit Log</relationshipLabel>
    <relationshipName>Audit_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/Field_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Api_Name__c</fullName>
    <description>Captures the API name of the field that was affected during the audited action.</description>
    <label>Field Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/Modified_Date__c.field-meta.xml
<CustomField>
    <fullName>Modified_Date__c</fullName>
    <description>Records the date and time when the audited action was performed on the specified record.</description>
    <label>Modified Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <description>Represents the new value assigned to the field after the audited action.</description>
    <label>New Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/New_Value_Datetime__c.field-meta.xml
<CustomField>
    <fullName>New_Value_Datetime__c</fullName>
    <description>Indicates the date and time when the new value was assigned to the field during the audited action.</description>
    <label>New Value Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description> Specifies the name of the Salesforce object associated with the audited action.</description>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/Old_Value__c.field-meta.xml
<CustomField>
    <fullName>Old_Value__c</fullName>
    <description>Captures the previous or old value of the field before the audited action.</description>
    <label>Old Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/Old_Value_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Old_Value_Datetime__c</fullName>
    <description>Records the date and time when the old value was replaced during the audited action.</description>
    <label>Old Value Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <description>Represents the parent record ID associated with the audited action.</description>
    <label>Parent Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AuditTrailUtility.cls
global class AuditTrailUtility implements Queueable{
    
    global Map<Id,sObject> newSobjectMap;
    global Map<Id,sObject> oldSobjectMap;
    global String objectName;
    global String actionType;
    @deprecated
    global AuditTrailUtility(Map<Id,sObject> newSobjectMap,Map<Id,sObject> oldSobjectMap){ }
    global AuditTrailUtility(Map<Id,sObject> newSobjectMap,Map<Id,sObject> oldSobjectMap,String objectName){
        this.newSobjectMap = newSobjectMap;
        this.oldSobjectMap = oldSobjectMap;
        this.objectName = objectName;
    }
    global void execute(QueueableContext context) {
        List<Audit_Log__c> auditList = new List<Audit_Log__c>();
        Map<String,Set<String>> objToField = new Map<String,Set<String>>();
        
        Set<String> allFields = new Set<String>();
        Set<String> allObjects = new Set<String>();
        
        System.debug('newSobjectMap**'+newSobjectMap);
        System.debug('oldSobjectMap**'+oldSobjectMap);
        System.debug('objectName**'+objectName);
        
        try{
            
            allObjects.add(objectName);
            List<ElixirSuite__Audit_fields_new__mdt> metadata = [SELECT Id, 
                                                                 ElixirSuite__Audit_Object__c, 
                                                                 ElixirSuite__Audit_fields__c 
                                                                 FROM ElixirSuite__Audit_fields_new__mdt
                                                                 WHERE ElixirSuite__Audit_Object__c IN : allObjects
                                                                 WITH SECURITY_ENFORCED];//Getting metadata
            
            if(metadata!=null && metadata.size()>0){ 
                for(ElixirSuite__Audit_fields_new__mdt meta : metadata){
                    allFields.addAll((meta.ElixirSuite__Audit_fields__c.split(';')));
                    objToField.put(meta.ElixirSuite__Audit_Object__c,new Set<String>(meta.ElixirSuite__Audit_fields__c.split(';')));
                }
            }
            
            System.debug('allFields**'+allFields);
            
            for(sObject newSobject : newSobjectMap.values()){
                Schema.DescribeSObjectResult obj= newSobject.Id.getsobjecttype().getDescribe();
                
                if(allFields!=null && allFields.size()>0){
                    for(String fieldApi :allFields){
                        SObjectType objName = ((SObject) Type.forName(objectName).newInstance()).getSObjectType();
                        Map<String,Schema.SObjectField> mfields = objName.getDescribe().fields.getMap();
                        Schema.DescribeFieldResult fieldResult = mfields.get(fieldApi).getDescribe();
                        System.debug('field label*****'+fieldResult.getLabel());
                        String fieldLabel = fieldResult.getLabel();
                        system.debug('oldSobjectMap '+oldSobjectMap);
                        if(((oldSobjectMap != null && oldSobjectMap.get(newSobject.Id)!=null) && oldSobjectMap.get(newSobject.Id).get(fieldApi) != newSobjectMap.get(newSobject.Id).get(fieldApi)) || (oldSobjectMap == null)){
                            System.debug('line 78');
                            
                            Audit_Log__c auditLog = new Audit_Log__c();
                            auditLog.Field_Api_Name__c = fieldApi;
                            auditLog.Parent_Id__c = newSobject.Id;
                            auditLog.ElixirSuite__Field_Label__c = fieldLabel;
                            if(objectName=='Account'){
                                auditLog.Account_Name__c = newSobject.Id;
                            }
                            if(objectName=='ElixirSuite__Patient_Device__c' && newSobject != null && newSobject.get('ElixirSuite__Account__c') != null){
                                auditLog.ElixirSuite__Account_Name__c = (String)newSobject.get('ElixirSuite__Account__c');
                            }
                            auditLog.Object_Name__c = obj.getName();
                            auditLog.Modified_Date__c = System.now();
                            String fieldName = 'lastmodifieddate';
                            Schema.DisplayType fieldDataType = obj.getSObjectType().getDescribe().fields.getMap().get(fieldName).getDescribe().getType();
                            if(String.valueOf(fieldDataType) == 'DATETIME'){
                                if(oldSobjectMap == null || oldSobjectMap.get(newSobject.Id)==null){
                                    auditLog.Old_Value_Datetime__c = null;
                                }else{
                                    auditLog.Old_Value_Datetime__c = Datetime.valueOf(oldSobjectMap.get(newSobject.Id).get(fieldName));
                                }
                                auditLog.New_Value_Datetime__c = Datetime.valueOf(newSobjectMap.get(newSobject.Id).get(fieldName));
                            }
                            
                            Schema.DescribeFieldResult dr = obj.fields.getMap().get(fieldApi).getDescribe();
                            String typ = dr.getType().name();
                            System.debug('typ**'+typ);
                            if(String.valueOf(typ) == 'PICKLIST'){
                                
                                for( Schema.PicklistEntry ple : dr.getPicklistValues()){
                                    if(ple.getValue()== newSobject.get(fieldApi)){
                                        
                                        auditLog.New_Value__c = ple.getLabel(); 
                                        
                                    }
                                    else if (oldSobjectMap == null || oldSobjectMap.get(newSobject.Id)==null){
                                        auditLog.Old_Value__c = null;
                                    }
                                    else if(ple.getValue()== oldSobjectMap.get(newSobject.Id).get(fieldApi)){
                                        auditLog.Old_Value__c = ple.getLabel(); 
                                    }
                                } 
                            }
                            else if(String.valueOf(typ) == 'DATE'){
                                Date dToday = Date.valueOf(newSobject.get(fieldApi));
                                String dateStr;
                                if(dToday==null){
                                    dateStr = '';
                                }
                                else{
                                    DateTime dt = DateTime.newInstance(dToday.year(), dToday.month(),dToday.day());
                                    dateStr = dt.format('yyyy-MM-dd');   
                                }
                                auditLog.New_Value__c = dateStr;
                                
                                Date oldToday = null ;
                                if (oldSobjectMap == null || oldSobjectMap.get(newSobject.Id)==null){
                                    oldToday  = null;
                                }else{
                                    oldToday  = Date.valueOf(oldSobjectMap.get(newSobject.Id).get(fieldApi));
                                }
                                String dateOldStr;
                                if(oldToday==null){
                                    dateOldStr = '';
                                }
                                else{
                                    DateTime dtOld = DateTime.newInstance(oldToday.year(), oldToday.month(),oldToday.day());
                                    dateOldStr = dtOld.format('yyyy-MM-dd');
                                }
                                auditLog.Old_Value__c = dateOldStr;
                            }
                            else if(String.valueOf(typ) == 'BOOLEAN'){
                                
                                String oldVal = '';
                                if (oldSobjectMap == null || oldSobjectMap.get(newSobject.Id)==null){
                                    oldVal = null;
                                }else{
                                    oldVal = String.valueOf(oldSobjectMap.get(newSobject.Id).get(fieldApi));
                                }
                                String newVal = String.valueOf(newSobject.get(fieldApi));
                                System.debug('line 106');
                                System.debug('oldVal**'+oldVal);
                                System.debug('newVal**'+newVal);
                                String finalOldVal;
                                String finalNewVal;
                                if(oldVal==''){
                                    finalOldVal = '';
                                }
                                else{
                                    if(oldVal == 'true'){
                                        finalOldVal = 'True';
                                    }
                                    else{
                                        finalOldVal = 'False';
                                    }
                                }
                                
                                if(newVal==''){
                                    finalNewVal = '';
                                }
                                else{
                                    if(newVal == 'true'){
                                        finalNewVal = 'True';
                                    }
                                    else{
                                        finalNewVal = 'False';
                                    }
                                }
                                
                                auditLog.Old_Value__c = finalOldVal;
                                auditLog.New_Value__c = finalNewVal;
                                
                            }
                            else{
                                auditLog.New_Value__c = String.valueOf(newSobject.get(fieldApi));
                                if (oldSobjectMap == null || oldSobjectMap.get(newSobject.Id)==null){
                                    auditLog.Old_Value__c = null;
                                }else{
                                    auditLog.Old_Value__c = String.valueOf(oldSobjectMap.get(newSobject.Id).get(fieldApi));
                                }
                            }
                            auditList.add(auditLog);
                        }   
                    }
                }
            }
            if(auditList!=null && auditList.size()>0){
                DMLManager.insertAsUser(auditList);
            }
        }
        catch(Exception e){
            ExceptionLog.logError(e);
        }
        
    }
}