force-app/main/default/objects/Master_Object__c/Master_Object__c.object-meta.xml
<CustomObject>
    <label>Record</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Object__c/fields/Master_Object__c.field-meta.xml
<CustomField>
    <fullName>Master_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Object</label>
    <referenceTo>Master_Object__c</referenceTo>
    <relationshipLabel>Master Objects</relationshipLabel>
    <relationshipName>Master_Objects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TimelineSortWrapperTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-17-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class TimelineSortWrapperTest {
    @isTest
    static void testCompareTo() {
        // Create two Master_Object__c records with different Sort_Order__c values
        Master_Object__c oppy1 = new Master_Object__c(Sort_Order__c = 2);
        insert oppy1;
        Master_Object__c oppy2 = new Master_Object__c(Sort_Order__c = 1);
        insert oppy2;
        
        // Create two TimelineSortWrapper objects
        TimelineSortWrapper wrapper1 = new TimelineSortWrapper(oppy1);
        TimelineSortWrapper wrapper2 = new TimelineSortWrapper(oppy2);
        
        // Verify that the compareTo method returns 1 for wrapper1 and wrapper2
        System.assertEquals(wrapper1.compareTo(wrapper2), 1, 'Expecting 1');
        
        // Verify that the compareTo method returns -1 for wrapper2 and wrapper1
        System.assertEquals(wrapper2.compareTo(wrapper1), -1, 'Expecting -1');
        
        // Create a third TimelineSortWrapper object with the same Master_Object__c as wrapper2
        TimelineSortWrapper wrapper3 = new TimelineSortWrapper(oppy2);
        
        // Verify that the compareTo method returns 0 for wrapper2 and wrapper3
        System.assertEquals(wrapper2.compareTo(wrapper3), 0, 'Expecting 0');
    }
}