force-app/main/default/objects/CMS_1500_Claim_Generation__c/CMS_1500_Claim_Generation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CMS 1500 Claim Generation</label>
</CustomObject>

force-app/main/default/objects/CMS_1500_Claim_Generation__c/fields/After_every_hours__c.field-meta.xml
<CustomField>
    <fullName>After_every_hours__c</fullName>
    <label>After every hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CMS_1500_Claim_Generation__c/fields/days__c.field-meta.xml
<CustomField>
    <fullName>days__c</fullName>
    <label>days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/scheduledBatchable.cls
global with sharing class scheduledBatchable implements Schedulable {
    
    global void execute(SchedulableContext sc) {
        /*
		List<CMS_1500_Claim_Generation__c> CMSlist = [SELECT ID, days__c, After_every_hours__c, Active__c 
		FROM CMS_1500_Claim_Generation__c WHERE Active__c = true WITH SECURITY_ENFORCED];
		for(CMS_1500_Claim_Generation__c cms : CMSlist){ 
			Integer day = Integer.valueOf(cms.days__c);
			system.debug('day--'+day);
			String sch = '0 0 '+day+' * ?';
		}
        OpenClaimGenerationBatch b = new OpenClaimGenerationBatch(); */
		// system.schedule('Batch Scheduled', sch15, b);
		// system.schedule('Batch Scheduled', sch30, b);
    }
}