force-app/main/default/objects/Claim_Line_Items__c/Claim_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This object is used to store procedure level details related to a claim.</description>
    <label>Claim Procedure Line Item</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>Claim Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Procedure Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim_Line_Items__c/fields/Amount_Paid_by_Insurance__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid_by_Insurance__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The monetary sum covered by the insurance provider.</description>
    <label>Amount Paid by Insurance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim_Line_Items__c/fields/Total_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Total_Adjustment__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Denote the overall adjustment made to the claim amount.</description>
    <label>Total Adjustment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim_Line_Items__c/fields/Total_Allowed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Allowed_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Denote the total approved amount for reimbursement.</description>
    <label>Total Allowed Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ERA_Line_Item__c/ERA_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This object is used to track the line level details of each Child ERA record.</description>
    <label>ERA Procedure Line Item</label>
    <nameField>
        <displayFormat>ELI-{0000}</displayFormat>
        <label>ERA Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERA Procedure Line Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ERA_Line_Item__c/fields/Adjustment_Amount_1__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Amount_1__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Denote the amount adjustment for a healthcare claim.</description>
    <label>Adjustment Amount 1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ERA_Line_Item__c/fields/Adjustment_Amount_2__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Amount_2__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Denote the amount adjustment for a healthcare claim.</description>
    <label>Adjustment Amount 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ERA_Line_Item__c/fields/Adjustment_Amount_3__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Amount_3__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Denote the amount adjustment for a healthcare claim.</description>
    <label>Adjustment Amount 3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ERA_Line_Item__c/fields/Adjustment_Amount_4__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Amount_4__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Denote the amount adjustment for a healthcare claim.</description>
    <label>Adjustment Amount 4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ERA_Line_Item__c/fields/Adjustment_Amount_5__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Amount_5__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Denote the amount adjustment for a healthcare claim.</description>
    <label>Adjustment Amount 5</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ERA_Line_Item__c/fields/Adjustment_Amount_6__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Amount_6__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Denote the amount adjustment for a healthcare claim.</description>
    <label>Adjustment Amount 6</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ERA_Line_Item__c/fields/Claim_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>Claim_Line_Items__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate the Claim line item with the ERA line item.</description>
    <label>Claim Line Items</label>
    <referenceTo>Claim_Line_Items__c</referenceTo>
    <relationshipLabel>ERA Line Item</relationshipLabel>
    <relationshipName>ERA_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ERA_Line_Item__c/fields/Paid__c.field-meta.xml
<CustomField>
    <fullName>Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total amount paid by the insurance company for the healthcare claim.</description>
    <label>Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ERA_Line_Item__c/fields/Total_Allowed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Allowed_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total amount approved by the insurance payer for payment.</description>
    <label>Total Allowed Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/GlobalVirtualValueUpdationHelper.cls
global with sharing virtual class GlobalVirtualValueUpdationHelper {
    
    global virtual void afterInsert(List<ERA_Line_Item__c> eraLineItem){
        afterInsertUpdate(eraLineItem);
    }
    global virtual void afterUpdate(List<ERA_Line_Item__c> eraLineItem){
        afterInsertUpdate(eraLineItem);
    }
    global virtual void afterInsertUpdate(List<ERA_Line_Item__c> eraLineItem){
        String Claim_Line_Items_c;
        set<id> prentsIds=new set<id>();
        
        for(ERA_Line_Item__c tc:eraLineItem){
            System.debug('new '+tc.Claim_Line_Items__c);
            prentsIds.add(tc.Claim_Line_Items__c);
        }
        
        System.debug('set of ids '+prentsIds);
        list<Claim_Line_Items__c >  parentList= new list<Claim_Line_Items__c >();
        list<Claim_Line_Items__c> ParentData = new list<Claim_Line_Items__c>();
        ParentData =[select id,Amount_Paid_by_Insurance__c,Total_Adjustment__c,Total_Allowed_Amount__c from Claim_Line_Items__c 
                     where id IN:prentsIds WITH SECURITY_ENFORCED];
        for(Claim_Line_Items__c c : ParentData){
            for(ERA_Line_Item__c trgInstance : eraLineItem){
                system.debug('meg' + trgInstance.Paid__c);
                c.Amount_Paid_by_Insurance__c=trgInstance.Paid__c;
                system.debug('meg' + c.Amount_Paid_by_Insurance__c);
                //  System.debug('5678 '+trgInstance.Adjustment_Amount_1__c+'2nd '+trgInstance.Adjustment_Amount_2__c); 
                c.Total_Adjustment__c =trgInstance.Adjustment_Amount_1__c+trgInstance.Adjustment_Amount_2__c+trgInstance.Adjustment_Amount_3__c+trgInstance.Adjustment_Amount_4__c+trgInstance.Adjustment_Amount_5__c+trgInstance.Adjustment_Amount_6__c;
                c.Total_Allowed_Amount__c=trgInstance.Total_Allowed_Amount__c;
                parentList.add(c);
            }
            
        }
        if(parentList.size()>0){
            try{
                if(Schema.sObjectType.Claim_Line_Items__c.fields.Amount_Paid_by_Insurance__c.isUpdateable() &&
                   Schema.sObjectType.Claim_Line_Items__c.fields.Total_Adjustment__c.isUpdateable() &&
                   Schema.sObjectType.Claim_Line_Items__c.fields.Total_Allowed_Amount__c.isUpdateable()){
                       update parentList;
                   }
            }
            catch(DMLException e){
                system.debug('Exception has occured! ' +e.getMessage());
            }
        }
    }
}