force-app/main/default/objects/EMR_License__c/EMR_License__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Heat Map Setup Object</label>
</CustomObject>

force-app/main/default/objects/EMR_License__c/fields/key__c.field-meta.xml
<CustomField>
    <fullName>key__c</fullName>
    <defaultValue>&apos;9876-5432-1001-2345-6789&apos;</defaultValue>
    <label>key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateCustomSettingtest.cls
@isTest
public class UpdateCustomSettingtest {
   
    public static testmethod void testupdate(){
       
        //UpdateCustomSetting.updateKey('keyString');
        
        
        EMR_License__c e=new EMR_License__c();
        e.key__c='test';
        e.name='ue';
        //e.keyString='test1';
        insert e;
        test.startTest();
       // UpdateCustomSetting.deleteAllKeys();
        UpdateCustomSetting.getKeyCount();
       // UpdateCustomSetting.updateKey('test');
        UpdateCustomSetting.checkLicenseKey();
        UpdateCustomSetting.fakemethod();
        test.stopTest();
       
        System.assertEquals(1, 1, ' ');
    }
   
}