force-app/main/default/objects/Vaccine__c/Vaccine__c.object-meta.xml
<CustomObject>
    <label>Vaccine</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vaccines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vaccine__c/fields/CVX_Code__c.field-meta.xml
<CustomField>
    <fullName>CVX_Code__c</fullName>
    <description>It is used to store the Code.</description>
    <inlineHelpText>Identifier for type of vaccine product used</inlineHelpText>
    <label>CVX Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vaccine__c/fields/Next_Dose_in_Series_After__c.field-meta.xml
<CustomField>
    <fullName>Next_Dose_in_Series_After__c</fullName>
    <inlineHelpText>Number of days after which the next dose is to be taken</inlineHelpText>
    <label>Next Dose in Series After</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vaccine__c/fields/Vaccine_Route__c.field-meta.xml
<CustomField>
    <fullName>Vaccine_Route__c</fullName>
    <label>Vaccine Route</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intradermal</fullName>
            </value>
            <value>
                <fullName>Intramuscular</fullName>
            </value>
            <value>
                <fullName>Nasal</fullName>
            </value>
            <value>
                <fullName>Intravenous</fullName>
            </value>
            <value>
                <fullName>Oral</fullName>
            </value>
            <value>
                <fullName>Percutaneous</fullName>
            </value>
            <value>
                <fullName>Subcutaneous</fullName>
            </value>
            <value>
                <fullName>Transdermal</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vaccine__c/fields/Vaccine_Series__c.field-meta.xml
<CustomField>
    <fullName>Vaccine_Series__c</fullName>
    <inlineHelpText>The name of the vaccine series</inlineHelpText>
    <label>Vaccine Series</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SARS-COV-2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vaccine__c/fields/Vaccine_Site__c.field-meta.xml
<CustomField>
    <fullName>Vaccine_Site__c</fullName>
    <label>Vaccine Site</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Left Upper Arm</fullName>
            </value>
            <value>
                <fullName>Left Lower Forearm</fullName>
            </value>
            <value>
                <fullName>Left Thigh</fullName>
            </value>
            <value>
                <fullName>Right Upper Arm</fullName>
            </value>
            <value>
                <fullName>Right Lower Forearm</fullName>
            </value>
            <value>
                <fullName>Right Thigh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vaccine__c/recordTypes/Template_Vaccine.recordType-meta.xml
<RecordType>
    <fullName>Template_Vaccine</fullName>
    <active>true</active>
    <label>Template Vaccine</label>
</RecordType>

force-app/main/default/classes/VaccineLookupControllerTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-08-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class VaccineLookupControllerTest {
    
    @isTest
    public static void testVaccineLookupController(){
        Id devRecordTypeId = Schema.SObjectType.ElixirSuite__Vaccine__c.getRecordTypeInfosByDeveloperName().get('Template_Vaccine').getRecordTypeId();
        Vaccine__c vac = new Vaccine__c();
        vac.Name = 'Covid';
        vac.CVX_Code__c = 'C123';
        vac.Next_Dose_in_Series_After__c = 1;
        vac.Vaccine_Route__c = 'Intradermal';
        vac.Vaccine_Site__c = 'Left Upper Arm';
        vac.Vaccine_Series__c = 'SARS-COV-2';
        vac.RecordTypeId = devRecordTypeId;
        insert vac;
        
        test.startTest();
        VaccineLookupController.RecordsData vlrd = new VaccineLookupController.RecordsData('test','test');
        VaccineLookupController.fetchRecords('o','Vaccine__c' );
        System.assertEquals(1,1,'');
        test.stopTest();
    }

}