force-app/main/default/objects/Visits__c/Visits__c.object-meta.xml
<CustomObject>
    <description>This object is used to track every single visit or encounter for a patient.</description>
    <label>Care Episode</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visits__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents the relationship b/w Patient and Care Episode.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Care Episodes</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ElixirOEM_VisitForPatientAdmitHelper.cls
public with sharing class ElixirOEM_VisitForPatientAdmitHelper {
    @AuraEnabled
    public static wrapperForVisit generateAutoNumber(String patientID){
        wrapperForVisit wrpr = new wrapperForVisit();
        ElixirSuite__Visits__c[] forCount = [SELECT ID,Account__r.Name,Name FROM ElixirSuite__Visits__c 
                                             WHERE Account__c = : patientID AND Name LIKE '%Visit%' 
                                             WITH SECURITY_ENFORCED
                                             order by createdDate desc limit 1];
        System.debug('forCount'+forCount);
        List<Account> accLst = [SELECT ID,Name from Account where id = : patientID WITH SECURITY_ENFORCED];
        if(accLst.size()>0 && accLst!=null){ 
            wrpr.accName = accLst[0].Name;
        }
        String tpName;
        if(forCount!=null && forCount.size()>0){
            System.debug('inside ');
            if(String.isnotBlank(forCount[0].Name)){ 
                if(forCount[0].Name.containsIgnoreCase('Visit')){
                    tpName = forCount[0].Name.right(1); 
                }         
            }
        }
        else {
            tpName = '0';
        } 
        wrpr.countRecords = Integer.valueOf(tpName)+1;
        System.debug('here '+wrpr);
        // ElixirSuite__Visits__c.Name
        return wrpr;
    }
    public class wrapperForVisit{
        @AuraEnabled  public Integer countRecords;
        @AuraEnabled  public String accName; 
    }
    
    @AuraEnabled
    public static void abc(){
        
    }
}