force-app/main/default/objects/Elixir_Custom_Setting__c/Elixir_Custom_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Elixir Custom Setting</label>
</CustomObject>

force-app/main/default/objects/Elixir_Custom_Setting__c/fields/Elixir_portal_url__c.field-meta.xml
<CustomField>
    <fullName>Elixir_portal_url__c</fullName>
    <label>Elixir portal url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message_Details__c/Message_Details__c.object-meta.xml
<CustomObject>
    <label>Message Details</label>
    <nameField>
        <displayFormat>MD-{0000000}</displayFormat>
        <label>Message Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Message Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Message_Details__c/fields/lookup_Message_Subject__c.field-meta.xml
<CustomField>
    <fullName>lookup_Message_Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate Message Subject with the Message Subject.</description>
    <label>Message Subject</label>
    <referenceTo>Message_Subject__c</referenceTo>
    <relationshipLabel>Message Details (Message Subject)</relationshipLabel>
    <relationshipName>Message_Details_lookup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message_Details__c/fields/Message_Body__c.field-meta.xml
<CustomField>
    <fullName>Message_Body__c</fullName>
    <description>This field is used to store the details of the Message.</description>
    <label>Message Body</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Message_Subject__c/Message_Subject__c.object-meta.xml
<CustomObject>
    <label>Message Subject</label>
    <nameField>
        <displayFormat>MS-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Message Subjects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Message_Subject__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate Account with the Message Subject.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Message Subjects</relationshipLabel>
    <relationshipName>Message_Subjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message_Subject__c/fields/IsPortal__c.field-meta.xml
<CustomField>
    <fullName>IsPortal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to determine whether the message is from portal or CRM.</description>
    <label>IsPortal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message_Subject__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>This field is used for storing the message subject value.</description>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message_Subject__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate User with the Message Subject.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Message_Subjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VisitSummaryNotificationHandler.cls
public with sharing class VisitSummaryNotificationHandler {
    public static void visitNotifications(String accountId) {
        
        
        Account acc = [SELECT ID,Name,ElixirSuite__Email_Id__c FROM Account where id = :AccountId WITH security_enforced];
        EmailTemplate emailTemplate = [select Id, Subject, HtmlValue, Body from EmailTemplate where Id =: CreateFormForPortal.fetchEmailTemplateId('Patient_Notification_for_visit_summaries') WITH security_enforced];
        String htmlBody = emailTemplate.HtmlValue;
        
        //Elixir_Custom_Setting__c portalUrl = [SELECT Elixir_portal_url__c  FROM Elixir_Custom_Setting__c];
        Elixir_Custom_Setting__c portalUrl = ElixirSuite__Elixir_Custom_Setting__c.getOrgDefaults();
        
        htmlBody = htmlBody.replace('{!Account.Name}',acc.Name); 
        htmlBody = htmlBody.replace('{!Organization.Name}', UserInfo.getOrganizationName());
        htmlBody = htmlBody.replace('{Patientportallink}', '<a href='+ portalUrl.Elixir_portal_url__c+ '>click here</a>');
        // process the merge fields
        String subject = emailTemplate.Subject;
        subject = subject.replace('{!Organization.Name}',UserInfo.getOrganizationName()); 
        String plainBody = emailTemplate.Body;
        
        List<OrgWideEmailAddress> specificOrgWideEmailAddress = [SELECT Id, Address FROM OrgWideEmailAddress LIMIT 1];
        //build the email message
        Messaging.Singleemailmessage email = new Messaging.Singleemailmessage();
        email.setTargetObjectId(UserInfo.getUserId());
        email.setSaveAsActivity(false);
        email.setTreatTargetObjectAsRecipient(false);
        email.setToAddresses(new List<String>{acc.ElixirSuite__Email_Id__c}); 
        if(specificOrgWideEmailAddress!=null && specificOrgWideEmailAddress.size() >0){
            email.setOrgWideEmailAddressId(specificOrgWideEmailAddress[0].Id);   
          }      
        email.setSubject(subject);
        email.setHtmlBody(htmlBody);
        email.setPlainTextBody(plainBody);           
        Messaging.sendEmail(new Messaging.SingleEmailmessage[] {email});  

        
        
        String userId = UserInfo.getUserId();
        //Inserting a record in message subject 
        Message_Subject__c messageSubject = new Message_Subject__c();
        messageSubject.Subject__c = subject;
        messageSubject.Account__c = accountId;
        messageSubject.IsPortal__c = false;
        messageSubject.User__c = userId;
        DMLManager.insertAsUser(messageSubject);
        
        System.debug('messageSubject: ' + messageSubject.Id);
        System.debug('messageSubject - subject: ' + messageSubject.Subject__c);
        
     
         //Inserting a record in message Detail
        Message_Details__c messageDetails = new Message_Details__c();
        messageDetails.Message_Body__c = htmlBody;
        messageDetails.lookup_Message_Subject__c = messageSubject.Id;
        DMLManager.insertAsUser(messageDetails);
        
        System.debug('messageDetails-Body: ' + messageDetails.Message_Body__c);
    }
}