force-app/main/default/objects/Elixir_Custom_Setting__c/Elixir_Custom_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Elixir Custom Setting</label>
</CustomObject>

force-app/main/default/objects/Elixir_Custom_Setting__c/fields/Forms_Columns__c.field-meta.xml
<CustomField>
    <fullName>Forms_Columns__c</fullName>
    <label>Forms Columns</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/FormsColumnsConfigurationTest.cls
@isTest
private with sharing class FormsColumnsConfigurationTest {
    @isTest
    private static void createSettings() {
        Elixir_Custom_Setting__c columns = new Elixir_Custom_Setting__c(
            Forms_Columns__c = 'Status'
        ); 
        insert columns;
        FormsColumnsConfiguration.getFormsColumns();
        FormsColumnsConfiguration.saveColumns(new List<Object>{'CreatedBy'});
        Elixir_Custom_Setting__c savedColumns = Elixir_Custom_Setting__c.getOrgDefaults();
        system.assertEquals('CreatedBy', savedColumns.Forms_Columns__c,'');
    }
}