force-app/main/default/objects/Opportunity/fields/DOB__c.field-meta.xml
<CustomField>
    <fullName>DOB__c</fullName>
    <inlineHelpText>Client&apos;s Date of Birth</inlineHelpText>
    <label>DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Pre_assessment__c/Pre_assessment__c.object-meta.xml
<CustomObject>
    <label>Pre Assessment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Pre-Asessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Pre_assessment__c/fields/Date_Of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Birth__c</fullName>
    <description>This field is used to record the patient&apos;s date of birth</description>
    <label>Date Of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pre_assessment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to record the full name of the patient.</description>
    <inlineHelpText>If You Choose Patient Name than &quot;DOB,Subscriber DOB,Phone,Policy Subscriber Name&quot; will auto fill after save of record</inlineHelpText>
    <label>Name of Patient</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Pre Assessments</relationshipLabel>
    <relationshipName>Pre_assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pre_assessment__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>This field is used to record the phone number of the patient.</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Pre_assessment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>This field is used to describe the patient&apos;s current stage in the treatment process.</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assesment Pending</fullName>
                <default>true</default>
                <label>Assesment Pending</label>
            </value>
            <value>
                <fullName>Submit For Approval</fullName>
            </value>
            <value>
                <fullName>Assessment Approval Requested</fullName>
                <label>Assessment Requested</label>
            </value>
            <value>
                <fullName>Assessment Approved</fullName>
            </value>
            <value>
                <fullName>Assessment Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InsertPreAssessment.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-16-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class  InsertPreAssessment {
@auraEnabled
    public static void InsertPreAssessmentid(Id Oppid){
        system.debug('opp id'+oppid);
        
        Pre_assessment__c p=new Pre_assessment__c();
        try{
        if(Schema.sobjecttype.Opportunity.isAccessible()
                          && Schema.sObjectType.Opportunity.fields.Phone__c.isAccessible() && Schema.sObjectType.Opportunity.fields.DOB__c.isAccessible() )
        {
            Opportunity o=[select id,StageName,Phone__c,DOB__c from Opportunity where id=:Oppid];
            if(Schema.sObjectType.Pre_assessment__c.fields.Opportunity__c.isCreateable())
            {
              p.Opportunity__c=o.id;  
            }
             if( Schema.sObjectType.Pre_assessment__c.fields.Date_Of_Birth__c.isCreateable())
             {
                 p.Date_Of_Birth__c=o.DOB__c;
             }
       if( Schema.sObjectType.Pre_assessment__c.fields.Phone__c.isCreateable())
       {
         p.Phone__c=o.Phone__c;  
       }
        if(Schema.sObjectType.Pre_assessment__c.fields.Stage__c.isCreateable())
        {
            p.Stage__c=o.StageName;  
        }
      
        }
        
       
     if(schema.sobjecttype.Pre_assessment__c.isCreateable())
     {
         //insert p;
         DMLManager.insertAsUser(p);
     }
        }
         catch(Exception e){
         ExceptionLog.logError(e);
        }
   }
    
}