force-app/main/default/objects/Opportunity/fields/Location_text_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_text_Id__c</fullName>
    <label>Location text Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOB__c/VOB__c.object-meta.xml
<CustomObject>
    <description>This object tracks the verification of benefits/Patient Insurance details.</description>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VOB__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate the Patient Name with Opportunity.</description>
    <label>Patient Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Insurance</relationshipLabel>
    <relationshipName>VOB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SharingRuleBatchableVOBDelete.cls
public without sharing class SharingRuleBatchableVOBDelete implements Database.Batchable<sObject>, Database.Stateful{
    public Map<Id,List<Id>> userAllLocationsAccess = new Map<Id,List<Id>>();
    public SharingRuleBatchableVOBDelete(Map<Id,List<Id>> userAllLocationsAccess) {
        this.userAllLocationsAccess = userAllLocationsAccess;
    }
    public Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id, Opportunity__r.Location_Text_Id__c FROM VOB__c WHERE Opportunity__c!=NULL';
        return Database.getQueryLocator(query);
    }
   public void execute(Database.BatchableContext BC, List<sObject> scope){
       List<Vob__c> vobs = (List<Vob__c>)scope;
       Map<Id,sObject> vobMap = new Map<Id,sObject>(scope);
       Set<Id> vobIds = vobMap.keySet();
       Map<Id,Id> vobToActiveLocation = new Map<Id,Id>();
       for(Vob__c vob :vobs){
           vobToActiveLocation.put(vob.Id,vob.Opportunity__r.Location_Text_Id__c);
       }
       List<Vob__Share> vobSharedRecords = [SELECT Id, ParentId, UserOrGroupId FROM Vob__Share 
        WHERE ParentId IN :vobIds AND RowCause='Manual'];
        List<Vob__Share> recordsToDel = new List<Vob__Share>();
        for(Vob__Share vobSharedRecord :vobSharedRecords){
            Id vobId = vobSharedRecord.ParentId;
            Id userId = vobSharedRecord.UserOrGroupId;
            Id activeLocation = vobToActiveLocation.get(vobId);
            if(userAllLocationsAccess.containsKey(userId)){
                List<Id> allowedLocations = userAllLocationsAccess.get(userId);
                if(!allowedLocations.contains(activeLocation)){
                    recordsToDel.add(vobSharedRecord);
                }
            }
        }
        if(recordsToDel.size()>0){
            delete recordsToDel;
        }
   }
   public void finish(Database.BatchableContext BC){
    Database.executeBatch(new SharingRuleBatchablePreAssessmentDelete(userAllLocationsAccess),2000);
   }
}