force-app/main/default/objects/Opportunity/fields/Location_text_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_text_Id__c</fullName>
    <label>Location text Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOB__c/VOB__c.object-meta.xml
<CustomObject>
    <description>This object tracks the verification of benefits/Patient Insurance details.</description>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VOB__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate the Patient Name with Opportunity.</description>
    <label>Patient Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Insurance</relationshipLabel>
    <relationshipName>VOB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SharingRuleBatchableVOBInsert.cls
public without sharing class SharingRuleBatchableVOBInsert implements Database.Batchable<sObject>, Database.Stateful{
    public Map<Id,List<Id>> userAllLocationsAccess = new Map<Id,List<Id>>();
    public SharingRuleBatchableVOBInsert(Map<Id,List<Id>> userAllLocationsAccess) {
        this.userAllLocationsAccess = userAllLocationsAccess;
    }
    public Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id, Opportunity__r.Location_Text_Id__c FROM VOB__c WHERE Opportunity__c!=NULL';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<sObject> scope){
        List<Vob__c> vobs = (List<Vob__c>) scope;
        Map<Id,Id> vobToActiveLocation = new Map<Id,Id>();
        for(Vob__c vob :vobs){
            vobToActiveLocation.put(vob.Id,vob.Opportunity__r.Location_Text_Id__c);
        }
        List<Vob__share> newRecords = new List<Vob__share>();
        for(Vob__c vob :vobs){
            if(!vobToActiveLocation.containsKey(vob.Id)){
                continue;
            }
            Id vobActiveLocation = vobToActiveLocation.get(vob.Id);
            for(Id userId :userAllLocationsAccess.KeySet()){
                List<Id> userAccessibleLocations = userAllLocationsAccess.get(userId);
                if(userAccessibleLocations.contains(vobActiveLocation)){
                    VOB__share vobShare = new VOB__share();
                    vobShare.ParentId = vob.Id;
                    vobShare.UserOrGroupId = userId;
                    vobShare.RowCause = Schema.Vob__share.RowCause.Manual;
                    vobShare.AccessLevel = 'Edit';
                    newRecords.add(vobShare);
                }
            }
        }
        if(newRecords.size()>0){
            Database.insert(newRecords,false);
        }
    }
    public void finish(Database.BatchableContext BC){
        Database.executeBatch(new SharingRuleBatchablePreAssessmentInsert(userAllLocationsAccess),2000);
    }
}