force-app/main/default/objects/Opportunity/fields/Referral_Type__c.field-meta.xml
<CustomField>
    <fullName>Referral_Type__c</fullName>
    <inlineHelpText>Select &quot;Inbound&quot; if client was referred to us from another facility. Select &quot;Outbound&quot; if we are referring client out</inlineHelpText>
    <label>Referral Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referred_In_Organization__c.field-meta.xml
<CustomField>
    <fullName>Referred_In_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred In Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Patient Account</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Referred In Organization)</relationshipLabel>
    <relationshipName>Opportunities5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referred_Out_Organization__c.field-meta.xml
<CustomField>
    <fullName>Referred_Out_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred Out Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Patient Account</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Referred Out Organization)</relationshipLabel>
    <relationshipName>Opportunities6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOB__c/VOB__c.object-meta.xml
<CustomObject>
    <description>This object tracks the verification of benefits/Patient Insurance details.</description>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VOB__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate the Patient Name with Opportunity.</description>
    <label>Patient Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Insurance</relationshipLabel>
    <relationshipName>VOB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOB__c/fields/Payer__c.field-meta.xml
<CustomField>
    <fullName>Payer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to associate the Payer with payor.</description>
    <label>Payer</label>
    <referenceTo>Payor__c</referenceTo>
    <relationshipLabel>Insurance (Payer)</relationshipLabel>
    <relationshipName>VOB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestOpportunityAccountCounterTrigger.cls
/* BY Prachi Goel
* Coverage At time of Execution-83%
* 16-Apr-2020
*/


@isTest
public class TestOpportunityAccountCounterTrigger {
    @isTest
    //opp is choose referredout account  on updation of opp
    static void updateCountersAfterUpdate()
    {
        Test.startTest();
        Account getRecordsReferredin=TestDataUtility.setupAccountInboundTestData();
        Account getRecordsReferredout=TestDataUtility.setupAccountoutboundTestData();
        Map<id,Opportunity> oppMap=new Map<Id,Opportunity>();
        Opportunity getRecords=TestDataUtility.setupOpportunityOutReferralTestData();
        List<Opportunity> opplist=new List<Opportunity>();
        opplist.add(getRecords);
        for(Opportunity o:opplist)
        {
            o.Referred_In_Organization__c=getRecordsReferredin.id;
            o.Referred_Out_Organization__c=getRecordsReferredout.id;
        }
        update opplist;
        Test.stopTest();
          System.assertEquals('1', '1','');
    }
    
    @isTest
    //opp is choose referredin account  on updation of opp with inbound referral type
    static void updateCountersAfterAccountUpdate()
    {
        Test.startTest();
        Account getRecordsReferredin=TestDataUtility.setupAccountInboundTestData();
        //Account getRecordsReferredout=TestDataUtility.setupAccountoutboundTestData();
        Map<id,Opportunity> oppMap=new Map<Id,Opportunity>();
        Opportunity getRecords=TestDataUtility.setupOpportunityInReferralTestData();
        List<Opportunity> opplist=new List<Opportunity>();
        opplist.add(getRecords);
        for(Opportunity o:opplist)
        {
            o.Referred_In_Organization__c=getRecordsReferredin.id;
            o.Referral_Type__c='Inbound';
            
        }
        update opplist;
        Test.stopTest();
          System.assertEquals('1', '1','');
    }
    
    @istest
    static void testupdateCountersAfterReferralTypeUpdatefirst()
    {
        Test.startTest();
        Account getRecordsReferredin=TestDataUtility.setupAccountInboundTestData();
        //Account getRecordsReferredout=TestDataUtility.setupAccountoutboundTestData();
        Map<id,Opportunity> oppMap=new Map<Id,Opportunity>();
        Opportunity getRecords=TestDataUtility.setupOpportunityTestData();
        List<Opportunity> opplist=new List<Opportunity>();
        opplist.add(getRecords);
        for(Opportunity o:opplist)
        {
            o.Referred_In_Organization__c=getRecordsReferredin.id;
            o.Referral_Type__c='Inbound';
            
        }
        update opplist;
        Test.stopTest();
          System.assertEquals('1', '1','');
    }
    @istest
    static void testupdateCountersAfterReferralTypeUpdateSecond()
    {
        Test.startTest();
        Account getRecordsReferredin=TestDataUtility.setupAccountInboundTestData();
        //Account getRecordsReferredout=TestDataUtility.setupAccountoutboundTestData();
        Map<id,Opportunity> oppMap=new Map<Id,Opportunity>();
        Opportunity getRecords=TestDataUtility.setupOpportunityTestData();
        List<Opportunity> opplist=new List<Opportunity>();
        opplist.add(getRecords);
        for(Opportunity o:opplist)
        {
            o.Referred_In_Organization__c=getRecordsReferredin.id;
            o.Referral_Type__c='Outbound';
            
        }
        update opplist;
        Test.stopTest();
          System.assertEquals('1', '1','');
    }
    @istest
    static void testupdateCountersAfterReferralTypeUpdatefirstThird()
    {
        Test.startTest();
        Account getRecordsReferredin=TestDataUtility.setupAccountInboundTestData();
        //Account getRecordsReferredout=TestDataUtility.setupAccountoutboundTestData();
        Map<id,Opportunity> oppMap=new Map<Id,Opportunity>();
        Opportunity getRecords=TestDataUtility.setupOpportunityInReferralOutboundTestData();
        List<Opportunity> opplist=new List<Opportunity>();
        opplist.add(getRecords);
        for(Opportunity o:opplist)
        {
            o.Referred_In_Organization__c=getRecordsReferredin.id;
            o.Referral_Type__c='Inbound';
            
        }
        update opplist;
        Test.stopTest();
          System.assertEquals('1', '1','');
    }
    @istest
    static void testupdateCountersAfterReferralTypeUpdatefirstFourth()
    {
        Test.startTest();
        Account getRecordsReferredin=TestDataUtility.setupAccountInboundTestData();
        //Account getRecordsReferredout=TestDataUtility.setupAccountoutboundTestData();
        Map<id,Opportunity> oppMap=new Map<Id,Opportunity>();
        Opportunity getRecords=TestDataUtility.setupOpportunityInReferralTestData();
        List<Opportunity> opplist=new List<Opportunity>();
        opplist.add(getRecords);
        for(Opportunity o:opplist)
        {
            o.Referred_In_Organization__c=getRecordsReferredin.id;
            o.Referral_Type__c='Outbound';
            
        }
        update opplist;
        Test.stopTest();
          System.assertEquals('1', '1','');
    }
    
    @istest
    //opp is choose referredin account with inbound referraltype
    static void testupdateCountersAfterInsert2()
    {
        Test.startTest();
        Account getRecordsReferredin=TestDataUtility.setupAccountInboundTestData();
        Account getRecordsReferredout=TestDataUtility.setupAccountoutboundTestData();
        Map<id,Opportunity> oppMap=new Map<Id,Opportunity>();
        Opportunity getRecords=TestDataUtility.setupOpportunityInReferralTestData();
        List<Opportunity> opplist=new List<Opportunity>();
        opplist.add(getRecords);
        Test.stopTest();
          System.assertEquals('1', '1','');
    }
    @istest
    //opp is choose referredin account with outbound referraltype
    static void testupdateCountersAfterInsert3()
    {
        Test.startTest();
        Account getRecordsReferredin=TestDataUtility.setupAccountInboundTestData();
        Account getRecordsReferredout=TestDataUtility.setupAccountoutboundTestData();
        Map<id,Opportunity> oppMap=new Map<Id,Opportunity>();
        Opportunity getRecords=TestDataUtility.setupOpportunityInReferralOutboundTestData();
        List<Opportunity> opplist=new List<Opportunity>();
        opplist.add(getRecords);
        
        Test.stopTest();
          System.assertEquals('1', '1','');
    }
    @istest
    //opp is Deleted with Outbound referral type
    static void updateCountersAfterDelete()
    {
        Test.startTest();
        Account getRecordsReferredin=TestDataUtility.setupAccountInboundTestData();
        Account getRecordsReferredout=TestDataUtility.setupAccountoutboundTestData();
        Map<id,Opportunity> oppMap=new Map<Id,Opportunity>();
        Opportunity getRecords=TestDataUtility.setupOpportunityInReferralOutboundTestData();
        List<Opportunity> opplist=new List<Opportunity>();
        opplist.add(getRecords);
        delete opplist;
        Test.stopTest();
          System.assertEquals('1', '1','');
    }
    
    @istest
    //opp is Deleted with Inbound referral type
    static void updateCountersAfterDeleteSecond()
    {
        Test.startTest();
        Account getRecordsReferredin=TestDataUtility.setupAccountInboundTestData();
        Account getRecordsReferredout=TestDataUtility.setupAccountoutboundTestData();
        Map<id,Opportunity> oppMap=new Map<Id,Opportunity>();
        Opportunity getRecords=TestDataUtility.setupOpportunityInReferralOutboundTestData();
        List<Opportunity> opplist=new List<Opportunity>();
        opplist.add(getRecords);
        for(Opportunity o:opplist)
        {
            o.Referral_Type__c='Outbound';
        }
        update opplist;
        delete opplist;
        Test.stopTest();
          System.assertEquals('1', '1','');
    }
    @istest
    //Opp is updated with In Transit Stage
    static void exportAsPdf()
    {
        Test.startTest();
        Account getRecordsReferredin=TestDataUtility.setupAccountInboundTestData();
        Account getRecordsReferredout=TestDataUtility.setupAccountoutboundTestData();
        Map<id,Opportunity> oppMap=new Map<Id,Opportunity>();
        Opportunity getRecords=TestDataUtility.setupOpportunityInReferralOutboundTestData();
        ElixirSuite__Payor__c p  =new ElixirSuite__Payor__c();
        p.ElixirSuite__Payer_Code__c = 'abc1234';
        p.Name = 'demo';
        insert p;
        VOB__c v=new VOB__c();
        v.payer__c = p.Id;
       
        v.Opportunity__c=getRecords.id;
        v.ElixirSuite__Insured_Address__c = 'ABC';
        v.ElixirSuite__Date_Of_Birth__c = date.valueOf('2000-04-16');
        insert v;
        list<Opportunity> opplist=new list<Opportunity>();
        opplist.add(getRecords);
        for(Opportunity o:opplist)
        {
            o.StageName='In Transit';
        }
        update opplist;
        Test.stopTest();
          System.assertEquals('1', '1','');
    }
}