force-app/main/default/objects/Contact/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa/Addis_Ababa</fullName>
            </value>
            <value>
                <fullName>Africa/Algiers</fullName>
            </value>
            <value>
                <fullName>Africa/Asmera</fullName>
            </value>
            <value>
                <fullName>Africa/Bangui</fullName>
            </value>
            <value>
                <fullName>frica/Blantyre</fullName>
            </value>
            <value>
                <fullName>Africa/Brazzaville</fullName>
            </value>
            <value>
                <fullName>Africa/Bujumbura</fullName>
            </value>
            <value>
                <fullName>Africa/Cairo</fullName>
            </value>
            <value>
                <fullName>Africa/Casablanca</fullName>
            </value>
            <value>
                <fullName>Africa/Ceuta</fullName>
            </value>
            <value>
                <fullName>Africa/Dar_es_Salaam</fullName>
            </value>
            <value>
                <fullName>Africa/Djibouti</fullName>
            </value>
            <value>
                <fullName>Africa/Douala</fullName>
            </value>
            <value>
                <fullName>Africa/El_Aaiun</fullName>
            </value>
            <value>
                <fullName>Africa/Gaborone</fullName>
            </value>
            <value>
                <fullName>Africa/Harare</fullName>
            </value>
            <value>
                <fullName>Africa/Johannesburg</fullName>
            </value>
            <value>
                <fullName>Africa/Juba</fullName>
            </value>
            <value>
                <fullName>Africa/Kampala</fullName>
            </value>
            <value>
                <fullName>Africa/Khartoum</fullName>
            </value>
            <value>
                <fullName>Africa/Kigali</fullName>
            </value>
            <value>
                <fullName>Africa/Kinshasa</fullName>
            </value>
            <value>
                <fullName>Africa/Lagos</fullName>
            </value>
            <value>
                <fullName>Africa/Libreville</fullName>
            </value>
            <value>
                <fullName>Africa/Luanda</fullName>
            </value>
            <value>
                <fullName>Africa/Lubumbashi</fullName>
            </value>
            <value>
                <fullName>Africa/Lusaka</fullName>
            </value>
            <value>
                <fullName>Africa/Malabo</fullName>
            </value>
            <value>
                <fullName>Africa/Maputo</fullName>
            </value>
            <value>
                <fullName>Africa/Maseru</fullName>
            </value>
            <value>
                <fullName>Asia/Kolkata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Practitioner.recordType-meta.xml
<RecordType>
    <fullName>Practitioner</fullName>
    <active>true</active>
    <label>Practitioner</label>
</RecordType>

force-app/main/default/objects/Elixir_Custom_Setting__c/Elixir_Custom_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Elixir Custom Setting</label>
</CustomObject>

force-app/main/default/objects/Work_Schedule__c/Work_Schedule__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage the work timings for a practitioner within a facility.</description>
    <label>Work Schedule</label>
    <nameField>
        <displayFormat>WSN No-{0000}</displayFormat>
        <label>Work Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Schedule__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <description>Represents the days of the week covered by the work schedule.</description>
    <label>Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Schedule__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Captures the end date of the work schedule.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Schedule__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>Represents the end time of the work schedule.</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Work_Schedule__c/fields/Practitioner_Name__c.field-meta.xml
<CustomField>
    <fullName>Practitioner_Name__c</fullName>
    <description>Represents the name of the practitioner associated with the work schedule.</description>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Practitioner Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Practitioner</value>
        </filterItems>
        <filterItems>
            <field>Contact.Elixir_Contact_Type__c</field>
            <operation>equals</operation>
            <value>Elixir_Practitioner_Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Work Schedule</relationshipLabel>
    <relationshipName>Work_Schedule</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Schedule__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Captures the start date of the work schedule.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Schedule__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Represents the start time of the work schedule.</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Work_Schedule__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Specifies the time zone for the work schedule.</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Africa/Addis_Ababa</fullName>
            </value>
            <value>
                <fullName>Africa/Algiers</fullName>
            </value>
            <value>
                <fullName>Africa/Asmera</fullName>
            </value>
            <value>
                <fullName>Africa/Bangui</fullName>
            </value>
            <value>
                <fullName>Africa/Blantyre</fullName>
            </value>
            <value>
                <fullName>Africa/Brazzaville</fullName>
            </value>
            <value>
                <fullName>Africa/Bujumbura</fullName>
            </value>
            <value>
                <fullName>Africa/Cairo</fullName>
            </value>
            <value>
                <fullName>Africa/Casablanca</fullName>
            </value>
            <value>
                <fullName>Africa/Ceuta</fullName>
            </value>
            <value>
                <fullName>Africa/Dar_es_Salaam</fullName>
            </value>
            <value>
                <fullName>Africa/Djibouti</fullName>
            </value>
            <value>
                <fullName>Africa/Douala</fullName>
            </value>
            <value>
                <fullName>Africa/El_Aaiun</fullName>
            </value>
            <value>
                <fullName>Africa/Gaborone</fullName>
            </value>
            <value>
                <fullName>Africa/Harare</fullName>
            </value>
            <value>
                <fullName>Africa/Johannesburg</fullName>
            </value>
            <value>
                <fullName>Africa/Juba</fullName>
            </value>
            <value>
                <fullName>Africa/Kampala</fullName>
            </value>
            <value>
                <fullName>Africa/Khartoum</fullName>
            </value>
            <value>
                <fullName>Africa/Kigali</fullName>
            </value>
            <value>
                <fullName>Africa/Kinshasa</fullName>
            </value>
            <value>
                <fullName>Africa/Lagos</fullName>
            </value>
            <value>
                <fullName>Africa/Libreville</fullName>
            </value>
            <value>
                <fullName>Africa/Luanda</fullName>
            </value>
            <value>
                <fullName>Africa/Lubumbashi</fullName>
            </value>
            <value>
                <fullName>Africa/Lusaka</fullName>
            </value>
            <value>
                <fullName>Africa/Malabo</fullName>
            </value>
            <value>
                <fullName>Africa/Maputo</fullName>
            </value>
            <value>
                <fullName>Africa/Maseru</fullName>
            </value>
            <value>
                <fullName>Asia/Kolkata</fullName>
                <default>true</default>
                <label>Asia/Kolkata</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Schedule__c/fields/Work_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Work_Schedule__c</fullName>
    <description>Represents the self lookup field associated with work schedule.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Schedule</label>
    <referenceTo>Work_Schedule__c</referenceTo>
    <relationshipLabel>Work Schedule</relationshipLabel>
    <relationshipName>Work_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WorkScheduleControllerTest.cls
@isTest
public class WorkScheduleControllerTest {
    
    @isTest
    public static void workSchedulesTest(){
        Elixir_Custom_Setting__c pracRectype = new Elixir_Custom_Setting__c();
        pracRectype.ElixirSuite__Practitioner_Contact_Recordtype__c = 'Practitioner';
        insert pracRectype;
        String contactRecType = pracRectype.ElixirSuite__Practitioner_Contact_Recordtype__c;  
        Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get(contactRecType).getRecordTypeId();
        Contact con = new Contact();
        con.RecordTypeId = recordTypeId;
        con.Is_Active__c = true;
        con.lastName = 'Mahendra';
        insert con;
        
        List<Work_Schedule__c> newWorkScheduleList = new List<Work_Schedule__c>();
        
        Work_Schedule__c workSchedule = new Work_Schedule__c();
        workSchedule.Practitioner_Name__c = con.Id;
        workSchedule.Start_Date__c = Date.today();
        workSchedule.End_Date__c = Date.today()+30;
        workSchedule.Start_Time__c = Time.newInstance(9, 0, 0, 0);
        workSchedule.End_Time__c = Time.newInstance(9, 30, 0, 0);
        workSchedule.Time_Zone__c = 'Asia/Kolkata';
        workSchedule.Days__c = 'Monday';
        newWorkScheduleList.add(workSchedule);
        insert newWorkScheduleList;
        List<ElixirSuite__Work_Schedule__c> ExistingWorkSchedule = [Select Id,ElixirSuite__Work_Schedule__c,ElixirSuite__Practitioner_Name__c 
                                                                    FROM ElixirSuite__Work_Schedule__c 
                                                                    WHERE ElixirSuite__Work_Schedule__c!= null];
        test.startTest();
        WorkScheduleController.getPractitionerList('Mah');
        WorkScheduleController.getPractitionerAvailability(con.id);
        system.assertEquals(1, 1, 'msg');
        test.stopTest();
    }
    
}