force-app/main/default/objects/Contact/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa/Addis_Ababa</fullName>
            </value>
            <value>
                <fullName>Africa/Algiers</fullName>
            </value>
            <value>
                <fullName>Africa/Asmera</fullName>
            </value>
            <value>
                <fullName>Africa/Bangui</fullName>
            </value>
            <value>
                <fullName>frica/Blantyre</fullName>
            </value>
            <value>
                <fullName>Africa/Brazzaville</fullName>
            </value>
            <value>
                <fullName>Africa/Bujumbura</fullName>
            </value>
            <value>
                <fullName>Africa/Cairo</fullName>
            </value>
            <value>
                <fullName>Africa/Casablanca</fullName>
            </value>
            <value>
                <fullName>Africa/Ceuta</fullName>
            </value>
            <value>
                <fullName>Africa/Dar_es_Salaam</fullName>
            </value>
            <value>
                <fullName>Africa/Djibouti</fullName>
            </value>
            <value>
                <fullName>Africa/Douala</fullName>
            </value>
            <value>
                <fullName>Africa/El_Aaiun</fullName>
            </value>
            <value>
                <fullName>Africa/Gaborone</fullName>
            </value>
            <value>
                <fullName>Africa/Harare</fullName>
            </value>
            <value>
                <fullName>Africa/Johannesburg</fullName>
            </value>
            <value>
                <fullName>Africa/Juba</fullName>
            </value>
            <value>
                <fullName>Africa/Kampala</fullName>
            </value>
            <value>
                <fullName>Africa/Khartoum</fullName>
            </value>
            <value>
                <fullName>Africa/Kigali</fullName>
            </value>
            <value>
                <fullName>Africa/Kinshasa</fullName>
            </value>
            <value>
                <fullName>Africa/Lagos</fullName>
            </value>
            <value>
                <fullName>Africa/Libreville</fullName>
            </value>
            <value>
                <fullName>Africa/Luanda</fullName>
            </value>
            <value>
                <fullName>Africa/Lubumbashi</fullName>
            </value>
            <value>
                <fullName>Africa/Lusaka</fullName>
            </value>
            <value>
                <fullName>Africa/Malabo</fullName>
            </value>
            <value>
                <fullName>Africa/Maputo</fullName>
            </value>
            <value>
                <fullName>Africa/Maseru</fullName>
            </value>
            <value>
                <fullName>Asia/Kolkata</fullName>
            </value>
            <value>
                <fullName>America/New_York</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Practitioner.recordType-meta.xml
<RecordType>
    <fullName>Practitioner</fullName>
    <active>true</active>
    <label>Practitioner</label>
</RecordType>

force-app/main/default/objects/Procedure__c/Procedure__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the template procedures in the system. These might include lab order, medications, CPT codes, Appointment procedures.</description>
    <label>Procedure Codes</label>
    <nameField>
        <label>Code Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedure Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Procedure__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rendering Provider</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Provider__c.Account__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipName>Procedures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provider__c/Provider__c.object-meta.xml
<CustomObject>
    <description>This object stores both template and patient providers. Providers in elixir are facilties.</description>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents self-relationship.</description>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.Account__r.Id</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Specialty__c/Specialty__c.object-meta.xml
<CustomObject>
    <description>Specialty represents specialties for a practitioner or a service organization. A provider can have multiple specialties such as anesthesiology and cardiovascular.</description>
    <label>Specialty</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Specialty</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Specialties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Specialty__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserLocation__c/UserLocation__c.object-meta.xml
<CustomObject>
    <description>Practitioner Location stores all the practitioners working in a particular location  (location here represents a record saved in the Provider Object)</description>
    <label>Practitioner Location</label>
    <nameField>
        <label>UserLocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Practitioner Location</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UserLocation__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Template_Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider__c</referenceTo>
    <relationshipLabel>UserLocation</relationshipLabel>
    <relationshipName>UserLocation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserLocation__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Specialty</label>
    <referenceTo>Specialty__c</referenceTo>
    <relationshipLabel>UserLocation</relationshipLabel>
    <relationshipName>UserLocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Schedule__c/Work_Schedule__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage the work timings for a practitioner within a facility.</description>
    <label>Work Schedule</label>
    <nameField>
        <displayFormat>WSN No-{0000}</displayFormat>
        <label>Work Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Schedule__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <description>Represents the days of the week covered by the work schedule.</description>
    <label>Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Schedule__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Captures the end date of the work schedule.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Schedule__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>Represents the end time of the work schedule.</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Work_Schedule__c/fields/Practitioner_Name__c.field-meta.xml
<CustomField>
    <fullName>Practitioner_Name__c</fullName>
    <description>Represents the name of the practitioner associated with the work schedule.</description>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Practitioner Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Practitioner</value>
        </filterItems>
        <filterItems>
            <field>Contact.Elixir_Contact_Type__c</field>
            <operation>equals</operation>
            <value>Elixir_Practitioner_Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Work Schedule</relationshipLabel>
    <relationshipName>Work_Schedule</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Schedule__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Captures the start date of the work schedule.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Schedule__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Represents the start time of the work schedule.</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Work_Schedule__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Specifies the time zone for the work schedule.</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Africa/Addis_Ababa</fullName>
            </value>
            <value>
                <fullName>Africa/Algiers</fullName>
            </value>
            <value>
                <fullName>Africa/Asmera</fullName>
            </value>
            <value>
                <fullName>Africa/Bangui</fullName>
            </value>
            <value>
                <fullName>Africa/Blantyre</fullName>
            </value>
            <value>
                <fullName>Africa/Brazzaville</fullName>
            </value>
            <value>
                <fullName>Africa/Bujumbura</fullName>
            </value>
            <value>
                <fullName>Africa/Cairo</fullName>
            </value>
            <value>
                <fullName>Africa/Casablanca</fullName>
            </value>
            <value>
                <fullName>Africa/Ceuta</fullName>
            </value>
            <value>
                <fullName>Africa/Dar_es_Salaam</fullName>
            </value>
            <value>
                <fullName>Africa/Djibouti</fullName>
            </value>
            <value>
                <fullName>Africa/Douala</fullName>
            </value>
            <value>
                <fullName>Africa/El_Aaiun</fullName>
            </value>
            <value>
                <fullName>Africa/Gaborone</fullName>
            </value>
            <value>
                <fullName>Africa/Harare</fullName>
            </value>
            <value>
                <fullName>Africa/Johannesburg</fullName>
            </value>
            <value>
                <fullName>Africa/Juba</fullName>
            </value>
            <value>
                <fullName>Africa/Kampala</fullName>
            </value>
            <value>
                <fullName>Africa/Khartoum</fullName>
            </value>
            <value>
                <fullName>Africa/Kigali</fullName>
            </value>
            <value>
                <fullName>Africa/Kinshasa</fullName>
            </value>
            <value>
                <fullName>Africa/Lagos</fullName>
            </value>
            <value>
                <fullName>Africa/Libreville</fullName>
            </value>
            <value>
                <fullName>Africa/Luanda</fullName>
            </value>
            <value>
                <fullName>Africa/Lubumbashi</fullName>
            </value>
            <value>
                <fullName>Africa/Lusaka</fullName>
            </value>
            <value>
                <fullName>Africa/Malabo</fullName>
            </value>
            <value>
                <fullName>Africa/Maputo</fullName>
            </value>
            <value>
                <fullName>Africa/Maseru</fullName>
            </value>
            <value>
                <fullName>Asia/Kolkata</fullName>
                <default>true</default>
                <label>Asia/Kolkata</label>
            </value>
            <value>
                <fullName>America/New_York</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Schedule__c/fields/Work_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Work_Schedule__c</fullName>
    <description>Represents the self lookup field associated with work schedule.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Schedule</label>
    <referenceTo>Work_Schedule__c</referenceTo>
    <relationshipLabel>Work Schedule</relationshipLabel>
    <relationshipName>Work_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/showAvailabilityAppointmentTest.cls
@isTest
public class showAvailabilityAppointmentTest {
	@isTest
    static void testGetPracDataForPortal(){
        Profile profileId = [SELECT Id FROM Profile WHERE Name ='System Administrator' LIMIT 1];
        User user = new User();
        user.ProfileID = profileId.id;
        user.EmailEncodingKey = 'ISO-8859-1';
        user.LanguageLocaleKey = 'en_US';
        user.TimeZoneSidKey = 'America/New_York';
        user.LocaleSidKey = 'en_US';
        user.FirstName = 'firstt';
        user.LastName = 'lastt';
        user.Username = 'testtt@uniquedomain.com';
        user.CommunityNickname = 'testUser123';
        user.Alias = 't1';
        user.Email = 'no@email.com';
        //user.ContactId = con.Id;
        insert user;
        Elixir_Custom_Setting__c pracRectype = new Elixir_Custom_Setting__c();
        pracRectype.ElixirSuite__Practitioner_Contact_Recordtype__c = 'Practitioner';
        insert pracRectype;
        String contactRecType = pracRectype.ElixirSuite__Practitioner_Contact_Recordtype__c; 
        Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get(contactRecType).getRecordTypeId();
        Contact con = new Contact();
        con.RecordTypeId = recordTypeId;
        con.LastName = 'Test Contact';
        con.ElixirSuite__Practitioner_User__c = user.Id;
        insert con;
        
        Specialty__c sp = new Specialty__c ();
        sp.ElixirSuite__Specialty_Name__c = 'Surgian';
        sp.Code__c = 'N124';
        insert sp;
        
        Provider__c p = TestDataFactory.createProviderTemp();
        insert p;
        
        Procedure__c procedure = new Procedure__c();
        procedure.Name = 'A90';
        procedure.ElixirSuite__Active__c = true;
        procedure.ElixirSuite__Procedure_Duration__c = '30';
        procedure.ElixirSuite__Appointment_Type__c = true;
        insert procedure;
        
        Procedure__c procedure1 = new Procedure__c();
        procedure1.Name = 'A91';
        procedure1.ElixirSuite__Active__c = true;
        procedure1.ElixirSuite__Procedure_Duration__c = '15';
        procedure1.ElixirSuite__Appointment_Type__c = true;
        insert procedure1;
        
        List<Work_Schedule__c> newWorkScheduleList = new List<Work_Schedule__c>();

        Work_Schedule__c workSchedule = new Work_Schedule__c();
        workSchedule.Practitioner_Name__c = con.Id;
        workSchedule.Start_Date__c = Date.today();
        workSchedule.End_Date__c = Date.today()+30;
        workSchedule.Start_Time__c = Time.newInstance(6, 0, 0, 0);
        workSchedule.End_Time__c = Time.newInstance(8, 30, 0, 0);
        workSchedule.Time_Zone__c = 'Asia/Kolkata';
        workSchedule.Days__c = 'Monday';
        workSchedule.ElixirSuite__Appointment_Types__c = 'A90';
        workSchedule.ElixirSuite__Provider_Location__c = p.Id;
        newWorkScheduleList.add(workSchedule);
        insert newWorkScheduleList;
		
        List<Work_Schedule__c> newWorkScheduleList1 = new List<Work_Schedule__c>();

        Work_Schedule__c workSchedule1 = new Work_Schedule__c();
        workSchedule1.Practitioner_Name__c = con.Id;
        workSchedule1.Start_Date__c = Date.today();
        workSchedule1.End_Date__c = Date.today()+30;
        workSchedule1.Start_Time__c = Time.newInstance(10, 0, 0, 0);
        workSchedule.End_Time__c = Time.newInstance(11, 30, 0, 0);
        workSchedule1.Time_Zone__c = 'Asia/Kolkata';
        workSchedule1.Days__c = 'Monday';
        workSchedule.ElixirSuite__Appointment_Types__c = 'A91';
        workSchedule1.ElixirSuite__Provider_Location__c = p.Id;
        newWorkScheduleList1.add(workSchedule1);
        insert newWorkScheduleList1;
        
        UserLocation__c ul = new UserLocation__c();
        ul.Practitioner__c = con.Id;
        ul.ElixirSuite__Specialty__c = sp.Id;
        ul.ElixirSuite__Provider__c = p.Id;
        insert ul;
        system.runAs(user) {
        Test.startTest();
        showAvailabilityAppointmentController.getPracDataForPortal(user.Id,Date.today(),Date.today()+1);
        showAvailabilityAppointmentController.getAppointmentType(con.id,p.id,Date.today(),Date.today()+7);
        showAvailabilityAppointmentController.workslot(con.id,p.id,Date.today(),Date.today()+7,'A90');
        showAvailabilityAppointmentController.getPatientId();
        showAvailabilityAppointmentController.getAppointmentTypePortal();
        system.assertEquals(1, 1,' ');
        Test.stopTest();
        }
    }
}