force-app/main/default/objects/Form_Template_Data__c/Form_Template_Data__c.object-meta.xml
<CustomObject>
    <description>Form Template Data stores all the macros chosen on the forms. This object stores the transactional data of the macros.</description>
    <label>Form Template Data</label>
    <nameField>
        <displayFormat>FT-{0000}</displayFormat>
        <label>Form Template Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Template Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Template_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Form Template Data</relationshipLabel>
    <relationshipName>Form_Template_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Template_Data__c/fields/Form_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Form_Unique_Id__c</fullName>
    <label>Form Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Template_Data__c/fields/Section_Number__c.field-meta.xml
<CustomField>
    <fullName>Section_Number__c</fullName>
    <label>Section Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/Form_Value__c.object-meta.xml
<CustomObject>
    <description>Form value stores all the miscellaneous features of the saved forms like Approvals, Care Episodes and Status. All the problems, diagnoses, medications and allergies selected on the forms are also linked with this object as the record in this object is also responsible for giving one identity to the forms saved in multiple objects.</description>
    <label>Form Value</label>
    <nameField>
        <label>Form Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Value__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Form Values</relationshipLabel>
    <relationshipName>Form_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Care_Episode__c.field-meta.xml
<CustomField>
    <fullName>Care_Episode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Episode</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Is_CareEpisode__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Visits__c</referenceTo>
    <relationshipLabel>Forms/Notes</relationshipLabel>
    <relationshipName>Form_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Episode_Id__c.field-meta.xml
<CustomField>
    <fullName>Episode_Id__c</fullName>
    <label>Episode Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Form_Id__c.field-meta.xml
<CustomField>
    <fullName>Form_Id__c</fullName>
    <label>Form Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Form_Name__c.field-meta.xml
<CustomField>
    <fullName>Form_Name__c</fullName>
    <label>Form Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Value__c/fields/Is_CareEpisode__c.field-meta.xml
<CustomField>
    <fullName>Is_CareEpisode__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is CareEpisode</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/inlineEditCareEpisodeControllerTest.cls
@isTest
public class inlineEditCareEpisodeControllerTest {
    
    @isTest
    public static void insCareEps(){
        
        Account accRec = new Account();
        accRec.Name = 'Mahima';
        accRec.ElixirSuite__DOB__c = System.today();
        accRec.ElixirSuite__Gender__c = 'Female';
        accRec.ElixirSuite__Email_Id__c = 'anmolsaxena.25@gmail.com';
        accRec.ElixirSuite__MRN_Number_New__c = 'mir770';
        insert accRec;
        
        ElixirSuite__Visits__c careRec = new ElixirSuite__Visits__c();
        careRec.ElixirSuite__Account__c = accRec.Id;
        careRec.Name = 'Mahima Vist';
        careRec.ElixirSuite__Status__c = 'Active';
        insert careRec;
        
        Form_Template_Data__c tdRec = new Form_Template_Data__c(Form_Unique_Id__c = 'I874841232323', Section_Number__c = '2', Account__c = accRec.Id);
        
        DMLManager.insertAsUser(tdRec);
        
        String formUnId = tdRec.Form_Unique_Id__c;
        
        String res = inlineEditCareEpisodeController.updateCareEpisode(careRec.Id,accRec.Id,formUnId);
        
        System.AssertEquals('completed',res);
        
    }
    
    @isTest
    public static void updCareEps(){
        
        Account accRec = new Account();
        accRec.Name = 'Mahima';
        accRec.ElixirSuite__DOB__c = System.today();
        accRec.ElixirSuite__Gender__c = 'Female';
        accRec.ElixirSuite__Email_Id__c = 'anmolsaxena.25@gmail.com';
        accRec.ElixirSuite__MRN_Number_New__c = 'mir770';
        insert accRec;
        
        ElixirSuite__Visits__c careRec = new ElixirSuite__Visits__c();
        careRec.ElixirSuite__Account__c = accRec.Id;
        careRec.Name = 'Mahima Vist';
        careRec.ElixirSuite__Status__c = 'Active';
        insert careRec;
        
        Form_Template_Data__c tdRec = new Form_Template_Data__c(Form_Unique_Id__c = 'I874841232323', Section_Number__c = '2', Account__c = accRec.Id);
        
        DMLManager.insertAsUser(tdRec);
        
        String formUnId = tdRec.Form_Unique_Id__c;
        
        String formValueName = '';
        formValueName = 'Form -' + system.now().format();
        Form_value__c formValue = new Form_Value__C(
            Name = formValueName,
            Form_Name__c= formValueName,
            Form_Id__c = formUnId,
            Account__c = accRec.Id,
            Is_CareEpisode__c = true,
            Care_Episode__c = careRec.Id,
            Episode_Id__c = careRec.Id
        );
        DMLManager.insertAsUser(formValue);
        
        String res = inlineEditCareEpisodeController.updateCareEpisode(careRec.Id,accRec.Id,formUnId);
        
        System.AssertEquals('completed',res);
        
    }
    
}