force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Elixir_Custom_Setting__c/Elixir_Custom_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Elixir Custom Setting</label>
</CustomObject>

force-app/main/default/objects/Elixir_Custom_Setting__c/fields/Lab_Order__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Lab Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HL7__c/HL7__c.object-meta.xml
<CustomObject>
    <label>LabOrder HL7 Results</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>LabOrder HL7 Results ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LabOrder HL7 Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HL7__c/fields/Order_ID__c.field-meta.xml
<CustomField>
    <fullName>Order_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order_ID</label>
    <referenceTo>Lab_Order__c</referenceTo>
    <relationshipName>LabOrder_HL7_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/Lab_Order__c.object-meta.xml
<CustomObject>
    <label>Lab Test</label>
    <nameField>
        <displayFormat>LabOrder-{0000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab_Order__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Collection_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Collection_Date_Time__c</fullName>
    <label>Collection Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Doctors_Note__c.field-meta.xml
<CustomField>
    <fullName>Doctors_Note__c</fullName>
    <label>Doctors Note</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Expected_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Expected_Date_Time__c</fullName>
    <label>Expected Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Facility_Id__c.field-meta.xml
<CustomField>
    <fullName>Facility_Id__c</fullName>
    <label>Facility Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/ICD_Id__c.field-meta.xml
<CustomField>
    <fullName>ICD_Id__c</fullName>
    <label>ICD Id</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Lab_Id__c.field-meta.xml
<CustomField>
    <fullName>Lab_Id__c</fullName>
    <label>Lab Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Lab_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order_Number__c</fullName>
<description>This field is used for storing Order ID</description>
    <label>Lab Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Lab_Order_Req__c.field-meta.xml
<CustomField>
    <fullName>Lab_Order_Req__c</fullName>
<description>This field used to store placer order number</description>
    <label>Lab Order Req</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/LabName__c.field-meta.xml
<CustomField>
    <fullName>LabName__c</fullName>
    <label>LabName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Physician_Name__c.field-meta.xml
<CustomField>
    <fullName>Physician_Name__c</fullName>
    <label>Physician Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>E</fullName>
                <label>Entered</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Transmitted</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Results Received (Partial)</fullName>
            </value>
            <value>
                <fullName>Results Received</fullName>
            </value>
            <value>
                <fullName>Final Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It is used to connect the test to the lab order.</description>
    <label>Test</label>
    <referenceTo>Test__c</referenceTo>
    <relationshipName>Lab_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Test_Id__c.field-meta.xml
<CustomField>
    <fullName>Test_Id__c</fullName>
    <label>Test Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Test_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Name__c</fullName>
    <label>Test Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab_Order__c/fields/Test_Result_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Result_Name__c</fullName>
    <label>Test_Result_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LabOrder_Hl7_Results_Tests_Info__c/LabOrder_Hl7_Results_Tests_Info__c.object-meta.xml
<CustomObject>
    <label>LabOrder Hl7 Results Tests Info</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>LabOrder Hl7 Results Tests Info ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LabOrder Hl7 Results Tests Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LabOrder_Hl7_Results_Tests_Info__c/fields/LabOrder_HL7_Results_ID__c.field-meta.xml
<CustomField>
    <fullName>LabOrder_HL7_Results_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LabOrder_HL7_Results_ID</label>
    <referenceTo>HL7__c</referenceTo>
    <relationshipName>Test_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LabOrder_Hl7_Results_Tests_Info__c/fields/Test_Result_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Result_Name__c</fullName>
    <label>Test_Result_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notes__c/Notes__c.object-meta.xml
<CustomObject>
    <label>Notes</label>
    <nameField>
        <displayFormat>NT-{0000}</displayFormat>
        <label>Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notes__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Notes__c/fields/test__c.field-meta.xml
<CustomField>
    <fullName>test__c</fullName>
    <formula>&apos;hello....&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>test</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>This object is used to track order details for a patient. The orders can be medication, lab or any inventory related orders.</description>
    <label>Order</label>
    <nameField>
        <displayFormat>OR{MMDDYYYY}{000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <description>Specifies the type or category of the order.</description>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inventory Order</fullName>
            </value>
            <value>
                <fullName>Prescription Order</fullName>
            </value>
            <value>
                <fullName>Lab Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test__c/Test__c.object-meta.xml
<CustomObject>
    <label>Test</label>
    <nameField>
        <displayFormat>Id-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test__c/fields/Lab_Id__c.field-meta.xml
<CustomField>
    <fullName>Lab_Id__c</fullName>
    <label>Lab Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test__c/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Users are able to select only package tests.</errorMessage>
        <filterItems>
            <field>Test__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Package</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Test__c</referenceTo>
    <relationshipLabel>Tests</relationshipLabel>
    <relationshipName>Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test__c/fields/Test_Id__c.field-meta.xml
<CustomField>
    <fullName>Test_Id__c</fullName>
    <label>Test Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Test__c/fields/Test_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Result_Detail__c/Test_Result_Detail__c.object-meta.xml
<CustomObject>
    <label>Lab Test Results</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>LabOrder Hl7 Results Tests Parameters ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Test Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Result_Detail__c/fields/DataforTrends__c.field-meta.xml
<CustomField>
    <fullName>DataforTrends__c</fullName>
    <formula>IF( Observation_Value_type__c = &apos;ST&apos;,VALUE( Observation_Value_Text__c ),IF( Observation_Value_type__c = &apos;NM&apos;, Observation_Value_Numeric__c ,null))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DataforTrends</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Test_Result_Detail__c/fields/Observation_Value__c.field-meta.xml
<CustomField>
    <fullName>Observation_Value__c</fullName>
    <label>Observation Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Result_Detail__c/fields/Observation_Value_Text__c.field-meta.xml
<CustomField>
    <fullName>Observation_Value_Text__c</fullName>
    <label>Observation Value - Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Result_Detail__c/fields/Observation_Value_type__c.field-meta.xml
<CustomField>
    <fullName>Observation_Value_type__c</fullName>
    <label>Observation Value type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Result_Detail__c/fields/References_Range__c.field-meta.xml
<CustomField>
    <fullName>References_Range__c</fullName>
    <label>References Range</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Test_Result_Detail__c/fields/Test_Result_Detail_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Result_Detail_Name__c</fullName>
    <label>Test Result Detail Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Result_Detail__c/fields/Test_ResultId__c.field-meta.xml
<CustomField>
    <fullName>Test_ResultId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Result Id</label>
    <referenceTo>Lab_Order__c</referenceTo>
    <relationshipName>LabOrder_Hl7_Results_Tests_Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Result_Detail__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <label>Unit</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/LabOrderDetails.cls
public with sharing class LabOrderDetails {

    @AuraEnabled(cacheable=true)
    public static String getPatientId() {
        String patientId='';
        String uId = UserInfo.getUserId();
        List<User> userRecs = Database.query('SELECT id,ContactId,AccountId FROM User WHERE Id =:uId');
        if(userRecs!=null && userRecs.size()>0){
            patientId = (String)userRecs[0].get('AccountId');
        }
        return patientId;
    }
    //method to fetch the details of selected lab order
    @AuraEnabled(cacheable=true)
    public static Lab_Order__c getLabOrderDetails(String recordId) {
     
        try{return [SELECT Id, ElixirSuite__Account_Id__c, Lab_Order_Req__c , Doctors_Note__c, Expected_Date_Time__c, Order_Type__c,ElixirSuite__Ordering_Provider__c, ElixirSuite__Ordering_Provider__r.Name,ElixirSuite__Ordering_Provider__r.FirstName,ElixirSuite__Ordering_Provider__r.LastName, Physician_Name__c ,ICD_Id__c,  Facility_Id__c , Test_Id__c, Collection_Date_Time__c,Lab_Id__c  FROM Lab_Order__c where id =: recordId WITH SECURITY_ENFORCED];}
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
       
    }

    //method to update doctor's note in the lab order records
    @AuraEnabled
    public static void addNote(String recordId, string doctorNote ){
        try{Lab_Order__c l = [SELECT Id, Doctors_Note__c FROM Lab_Order__c where id =: recordId WITH SECURITY_ENFORCED];

          
            l.Doctors_Note__c = doctorNote;
            //Database.update(l);
            DMLManagerV2.updateAsUser(l);
        
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
 
           
    }
    
    //method to get Tests list
    @AuraEnabled(cacheable=true)
    public static List<Test__c> getTests(string OrderId){
       try{list<Lab_Order__c> orders = [Select Id, Test_Id__c from Lab_Order__c where Lab_Order_Req__c =: OrderId WITH SECURITY_ENFORCED];
       list<string> ids = new list<string>();
       for(Lab_Order__c l : Orders){
            ids.add(l.Test_Id__c);
       }

        return [SELECT Id, Test_Id__c, Test_Name__c, Lab_Id__c FROM Test__c where Test_Id__c IN :ids WITH SECURITY_ENFORCED order by Test_Name__c];}
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    //method to get ICD list
    @AuraEnabled(cacheable=true)
    public static List<ElixirSuite__ICD_Codes__c> getICDs(list<string> ICD_Id, String accountId){
        try {
        String queryWithAccount = 'SELECT Id, Name, ElixirSuite__Code_Description1__c FROM ElixirSuite__ICD_Codes__c WHERE Name IN :ICD_Id AND ElixirSuite__Account__c = :accountId WITH SECURITY_ENFORCED ORDER BY Name';

        List<ElixirSuite__ICD_Codes__c> resultWithAccount = Database.query(queryWithAccount);
List<ElixirSuite__ICD_Codes__c> filteredResult = new List<ElixirSuite__ICD_Codes__c>();

// Populate filteredResult with unique records from resultWithAccount
        Set<String> uniqueNamesSet = new Set<String>();
for (ElixirSuite__ICD_Codes__c record : resultWithAccount) {
    // Check if the Name value is unique
    if (!uniqueNamesSet.contains(record.Name)) {
        // Add the record to the filtered result
        filteredResult.add(record);
uniqueNamesSet.add(record.Name); // Add the Name to the set to track uniqueness
    }
}

            String queryWithoutAccount = 'SELECT Id, Name, ElixirSuite__Code_Description1__c FROM ElixirSuite__ICD_Codes__c WHERE Name IN :ICD_Id WITH SECURITY_ENFORCED ORDER BY Name';

            List<ElixirSuite__ICD_Codes__c> resultWithoutAccount = Database.query(queryWithoutAccount);
            
// Populate filteredResult with unique records from resultWithoutAccount
            for (ElixirSuite__ICD_Codes__c record : resultWithoutAccount) {
                // Use the Name field as the key in the map to ensure uniqueness
                if (!uniqueNamesSet.contains(record.Name)) {
        filteredResult.add(record);
        uniqueNamesSet.add(record.Name);
    }
            }

            return filteredResult;


           
        
    } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
        }
    }
    
    //method to get physician list
    @AuraEnabled(cacheable=true)
    public static List<Contact> getPhysicians(){
        try{
            Elixir_Custom_Setting__c val = Elixir_Custom_Setting__c.getOrgDefaults();
        String contactRecType = val.ElixirSuite__Practitioner_Contact_Recordtype__c;
        Id practitionerRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get(contactRecType).getRecordTypeId();
            return [SELECT Id, FirstName, LastName,Name FROM Contact where ElixirSuite__Is_Active__c=TRUE AND RecordTypeId=:practitionerRecTypeId WITH SECURITY_ENFORCED order by LastName];
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    
   
    //method use in lwc component to fetch obx details
    /* @AuraEnabled(cacheable=true)
    public static list<Lab_Order__c> getTestResultsLWC(string r_id){
        try{
            // Lab_Order__c l = [select Test_Name__c from Lab_Order__c where Id =: r_id WITH SECURITY_ENFORCED];
            // HL7__c hl7 = [select Id from HL7__c where Order_ID__c =: r_id WITH SECURITY_ENFORCED Limit 1];
            // list<LabOrder_Hl7_Results_Tests_Info__c> ObrList = [select Id from LabOrder_Hl7_Results_Tests_Info__c where LabOrder_HL7_Results_ID__c =: hl7.Id and Test_Result_Name__c =: l.Test_Name__c WITH SECURITY_ENFORCED];
            // list<string> ObrIds = new list<string>();
            // for(LabOrder_Hl7_Results_Tests_Info__c o : ObrList){
            //     ObrIds.add(o.Id);
            // }
        list<Test_Result_Detail__c> testresults = [select id, Test_Result_Detail_Name__c, Notes__c, DataforTrends__c  , References_Range__c, Units__c, Observation_Value__c, Observation_Value_type__c from Test_Result_Detail__c where Test_ResultId__c =: r_id AND Test_Result_Detail_Name__c != 'NOTE' AND Observation_Value_type__c IN ('NM', 'ST') AND DataforTrends__c != null WITH SECURITY_ENFORCED];
        
        return testresults;}
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
      

    }*/
     public class LabOrderTestResultWrapper {
        @AuraEnabled
        public List<Test_Result_Detail__c> testResults;
        
        @AuraEnabled
        public List<Lab_Order__c> labOrders;

        public LabOrderTestResultWrapper(List<Test_Result_Detail__c> testResults, List<Lab_Order__c> labOrders) {
            this.testResults = testResults;
            this.labOrders = labOrders;
        }
    }

    @AuraEnabled(cacheable=true)
    public static LabOrderTestResultWrapper getTestResultsLWC(String r_id) {
        LabOrderTestResultWrapper resultWrapper = new LabOrderTestResultWrapper(new List<Test_Result_Detail__c>(), new List<Lab_Order__c>());

        try {
            List<Test_Result_Detail__c> testResults= new List<Test_Result_Detail__c>();
            testResults = [SELECT Id, Test_Result_Detail_Name__c, Notes__c, ElixirSuite__Test_ResultId__c, DataforTrends__c, References_Range__c, Units__c, Observation_Value__c, Observation_Value_type__c FROM Test_Result_Detail__c WHERE Test_ResultId__c = :r_id AND Test_Result_Detail_Name__c != 'NOTE' AND Observation_Value_type__c IN ('NM', 'ST') AND DataforTrends__c != null WITH SECURITY_ENFORCED];

            if (!testResults.isEmpty()) {
                List<Lab_Order__c> labOrders = new List<Lab_Order__c>();
                labOrders = [SELECT Id, Name, (SELECT Id FROM LabOrder_HL7_Results__r), (SELECT Id, Name FROM Attachments), ElixirSuite__Result_Status__c, LastModifiedDate, Physician_Name__c, LabName__c, Facility_Name__c, Test_Name__c, Lab_Order_Req__c, Lab_Order_Number__c, Order__c, ElixirSuite__Order__r.Name, Account_Id__c, toLabel(Status__c), CreatedDate, ElixirSuite__Lab_Type__c FROM Lab_Order__c WHERE Id = :testResults[0].ElixirSuite__Test_ResultId__c WITH SECURITY_ENFORCED LIMIT 1];

                resultWrapper = new LabOrderTestResultWrapper(testResults, labOrders);
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return resultWrapper;
    }
    //method use in lwc component to fetch obx details
    @AuraEnabled(cacheable=true)
    public static list<Test_Result_Detail__c> getTestResultsTextLWC(string r_id){
        try{
            // Lab_Order__c l = [select Test_Name__c from Lab_Order__c where Id =: r_id WITH SECURITY_ENFORCED];
            // HL7__c hl7 = [select Id from HL7__c where Order_ID__c =: r_id WITH SECURITY_ENFORCED Limit 1];
            // list<LabOrder_Hl7_Results_Tests_Info__c> ObrList = [select Id from LabOrder_Hl7_Results_Tests_Info__c where LabOrder_HL7_Results_ID__c =: hl7.Id and Test_Result_Name__c =: l.Test_Name__c WITH SECURITY_ENFORCED];
            // list<string> ObrIds = new list<string>();
            // for(LabOrder_Hl7_Results_Tests_Info__c o : ObrList){
            //     ObrIds.add(o.Id);
            // }
        list<Test_Result_Detail__c> testresults = [select id, Test_Result_Detail_Name__c, Observation_Value_Text__c,  Observation_Value__c, Observation_Value_type__c from Test_Result_Detail__c where Test_ResultId__c =: r_id AND Test_Result_Detail_Name__c != 'NOTE' AND Observation_Value_type__c IN ('TX', 'ST') AND DataforTrends__c = null WITH SECURITY_ENFORCED];
        
        return testresults;}
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
      

    }

    
    public static string rid{ get; set; }
    //method to fetch requisition pdf 
    public static Attachment getAttachment(){
     try{if(rid== null || rid == ''){
        rid = Apexpages.currentPage().getParameters().get('id');
    }
         Lab_Order__c l = [Select Id, Lab_Order_Req__c, Account_Id__c from Lab_Order__c where Id =:rid WITH SECURITY_ENFORCED Limit 1];
     string pdfName = l.Lab_Order_Req__c+'.pdf';
     Attachment a = [Select Id from Attachment where ParentId =: l.Account_Id__c AND name =: pdfName WITH SECURITY_ENFORCED Limit 1 ];
     return a;}
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    
     //method to fetch requisition label 
    public static Attachment getAttachmentLabel(){
     try{if(rid== null || rid == ''){
        rid = Apexpages.currentPage().getParameters().get('id');
    }
         Lab_Order__c l = [Select Id, Lab_Order_Req__c, Account_Id__c from Lab_Order__c where Id =:rid WITH SECURITY_ENFORCED Limit 1];
     string pdfName = 'Label'+l.Lab_Order_Req__c+'.pdf';
     Attachment a = [Select Id from Attachment where ParentId =: l.Account_Id__c AND name =: pdfName WITH SECURITY_ENFORCED Limit 1 ];
     return a;}
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }

    //method to fetch pdf report
    public static Attachment getPdfReport(){
        try{if(rid== null || rid == ''){
           rid = Apexpages.currentPage().getParameters().get('id');
       }
            
        string pdfName = 'PdfReport.pdf';
        Attachment a = [Select Id from Attachment where ParentId =: rid AND name =: pdfName WITH SECURITY_ENFORCED Limit 1 ];
        return a;}
           catch(Exception e){
               throw new AuraHandledException(e.getMessage());
           }
       }
    

}