force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/UA_Sample_Details__c/UA_Sample_Details__c.object-meta.xml
<CustomObject>
    <label>UA Sample Detail</label>
    <nameField>
        <displayFormat>Lab Order-{0000}</displayFormat>
        <label>Lab Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UA Sample Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/UA_Sample_Details__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>UA Sample Details</relationshipLabel>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Medical_Test__c.field-meta.xml
<CustomField>
    <fullName>Medical_Test__c</fullName>
    <label>Medical Test</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Necessity_Details__c.field-meta.xml
<CustomField>
    <fullName>Necessity_Details__c</fullName>
    <label>Necessity Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/On_Admission__c.field-meta.xml
<CustomField>
    <fullName>On_Admission__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Admission</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/Ordered_Via__c.field-meta.xml
<CustomField>
    <fullName>Ordered_Via__c</fullName>
    <label>Ordered Via</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Phone, read back and verified</fullName>
            </value>
            <value>
                <fullName>Verbal, read back and verified</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
            <value>
                <fullName>Previously prescribed medication approved by doctor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UA_Sample_Details__c/fields/UA_Sample_Details__c.field-meta.xml
<CustomField>
    <fullName>UA_Sample_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UA Sample Details</label>
    <referenceTo>UA_Sample_Details__c</referenceTo>
    <relationshipLabel>UA Sample Details</relationshipLabel>
    <relationshipName>UA_Sample_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDataDisplayController.cls
@isTest
public class TestDataDisplayController {
    
    public static testMethod void  coverScenariosForGeneratePDF(){
        
        Account a  = new Account(name = 'DmeoAccount');
        insert a;
        Contact con = new Contact(LastName='Roy',birthdate=System.today(),AccountId=a.Id);
        insert con;
        UA_Sample_Details__c demoInsertRecords= new UA_Sample_Details__c(Account__c = a.id,Medical_Test__c='Test',Fax__c = '0001',
                                                                         Ordered_Via__c='Email', Necessity_Details__c='Quack\nIm flying!!\nI cant fly\nIm flying with a rocket',
                                                                         On_Admission__c=true,Start_Date__c=System.today());
        
        insert demoInsertRecords;
        
        System.debug('inserted '+demoInsertRecords.id);
        
        Test.StartTest();
        
        PageReference pageRef = Page.PDFgenerator;
        pageRef.getParameters().put('orderId',demoInsertRecords.id);
        // ApexPages.currentPage().getParameters().put('orderId',String.valueOf(demoInsertRecords.id));
        
        Test.setCurrentPage(pageRef);
        System.debug('Apex page order id=='+ApexPages.currentPage().getParameters().get('orderId'));
        DataDisplayController objectTocall = new DataDisplayController();             
        objectTocall.getlabOrderInfo(demoInsertRecords.Id);
        objectTocall.getAccountInfo(a.id); 
        // DataDisplayController callContrct = new DataDisplayController();
        
        Test.StopTest();
        System.assertEquals(1, 1, ' ');
    }
    
}