force-app/main/default/objects/Work_Schedule__c/Work_Schedule__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage the work timings for a practitioner within a facility.</description>
    <label>Work Schedule</label>
    <nameField>
        <displayFormat>WSN No-{0000}</displayFormat>
        <label>Work Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Schedule__c/fields/Work_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Work_Schedule__c</fullName>
    <description>Represents the self lookup field associated with work schedule.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Schedule</label>
    <referenceTo>Work_Schedule__c</referenceTo>
    <relationshipLabel>Work Schedule</relationshipLabel>
    <relationshipName>Work_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GlobalVirtualWorkScheduleTriggerHelper.cls
global virtual class GlobalVirtualWorkScheduleTriggerHelper {
    
    global virtual void beforeInsert(List<ElixirSuite__Work_Schedule__c> workScheduleLst)
    {
        WorkScheduleTriggerHandler.dateValidations(workScheduleLst); 
        //WorkScheduleTriggerHandler.dateFieldUpdate(workScheduleLst);
        WorkScheduleTriggerHandler.workScheduleduplicate(workScheduleLst);
        WorkScheduleTriggerHandler.checkLocation(workScheduleLst);
        //WorkScheduleTriggerHandler.beforeInsertOrUpdateDateTimeConversion(workScheduleLst);
    }

    global virtual void afterDelete(List<ElixirSuite__Work_Schedule__c> workScheduleLst,Map<Id,ElixirSuite__Work_Schedule__c> oldWorkScheduleMap)
    {
        WorkScheduleTriggerHandler.calculateNextAvailSlot(workScheduleLst,oldWorkScheduleMap);
    }
    
    global virtual void beforeUpdate(List<ElixirSuite__Work_Schedule__c> workScheduleLst)
    {
        WorkScheduleTriggerHandler.dateValidations(workScheduleLst);
        WorkScheduleTriggerHandler.workScheduleduplicateupdate(workScheduleLst);
        WorkScheduleTriggerHandler.checkLocation(workScheduleLst);
        //WorkScheduleTriggerHandler.dateFieldUpdate(workScheduleLst);
        //WorkScheduleTriggerHandler.beforeInsertOrUpdateDateTimeConversion(workScheduleLst);
    }
    global virtual void afterInsert(List<ElixirSuite__Work_Schedule__c> workScheduleLst)
    {                  
        Map<Id,Work_Schedule__c> oldWorkScheduleMap = new Map<Id,Work_Schedule__c>();
        WorkScheduleTriggerHandler.calculateNextAvailSlot(workScheduleLst,oldWorkScheduleMap);
        if(CheckRecursive.runOnce()){
            //WorkScheduleTriggerHandler.afterInsertWorkSchedule(workScheduleLst);
        }
    }
    global virtual void afterUpdate(Map<Id,ElixirSuite__Work_Schedule__c> newWorkScheduleMap, Map<Id,ElixirSuite__Work_Schedule__c> oldWorkScheduleMap)
    {
        WorkScheduleTriggerHandler.calculateNextAvailSlot(newWorkScheduleMap.values(),oldWorkScheduleMap);
        if(CheckRecursive.runOnce()){
            //WorkScheduleTriggerHandler.afterUpdateWorkSchedule(newWorkScheduleMap,newWorkScheduleMap);
        }
    }
	
}